oracle/opengrok

- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Prefix.java
- opengrok-web/src/main/java/org/opengrok/web/AuthorizationFilter.java
- opengrok-web/src/main/java/org/opengrok/web/StatisticsFilter.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
- opengrok-web/src/main/webapp/WEB-INF/web.xml
This change simplifies handling of meters by concentrating most of the request related meters to `StatisticsFilter`. It addresses most of the outstanding metrics issues.
Example:
```
requests_latency_seconds_count{category="metrics",code="200",} 6.0
requests_latency_seconds_sum{category="metrics",code="200",} 0.065338
requests_latency_seconds_count{category="history",code="200",} 1.0
requests_latency_seconds_sum{category="history",code="200",} 0.121469
requests_latency_seconds_count{category="api",code="200",} 3.0
requests_latency_seconds_sum{category="api",code="200",} 0.311119
requests_latency_seconds_count{category="root",code="200",} 2.0
requests_latency_seconds_sum{category="root",code="200",} 0.656422
requests_latency_seconds_count{category="xref",code="302",} 1.0 …
```
> Monitoring responses

- apiary.apib
This change adds `/metric` endpoint to the list of generally allowed endpoints in the Apiary documentation.
> the /metrics endpoint is accessible from everywhere

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
When watching the indexer I noticed that executions of `hg log` is missing separator between arguments and the file path.
> add argument separator before path to Mercurial history executor

- plugins/src/main/java/opengrok/auth/plugin/configuration/Configuration.java
- plugins/src/main/java/opengrok/auth/plugin/ldap/LdapFacade.java
- plugins/src/main/java/opengrok/auth/plugin/ldap/LdapServer.java
- plugins/src/test/java/opengrok/auth/plugin/LdapServerTest.java
- plugins/src/test/java/opengrok/auth/plugin/ldap/LdapFacadeTest.java
Another post-mortem induced change: when a LDAP server went down so that it accepted TCP connections without replying to received data, the authorization reload API endpoint call got stuck when the LDAP server was being reconnected. Leaving aside whether API call that can require potentially expensive server side processing should be synchronous for now.
The `connectTimeout` set in `LdapServer` (or plugin `Configuration`) only works for TCP connect. Also, looking at the source of `/jdk8u/jdk/src/share/classes/com/sun/jndi/ldap/LdapCtx.java`, it is using wrong name. It is using `com.sun.jndi.ldap.connect.connectTimeout` and it should be:
```java
181      // Timeout for socket connect
182      private static final String CONNECT_TIMEOUT =
183          "com.sun.jndi.ldap.connect.timeout"; …
```
> fix LDAP timeout handling for LdapCtx

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
Adds 2 options. This is how the help looks like for the tread count related options:
``` 
--historyThreads number
The number of threads to use for history cache generation. By default the number
of threads will be set to the number of available CPUs. Assumes -H/--history.
--historyRenamedThreads number
The number of threads to use for history cache generation when dealing with renamed files.
By default the number of threads will be set to the number of available CPUs.
Assumes --renamedHistory=on
-T, --threads number
The number of threads to use for index generation. By default the number
of threads will be set to the number of available CPUs. This influences the number
of spawned ctags processes as well.
```
> add options to set history parallelism level

- pom.xml
When doing security cup at work I've noticed this plugin and I found it really helpful. It will list all the dependencies with known CVEs and create a report.
I debated whether to add it among `reporting` plugins but I found the usage easier like this since I could call it directly from IDEA.
Output from console:
```
One or more dependencies were identified with known vulnerabilities in Distribution:
ant-1.10.1.jar (pkg:maven/org.apache.ant/ant@1.10.1, cpe:2.3:a:apache:ant:1.10.1:*:*:*:*:*:*:*) : CVE-2020-1945
source.war: chronicle-wire-2.20.4.jar (pkg:maven/net.openhft/chronicle-wire@2.20.4, cpe:2.3:a:wire:wire:2.20.4:*:*:*:*:*:*:*) : CVE-2018-8909
source.war: jquery-3.4.1.min.js (pkg:javascript/jquery@3.4.1.min) : CVE-2020-11022, CVE-2020-11023
source.war: jstl-1.2.jar …
```
> Add maven dependency check plugin

- suggester/src/main/java/org/opengrok/suggest/popular/impl/chronicle/BytesRefSizedReader.java
When building with recent IDEA I am getting warnings for `missing type arguments for generic class` in `BytesRefSizedReader`. This change suppresses the warning - the class overrides a method from `net.openhft.chronicle.hash.serialization`.
> suppress raw type warning in IDEA

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/GroupsTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
For the past week or so I have been trying to determine the cause of slowly running reindex from scratch which made me to run it over and over with different settings/versions. Watching the behavior of the initial phase of such indexing made me to address the speed of repository scanning. This change adds parallelism on the level of source root sub-directories. The original behavior should be preserved.
> parallelize repository scan

- opengrok-web/src/main/webapp/search.jsp
This change removes the 'Completed in <duration>' message from the search results page. I think it is not necessary and clutters the UI. If the user is interested in the latency for debugging purposes, he can always use e.g. Web console in Firefox or such. For admins this value is available via the monitoring endpoint.
> remove 'Completed in <duration>' message from the UI

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
Looking at `ensureHistoryCacheExists()` to fix the double emitted log message during reindex, it seems that there is some unnecessary logic there. If the history cache was created for the repository in the 1st step of indexing (the existence of the history cache directory should be enough to tell), it should not be necessary to call `createCache()` again - only for complete failure to create the history cache.
`ensureHistoryCacheExists()` will probably disappear anyway with the fix for #747.
> do not call createCache() unnecessarily

- opengrok-indexer/pom.xml
- opengrok-indexer/src/main/java/org/opengrok/indexer/Metrics.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/ConfigurationHelp.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/StatsdConfig.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/Statistics.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/StatsdConfigTest.java
- opengrok-web/src/main/java/org/opengrok/web/StatisticsFilter.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
- opengrok-web/src/main/java/org/opengrok/web/servlet/MetricsServlet.java
This change introduces remote monitoring of indexer via statsd registry in Micrometer. I wanted to use statsd for indexer because it does not require scraping and therefore the need for a web server. This would either conflict with already running web server on the same machine (assuming the indexer is usually run on the same machine as the web application) or would involve poking holes into firewall to allow the scraping to pass through to distinct TCP port.
Example read-only configuration:
```xml
<java version="11.0.4" class="java.beans.XMLDecoder">
<object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">
<void property="statsdConfig">
<void property="port">
<int>8125</int>
</void>
<void property="host"> …
```
> use statsd for indexer monitoring

- opengrok-tools/pom.xml
Increase the line length in python tools to 120
> increasing the max line length for python tools checkstyle

- opengrok-tools/src/test/python/web.xml
fixes #3297
Seems this should be enough to make it work under python 3.8.
> assert xml attributes in correct order for python 3.8

- .travis.yml
This should fix the macOS build with Xcode 10.1.
> disable the Coverity addon, causes TLS black hole

- .travis.yml
- dev/main
- opengrok-indexer/pom.xml
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/pascal/PascalUtils.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationFramework.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationPlugin.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationStack.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginFramework.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/JFlexXrefTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/DummyHttpServletRequest.java
- opengrok-web/pom.xml
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- plugins/pom.xml
- plugins/src/main/java/opengrok/auth/plugin/AbstractLdapPlugin.java
- pom.xml
- suggester/pom.xml
Upcoming Lucene 9.0.0 has updated its System Requirements with LUCENE-8738: Move to Java 11 as minimum Java version.
This is a patch to try a revised configuration to move OpenGrok to 11 too.
> [WIP] Move to Java 11 as the minimum version to anticipate Lucene

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
Keeping the `dtags.eftar` file underneath the `index` directory does not make sense to me. After all it does not hold index data. Also, when upgrading OpenGrok from scratch, I tend to clone the directory structure (yes, via ZFS) and recreate the subdirectories (er, datasets) such as `index,historycache,...`. With this procedure the file is lost.
> change default path to dtags.eftar

- opengrok-tools/src/main/python/opengrok_tools/scm/cvs.py
- opengrok-tools/src/main/python/opengrok_tools/scm/git.py
- opengrok-tools/src/main/python/opengrok_tools/scm/mercurial.py
- opengrok-tools/src/main/python/opengrok_tools/scm/perforce.py
- opengrok-tools/src/main/python/opengrok_tools/scm/repo.py
- opengrok-tools/src/main/python/opengrok_tools/scm/repository.py
- opengrok-tools/src/main/python/opengrok_tools/scm/svn.py
- opengrok-tools/src/main/python/opengrok_tools/scm/teamware.py
- opengrok-tools/src/test/python/test_mirror.py
Of course the change is compatible with the current setup:
mirror.conf:
```
commands:
git: /usr/bin/git
```
The syntax is extended to support custom commands as follows:
```
commands:
git:
command: /usr/local/bin/git
incoming: ['git', 'pull', '--dry-run']
```
```
commands:
git:
command: /usr/local/bin/git
sync: ['git', 'pull', '--ff-only']
```
```
commands:
git:
command: /usr/local/bin/git
incoming: ['git', 'pull', '--dry-run']
sync: ['git', 'pull', '--ff-only']
```
This pull request is to allow user to overcome problems from #2583 and #2432 before an universal solution exists in opengrok.
> Allow users to specify custom mirroring and sync command

- opengrok-tools/src/test/python/test_mirror.py
Set user prior to commit() in the `test_incoming_retval` Python tools test to avoid failure.
> set user prior to commit

- opengrok-indexer/src/test/java/org/opengrok/indexer/web/EftarFileTest.java
- opengrok-web/src/main/java/org/opengrok/web/DirectoryListing.java
- opengrok-web/src/test/java/org/opengrok/web/DirectoryListingTest.java
This change adds handling of `IOException` from `EftarFileReader#getNode()` to avoid UI disruption when the `dtags.eftar` file has unexpected contents.
> handle some exceptions related to path descriptions

- plugins/src/main/java/opengrok/auth/plugin/LdapFilterPlugin.java
The warning level used when LDAP server returns empty output is undesirable - this happens whenever LDAP user does not match a filter, i.e. is not permitted.
> adjust log levels in LdapFilterPlugin

- .github/workflows/apiary.yml
- .github/workflows/build.yml
- .github/workflows/docker.yml
- .github/workflows/javadoc.yml
- .travis.yml
- dev/before_install
- dev/docker.sh
- dev/javadoc.sh
- dev/main
- opengrok-indexer/pom.xml
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
- opengrok-web/pom.xml
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
Travis backlog has started being unbearable recently (see https://www.traviscistatus.com/). This change enables basic Github actions for building. Relase related tasks will be done in later PR.
The macOS build fails due to #3296. For the Windows build to pass I had to exclude some of the tests. Will file issues for these.
Info about the build environments: https://github.com/actions/virtual-environments
> enable GitHub actions for building

- pom.xml
Running Javadoc Github acitons workflow currently fails with:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project opengrok-top: failed to get report for org.apache.maven.plugins:maven-pmd-plugin: org.apache.maven.reporting.MavenReportException: Unsupported targetJdk value '11'. -> [Help 1]
```
Currently the PMD plugin is on 3.8 which was released in 2017. The official docs claim that Java 11 is supported: https://maven.apache.org/plugins/maven-pmd-plugin/pmd-mojo.html#targetJdk
> upgrade Maven PMD plugin to 3.13.0

- opengrok-indexer/pom.xml
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
This was meant to help a bit #3243 however it does not do much for my particular use case as described in the issue. Still, should save some heap memory in case of running the indexer with -G.
> do not deep copy history entries

- suggester/src/main/java/org/opengrok/suggest/Suggester.java
This change fixes a regression in suggester rebuild metrics computation.
Checked by hand that positive duration is output to the log:
```
30-Oct-2020 09:05:15.518 INFO [Thread-102] org.opengrok.suggest.Suggester.rebuild Rebuilding the following suggesters: [grizzly, new, opengrok, foo, opengrok-1.0, bar, sics, sudo-1.8.9p5, sudo-1.8.15, symlink, sudo, universal-ctags]
30-Oct-2020 09:05:20.380 INFO [Thread-102] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggesters for [grizzly, new, opengrok, foo, opengrok-1.0, bar, sics, sudo-1.8.9p5, sudo-1.8.15, symlink, sudo, universal-ctags] were successfully rebuilt (took 4 seconds)
```
> compute suggester rebuild duration correctly

- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/LangMapTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/clojure/ClojureAnalyzerFactoryTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/pascal/PascalAnalyzerFactoryTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/BitKeeperRepositoryTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/BooleanUtilTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/UtilTest.java
- pom.xml
- suggester/src/test/java/org/opengrok/suggest/SuggesterUtilsTest.java
- suggester/src/test/java/org/opengrok/suggest/popular/impl/ChronicleMapAdapterTest.java
- suggester/src/test/java/org/opengrok/suggest/query/customized/CustomSloppyPhraseScorerTest.java
While trying to make https://github.com/oracle/opengrok/pull/3336 work I've tried to update the junit and had to fix a few files.
`assertThat` and `ExpectedException.none()` became deprecated in junit 4.13.
Thanks.
> Update junit to 5.7.0

- opengrok-tools/src/test/python/conftest.py
- opengrok-tools/src/test/python/test_command.py
- opengrok-tools/src/test/python/test_mirror.py
> Extract and reuse pytest parameters

- plugins/src/main/java/opengrok/auth/plugin/LdapAttrPlugin.java
- plugins/src/main/java/opengrok/auth/plugin/UserWhiteListPlugin.java
This change adds a bit more logging to the init()/load() functions of the plugins using whitelists.
Sample output:
```
03-Nov-2020 16:16:06.058 FINE [http-nio-8080-exec-29] opengrok.auth.plugin.UserWhiteListPlugin.load UserWhiteList plugin loaded with filePath=/opengrok/auth/config/whitelists/foo.txt (404 entries), fieldName=id
03-Nov-2020 16:16:07.770 FINE [http-nio-8080-exec-29] opengrok.auth.plugin.LdapAttrPlugin.init LdapAttrPlugin plugin loaded with attr=gidNumber, whitelist=/opengrok/auth/config/whitelists/bar.txt (2 entries), instance=33
```
> log more info during init() in plugins using whitelist

- .github/workflows/build.yml
Changes all Maven builds to start from `bash`.  This should resolve  #3330.
> use common Maven build for all OSes

- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SuggesterController.java
- suggester/src/main/java/org/opengrok/suggest/Suggester.java
This change removes unnecessary Counter and making the API calls to spawn a thread when calling into suggester.
The change merely changes the behavior of the API calls. In terms of #3347 it actually makes the situation worse since there will be more threads created.
> make ProjectsController API calls using suggester async

- .github/workflows/javadoc.yml
This avoids failures when pushing to the `master` branch in forked repository. Not everyone has `gh-branch` in his forked repo.
> restrict checkout of gh-pages to the main repo

- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
This change cleans up the `testRemoveFileOnFileChange` test, adds assert and removes the sleep. Hopefully this will shed more light on the failure reported in #3276.
> clean up testRemoveFileOnFileChange

- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SystemController.java
Forgot make one of the `suggester.rebuild()` calls async when working on #3349. Noticed this in Grafana as it skews the overall request max latency graphs.
> another suggester.rebuild() to become async

- .github/workflows/build.yml
also adds some ignore paths to the `push` event.
> run the build once a week

- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Prefix.java
Noticed bunch of "unknown"s in the monitoring, these are actually requests to `/webjars`.
> add /webjars

- opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthControlFlag.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationEntity.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationStack.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/authorization/AuthorizationFrameworkTest.java
This introduces the `OPTIONAL` authorization control flag.
Tested with stack that contained this at the top level:
```
LdapUserPlugin (OPTIONAL)
- substack (REQUIRED)
UserWhiteListPlugin (SUFFICIENT)
LdapFilterPlugin (REQUIRED)
```
Works fine except when `LdapUserPlugin` fails the check because the user does not exist in LDAP it will cause a LDAP query each time the user sends a request as there is no negative caching.
> support OPTIONAL control flag in authorization framework

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
This change makes it possible to produce xref's for compressed files. The most complex part is trying to make sure that empty xref files are not lying around.
> generate xref for non empty compressed files

- opengrok-tools/src/main/python/opengrok_tools/deploy.py
I find the extra output from `opengrok-deploy` a bit too verbose. This change changes the log level of certain messages to `debug` and removes the not really helpful overall message emitted at the end.
> make opengrok-deploy silent by default

- plugins/src/main/java/opengrok/auth/plugin/ldap/LdapServer.java
This change fixes problems related to LDAP server connections. This will decrease the utilization of LDAP servers used by the LDAP authorization plugins.
> LDAP server fixes

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
This change allows to set thread pool size in `HistoryGuru#invalidateRepositories()` via `-T` indexer option.
> control thread pool size in invalidateRepositories()

- plugins/src/main/java/opengrok/auth/plugin/ldap/LdapFacade.java
- plugins/src/test/java/opengrok/auth/plugin/ldap/LdapFacadeTest.java
This change makes sure that inactive LDAP servers are closed in `LdapFacade#prepareServers()` after the working one is determined. The main goal is resource efficiency.
I had contemplated this change for a while. While it is nice to have connections/contexts established for these servers for quicker failover, it is not guaranteed that they will be in a working state by the time search request is made through them. Also, usually the 3-way TCP hadshake and LDAP bind operation do not take too long compared to LDAP query latency so the benefit of keeping them around is arguable.
> close inactive servers in prepareServers()

- suggester/src/main/java/org/opengrok/suggest/Suggester.java
This should take care of the long wait on undeploy when there is a number of outstanding suggester rebuild jobs.
It does so by setting a flag so if there is a long running rebuild in progress already it will still wait for that. That would be the case also when shutting down an executor (interrupting the threads by shutting the executor down immediately would not be a good practice).
> Suggester rebuild terminate on undeploy

- opengrok-tools/README.md
- opengrok-tools/requirements.txt
I don't think capturing the exact developer environment via `requirements.txt` for the Python tools is necessary. This change will make `pip install -r requirements.txt` to install whatever is in the package dependencies in `setup.py`.
> do not hardcode exact versions in requirements.txt

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexCheck.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexCheckTest.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
This change checks the project indexes during web app startup. If a project does not have valid index, it is marked as not indexed. This is to catch cases such as the one described in #3418.
In web app log this looks like this:
```
17-Feb-2021 10:36:54.452 WARNING [RMI TCP Connection(10)-127.0.0.1] org.opengrok.web.WebappListener.contextInitialized Project foo index check failed, marking as not indexed
Directory /var/opengrok/data/index/foo has index version discrepancy: Lucene version = 8, index version = 7
at org.opengrok.indexer.index.IndexCheck.checkDir(IndexCheck.java:146)
at org.opengrok.web.WebappListener.contextInitialized(WebappListener.java:115)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
at …
```
> check indexes on webapp startup

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerUtil.java
This change adds `--token` Indexer option to allow setting API tokens in the requests made to the web application.
Out of the occurrences where requests are made to the web app `plugins/src/main/java/opengrok/auth/plugin/util/RestfulClient.java#postIt()` was left untouched because it is effectively running in the web app context.
Tested with the `isSecure()` check commented out in the `IncomingFilter` and making sure the token matched.
> add Indexer option to set API token

- docker/README.md
OpenGrok mirroring by default does a "git pull --ff-only" for Git repos, not a regular "git pull". This avoids merges occurring.
> Update README.md: "git pull --ff-only"

- dev/before_install
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/filter/IncomingFilter.java
- tools/src/main/python/opengrok_tools/mirror.py
- tools/src/main/python/opengrok_tools/projadm.py
- tools/src/main/python/opengrok_tools/reindex_project.py
- tools/src/main/python/opengrok_tools/sync.py
- tools/src/main/python/opengrok_tools/utils/commandsequence.py
- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/main/python/opengrok_tools/utils/opengrok.py
- tools/src/main/python/opengrok_tools/utils/parsers.py
- tools/src/main/python/opengrok_tools/utils/restful.py
- tools/src/test/python/test_command_sequence.py
- tools/src/test/python/test_mirror.py
- tools/src/test/python/test_mirror_incoming_retval.py
- tools/src/test/python/test_opengrok.py
- tools/src/test/python/test_parsers.py
- tools/src/test/python/test_restful.py
This change broadens the HTTP header support in the Python tools. This is primarily done to allow Bearer API token to be used e.g. for `opengrok-sync` arguments and configuration.
For `opengrok-sync` specifically, this allows to specify the headers both as command line (`-H/--header` , accepts multiple values) and also in the configuration file, e.g.:
```yml
headers:
'Authorization': 'Bearer foo'
'X-Special-header': 'bar'
commands:
- command:
...
```
> allow to use API token with Python tools

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/Statistics.java
This is to help identify the long history index times reported in #3434.
> report duration for file history cache updates

- suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
- suggester/src/test/java/org/opengrok/suggest/SuggesterProjectDataTest.java
Fixes issue when suggester did not work in docker image due to changes in https://github.com/oracle/opengrok/pull/3402
Thanks.
> Suggester rebuild does not reflect fields change

- tools/src/main/python/opengrok_tools/mirror.py
- tools/src/main/python/opengrok_tools/projadm.py
- tools/src/main/python/opengrok_tools/reindex_project.py
- tools/src/main/python/opengrok_tools/sync.py
- tools/src/main/python/opengrok_tools/utils/commandsequence.py
- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/main/python/opengrok_tools/utils/opengrok.py
- tools/src/main/python/opengrok_tools/utils/restful.py
- tools/src/test/python/test_command_sequence.py
- tools/src/test/python/test_mirror.py
- tools/src/test/python/test_opengrok.py
- tools/src/test/python/test_restful.py
This change introduces the request timeout to the tools. The default is set to 60 seconds in `requests#do_api_call()`. The command line tools received the `--api_timeout` option.
So far it is not possible to specify per command (as in command sequence) timeout, tracked by #3453.
> requests timeout for tools

- docker/start.py
This change propagates the `INDEXER_OPT` to the initial configuration.
> honor INDEXER_OPT in create_bare_config()

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/DirectoryExtraReader.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/SearchEngine.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/Statistics.java
- opengrok-web/src/main/java/org/opengrok/web/StatisticsFilter.java
When investigating big latencies I came across the `search.latency` meter and realized that it is only used when searching the index via part of the UI. This change adds more categories. Because of Prometheus limitation the set of tags for the common meter name has to be the same.
Tested by performing search in the main form and via RESTful API and listing a directory.
> add more search.latency categories

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/FileAnalyzer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/DirectoryExtraReader.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/FileExtra.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/QueryBuilder.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
This change stores last revision of given file in the index. Web app will then take advantage of this when getting the revision number in order to perform redirection. If the newly introduced `LASTREV` field is not found, it will fall back to the old behavior.
In general this should be quicker than getting the history from the history cache since the index is usually memory mapped, i.e. avoids reading the history cache file, deserializing potentially huge `History` object and picking just one `HistoryEntry`.
> get last revision date from the index first

- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
This change should take care of the project addition/removal via the RESTful API w.r.t. repositories and disabled history.
> Projects controller vs history

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/MercurialIsWorkingTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/RepositoryFactoryTest.java
This mimics the changes done in `GitRepository` to avoid checking Mercurial command for some of repository operations repeatedly. Should help repository scan/invalidation performance and thus web app startup.
> run hg binary only once per isWorking()

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryOctopusTest.java
This change allows to control whether the merge commits should be stored in history. Should work as workaround with indexing large repositories that have rich history. This is relevant only to Git so far.
I did not want to introduce yet another command line option so this needs to be used via read-only configuration.
> Merge commits tunable

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuruHelp.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/document/MandocAnalyzer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/document/MandocAnalyzerFactory.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/LuceneCompatibilityTest.java
This change adds table of analyzer -> name to the output of `-h guru`:
```
List of analyzers:
The names of the analyzers (left column) can be used for the -A indexer option:
Ada        : Ada
Asm        : Asm
BZip2      : Bzip(2)
C          : C
CSharp     : C#
Cxx        : C++
Clojure    : Clojure
Eiffel     : Eiffel
ELF        : ELF
Erlang     : Erlang
File       : N/A
Fortran    : Fortran
Golang     : Golang
GZIP       : GZIP
Haskell    : Haskell
HCL        : HCL
Ignorant   : N/A
Image      : Image file
Jar        : Jar
Java       : Java
JavaClass  : Java class
JavaScript : JavaScript
Json       : Json
Kotlin     : Kotlin
Lisp       : Lisp
Lua        : Lua
Mandoc     : Manual pages
Pascal     : Pascal
Perl       : Perl
Php        : PHP
PLSQL      : PL/SQL
Plain      : Plain Text …
```
> print list of analyzers with -h guru

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
With this change the tag rebuild for the linux-mainline repository finishes fine, with some 687 `tagList` entries currently.
> skip over false tags

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/HostUtil.java
#3517 inspired me to add this check. Wanted to do this outside of argument parsing - if there is any problem with options this should fail first. These methods come from authnz plugins so this is code duplication however plugins needs to be independent.
> fail early if web app URI is not reachable

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/c/CxxAnalyzerFactory.java
fixes #3518
From https://en.wikipedia.org/wiki/CUDA : "CUDA source code is now processed according to C++ syntax rules".
I've tested on https://github.com/NVIDIA/cuda-samples and the results looked good.
Thanks to @saltuser16
> Interpret .cu/.cuh files as .cxx files

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/ConfigurationClassLoader.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/ConfigurationTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/RuntimeEnvironmentTest.java
- opengrok-indexer/src/test/resources/configuration/valid_configuration.xml
Creating this as a draft because this fix is only a workaround. I'm not really sure I whitelisted all the possible classes and I do not know how to achieve this more nicely. I think we can use this as an interim solution until we get the yaml config working.
Thanks to Bobby Rauch (Accenture) for reporting the issue.
> Prevent XMLDecoder from loading other than whitelisted classes

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Definitions.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Scopes.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexAnalysisSettings.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexAnalysisSettings3.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/WhitelistObjectInputFilter.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/ScopesTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexAnalysisSettingsUpgraderTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/WhitelistObjectInputFilterTest.java
- suggester/src/main/java/org/opengrok/suggest/popular/impl/chronicle/ChronicleMapConfiguration.java
I was debating whether to put some default allowed classes to the whitelist filter (e.g. `Integer.class`, `Double.class`) but since it's used only in a couple of places, I decided against it.
Thanks.
> Add serial filtering when deserializing classes

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
#3536 inspired me to add permissions checks for source and data root. Granted, this is still prone to the _TOUTOC_ problem however will provide early exit. Also, the existence of the directories is checked only when parsing the -s/-d options, i.e. will not apply to read-only configuration.
> check source and data root access

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
After trying to create history for linux-mainline Git repository from scratch (https://github.com/oracle/opengrok/issues/3539#issuecomment-818752840) and seeing the difference when merge commits are disabled I think it is reasonable to disable merge commits by default.
This is the difference on Java 11 VM with 16 GB heap:
The indexer with merge commits disabled was started at 16:00 and very quickly progressed to create the file history cache while the first actually ended with OOM and did not even get to storing a single file history cache entry on disk.
> disable merge commits by default

- plugins/src/test/java/opengrok/auth/plugin/LdapServerTest.java
The LdapServerTest is still failing due to
```
Error:  Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.225 s <<< FAILURE! - in opengrok.auth.plugin.LdapServerTest
Error:  testIsReachable  Time elapsed: 0.019 s  <<< ERROR!
java.net.BindException: Cannot assign requested address (Bind failed)
at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
at java.base/java.net.ServerSocket.<init>(ServerSocket.java:257)
at opengrok.auth.plugin.LdapServerTest.testIsReachable(LdapServerTest.java:84)
```
The fix done in 476443edddbb606ccf738095d424034494b8dd71 was not sufficient it seems so reintroducing the original approach.
> LdapServerTest redux

- README.md
- opengrok-web/src/main/webapp/foot.jspf
- pom.xml
The github.com webpage links stopped working.
Thanks!
> Fix github webpage links

- opengrok-web/src/main/webapp/xref.jspf
The xref page for binary files contains the misplaced comment, this change fixes that.
> fix misplaced comment

- opengrok-web/src/main/webapp/minisearch.jspf
The look is the same but now clicking on the text also checks the checkbox.
Thanks.
> Use label for minisearch's "current directory" checkbox

- pom.xml
Recently the dependency check caused some build instability, this update hopefully fixes that.
> update dependency-check to 6.1.5

- Dockerfile
- docker/README.md
- docker/start.py
This change allows to trigger reindex from outside of the Docker container via `GET` request to `/reindex` on certain port (5000 by default). This works only if the periodic reindex is disabled, i.e. when `SYNC_TIME_MINUTES` environment variable is set to 0.
> add port and REST endpoint to trigger reindex

- docker/README.md
- docker/start.py
This change runs the initial reindex if sync period is set to 0.
Also, renames `SYNC_TIME_MINUTES` to `SYNC_PERIOD_MINUTES`.
> run reindex if period is 0

- apiary.apib
This change adds wiki link to project properties to the API documentation and renames field to property.
> add link to project property documentation

- docker/start.py
This change is sort of low effort approach to addressing termination of the Docker container via Ctrl-C when running as `docker run`. Setting the threads with `daemon=True` allows them to be terminated (https://stackoverflow.com/a/2564282/11582827) along with the main thread. Otherwise Tomcat would exit and the threads would be still running with the root process/thread waiting in `sys.exit()`. Perhaps more proper way to address that would be to wake them up and let them finish on their own, using a global termination flag. For the REST thread that would probably mean adding a separate API endpoint solely for the purpose of terminating the Flask server (use something like https://code-examples.net/en/q/ed76ce) or muck around with `waitress` internals …
> attempt at graceful exit in Docker

- dev/docker.sh
This change should build and push `opengrok/docker:master` for each non release build in the main repo.
> publish Docker image for non release builds as well

- docker/README.md
- docker/start.py
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
Another piece for the OpenGrok demo. This change introduces the `CHECK_INDEX` environment variable that triggers the run of the indexer with `--checkIndex`. If this fails, the data root is wiped out. This is necessary for upgrades across major versions.
> check index and wipe out data root on mismatch

- docker/start.py
This takes care of the Ctrl+C case in `docker-compose`, at least in the basic sense. This event leads to `docker stop` which sends `SIGTERM` to PID 1 in the container (https://github.com/docker/compose/issues/7135#issuecomment-573621185).
Still, the sync and REST thread could be dealt with in a better way.
> handle SIG{TERM,INT} in Docker

- docker/start.py
This change allows to the reindex/sync to be triggered based on both timeout and RESTful API call. This has some limitiations that stem from the underlying implementation, e.g. if reindex is already running and the `/reindex` API endpoint is called, the event will be lost.
Inspired by #3578.
Also added some signal handling related changes that I think prevent `watchtower` from restarting the container on image update.
> rework reindex/sync event triggers in Docker

- opengrok-web/src/main/webapp/WEB-INF/tags/repository.tag
On Windows the repository can be misinterpreted as subrepository which can cause display similar to below:
The problem seems to be that `Project`s are using `/` as path separator  whereas `RepositoryInfo` can have it as `\` which is causing the inequality:
http://demo.opengrok.org/xref/OpenGrok/opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java?r=93915c65#192
I believe the best way would be to use `/` in `RepositoryInfo` as well but I'm not sure what else such change could affect. @vladak what do you think?
Thanks!
> Fix subrepository display on Windows

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryTest.java
One of the last steps in the JGit conversion (#1113). Executing the `git` command is no longer needed, at least for the indexer/webapp.
> convert findOriginalName() to JGit

- .github/workflows/build.yml
- dev/before
- dev/before_install
- dev/install-universal_ctags.sh
- opengrok-indexer/src/test/java/org/opengrok/indexer/condition/RepositoryInstalled.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheOctopusTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryOctopusTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseSymlinksTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerRepoTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/AnnotationControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/HistoryControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/RepositoriesControllerTest.java
- tools/src/main/python/opengrok_tools/utils/indexer.py
Last piece of the changes for #1113. Cleans the tests + removes the need for the `git` command during build. The javadoc workflow still needs it (installed by default) however that is separate from the regular build.
The Docker image still needs the `git` command to perform repository synchronization (until #2852 is implemented).
> JGit related test/build cleanup

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
With the history per partes change I forgot to remove one piece of history cache for directories.
> remove remnants of history cache for top level directory

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
Another piece of post JGit cleanup. No need to cache `true`.
> JGit is always working

- tools/src/main/python/opengrok_tools/projadm.py
Fixes small problem encountered when running projadm delete on non-existent directory.
> handle exceptions from rmtree() gracefully

- tools/src/main/python/opengrok_tools/projadm.py
Inspired by https://github.com/oracle/opengrok/issues/3593#issuecomment-845215658
Sample output:
```
$ opengrok-projadm -a foo
Adding project foo
Added project foo with repositories: ['/foo', '/foo/nested']
Refreshing configuration
```
> print added repositories

- docker/start.py
fixes the problem with CPU load/log flood.
> do not start timeout thread with 0 period

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialHistoryParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialHistoryParserRevisionsOnly.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/MercurialRepositoryTest.java
Converts Mercurial history handling to the per partes style done in #3589 for Git.
In Mercurial I happen to be using (5.3.1) the revision filtering for file history log is still broken, i.e. `hg log -r X:Y --follow <file>` does not display expected list of changesets. This is only relevant to renamed file handling. I strip the unwanted `HistoryEntry` objects as a workaround. Even if it worked, it would be probably unusable - thinking the revision filtering for files works, I tried it first and it resulted in some of the `hg` processes to consume over 12 GB RSS and the system got into unhappy place (heavy swapping, the OOM killer striking).
The history cache was much slower to generate with the repository I tried this on (OpenSolaris ON gate with some 16k changesets, the majority of files …
> Mercurial history per partes

- opengrok-indexer/src/test/java/org/opengrok/indexer/condition/RepositoryInstalled.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
test-jar is not being propagated with dependencies which caused `NoClassDefFoundError` when `@EnabledForRepository` was used in webapp. This consequently caused the tests to be silently ignored. There are 3 failing tests in `PageConfigTest` caused by the recent jgit changes. 
I've tried to fix the tests by doing something like this (as jgit does not seem to have any nice API for this scenario) which fixed the tests but seems to add a lot of unnecessary work and tests for renamed files started to fail:
```java
SortedSet<String> files = new TreeSet<>();
SortedSet<String> renamedFilesHolder = new TreeSet<>();
getFilesForCommit(renamedFilesHolder, files, commit, repository);
boolean inFiles = files.stream().anyMatch(f -> f.startsWith(relativePath));
if (!inFiles) {
continue;
}
if …
```
> Fix @EnabledForRepository usages in webapp

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
As noticed in #3602, path filtering for Git is broken. The tree filter needs to be used in different way as noted on https://stackoverflow.com/a/12697369/11582827
> fix path filtering for Git

- index.html
Just a couple of stale links I noticed while searching for javadoc.
Thanks!
> Remove stale links on gh-pages

- opengrok-indexer/pom.xml
- opengrok-web/pom.xml
- plugins/pom.xml
- pom.xml
I was revisiting https://github.com/oracle/opengrok/pull/3336 and it seems that test-jar and javadoc generation were causing the problems with parallel build so I've tried to update the related maven plugins but it did not help so at least this PR.
Thanks!
> Update maven plugins

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
with per partes history the 'Done storing ...' log message is repeated:
```
2021-05-24 16:28:04.134+0200 FINE t31 FileHistoryCache.store: Stored history for 507 files in repository '/ws-local/linux'
2021-05-24 16:28:04.135+0200 FINE t31 FileHistoryCache.finishStore: Done storing history for repository /ws-local/linux
2021-05-24 16:28:04.135+0200 FINE t31 Statistics.logIt: finished chunk 1702/1981 of history cache for repository '/ws-local/linux' (took 0:02:36)
2021-05-24 16:30:27.573+0200 FINE t31 FileHistoryCache.store: Stored history for 1,107 files in repository '/ws-local/linux'
2021-05-24 16:30:59.614+0200 FINE t31 FileHistoryCache.storeRenamed: Stored history for 48 renamed files in repository '/ws-local/linux'
2021-05-24 16:30:59.615+0200 FINE t31 FileHistoryCache.finishStore: Done …
```
> move log message to Repository

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialHistoryParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryTest.java
This set of changes should save same memory and make the code in `FileHistoryCache#store()` more readable.
>  cleanup of renamed file handling in FileHistoryCache

- opengrok-indexer/pom.xml
- opengrok-web/pom.xml
- pom.xml
- suggester/pom.xml
These annotations are only for IDE and are not being processed at runtime so there is no need to include them. `provided` scope is also specified at their github page: https://github.com/JetBrains/java-annotations
Thanks!
> Use provided scope for jetbrains annotations

- tools/src/main/python/opengrok_tools/reindex_project.py
Prevents `NoneType` exceptions in `opengrok-reindex-project` if config could not be retrieved from the web application.
> check None config

- docker/README.md
- docker/start.py
- docker/sync.yml
- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/main/python/opengrok_tools/utils/utils.py
- tools/src/test/python/test_mirror.py
This change allows to override the incoming check in `opengrok-mirror`. It also adds mirror configuration to Docker.
Sort of paves the way for #3500.
> incoming check override

- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/test/python/test_mirror.py
This change adds `ignore_errors` configuration parameter to the `opengrok-mirror` configuration, allowing to ignore any error during the mirroring process, be it repository sync or hook failure.
> ignore errors for opengrok-mirror configuration

- tools/src/main/python/opengrok_tools/projadm.py
Ignore file not found error when deleting project sources.
> ignore FileNotFoundError when deleting project sources

- tools/src/main/python/opengrok_tools/utils/readconfig.py
- tools/src/test/python/test_readconfig.py
This fixes a problem in the recent PR #3614 which assumed that `read_config()` returns empty dictionary on a valid yet empty YAML config however `None` is returned.
> deal with read_config() for empty YAML file properly

- opengrok-web/src/main/webapp/xref.jspf
fixes #3620
I've reproduced the error by removing the xref file. The implementation tried to get the file contents from history with empty revision which then produced an error from jgit.
At first I wanted to use `PageConfig#isLatestRevision` method but we map `rev` to empty string whereas `isLatestRevision` can use a `null` value and it did not work properly.
Thanks!
> Fix "on the fly" xref generation for empty revisions

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialHistoryParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/MercurialRepositoryTest.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
When looking at #3622 I realized that `PageConfig#getLastRevFromHistory()` retrieves complete history for given file only to throw most of it away. This change fixes that for Git. This is covered by tests in `PageConfigTest`.
The `ui` parameter is ignored in `GitRepository#getLastHistoryEntry()`, assuming this sort of operation will be quick.
> PageConfig#getLastRevFromHistory() should work with history efficiently

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/AccuRevHistoryParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/BazaarTagParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/CVSHistoryParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/DirectoryHistoryReader.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/History.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryEntry.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/CVSHistoryParserTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryEntryTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryTest.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/HistoryController.java
- opengrok-web/src/main/webapp/history.jsp
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/HistoryControllerTest.java
This change parallelizes the creation of file history cache for individual files, mimicking what is already done for renamed files.
On my laptop with i7-8665U (4 cores) and built in SSD I am seeing some decent speedup (6 vs 9 minutes) when creating history cache for the OpenSSL Git repository (renamed files on, merge commits on).
There is some potential for further speedup - the directories are still created sequentially and the process should avoid duplications.
> parallelize creation of file history cache for individual files

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java
> finish rename of executor for individual files

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryEntry.java
This is another follow up change to #3636. The removal of tags in `HistoryEntry` does not cause a functional problem with old history cache however produces warning messages when deserializing these objects as visible in  `FileHistoryCacheTest#testReadCacheValid()`:
```
java.lang.NoSuchMethodException: <unbound>=HistoryEntry.setTags("1.6.4, 1.6.3, 1.6.2, 1.6.1, 1.6.0");
Continuing ...
...
```
> reintroduce setTags() in HistoryEntry

- opengrok-web/src/main/java/org/opengrok/web/Scripts.java
- opengrok-web/src/main/webapp/default/style-1.0.3.css
- opengrok-web/src/main/webapp/httpheader.jspf
- opengrok-web/src/main/webapp/js/utils-0.0.41.js
- opengrok-web/src/main/webapp/menu.jspf
- opengrok-web/src/main/webapp/settings.jsp
This is an attempt to introduce user settings page which would allow every user to slightly modify their OpenGrok experience in a nicer way (i.e. not using cookies). It uses local storage to store the values which should be persisted for a long time unless user explicitly clears them.
This change just introduces suggester enabled/disabled checkbox and is meant to be a founding stone for more things like:
- suggester configuration (show projects, speed time, number of results, min chars, ...)
- font type or size
- line spacing
- color themes
- default project
- ...
https://github.com/oracle/opengrok/wiki/Cookies will need to be modified.
Tested in Chrome and Safari.
Thanks!
> Add user-specific settings page

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/BoundaryChangesets.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/BoundaryChangesetsTest.java
This change increases the default counts of changesets in history cache chunks. In general this is hard to get right because this is inherently dependent on the input data (i.e. the resitories being indexed) and because of nested parallelism - both the history cache for repositories and individual files for each repository are processed in parallel. Also, by default the thread pool sizes for these parallelisms depend on the number of CPUs; the more CPUs, the more memory will be consumed. (maybe there is a way to flatten this using similar concept as `IndexerParallelizer` for the 2nd phase of indexing ? That would require some pre-processing such as creating the history cache directories.)
Lastly, this depends on the heap size available. The baseline I used is 8 GB however some users might …
> bump history cache chunk counts and make it tunable

- docker/start.py
- tools/src/main/python/opengrok_tools/reindex_project.py
Fixes this problem:
```
24-Jun-2021 13:27:17.091 INFO [Thread-11] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
24-Jun-2021 13:27:17.158 INFO [Thread-11] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
could not get configuration from web application on http://localhost:8080/
Exception in thread Sync thread:
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/scripts/start.py", line 350, in project_syncer
save_config(logger, uri, config_path)
File "/scripts/start.py", line 250, in save_config
config_file.write(config)
TypeError: write() argument …
```
> check None from get_configuration()

- tools/src/main/python/opengrok_tools/utils/opengrok.py
As visible in #3651 the API errors lack the information about what went wrong. This was bugging me for quite some time so let's fix that. Works like this now:
```
>>> import logging
>>> logger = logging.getLogger()
>>> from opengrok_tools.utils.opengrok import get_repos
>>> get_repos(logger, 'fooa', 'http://localhost:8080/surce/')
could not get repositories for project 'fooa': 404 Client Error:  for url: http://localhost:8080/surce/api/v1/projects/fooa/repositories
>>> 
```
> log the actual HTTP error from requests

- opengrok-web/src/main/java/org/opengrok/web/Scripts.java
- opengrok-web/src/main/webapp/js/utils-0.0.42.js
fixes #3603
Now it seems that hiragana terms work properly. I'm not sure if I made a mistake during my testing of #3603 or the new Lucene version made a difference.
This is just a quick hack to fix the suggester display. The problem was caused by hiragana characters being slightly taller than latin letters.
Thanks!
> Fix suggester display of hiragana terms

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryWithPerPartesHistory.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/RepositoryWithPerPartesHistoryTest.java
Introduces the `historyCachePerPartesEnabled` tunable to disable per partes history cache creation. This is handy for those who have repositories with sizeable history (either in terms of number of changesets or changed files or both; thinking hundreds thousands of changesets) and can throw lots of memory on the JVM (think tens of gigabytes) for the sake of speeding the indexing.
> add option to turn off per partes history cache

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
This was failing almost all the time on my mac and I remembered the problem to be elusive so I was ignoring it. The root cause seems to be different than #3276 and this only fixes the parallel execution problem.
Thanks.
> Fix testRemoveFileOnFileChange test

- docker/start.py
- tools/src/main/python/opengrok_tools/mirror.py
This change adds `--check_config` option to the `opengrok-mirror` command and performs mirror configuration check during Docker startup. If the config check fails, sync is disabled. For the time being this is better than exiting the container. Given the problems with #3650 most run it with `restart: always` and that would leads to infinite cycle.
> check mirror config in Docker

- tools/src/main/python/opengrok_tools/scm/repofactory.py
- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/test/python/test_mirror.py
As discovered in https://github.com/oracle/opengrok/issues/3664#issuecomment-883564423 , the `commands` part of the `opengrok-mirror` configuration has to be checked.
> add check for commands section of the mirror configuration

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/BoundaryChangesets.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryTest.java
This change fixes Git submodule detection. The `SubmoduleWalk` is not really suitable for this and is `RepositoryBuilder()` wrapper anyway.
fixes #3666.
Also I did some semi-related cleanup.
> detect Git submodules properly

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
As explained in https://github.com/oracle/opengrok/pull/3669#issuecomment-885519978
> avoid warning in case of mkdirs() races

- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/main/webapp/WEB-INF/web.xml
- opengrok-web/src/main/webapp/eforbidden.jsp
- opengrok-web/src/main/webapp/enoent.jsp
- opengrok-web/src/main/webapp/mast.jsp
This change performs the check for forbidden access right in `mast.jsp` in order to produce better looking forbidden page. Unlike the `enoent` page it does not add the full menu (a practice which I find confusing).
> revamp forbidden check

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
fixes #3689
The problem was that the new git history implementation was passing the relative path to the source directory instead of the file name. I also improved the url encoding while I was at it.
Thanks.
> Fix clicking on revision in annotation mode returns 400

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/plain/PlainAnalyzer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java
This change introduces time out for xref processing/generation. Also, I took the opportunity to join some short wrapped lines.
The default timeout will be 30 seconds (default ctags timeout is 10 seconds).
In the indexer log this will look like this:
```
2021-08-12 13:44:00.802+0000 WARNING t143 IndexDatabase.addFile: File '/solaris-userland/components/desktop/firefox/firefox-78.11.0/accessible/windows/msaa/HyperTextAccessibleWrap.cpp' interrupted--failed to gen
erate xref :java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
```
> introduce timeout for generating xrefs

- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/test/python/test_mirror.py
The recently added check for commands in `opengrok-mirror` configuration is too strict. Specifically, Teamware needs to accept a directory: https://github.com/oracle/opengrok/blob/7f430e467c592672b420a552530c6e091e5b87f3/tools/src/main/python/opengrok_tools/scm/teamware.py#L34-L47
While I could just remove the check for file, this still captures (rare) cases such as FIFOs and such. Possibly better approach would be to reach out to the `scm` module and perform per repository type check however I need a quick fix.
> allow directory in commands

- docker/start.py
- tools/src/main/python/opengrok_tools/mirror.py
When looking at #3709 I noticed that the `OPENGROK_NO_MIRROR` environment variable name is not shared properly between the main Docker program and the tooling. This change fixes that.
> share the OPENGROK_NO_MIRROR env var definition

- tools/src/main/python/opengrok_tools/scm/cvs.py
- tools/src/main/python/opengrok_tools/scm/git.py
- tools/src/main/python/opengrok_tools/scm/mercurial.py
- tools/src/main/python/opengrok_tools/scm/perforce.py
- tools/src/main/python/opengrok_tools/scm/repo.py
- tools/src/main/python/opengrok_tools/scm/repofactory.py
- tools/src/main/python/opengrok_tools/scm/repository.py
- tools/src/main/python/opengrok_tools/scm/svn.py
- tools/src/main/python/opengrok_tools/scm/teamware.py
- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/test/python/test_mirror.py
This change fixes `opengrok-mirror` configuration check for overridden commands. I decided not to check the validity of the overridden commands.
> fix opengrok-mirror configuration check in the presence of overridden commands

- opengrok-web/src/main/java/org/opengrok/web/Scripts.java
- opengrok-web/src/main/webapp/js/utils-0.0.43.js
When opening pages with a mast the header was covering part of the content. Example:
http://demo.opengrok.org/xref/OpenGrok/pom.xml?r=5ec8ffa7
http://demo.opengrok.org/xref/OpenGrok/
Based on https://github.com/oracle/opengrok/pull/1194 it seems the change was done to allow scrolling with space or arrow keys. It's still possible even without the explicit focus (tested in Chrome and Safari). And the scrollbar stays on the same position when page is refreshed (which is in my opinion an added bonus).
Thanks!
> Fix header overflow

- docker/start.py
The sync configuration runs `opengrok-mirror` always with the mirror config file so the file needs to be always present.
> always create mirror.conf

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryWithPerPartesHistory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java
This change adds progress reporting for file history cache. For repositories that support per partes history cache creation an annotation of the terminal changeset is added.
> report file history cache progress

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/BoundaryChangesets.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- tools/src/main/python/opengrok_tools/utils/command.py
> Capitalize first letter in done logs for easier grepping

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/PatternUtil.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/ProjectTest.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/main/webapp/history.jsp
This change makes it possible to configure bug/review links on per project level. Due to the way de-serialization of the `Project` objects works (setters are not called for unspecified properties), the getters have to be equipped with null checks and fall back to the global configuration. The code in `completeWithDefaults()` is used only when adding new projects in the indexer.
https://github.com/oracle/opengrok/wiki/Per-project-configuration will have to be updated.
Sample configuration:
```xml
<java version="11.0.4" class="java.beans.XMLDecoder">
<object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">
<void property="projectsEnabled">
<boolean>true</boolean>
</void>
<void property="projects">
<void method="put"> …
```
> allow to configure bug/review properties per project

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryFactory.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ConfigurationController.java
This change lowers the pressure on the system imposed by `HistoryGuru#invalidateRepositories()` by changing the concurrency level (the web app uses _parallelism_ which is not technically correct, I think) for the web app and avoiding repository tag construction in that code path. This is mainly targeting setting the configuration in the web app.
https://github.com/oracle/opengrok/wiki/Webapp-configuration will have to be updated.
> add tunable for concurrency level of repository invalidation 

- tools/src/main/python/opengrok_tools/projadm.py
When running `projadm -a` I ran into this:
```
File "/opengrok/dist/bin/venv/bin/opengrok-projadm", line 11, in <module>
load_entry_point('opengrok-tools==1.7.21', 'console_scripts', 'opengrok-projadm')()
File "/opengrok/dist/bin/venv/lib/python3.7/site-packages/opengrok_tools/projadm.py", line 346, in main
lock = FileLock(get_lock_file(args))
File "/opengrok/dist/bin/venv/lib/python3.7/site-packages/opengrok_tools/projadm.py", line 227, in get_lock_file
project_list.extend(args.delete)
TypeError: 'NoneType' object is not iterable
```
This change fixes that.
> be more robust in face of None

- opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginClassLoader.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryTest.java
This change cleans some of the issues reported by Sonar. Those were chosen somewhat randomly when drinking morning coffee :-)
> address some issues reported by Sonar

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
This is a follow-up to #3775 to prevent:
```
java.lang.IllegalStateException: getTagList() is null
at org.opengrok.indexer.history.Repository.assignTagsInHistory(Repository.java:322)
at org.opengrok.indexer.history.GitRepository.getHistory(GitRepository.java:558)
at org.opengrok.indexer.history.GitRepository.getLastHistoryEntry(GitRepository.java:476)
at org.opengrok.indexer.history.HistoryGuru.getLastHistoryEntry(HistoryGuru.java:240)
at org.opengrok.web.PageConfig.getLastRevFromHistory(PageConfig.java:1312)
at org.opengrok.web.PageConfig.getLatestRevision(PageConfig.java:1302)
at org.apache.jsp.list_jsp._jspService(list_jsp.java:288)
```
> do not throw IllegalStateException in web app

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java
Another issue reported by Sonar. Should not harm anything as this is about `svn info` output parsing.
> prohibit access to external entities in Subversion XML parsing

- dev/before_install
When looking at Sonar reports, it occurred to me that Mercurial is not installed for macOS builds. This change fixes that via HomeBrew.
> install Mercurial on macOS

- opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginFramework.java
This change should fix the "zip slip" issue in plugin framework reported by Sonar. Normally the plugin archives are considered trusted however a bit of sanitization does not hurt.
> sanitize class paths

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/plain/PlainAnalyzer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/plain/DefinitionsTokenStreamTest.java
As identified in #3782, the `DefinitionsTokenStream` should not be used with try-with-resources. This change attempts to suppress the Sonar warnings.
> suppress Sonar warnings about auto-closeable DefinitionsTokenStream

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
This change is proposed to shed more light on #3771. If the operation turns out to be time intensive, it might make sense to parallelize it.
> record the time needed to refresh search managers

- opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginFramework.java
Looks like the change to sanitize paths from the archive did not help w.r.t. Sonar warnings so this change adds error suppression.
> suppress warning about lack of sanitization

- opengrok-web/pom.xml
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/AnnotationController.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/HistoryController.java
- opengrok-web/src/main/java/org/opengrok/web/util/FileUtil.java
- opengrok-web/src/test/java/org/opengrok/web/util/FileUtilTest.java
This change should address https://lgtm.com/query/rule:5970070/project:20900009/lang:java/ and https://lgtm.com/query/rule:5970070/project:20900009/lang:java/ to prevent passing unsanitized user supplied data to lower layers.
> sanitize path in {History/Annotation}Controller

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/pascal/PascalAnalyzerFactoryTest.java
- Use only short form for kinds, the long form is deprecated
- Define new kinds with the --kinddef-<LANG> flag
- Harmonize kind names and descriptions
This is an attempt to address  #3764
Note:
The number of flags to ctags is huge. Maybe it would be worth writing all these options to an option file passed via --options=PATHNAME (as described [here](https://docs.ctags.io/en/latest/option-file.html#options-pathname-option))
In this case the file can be part of the repository.
> Update ctag language regexp

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/CtagsTest.java
- opengrok-indexer/src/test/resources/sources/terraform/test.tf
There is a warning during indexing:
```
WARNING: Error from ctags: ctags: Warning: regcomp [[:<:]]resource[[:space:]]*"([[:alpha:]][-_[:alpha:]]*)"[[:space:]]*"([[:alpha:]][-_[:alpha:]]*)"[[:space:]]*\{: Invalid character class name
```
which causes no tf definitions to be recognized.
Thanks!
> Fix terraform definitions regex

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/SuggesterConfig.java
Looks like some of the defaults can have the visibility lowered.
> lower member visibility in SuggesterConfig

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
For some reason await() is used with a timeout to wait indefinitely even though there is await() without a timeout.
> use await() in Indexer to wait indefinitely

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
This change adds file delete failure handing for the file containing the last revision for given repository.
> handle delete failure in FileHistoryCache

- dev/checkstyle/suppressions.xml
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Prefix.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/SearchHelperTest.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/main/java/org/opengrok/web/StatisticsFilter.java
- opengrok-web/src/main/webapp/history.jsp
- opengrok-web/src/main/webapp/list.jsp
- opengrok-web/src/main/webapp/more.jsp
- opengrok-web/src/main/webapp/search.jsp
This change converts `SearchHelper` into proper class, by reducing field visibility to `private` and introducing non-default constructor and getters/setters as necessary.
> reduce field visibility in SearchHelper

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
LGTM reports `Configuration#decodeObject()` as unsafe deserialization (in particular when accepting data from `ConfigurationController` which is authorized or localhost only - via `IncomingFilter`), however `ConfigurationClassLoader` contains set of allowed classes. This change should suppress this warning.
> suppress unsafe deserialization error in Configuration

- opengrok-web/src/main/java/org/opengrok/web/util/FileUtil.java
This change silences the LGTM warning for uncontrolled path in `toFile()`.
This was reported as false positive: https://github.com/github/codeql/issues/7277
> suppress path injection error

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/main/webapp/opensearch.jsp
- opengrok-web/src/main/webapp/rss.jsp
In opensearch and rss JSPs the `X-Forwarded-Host` request header is used to construct URLs which Sonar finds inappropriate. Rather than sanitizing I think it would be more prudent to supply the value from the configuration.
https://github.com/oracle/opengrok/wiki/Webapp-configuration#configuration-tunables will need to be updated.
> replace X-Forwarded-Host with configuration value

- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
- opengrok-web/src/main/java/org/opengrok/web/DiffData.java
- opengrok-web/src/main/java/org/opengrok/web/DiffType.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/main/webapp/diff.jsp
- opengrok-web/src/test/java/org/opengrok/web/DiffTest.java
This change is half-hearted attempt to address Sonar issues found in `DiffData` and push it away from being a dumb container class. I moved it (along with `DiffType`) to the `org.opengrok.web` package which allows to access the now package-private fields from `PageConfig` and introduced bunch of getters to make `diff.jsp` work.
> DiffData cleanup

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AbstractAnalyzer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerFactory.java
Sonar says: 
> Constructors of abstract classes can only be called in constructors of their subclasses.
> lower the visibility of the constructor in AnalyzerFactory

- opengrok-indexer/src/main/jflex/analysis/plain/PlainFullTokenizer.lex
This change adds additional chars to the list of printable characters that is being recognized by full tokenizer.
This change will be especially useful for `""` queries that could now return proper results even for the following:
- `!= null`
- `new int[0]`
- `#!/bin/`
- `/**`
Thanks to @Aldarrion for the suggestion.
> Add additional printable chars to full index

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/History.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java
This change is aimed at aiding debugging of #1114. I suspect there is either something fishy in the history merging process or the forced history cache refresh in `get()`. Having the debug log capability in the release allows me to use in on our production instance.
I fixed some minor issues in the (neighboring) code and augmented the `Repositoryinfo` copy constructor (which might be actually relevant to the issue), otherwise the semantics should be retained.
Both the indexer and webapp would have to run with `FINEST` log level in order to get as much data about the problem as possible.
> log merged/written revisions in FileHistoryCache

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/ConfigMergeTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/RuntimeEnvironmentTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
This change removes the ability of `FileHistoryCache#get()` to modify the history cache as this can lead to cache corruption. I find this approach more robust than trying to add detection. This solves the problem described in https://github.com/oracle/opengrok/issues/1114#issuecomment-985059373
> FileHistoryCache#get() should not modify history cache

- opengrok-web/src/main/webapp/repos.jspf
This change should address the `Web:TableWithoutCaptionCheck` Sonar warning. The caption/description/label should be hidden yet accessible so I used the advice from https://stackoverflow.com/a/55861224/11582827
> add label to the tables in repos.jspf

- opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryTest.java
This change refactors a test to make sure it tests exception throwing in right piece of code. `getRepository()` can throw `IOException` however this is not the method tested.
> refactor to avoid multiple exceptions in single lambda

- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/main/webapp/xref.jspf
This change should silence Sonar warning about missing the `alt` attribute in images in `xref.jspf`.
> add alt attribute to images in xref

- opengrok-web/src/main/webapp/default/style-1.0.4.css
- opengrok-web/src/main/webapp/history.jsp
- opengrok-web/src/main/webapp/more.jsp
- opengrok-web/src/main/webapp/search.jsp
This change addresses Sonar reported issue by moving the `<b>` style into CSS. I did not bother with bumping CSS version as there has been no release since the last version change.
> move bold style into CSS

- opengrok-web/src/main/webapp/help.jsp
Thinking about the semantic HTML tags once again, I think the use of `<strong>` in most of the pages is wrong. This change replaces the use of `<strong>` with `<code>` which I find more appropriate for search examples in the help page.
> use code instead of strong in the help page

- opengrok-web/src/main/webapp/diff.jsp
- opengrok-web/src/main/webapp/history.jsp
- opengrok-web/src/main/webapp/menu.jspf
- opengrok-web/src/main/webapp/search.jsp
This change adds `<table>` descriptions to silence Sonar warnings.
> add table descriptions to JSPs

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
- suggester/src/main/java/org/opengrok/suggest/popular/impl/chronicle/ChronicleMapAdapter.java
Sonar reports some closeable resources as not closed in multiple code blocks. I believe these are all false positives and the resources should not be closed as they are part of a structure/object. This change suppresses these warnings.
> suppress 'Use try-with-resources or close' Sonar warning

- opengrok-web/src/main/webapp/search.jsp
Another round of `search.jsp` cleanup.
> search.jsp cleanup

- apiary.apib
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
- opengrok-web/src/main/java/org/opengrok/web/api/ApiTask.java
- opengrok-web/src/main/java/org/opengrok/web/api/ApiTaskManager.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ConfigurationController.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/StatusController.java
- opengrok-web/src/test/java/org/opengrok/web/api/ApiTaskManagerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/ApiTaskTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ApiUtils.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ConfigurationControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SearchControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/StatusControllerTest.java
- tools/src/main/python/opengrok_tools/projadm.py
- tools/src/main/python/opengrok_tools/utils/opengrok.py
- tools/src/main/python/opengrok_tools/utils/restful.py
This change introduces very simple framework for asynchronous API requests and adapts some of the API endpoints to use it. I made some tradeoff decisions like:
- there is no way how to pass output/result from an API task so far
- the clients need to employ busy wait in order to await the final state of an API task
- the cleanup of the resources associated with an API task is explicit (DELETE)
https://github.com/oracle/opengrok/wiki/Indexer-configuration#indexer-tunables will have to be updated with `connectTimeout` and `apiTimeout`.
> asynchronous API

- opengrok-web/src/main/java/org/opengrok/web/api/ApiTask.java
- opengrok-web/src/main/java/org/opengrok/web/api/ApiTaskManager.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ConfigurationController.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/StatusController.java
- opengrok-web/src/test/java/org/opengrok/web/api/ApiTaskManagerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/ApiTaskTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ApiUtils.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/StatusControllerTest.java
This change is follow up to the asynchronous API introduction in #3853. It adds the possibility to set payload in the final response. Either to the string representation of an exception (if one was thrown) or the string representation of object returned from the `Callable`.
> deal with exceptions in asynchronous API tasks

- pom.xml
The `dependency-check-maven` plugin has started failing quite a lot on macOS recently due to connection timeouts. While this may not fix this, it is good to update.
> update dependency-check-maven to 6.5.1

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/History.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryLookup.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryTest.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
When browsing FreeBSD project (`main` branch from https://github.com/freebsd/freebsd-src) on internal OpenGrok instance, I noticed that getting xrefs takes way too long - usually bunch of seconds. When looking at what the web app is doing, I noticed CPU load spikes and `jstack` revealed that the web app actually retrieved the revision string by getting the history via repository specific code:
```
"http-nio-8080-exec-5982" #237111 daemon prio=5 os_prio=64 cpu=3475.16ms elapsed=49069.29s tid=0x000000001359a800 nid=0x3aef1 runnable  [0x00007ff2e0556000]
java.lang.Thread.State: RUNNABLE
at java.util.zip.Inflater.inflateBytesBytes(java.base@11.0.7-internal/Native Method)
at java.util.zip.Inflater.inflate(java.base@11.0.7-internal/Inflater.java:385)
- locked <0x00007ff851064fd0> (a …
```
> use history cache when getting last revision of a file

- plugins/src/main/java/opengrok/auth/entity/LdapUser.java
- plugins/src/main/java/opengrok/auth/plugin/AbstractLdapPlugin.java
- plugins/src/main/java/opengrok/auth/plugin/LdapUserPlugin.java
- plugins/src/test/java/opengrok/auth/plugin/LdapUserPluginTest.java
I decided to store the negative "flag" in the `LdapUser` object itself as an attribute (as opposed to e.g. having the `attributes` field being `null` - this brings all kinds of trouble along the way). This also means that the negative cache is per session. In Tomcat the default session duration is 30 minutes however the authnz changes on the server/identity side are usually not fast either.
> negative cache for LdapUserPlugin 

- apiary.apib
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/ApiUtils.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ApiUtils.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
This change makes the `/projects/{project}/indexed` API endpoint asynchronous. I decided to leave the suggester rebuild in a separate thread.
> make markIndexed() asynchronous

- tools/src/main/python/opengrok_tools/sync.py
- tools/src/main/python/opengrok_tools/utils/commandsequence.py
- tools/src/main/python/opengrok_tools/utils/readconfig.py
- tools/src/test/python/test_command_sequence.py
This change should catch more invalid configurations of `opengrok-sync`. It introduces the `CommandConfigurationException`.
Looks like this:
```
$ opengrok-sync -c sync-invalid.yml 
Assuming directory: /var/opengrok/src
Invalid configuration: command 'foo' is not a dictionary
```
> check commands structure in CommandSequenceBase()

- tools/src/main/python/opengrok_tools/mirror.py
- tools/src/main/python/opengrok_tools/projadm.py
- tools/src/main/python/opengrok_tools/reindex_project.py
- tools/src/main/python/opengrok_tools/sync.py
- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/main/python/opengrok_tools/utils/opengrok.py
- tools/src/main/python/opengrok_tools/utils/restful.py
- tools/src/test/python/test_restful.py
This change addresses a problem with checking response status:
```
could not delete project 'foo' in web application: 'Response' object has no attribute 'status'
```
and also moves the timeout defaults to the programs.
> cleanup timeout handling in tools

- tools/src/main/python/opengrok_tools/scm/repo.py
- tools/src/main/python/opengrok_tools/scm/repository.py
- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/test/python/test_mirror.py
While playing with `repo` for #3872, I discovered the support for it is broken in `opengrok-mirror`. Firstly, the `RepoRepository`  init function has wrong order or arguments, secondly the `repo` synchronization should not descend into sub-repositories.
> fix repo repository mirroring

- tools/src/main/python/opengrok_tools/sync.py
Forgot to set the default for `opengrok-sync` in PR #3866.
> set default for API response timeout in opengrok-sync

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-web/src/main/webapp/index.jsp
The methods for checking whether to display repositories/projects on the index page should be called `isDisplayRepositories()` to match the boolean.
> rename displayRepositories getter to match the return type

- plugins/src/main/java/opengrok/auth/plugin/LdapAttrPlugin.java
- plugins/src/main/java/opengrok/auth/plugin/entity/User.java
- plugins/src/test/java/opengrok/auth/plugin/LdapAttrPluginTest.java
This change fixes a small problem in `LdapAttrPlugin` by avoiding variable shadowing, that could make it harder to follow the code.
> avoid variable shadowing in LdapAttrPlugin + nits

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Annotation.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SCCSRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SCCSRepositoryAuthorParser.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/SCCSRepositoryTest.java
Looking at the output from the `SCCSRepositoryTest#testAnnotation()` I can see a warning:
```
WARNING: Non-zero exit status 1 from command [sccs prs -e -d $':I: :P:' /tmp/source11618603591071727860/teamware/main.c] in directory /tmp/source11618603591071727860/teamware: prs: Cannot open SCCS file SCCS/s.:I: :P: for reading : No such file or directory
```
and also looking at the test it does not assert the authors in the `Annotation` object which is why this went uncovered.
The problem is that the 'cssc' implementation of SCCS requires the `-d` and its optarg to be single argument (as opposed to the SCCS implementation on Solaris):
```
$ sccs -V
sccs from GNU CSSC 1.4.1
$Id: sccs.c,v 1.44 2007/12/19 00:21:14 jay Exp $
SccsPath = 'SCCS'
SccsDir = ''
Default prefix for SCCS subcommands is …
```
> fix getAuthors() in SCCSRepository

- tools/src/main/python/opengrok_tools/utils/commandsequence.py
- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/main/python/opengrok_tools/utils/opengrok.py
Instead of catching specific exceptions (like `HTTPError` or `ReadTimeout` or `Timeout`), I chose to catch `RequestException` which encompasses all exceptions coming from `requests.exceptions`. Tested with `toxiproxy`:
```
$ toxiproxy-server
INFO[0000] API HTTP server starting                      host=localhost port=8474 version=2.1.4
...
$ toxiproxy-cli create tomcat -l localhost:33333 -u localhost:8080
Created new proxy tomcat
$ toxiproxy-cli toxic add tomcat --toxicName latency_downstream -t latency -a latency=5000
Added downstream latency toxic 'latency_downstream' on proxy 'tomcat'
$ toxiproxy-cli list
Name			Listen		Upstream		Enabled		Toxics
======================================================================================
tomcat			127.0.0.1:33333	localhost:8080		enabled		1 …
```
> handle requests exceptions gracefully

- tools/src/main/python/opengrok_tools/utils/restful.py
Fixes a logic problem introduced in 959b34e9. This could lead to false warnings produced by the Python tools such as:
```
$ opengrok-projadm --async_api_timeout 300 -a openssh-1
Adding project openssh-1
API request still not completed after 1 seconds: <Response [202]>
could not add project 'openssh-1' in web application
```
> return response from call_finished()

- docker/sync.yml
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
- tools/src/main/python/opengrok_tools/mirror.py
- tools/src/main/python/opengrok_tools/scm/git.py
- tools/src/main/python/opengrok_tools/scm/repository.py
- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/main/python/opengrok_tools/utils/opengrok.py
- tools/src/test/python/test_mirror.py
This change adds the `--strip-outgoing` CLI option and `strip_outgoing` config option (both global and per project) to `opengrok-mirror`. When set to true, the outgoing changesets (in repositories where this option is in effect and where supported) will be stripped and project data will be deleted (not the source code, just index/xrefs/cache) so that the project can be reindexed from scratch. This is handy in situations when mirroring a repository that has its history frequently rewritten and not caring about the reindex time (the project will disappear from the UI after its data is deleted. It will reappear after reindex automatically). So far only Git is supported, although this should be possible to implement also for Mercurial and other changeset based SCMs.
> --strip-outgoing option for opengrok-mirror

- tools/src/main/python/opengrok_tools/scm/git.py
When testing the outgoing changes handling with internal Linux UEK repository, a changeset that had no parent was wrongly detected as outgoing. This change fixes that.
Also, I realized that `git fetch` is needed before checking the outgoing changes.
> outgoing check needs to take current branch into account

- tools/src/main/python/opengrok_tools/utils/mirror.py
When introducing the changes for outgoing check+strip I forgot to add handling for top level repositories, breaking AOSP mirroring. This change fixes that.
> terminate the outgoing check for top level repository

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
This change makes the project/history data deletion softer w.r.t. `HistoryGuru` structures - these operations leave them alone so a project can be reindexed without having to refresh the structures.
Specifically, it allows one to run `opengrok-projadm add` and then `opengrok-sync` with `opengrok-mirror` using `--strip-outgoing` without having the history view disappear after the outgoing changes are stripped (and project data deleted) and the project reindexed from scratch.
> do not clear HistoryGuru structures on project data delete

- tools/src/main/python/opengrok_tools/mirror.py
- tools/src/main/python/opengrok_tools/reindex_project.py
- tools/src/main/python/opengrok_tools/sync.py
- tools/src/main/python/opengrok_tools/utils/log.py
This change adds formatter to some of the Python tools so that default values of options are printed in help, e.g.:
```
$ opengrok-mirror -h
...
--api_timeout API_TIMEOUT
Set response timeout in seconds for RESTful API calls (default: 3)
--async_api_timeout ASYNC_API_TIMEOUT
Set timeout in seconds for asynchronous RESTful API calls (default: 300)
```
> print default values of options

- docker/sync.yml
- tools/src/main/python/opengrok_tools/mirror.py
- tools/src/main/python/opengrok_tools/projadm.py
- tools/src/main/python/opengrok_tools/sync.py
- tools/src/main/python/opengrok_tools/utils/commandsequence.py
- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/main/python/opengrok_tools/utils/patterns.py
- tools/src/main/python/opengrok_tools/utils/restful.py
- tools/src/main/python/opengrok_tools/utils/utils.py
- tools/src/main/python/opengrok_tools/utils/webutil.py
- tools/src/test/python/test_command_sequence.py
- tools/src/test/python/test_mirror.py
- tools/src/test/python/test_restful.py
Changes the structure of API call configuration for `opengrok-sync` and `opengrok-mirror` to dictionary.
Example configuration for `opengrok-sync`:
```yml
commands:
- call:
uri: '%URL%/api/v1/messages'
method: POST
data:
messageLevel: warning
duration: PT1H
tags: ['%PROJECT%']
text: resync + reindex in progress
- command: ["/bin/sleep", "60"]
- call:
uri: '%URL%/api/v1/messages?tag=%PROJECT%'
method: DELETE
data: 'resync + reindex in progress'
headers:
'Content-type': 'text/plain'
api_timeout: 3
async_api_timeout: 30
```
The `api_timeout`/`async_api_timeout` keys override the `--api_timeout`/`--async_api_timeout` options of `opengrok-sync`, respectively.
https://github.com/oracle/opengrok/wiki/Repository-synchronization will have to be updated.
> convert API call configuration to dictionary

- opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/impl/SuggesterServiceImpl.java
- suggester/src/main/java/org/opengrok/suggest/Suggester.java
- suggester/src/test/java/org/opengrok/suggest/SuggesterTest.java
When writing https://github.com/oracle/opengrok/discussions/3928#discussioncomment-2530471 I realized it would not hurt to be more careful with the collection passed to `Suggester#init()`.
> make sure Suggester#init() does not receive duplicate entries

- apiary.apib
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SystemController.java
The API endpoint is redundant and causes suggester to be rebuilt twice in case of per project handling.
> remove /system/refresh API endpoint

- tools/src/main/python/opengrok_tools/mirror.py
- tools/src/main/python/opengrok_tools/sync.py
- tools/src/test/python/test_sync.py
After releasing 1.7.31 with the incompatible change to the API call configuration (#3924) used by both `opengrok-mirror` and `opengrok-sync`, I realized that only `opengrok-mirror` has an option to check the configuration. This change adds `--check_config` to `opengrok-sync` so they are on par.
> add --check_config to opengrok-sync

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/CVSRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/CVSRepositoryTest.java
This change transforms the implementation of `CVSRepository#getHistoryGet(String parent, String basename, String rev)` into `CVSRepository#getHistoryGet(OutputStream out, String parent, String basename, String rev)` so that getting contents of older revisions actually works.
This is done because `HistoryGuru#getRevision()` (used by `xref.jsp`) calls the 4-arg version and `CVSRepository` extends `RCSRepository` which implements it.
I did a bit of cleanup in other files as well.
> make sure getHistoryGet() implementations for CVSRepository are aligned

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/OptionParser.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/OptionParserTest.java
This change makes sure the indexer option descriptions are short enough to fit on a terminal with number of columns close to standard terminal.
> Option parser vs long descriptions

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/CVSHistoryParser.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/CVSHistoryParserTest.java
This change makes the code in `CVSHistoryParser` a bit more resilient. While there I refactored the code and added a test for per directory history.
fixes #957.
> match the exact number of dashes when parsing CVS history

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerRepoTest.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/HistoryControllerTest.java
This change returns power to the `HistoryGuru` w.r.t. fallback to the repository method when getting history. Previously this was done in `FileHistoryCache`, meaning any implementation would have to perform the fallback (and associated checks) which does not make sense. History cache should be just that.
Discovered when looking at #3953 so this also includes metering and logging for fetching last history entry.
> return power to the HistoryGuru

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexCheck.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexCheckTest.java
This change prevents unnecessary error message when starting the webapp with empty data directory.
> handle empty data directory in index check

- tools/src/main/python/opengrok_tools/deploy.py
- tools/src/test/python/test_deploy.py
This change allows to use `opengrok-deploy` in a way so that the target file path does not have all path components created.
> create all directories in deploy_war()

- apiary.apib
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Group.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/GroupsController.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/GroupsControllerTest.java
This change introduces API endpoints for project groups. This chunk of changes contains endpoints for querying various group related data.
The authorization is done via `IncomingFilter`.
Approaches #2516.
> add API endpoint for project groups

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
This change adds various log statements that should help when debugging web app problems. A user that had the 'History' and 'Annotate' links greyed out inspired me.
The `PageConfig#hasAnnotations()` was converted to use `HistoryGuru#hasAnnotation()`.
Also, I unsplit some lines and tidied the code.
The log level for the added messages is mostly FINE or FINEST, to be used with https://github.com/oracle/opengrok/wiki/Debugging#web-application
> add logging to debug webapp problems

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RCSRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/FileExtraZipper.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/UtilTest.java
- opengrok-web/src/main/java/org/opengrok/web/DirectoryListing.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
When working on #3990, I noticed that the 'H A D' links are printed irrespective to whether history for given repository is enabled. This change fixes that.
Also, I did some cleanup in related classes.
> display 'H A D' links in the webapp sensibly

- tools/src/main/python/opengrok_tools/scm/git.py
- tools/src/test/python/test_mirror_incoming_retval.py
This changes the way how incoming check for Git is done in the tools, particularly `opengrok-mirror`. This should provide some better robustness.
> reimplement incoming check via git log

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryFactory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/ProjectTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/RuntimeEnvironmentTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/RepositoryInfoTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/SubversionRepositoryTest.java
This change introduces project/repository properties for setting username/password. Currently this is used only for Subversion, where it replaces the environment variables used so far (`OPENGROK_SUBVERSION_USERNAME`, `OPENGROK_SUBVERSION_PASSWORD`). This impacts both indexer and the webapp.
This is a departure from global username/password towards per project username/password. While technically the username/password can be defined on repository level, the code is not ready for this just yet (`RepositoryInfo#fillFromProject()`) and also it is not clear whether this level of granularity is actually needed.
Example of per project [read-only configuration](https://github.com/oracle/opengrok/wiki/Read-only-configuration) with username/password:
```xml …
```
> make username/password configurable on project/repository level

- Dockerfile
This change should make it possible to have `ssh://` as Git origin in the Docker container.
> add openssh-client package to the docker image

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryFactory.java
This change improves logging of repository invalidation. Example:
```
20-Jul-2022 18:15:06.645 FINE [RMI TCP Connection(6)-127.0.0.1] org.opengrok.indexer.history.HistoryGuru.invalidateRepositories invalidating 3 repositories
20-Jul-2022 18:15:06.825 INFO [RMI TCP Connection(6)-127.0.0.1] org.opengrok.indexer.util.Statistics.logIt Done invalidating repositories (3 valid, 3 working) (took 178 ms)
```
> improve logging for repository invalidation

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/executables/JarAnalyzerTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/RuntimeEnvironmentTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexCheckTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseSymlinksTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerRepoTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/search/SearchEngineTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/search/context/SearchAndContextFormatterTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/search/context/SearchAndContextFormatterTest2.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/SearchHelperTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/UtilTest.java
- opengrok-web/src/test/java/org/opengrok/web/DiffTest.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/AnnotationControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/FileControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/HistoryControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/RepositoriesControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerProjectsDisabledTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerTest.java
This change removes the automatic index "optimization" (a.k.a. reduction of segment count for given index to 1) at the end of the indexing. The outcome is reduced indexing time - indexing [linux kernel repo](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git) with history off takes 06:49 minutes, out of which 50 seconds is the "optimization" step; with the step off, the indexing time is 6:03 minutes, which means 12 % improvement. On the other hand, it might theoretically slow down the search a bit and also the index size might increase - in multi segment index, each segment typically contains deleted documents. These are expunged on segment merge which happens during indexing. Comparing the size of the index of the linux kernel repository without and with the changes, …
> make index database "optimization" explicit operation

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/IndexSearcherFactory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/SuperIndexSearcherFactory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/DirectoryHistoryReader.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexAnalysisSettingsAccessor.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/NumLinesLOCAccessor.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/SearchEngine.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java
For multi-segment indexes, it is desirable to use [`IndexSearcher` with an executor](https://lucene.apache.org/core/8_8_1/core/org/apache/lucene/search/IndexSearcher.html#IndexSearcher-org.apache.lucene.index.IndexReader-java.util.concurrent.Executor-) so that the segments can be search in parallel.
This change addresses both indexer and webapp. For the former, the threads created should respect indexing parallelism level, for the latter the already existing search executor fixed thread pool should be used.
In a way this fixes the situation with `ThreadpoolSearcherFactory` - even though it is used to create `IndexSearcher` objects with a executor, these objects are not really used for searching (see #4009).
I verified with debugger/decompiler in IDEA that UI based searches that go through …
> make sure all IndexSearcher instances use an executor

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/SuperIndexSearcher.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/SuperIndexSearcherFactory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/DirectoryHistoryReader.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/SearchEngine.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/search/SearchEngineTest.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/impl/SuggesterServiceImpl.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/FileControllerTest.java
This change, or rather set of changes, purges all unnecessary `FSDirectory.open()` calls from all webapp related classes, replacing the related code blocks with calls to retrieve `(Super)IndexSearcher` instances (that can be used to get `IndexReader` instances). This should speed up the webapp a bit by avoiding the syscalls and I/O related to opening the index files.
As for the first part of https://github.com/oracle/opengrok/issues/4009#issue-1317000722 (about the `MultiReader` relationship to `IndexSearcher`s), I think it is not in dire need of addressing.
> improve Index searcher efficiency

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
The search Executor used for index searches performed during indexing since PR #4008 has to be shutdown at the end of the indexing, otherwise the indexer will hang in JVM after printing the 'Indexer finished' message.
The thread list in such case is visible in [jstack.log](https://github.com/oracle/opengrok/files/9192939/jstack.log). This change fixes that.
> shutdown search executor at the end of indexing

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/OpenGrokThreadFactory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/BoundedBlockingObjectPool.java
- opengrok-web/src/main/java/org/opengrok/web/api/ApiTaskManager.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/impl/SuggesterServiceImpl.java
- opengrok-web/src/test/java/org/opengrok/web/api/ApiTaskManagerTest.java
- plugins/src/main/java/opengrok/auth/plugin/util/WebHook.java
- suggester/src/main/java/org/opengrok/suggest/Suggester.java
This change introduces thread factory (succinctly called `OpenGrokThreadFactory`) that uses a common prefix to name threads and replaces various (hopefully all) thread pool creations to use this factory. This will make it easier to identify threads spawned by OpenGrok (indexer or webapp).
> unify thread naming

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Group.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/GroupTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/ProjectTest.java
This change removes the upper case conversion of Project/Group names. It is not clear to me why it was there in the first place.
> make Project/Group comparison case sensitive

- docker/start.py
When deploying the Docker image with `URL_ROOT: '/source'` the container will run into an exception and not continue to start.
This commit edits the check, to allow setting `URL_ROOT: '/source'``.
The reason for this is the check in `start.py` if the url root is `/source`. But the string is stripped of slashes in the method `set_url_root`.
Relevant logging message:
```
2022-09-21 06:28:21,947    DEBUG opengrok_tools | URL_ROOT = source
2022-09-21 06:28:24,888    DEBUG opengrok_tools | Setting up redirect from /source to 'source'
Exception in thread Sync thread:
File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
self.run()
File "/usr/lib/python3.10/threading.py", line 946, in run
self._target(*self._args, **self._kwargs)
File …
```
> Fix check if url root is 'source'

- .github/workflows/docker.yml
- dev/docker.sh
- dev/dockerhub_readme.py
This change fixes Docker hub README update. Before this change it failed because the payload was not actually formed JSON even though the Content-type header claimed so. Originally https://github.com/christian-korneck/docker-pushrm based Github action was used, however this was not possible.
As mentioned on https://stackoverflow.com/a/58478262/11582827 , it would be better if the conditional in the Github workflow was based on the `release` build type however the workflow needs to work for other types as well.
> use docker pushrm to update README on Docker Hub

- docker/periodic_timer.py
- docker/start.py
This is an attempt to fix #4037. The main change is to replace `threading.Event` with `threading.Condition`, in this case wrapped in a helper class (adapted from the Python cookbook).
```
docker run -e REST_TOKEN=foo -e SYNC_PERIOD_MINUTES=1 \
-v /var/opengrok/src.openssl:/opengrok/src \
-v /var/tmp/opengrok-dev-data:/opengrok/data 
-v $PWD/opengrok-vladak-scratch/docker:/scripts \
-p 5000:5000 \
opengrok-dev
```
Also triggered the reindex via:
```
curl -H 'Authorization: Bearer foo' http://localhost:5000/reindex
```
to make sure the manually triggered reindex still works.
> use Condition instead of Event for periodic event

- tools/src/main/python/opengrok_tools/utils/mirror.py
- tools/src/test/python/test_mirror.py
Sometimes it makes sense to take `opengrok-mirror` out of the loop (`opengrok-sync`) completely and just make it passthru. This change adds the `ignore` per project tunable that does that.
Sample config:
```yml
projects:
foo:
ignore: true
```
> add opengrok-mirror tunable to ignore a project

- tools/src/main/python/opengrok_tools/utils/mirror.py
Forgot to add the new property in #4061 to the list of allowed project properties in `opengrok-mirror` configuration.
> add ignore property to project configuration check

- docker/periodic_timer.py
- docker/start.py
This change fixes how the Docker startup program works with the recently introduced `PeriodicTimer` class. Firstly, the instance need to be referenced with `global`. Also, it should be created before the sync threads and the Flask app are started. Also, it should be possible to trigger reindex even though the periodic timer is set to 0.
> fix event handling in Docker (redux)

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/LazilyInstantiate.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/SubversionHistoryParserTest.java
This change mainly converts `SubversionRepository` to use lazy instantiation of the `working` flag so that is checked once per JVM run. This should speed up repository invalidation and other operations a bit.
Also contains improved logging for `HistoryGuru#hasHistory()`.
> Subversion fixes

- tools/setup.cfg
- tools/setup.py
The tools build has started failing recently due to exception within [pytest-xdist](https://github.com/pytest-dev/pytest-xdist) used to run the tests for the Python tools:
```
maximum crashed workers reached: 32
[gw39] node down: Traceback (most recent call last):
File "/home/vkotal/opengrok-vladak-scratch/tools/target/.eggs/execnet-1.9.0-py3.8.egg/execnet/gateway_base.py", line 1084, in executetask
do_exec(co, loc)  # noqa
/home/vkotal/opengrok-vladak-scratch/tools/target/env/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecat  File "/home/vkotal/opengrok-vladak-scratch/tools/target/.eggs/pytest_xdist-2.5.0-py3.8.egg/xdist/remote.py", line 290, in <module>
ionWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer. …
```
> disable pytest-xdist for now

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileAnnotationCache.java
This change removes extra pair of single quotes in log message emitted in store().
> remove double quotes in log message in FileAnnotationCache

- Dockerfile
Until #4075 is properly resolved, the Docker image needs to stay at Tomcat 10.0.x.
> use Tomcat 10.0 in Docker image

- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
This is to prevent running with unsupported Tomcat version.
Should be reverted once #4075 is fixed.
> check Tomcat version during webapp deploy

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/AccuRevAnnotationParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/BazaarAnnotationParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/CVSAnnotationParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialAnnotationParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceAnnotationParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RCSAnnotationParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SSCMRepository.java
When running indexer to create annotation cache for some repositories, I noticed these log entries:
```
2022-10-31 14:46:38.034+0100 SEVERE t1253 MercurialAnnotationParser.processStream: Error: did not find annotation in line 1: [thunderbird-icon.png: binary file]
```
The log severity is too high. The SEVERE should be reserved for general indexer failures, not used for problems to create particular index  data.
Also, luckily, the output in this case contained the filename so one might be able to see what is going on, however sometimes this is not the case. A filename should be added to the log statement.
> decrease log level for annotation problems

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java
This change bumps the pool size for xref watcher from 1 to the indexer parallelism level (by default set to the number of CPUs in the system). This speeds up the indexing by about 20% when indexing the Linux kernel repository from scratch on my laptop with 8 CPUs and using `--threads 32` and not using `-H` (i.e. only 2nd phase of indexing was run).
before and after the change: ![indexer-before](https://user-images.githubusercontent.com/2934284/200050514-62e06576-6295-4cd4-8669-fc0fa96ddfd3.png)
> use indexing parallelism when creating xref watcher thread pool

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
Observing indexer run of Linux kernel with regular logging configuration, the directory creation log entries stand out a little bit:
```
INFO: Generating history cache for all repositories ...
Nov 04, 2022 2:10:40 PM org.opengrok.indexer.history.HistoryGuru createHistoryCacheReal
INFO: Creating history cache for 1 repositories
Nov 04, 2022 2:10:40 PM org.opengrok.indexer.history.HistoryGuru createHistoryCache
INFO: Creating history cache for /var/opengrok/src.linux/linux (GitRepository) without renamed file handling
Nov 04, 2022 2:11:25 PM org.opengrok.indexer.util.Statistics logIt
INFO: Done creating directories for {dir=/var/opengrok/src.linux/linux,type=git,historyCache=on,renamed=false,merge=false,annotationCache=off} (regular files for history till revision …
```
> use FINE to log directory creation task

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceRepository.java
This should make it more efficient to invalidate Perforce repositories and also provide warning in case the Perforce command is not working.
> use lazy instantiation of the working state of Perforce

- Dockerfile
- docker/README.md
Adds bunch of SCMs so that the Docker image is more usable.
The Perforce addition was based on https://github.com/oracle/opengrok/discussions/4090#discussioncomment-4060064 which I refined (notably to avoid using the deprecated `apt-key` command)
> add more SCMs to the Docker image

- opengrok-indexer/pom.xml
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/AbstractCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/AnnotationData.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Cache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileAnnotationCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java
This is another tradeoff I am going to do (trading space for speed). To change the serialization scheme for annotation cache, I had multiple requirements for the implementation:
- speedy enough not to be noticeable in the UI (tens of ms)
- robust and well maintained library
- easy to use from Java (i.e. without running external tools or defining serialization scheme by hand)
- ideally extendable with Java annotations and such
- space efficient without compression => potentially being usable in streaming mode
I did not have many requirements for the format itself, assumed it will be some binary format.
Looked at bunch of alternatives to discover Jackson (that is already used in the webapp) offers some binary serialization formats so I went with exploring these.
To measure the impact, I …
> use Smile to serialize AnnotationData

- Dockerfile
- opengrok-indexer/pom.xml
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/DummyHttpServletRequest.java
- opengrok-web/pom.xml
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
- opengrok-web/src/main/webapp/WEB-INF/web.xml
- opengrok-web/src/test/java/org/opengrok/web/CookieFilterTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerProjectsDisabledTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SystemControllerTest.java
- plugins/src/test/java/opengrok/auth/plugin/util/DummyHttpServletRequestLdap.java
- plugins/src/test/java/opengrok/auth/plugin/util/DummyHttpServletRequestUser.java
- pom.xml
This change addresses the lack of support for Tomcat 10.1. The biggest challenge were the Jackson-Jersey dependencies. I casually tested the UI when deployed on Tomcat 10.1.0 and also checked the search API, plus built a Docker image and let it run for a bit to see if the API calls done during resync do not blow up.
> add support for Tomcat 10.1

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/CtagsUtil.java
- opengrok-indexer/src/main/resources/sample.c
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/CtagsTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/CtagsUtilTest.java
- opengrok-web/src/main/resources/sample.c
- opengrok-web/src/test/java/org/opengrok/web/WebappListenerTest.java
This change modifies the Ctags check done by the `validateUniversalCtags()` so that it actually runs the ctags program on a known file that is temporarily placed under source root. This should avoid nasty surprises when installing ctags from snap.
Even though I changed that a bit, I don't like the intra-dependencies between `Ctags` and `RuntimeEnvironment`, specifically the fact that the `validateUniversalCtags()` sets the list of languages in the `RuntimeEnvironment` instance that is then used for running the ctags commands. This actually posed a problem when implementing this change as running the ctags program successfully needs the list (now a set) of languages - sort of chicken/egg problem. It would be cleaner to separate the initialization and validation even more, however for …
> more thorough Ctags validation

- dev/checkstyle/suppressions.xml
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/main/webapp/list.jsp
- opengrok-web/src/main/webapp/xref.jspf
This change adds bunch of meters for the xref handling. Inspired by https://github.com/oracle/opengrok/discussions/4137. Decided to pass on the decompression meter.
Looks like this:
```
xref_file_get_total{what="miss",} 2.0
xref_file_get_total{what="hits",} 3.0
xref_write_latency_seconds_count 2.0
xref_write_latency_seconds_sum 0.058302
xref_write_latency_seconds_max 0.002391
xref_dump_latency_seconds_max 0.001895
xref_dump_latency_seconds_count 5.0
xref_dump_latency_seconds_sum 0.074593
```
Fixes #4142.
> add xref performance meters

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/CtagsUtil.java
Windows build has failed with:
```
java.lang.NullPointerException
at org.opengrok.indexer.util.CtagsUtil.canProcessFiles(CtagsUtil.java:96)
at org.opengrok.indexer.util.CtagsUtil.validate(CtagsUtil.java:65)
at org.opengrok.indexer.util.CtagsUtilTest.testValidateWithInvalidExtraOptions(CtagsUtilTest.java:79)
```
This is because the process failure was actually detected like this:
```
WARNING: Error from ctags: ctags.exe: Unknown option: --fooBar
Jan 05, 2023 4:43:48 PM org.opengrok.indexer.analysis.Ctags readTags
WARNING: ctags: Unexpected end of file!
Jan 05, 2023 4:43:48 PM org.opengrok.indexer.analysis.Ctags readTags
WARNING: ctags exited with code: 1
Jan 05, 2023 4:43:48 PM org.opengrok.indexer.analysis.Ctags doCtags
WARNING: execution exception
java.util.concurrent.ExecutionException: …
```
> handle null returned from doCtags()

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
This change unifies scan depth handling across various use cases (the`-S` indexer option can be specified multiple times and takes a path as argument), fixing the regression introduced with parallel repository scanning.
Tested with projects enabled and source root directory (`/var/opengrok/src.depth`) that had single project (Git repository) and there was Mercurial repository 2 levels below the project:
```
/var/opengrok/src.depth/
└── securitylab
├── .git
│   ├── branches
│   ├── hooks
...
├── foo
│   └── bar
│       └── .hg
│           ├── cache
...
```
When running with `--depth 3` (the new default) 2 repositories were discovered, with `--depth 2` just the top level repository was discovered.
> normalize scan depth based on the number of path components

- opengrok-indexer/src/main/java/org/opengrok/indexer/util/CtagsUtil.java
- pom.xml
When running the indexer from a jar file, the recently added ctags check results in:
```
Jan 06, 2023 5:38:08 PM org.opengrok.indexer.index.Indexer main
SEVERE: Unexpected Exception
java.nio.file.FileSystemNotFoundException
at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
at java.base/java.nio.file.Path.of(Path.java:208)
at org.opengrok.indexer.util.CtagsUtil.getResourceFile(CtagsUtil.java:131)
at org.opengrok.indexer.util.CtagsUtil.canProcessFiles(CtagsUtil.java:77)
at org.opengrok.indexer.util.CtagsUtil.validate(CtagsUtil.java:65)
at org.opengrok.indexer.configuration.RuntimeEnvironment.validateUniversalCtags(RuntimeEnvironment.java:685)
at …
```
> handle resource as a stream for ctags check

- opengrok-indexer/src/main/java/org/opengrok/indexer/util/CtagsUtil.java
The temporary file located under source root needs to be more, er, temporary in nature, otherwise e.g. per project indexers running in parallel will stomp on each other.
> use true temporary file name for ctags validation

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
This change restores the use of the `fetchHistoryWhenNotInCache` indexer tunable as documented on https://github.com/oracle/opengrok/wiki/Indexer-configuration
> reinstate the use of the fetchHistoryWhenNotInCache indexer tunable

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/CacheUtil.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
When browsing the code, I noticed that the `null` value from `CacheUtil.getRepositoryCacheDataDirname()` is not handled in `FileHistoryCache#store()`. This change provides remedy by throwing `CacheException`. It might be better to throw the exception from `getRepositoryCacheDataDirname()`, however not in this change.
> handle cache directory failures

- opengrok-indexer/pom.xml
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileCollector.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexWriterConfigFactory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/IOUtils.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerVsDeletedDocumentsTest.java
- pom.xml
- suggester/pom.xml
- suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
This long awaited change fixes a regression in document traversal with multi-segment indexes. The main idea is to assemble the list of deleted uids and then skip them when traversing the index during indexing. For this I had to significantly change the traversal algorithm for history based reindex.
This will necessitate reindex from scratch to fix the negative LOC/Line counts and duplicate items in search results.
> skip deleted documents during index traversal

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerVsDeletedDocumentsTest.java
This change avoids deprecation warnings in `IndexDatabase` and related classes after the recent Lucene 9.x upgrade. These were introduced by #4182.
> adapt IndexDatabase to Lucene 9.x

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
- opengrok-indexer/src/test/resources/history/svnlog.dump
> Fix svn history for files which were in a renamed directory

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexCheck.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexCheckTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerVsDeletedDocumentsTest.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
Inspired by https://github.com/oracle/opengrok/issues/4180#issuecomment-1447625787 , I thought there could be a way how to check index(es) for live documents with the same path, within the indexer. By refactoring the test added in PR #4182, the indexer can now run the same check.
> add documents argument to --indexCheck

- opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java
Inspired by https://github.com/oracle/opengrok/issues/4180#issuecomment-1453765351, this change will log the documents found by a search at the `FINEST` level. The document ID and path will be logged so that one can see whether there are multiple documents with the same path and different ID.
Here's example of the output (for the second page of search results, hence the 25-37) range:
```
03-Mar-2023 17:48:01.868 FINEST [http-nio-8080-exec-124] org.opengrok.indexer.search.Results.createMap directory hash contents for search hits (25,37):
03-Mar-2023 17:48:01.875 FINEST [http-nio-8080-exec-124] org.opengrok.indexer.search.Results.createMap 5,631: /lucene/lucene/core/src/java/org/apache/lucene/index/PointValues.java
03-Mar-2023 17:48:01.876 FINEST [http-nio-8080-exec-124] …
```
> Search results debugging

- opengrok-indexer/pom.xml
- suggester/pom.xml
Saw a complaint during the build:
```
Warning:  The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
```
This change fixes that.
> commons-io relocated

- pom.xml
Upgrades the dependency-check Maven plugin to the latest version, hoping that the macOS Github Actions runner problems with downloading artifacts will go away.
> bump dependency check

- suggester/pom.xml
This change bumps xstream version due to vulnerabilities found in 1.4.19.
> bump xstream to 1.4.20

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerUtil.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/HostUtil.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/HostUtilTest.java
This change replaces the TCP port response check done when -U is specified with API check, specifically to get the configuration, which is in a scope that the indexer will need anyway.
Tested with:
- not listening port
- URL not pointing to the web app (otherwise valid)
- invalid URL (unknown scheme)
- non-existent hostname
- token
I raised the connect timeout (which is not also read timeout) to account for situations when running many instances of indexer in parallel (for per project reindex). Still, it might be useful to introduce special "ping" API endpoint for this check, because getting configuration can be slow sometimes.
> check webapp via API call

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/DefaultIndexChangedListener.java
This change unifies the logging displayed by the indexer when adding/removing files. In particular, it wraps the file paths in quotes as is the custom throughout the code base.
> unify and improve logging in DefaultIndexChangedListener

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerUtil.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/ApiUtils.java
- plugins/src/main/java/opengrok/auth/plugin/util/RestfulClient.java
This change ensures that the `connectTimeout` is used everywhere. Also, I converted some `Response` uses to try-with-resources.
> use connectTimeout for all API calls

- distribution/assembly.xml
This change removes the `opengrok-$version.jar` file from the distribution tarball. I'd say the risk of someone using the file to actually run the indexer is fairly small, as they would need to change the version on every upgrade/downgrade.
> remove opengrok-$version.jar file from the distribution tarball

- suggester/pom.xml
This change should disable the Google analytics reporting done via Chronicle Map. For testing, I performed basic suggester check on web app deployed with the changes.
> use a specific chronicle-analytics version to disable reporting

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
As stated on https://github.com/oracle/opengrok/issues/4206#issuecomment-1466196490, this adds the requirement to use -R along with --checkIndex.
> require -R for the --indexCheck

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
Ruminating about the webapp check some more, I realized that the check does not honor the `--connectTimeout` option. This change fixes that.
> honor connect timeout indexer option for webapp check

- opengrok-indexer/src/main/java/org/opengrok/indexer/util/HostUtil.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/HostUtilTest.java
This change fixes the confusion in connect timeout units for performing webapp live check when using the -U indexer option.
> fix units for the connect timeout

- apiary.apib
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/HostUtil.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SystemController.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SystemControllerTest.java
This change introduces new /system endpoints for getting the version and pinging the webapp. The latter is now used when the indexer checks whether the webapp is alive. Also, I raised the default connect/read timeout to 10 seconds.
> introduce more /system endpoints

- pom.xml
The dependency check negatively contributes to build stability. In particular, the macOS builds almost always fail the dependency check due to networking error for some reason. Lately, the check fails on all the other builds, usually with HTTP 503 error, possibly when downloading the CVE data. This change moves the check to a Maven profile so that it is not executed by default. The goal is to execute the profile from a periodic Github action, so that it does not impact common builds.
> move dependency check to profile

- tools/src/main/python/opengrok_tools/utils/utils.py
Do not error out when creating a directory and directory already exists.
I got an error while running the sync job. There was an error during git fetch, and while reporting error sync job failed when creating the logs directory.
```
processing of project 'xxxxx' failed
failed commands:
'opengrok-mirror -U http://localhost:8080/source -c /etc/mirror-config.yml xxxxx': 1
cannot create /tmp/logs directory
```
> tools: utils: do not error during directory creation if it exists

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryWithHistoryTraversal.java
This improves the logging of changeset traversal, esp. by adding the boundary changesets.
> improve log messages for changeset traversal

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/BoundaryChangesets.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialHistoryParserRevisionsOnly.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryWithPerPartesHistory.java
This change reports the progress when getting boundary changesets when the `--progress` indexer option is in effect. This is not optimal as the level used to report start/end messages is `FINE`, #3736 would have helped here.
> report progress when getting boundary changesets

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/BoundaryChangesets.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/Progress.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/ProgressTest.java
This change allows to set base log level for `Progress`. This is specifically handy for code that goes like this:
```java
LOGGER.log(Level.FINE, "starting operation foo", ...);
try (Progress = new Progress(...)) {
...
progress.increment();
}
LOGGER.log(Level.FINE, "operation foo finished", ...);
```
Previously, the `Progress` logged the messages with `INFO` etc. level which might be confusing.
With this change, when a log level is supplied as argument to the `Progress` constructor, it will be used as a base log level. For the above example:
```java
Level logLevel = Level.FINE;
LOGGER.log(logLevel, "starting operation foo", ...);
try (Progress = new Progress(..., logLevel)) {
...
progress.increment();
}
LOGGER.log(logLevel, "operation foo finished", ...);
```
the "buckets" used will …
> Progress log level shifting

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
This change parallelizes the index check performed by webapp on startup. The parallelism level is set to `getRepositoryInvalidationParallelism()` given the sort of similar task and considering that the repository invalidation is already done at that stage (when reading the configuration).
By default the newly introduced `indexCheckTimeout` tunable is set to 60 seconds.
The wiki with webapp configuration will have to be updated.
> parallelize projects index check

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
This should satisfy https://github.com/oracle/opengrok/security/code-scanning/30. The report contains wrong code how to fix this, so using the one from https://github.com/github/codeql/commit/660e6d70855fcdb62172e3d784cb7047bd07c0f3 (for some reason the CodeQL report uses stale data).
> check if file is relative to repository path using File.separator

- docker/README.md
- docker/start.py
This change introduces `API_TIMEOUT` environment variable, allowing to set API timeout value in seconds. It is not complete, as in project mode this will not be propagated to the per project indexer instances.
> make API timeout settable

- Dockerfile
- docker/start.py
- docker/sync.yml
- tools/src/main/python/opengrok_tools/sync.py
- tools/src/main/python/opengrok_tools/utils/command.py
- tools/src/main/python/opengrok_tools/utils/commandsequence.py
- tools/src/test/python/test_command.py
- tools/src/test/python/test_command_sequence.py
https://github.com/oracle/opengrok/discussions/4247#discussioncomment-5468707 inspired me to allow command argument substitution to use environment variables as values.
While making the change, I realized that the command structure is broken - it needs to be a dictionary for stuff like resource limits and argument substitution to work. The [per project workflow wiki](https://github.com/oracle/opengrok/wiki/Per-project-management-and-workflow) will have to be adapted.
Command configuration in YAML now looks like this:
```yaml
- command:
args: [cmd, "--foo", "%FOO%"]
limits: {RLIMIT_NOFILE: 1024}
args_subst: {"%FOO%": "$FOO"}
```
The `$` prefix in the `$FOO` value means that it will not be taken as literal; instead, the value of environment variable `FOO` will be taken.
> Docker tools timeout redux

- docker/start.py
As suggested in https://github.com/oracle/opengrok/discussions/4252#discussioncomment-5479257, Tomcat temporary directory should reside under OpenGrok data root in Docker container.
> make Tomcat use temporary directory under OpenGrok data root

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/CtagsTest.java
https://github.com/universal-ctags/ctags/pull/3684 includes better support for Terraform in Universal ctags so the extra definitions are no longer needed.
> adapt to new Ctags (Terraform support)

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/LatestRevisionUtil.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
This change exploits the recent change of `FileHistoryCache` serialization method to one that allows for sequential access. Here, the retrieval of the last `HistoryEntry` for given file from cache was changed to avoid getting complete history from the cache.
> make HistoryGuru#getLastHistoryEntry more efficient

- docker/start.py
The Docker environment variable merging needs to adapt to the changes from PR #4253. Ideally the Docker program should not be cognizant of the commands structure, however as hot fix this will suffice.
> fix environment propagation in Docker

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
When running indexer, I noticed single quotes to be unnecessarily repeated, such as:
```
org.opengrok.indexer.history.HistoryException: failed to get history for ''/ws-local-upgrade/AOSP/external/selinux/python/audit2allow/audit2why''
```
The style used in the code is to use single quotes for paths. This change provides remedy for `GitRepository` and `HistoryGuru`.
> unify path logging in GitRepository

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
This change should make the indexer more efficient when history cache is enabled.
> use HistoryGuru#getLastHistoryEntry() in AnalyzerGuru

- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
This is more of a hot fix as the proper fix would be to remove the `/mercurial/usr/closed` repository at the end of each test that added it.
> rescan the repositories in testListFiles()

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
This change avoids exception to be thrown when getting history for a directory.
> do not attempt to get history cache for directories

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
This change adds progress reporting when adding (scanning for) and invalidating repositories. The former is done without percentage reporting because it is happening on directory level and the number of directories is not known before hand, while the latter is done on repository level where the count is known in advance.
> report progress when adding/invalidating repositories

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java
This change alters the logging of repository information when creating history cache. The current logging merely reports repository type/path and whether renamed file handling is on, however all of this can be gotten from the `toString()` repository method with other useful fields, such as merge changeset handling.
While at it, I also performed some cleanup in related areas.
> log the full repository representation

- opengrok-web/src/main/webapp/diff.jsp
When trying to identify a change, I often use annotate view, then click the 'S' link to search for changes in particular changeset, then use the diff view for a file. To pinpoint the change, I often need to display annotations for older revision of the file (and repeat the cycle). To aid this, I added links to file revisions in diff view:
Not sure whether to shorten the revision IDs (in the parens), so leaving them as they are for now.
> add links to file revisions in side diff view

- apiary.apib
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/DirectoryEntry.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/DirectoryExtraReader.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/FileExtraZipper.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/DummyHttpServletRequest.java
- opengrok-web/src/main/java/org/opengrok/web/DirectoryListing.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/main/java/org/opengrok/web/api/ApiTaskManager.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/DirectoryListingController.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/SuggesterService.java
- opengrok-web/src/main/webapp/list.jsp
- opengrok-web/src/main/webapp/xref.jspf
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/DirectoryListingControllerTest.java
This change introduces directory listing API.
There are couple of limitations:
- only directories are supported at the moment, i.e. one cannot get the properties of individual file
- not possible to list source root directly
- There is no paging (like for the `/history` API endpoint); it is assumed that the number of entries in a directory is fairly low (hundreds of files).
- the tests ought to have bigger coverage (DTO entry comparison, with/without extras, with path descriptions, authorization test, etc.)
At one point I contemplated moving the HTML production to a JSP, like it is mentioned in the comment in `DirectoryListing#extraListTo()`, however decided not to because the tests rely on the HTML/XML parsing.
> directory listing API

- plugins/src/main/java/opengrok/auth/plugin/LdapAttrPlugin.java
- plugins/src/main/java/opengrok/auth/plugin/LdapFilterPlugin.java
This change avoids NPE in LDAP authorization plugins. Tested on the same system I reproduced the bug first.
> avoid NPE in LDAP authorization plugins by checking the attribute first

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
This change enables merge commits by default. The reason being is that they are frequently used and the view would be incomplete without these. Also, the default mode of operation should not be tailored for big deployments where it might matter performance wise.
Will require reindex from scratch due to history cache contents being changed.
As a side effect, the dates in directory listing will be taken from history cache by default.
> enable merge commits by default

- opengrok-web/src/main/webapp/list.jsp
- opengrok-web/src/main/webapp/xref.jspf
The directory listing latency falls under the `xref` thanks to how the path is constructed and to `StatisticsFilter`. This change adds a separate log and mater for directory listing. This might be useful to track down the latencies, esp. when using history cache to display dates/titles.
> add directory listing statistics

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/ConfigurationClassLoader.java
After deploying 1.12.1 with the groups changed to map, the indexer failed due to `TreeMap` not being included in the white list of classed allowed for `Configuration` serialization. This likely surfaced only after configuration merge.
> add TreeMap for Groups serialization

- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ConfigurationController.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ConfigurationControllerTest.java
This change fixes result codes for PUT API calls to the configuration endpoint.
> return correct results for configuration API calls

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
The comments in PR #4295 mentioned all-or-nothing semantics for getting the dates from history cache, however this is not how it works currently. This change fixes that.
> use the all-or-nothing semantics for filling directory entries

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
This change should speed up getting directory listing when history cache is used to get the dates/descriptions for files.
> parallelize filling directory entries

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
When investigating hung indexer, I noticed number of threads named `Thread-N` that had `Ctags#run()` in the stack trace. These were threads reading the error output from ctags processes and should be properly named, i.e. with the `OpenGrok` prefix. This change fixes that.
> set name for the ctags error thread

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
The Ctags error reader threads have double `OpenGrok-` prefix. This change fixes that.
> avoid double prefix in thread name

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/XrefWork.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/plain/PlainAnalyzer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/plain/XMLAnalyzer.java
When indexing AOPS, I [noticed that the indexer has a tail in which only bunch of CPUs are executing](https://github.com/oracle/opengrok/discussions/4038#discussioncomment-5771342). The stacks of these look like this: 
```
"ForkJoinPool-1-worker-79" #3746 daemon prio=5 os_prio=0 cpu=1774894.92ms elapsed=1995.46s tid=0x00007efd9c09f800 nid=0x5d51f runnable  [0x00007efbbdedc000]
java.lang.Thread.State: RUNNABLE
at org.opengrok.indexer.analysis.plain.XMLXref.yylex(XMLXref.java:918)
at org.opengrok.indexer.analysis.JFlexXref.write(JFlexXref.java:489)
at org.opengrok.indexer.analysis.TextAnalyzer.writeXref(TextAnalyzer.java:82)
at org.opengrok.indexer.analysis.plain.XMLAnalyzer.analyze(XMLAnalyzer.java:84)
at org.opengrok.indexer.analysis.AnalyzerGuru.populateDocument(AnalyzerGuru.java:627)
at …
```
> use xref timeout for XMLAnalyzer

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/OpenGrokThreadFactory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java
This change gives names to thread created by the `ForkJoinPool` in `IndexerParallelizer`. These threads look like this:
```
"OpenGrok-ForkJoinPool-46" #46 daemon prio=5 os_prio=0 cpu=467,38ms elapsed=2,20s tid=0x00007f206c003800 nid=0x3ca62 runnable  [0x00007f20d1aee000]
java.lang.Thread.State: RUNNABLE
at sun.nio.cs.UTF_8$Decoder.decodeArrayLoop(java.base@11.0.18/UTF_8.java:320)
at sun.nio.cs.UTF_8$Decoder.decodeLoop(java.base@11.0.18/UTF_8.java:414)
at java.nio.charset.CharsetDecoder.decode(java.base@11.0.18/CharsetDecoder.java:576)
at sun.nio.cs.StreamDecoder.implRead(java.base@11.0.18/StreamDecoder.java:318)
at sun.nio.cs.StreamDecoder.read(java.base@11.0.18/StreamDecoder.java:178)
- locked <0x000000063d607bd0> (a java.io.InputStreamReader)
at …
```
> name the ForkJoinPool threads

- opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/impl/SuggesterServiceImpl.java
- suggester/src/main/java/org/opengrok/suggest/Suggester.java
- suggester/src/main/java/org/opengrok/suggest/util/Progress.java
- suggester/src/test/java/org/opengrok/suggest/SuggesterTest.java
Lately I become sort of obsessed with progress reporting, mostly after dealing with operations for a deployment. This change adds progress reporting to the suggester. The suggester module avoids any dependencies on the indexer etc. so the `Progress` class was basically copied.
> report progress when initializing/rebuilding suggester

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
Indexing with current Universal ctags, I can see this warning:
```
2023-05-11 04:04:27.197+0200 WARNING t81 Ctags.lambda$run$0: Error from ctags: ctags: Warning: the kind for letter `C' specified in "--kinddef-rust" option is already defined.
```
Indeed, the `const` support was added in https://github.com/universal-ctags/ctags/commit/648cbe273d9454a0556e871c5406db83f8968aa3 so this change removes the extra option passed to ctags.
> current Universal ctags has const support for rust

- opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/ContextArgs.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/OGKUnifiedHighlighter.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/OGPassageScorer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/search/context/PassageScorerTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/search/context/SearchAndContextFormatterTest.java
- opengrok-indexer/src/test/resources/sources/c/sdt.h
This changes the way how search results are displayed. Previously the passages were scored based on [multiple criteria](https://lucene.apache.org/core/9_4_1/highlighter/org/apache/lucene/search/uhighlight/PassageScorer.html) so that it could happen that trimmed results for given file did not show initial hits within that file which I find confusing.
While I could use `UnifiedHighlighter.Builder` with `withScorer()` in `Context#getContext2()`, I decided to override the `getScorer()` method in the `OGKUnifiedHighlighter` instead as it is more robust - no need to rely on the Builder to be used at all relevant places.
Eventually this could be made tunable per user so that it is possible to choose between the standard Lucene behavior and the new default.
> order passages in search results based strictly on file offsets

- docker/sync.yml
The sync configuration contained a directive to limit the number of open files for the indexer. This came from a demo configuration and should not be present.
Checking the limits of the indexer process after the change (running from `docker-compose`, no special configuration):
```
275 ?        Sl     0:01      \_ /opt/java/openjdk/bin/java -Dorg.opengrok.indexer.history.SCCS=/usr/bin/sccs -Dorg.opengrok.indexer.history.cvs=/usr/bin/cvs -Dorg.opengrok.indexer.history.Mercurial=/usr/bin/hg -Dorg.opengrok.indexer.history.RCS=/usr/bin/blame -Dorg.opengrok.indexer.history.Perforce=/usr/bin/p4 -Dorg.opengrok.indexer.history.Bazaar=/usr/bin/bzr -Dorg.opengrok.indexer.history.Subversion=/usr/bin/svn -jar /opengrok/lib/opengrok.jar -R /tmp/tmpyf0nbbrd --connectTimeout 30 -r dirbased -G -m 256 …
```
> do not contrain open files limit

- tools/src/main/python/opengrok_tools/indexer.py
- tools/src/main/python/opengrok_tools/sync.py
https://github.com/oracle/opengrok/discussions/4361 describes a use case for `--nolock` option in the `opengrok-indexer` Python tool. This makes it on par with the `opengrok-sync` tool (which had the nolock logic wrong).
> add --nolock option to indexer.py

- tools/setup.py
After fixing the locking logic in `sync.py` in e4b30323, the program started emitting logs via the filelock package in DEBUG mode even though it was running with log level INFO:
```
DEBUG:filelock:Attempting to acquire lock 140503852943824 on /tmp/opengrok-sync.lock
DEBUG:filelock:Lock 140503852943824 acquired on /tmp/opengrok-sync.lock
DEBUG:filelock:Attempting to release lock 140503852943824 on /tmp/opengrok-sync.lock
DEBUG:filelock:Lock 140503852943824 released on /tmp/opengrok-sync.lock
```
This change should fix this.
> unlock the filelock package

- opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java
As is the style in OpenGrok, file paths should be logged with single quotes. Noticed this today in the webapp logs:
```
06-Jun-2023 15:38:12.482 WARNING [http-nio-8080-exec-3798] org.opengrok.indexer.search.Results.printPlain No context for /ws-local/userland-default-prepped/components/wireshark/wireshark-4.0.5/capture/capture-wpcap.c
```
This change fixes that.
> add quotes to Results logging

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
This change reintroduces the `IndexParallelizer#bounce()` call for all the indexer cases.
> always bounce IndexParallelizer

- Dockerfile
- docker/README.md
Bionic was released in 2018, Jammy is a bit more up-to-date. The later used `tomcat:10.1-jdk11` image is based on Jammy as well, so we update the Perforce repo, too, and make it use HTTPS.
> Use Ubuntu Jammy (22.04) as base for Docker image

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Groups.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/GroupsTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/GroupsControllerTest.java
This change restores the `Groups` command functionality after the conversion of the group representation from `Set` to `Map`. Tested with trivial cases of add/delete/match.
This also unifies the type of actual map implementation used throughout the code to `TreeMap`.
> restore Groups command functionality

- suggester/src/main/java/org/opengrok/suggest/Suggester.java
- suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
This change makes sure directories are logged inside quotes. Also, the `IndexDeletionPolicy' exception message was augmented. The latter should help diagnose #4385.
> improve suggester logging

- apiary.apib
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SystemController.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/filter/IncomingFilter.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/filter/IncomingFilterTest.java
Resolves https://github.com/oracle/opengrok/issues/4397
Added system/ping endpoint to the list of apis accessible outside localhost without bearer token. Exposing this api outside localhost helps to use this endpoint as readiness probe for k8s based deployment
> Added system/ping endpoint to the list of apis accesible outside localhost

- opengrok-indexer/src/test/java/org/opengrok/indexer/util/CtagsUtilTest.java
- tools/src/test/python/test_readconfig.py
- tools/src/test/python/test_restful.py
Fixes the problem recently surfacing during Linux builds:
```
[INFO] --- exec:1.6.0:exec (Python flake8) @ tools ---
flake8.checker            MainProcess     93 INFO     Making checkers
flake8.main.application   MainProcess    756 INFO     Finished running
flake8.main.application   MainProcess    756 INFO     Reporting errors
flake8.main.application   MainProcess    757 INFO     Found a total of 13 violations and reported 2
/home/runner/work/opengrok/opengrok/tools/src/test/python/test_readconfig.py:40:12: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
/home/runner/work/opengrok/opengrok/tools/src/test/python/test_restful.py:33:55: E231 missing whitespace after ','
Error:  Command execution failed.
```
Also, remove the `OldC` ctags …
> fix nits in Python tests causing build failure

- Dockerfile
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/yaml/Consts.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/yaml/YamlAnalyzer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/yaml/YamlAnalyzerFactory.java
- opengrok-indexer/src/main/jflex/analysis/yaml/Yaml.lexh
- opengrok-indexer/src/main/jflex/analysis/yaml/YamlSymbolTokenizer.lex
- opengrok-indexer/src/main/jflex/analysis/yaml/YamlXref.lex
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/yaml/YamlSymbolTokenizerTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/yaml/YamlXrefTest.java
- opengrok-indexer/src/test/resources/analysis/yaml/sample.yml
- opengrok-indexer/src/test/resources/analysis/yaml/sample_xref.html
- opengrok-indexer/src/test/resources/analysis/yaml/sampletags
resolves #4353
Added yaml lexer support
Added libyaml for ctgs to parse yaml file
Sample output
> Added yaml lexer for yaml file analysis

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
As noted in https://github.com/oracle/opengrok/discussions/4145#discussioncomment-7100494, the fidelity of history cache creation reporting of file counts relies on `HistoryException` to be thrown for all problems in functions responsible for history cache entry creation/modification. This change fixes one (last ?) place where this was not done.
> make sure HistoryException is thrown for all problems in storeFile()

- distribution/pom.xml
- opengrok-web/pom.xml
- pom.xml
- suggester/pom.xml
- suggester/src/main/java/org/opengrok/suggest/popular/impl/chronicle/BytesRefDataAccess.java
Upgrade Chronicle-Map and other maven plugins
Update BytesRefDataAccess as per https://github.com/OpenHFT/Chronicle-Map/blob/ea/docs/CM_Tutorial_DataAccess.adoc
> Upgrade Chronicle-Map

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
This is an attempt to fix #4333. When the method returns, some of the futures might be still running. This might change the input entries, hence the discrepancy. I contemplated using `cancel()` on the futures which returned false or resulted in an exception, however this is more robust as the cancelled futures would have to be still checked via `isCancelled()`.
> wait for all the futures in fillLastHistoryEntries() to complete

- tools/src/main/python/opengrok_tools/sync.py
- tools/src/test/python/test_sync.py
This is attempt to fix #4430 by making the `Pool.map()` to be called only on non-empty list of commands.
> rework do_sync() tests

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexCheck.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexCheckException.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDocumentException.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexVersionException.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexCheckTest.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
This change primarily converts the `IndexCheck` class from static/utility class to plain class. This allowed to use Mockito for testing normally. While there, I folded the parallelized project checking done previously in `WebappListener` to the class. This resulted in reworking the way how errors are propagated. For index check errors, the result is single exception carrying the list of source root paths corresponding to the indexes that failed the test. For I/O exceptions, just one is propagated.
There are 2 main use cases for the index check:
1. done per project in the Docker image
1. done for all indexes (projects enabled or not) during webapp startup
The thread handling in `IndexCheck` uses common per-class-instance pool for the project parallel processing. There is another pool used …
> tidy IndexCheck and improve its testing

- opengrok-indexer/pom.xml
- pom.xml
upgrade jflex version and remove workaround added for https://github.com/jflex-de/jflex/issues/542
Removed test api-docs target since we are not pushing api docs for test classes 
Pending : Setting token_size_limit and skipping the entire line if line length is more than the limit
#4170
> upgrade jflex version and remove workaround

- apiary.apib
- docker/start.py
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
The Docker startup script should allow refresh of repositories for projects. This is more in line with the appliance like characteristics of the Docker image. This will make the resync slower, depending on the repositories.
While there, I did some small changes to the test.
Also, when log level is set to debug, the list of repositories for given project will be logged.
> always refresh the list of repositories for projects

- tools/src/main/python/opengrok_tools/utils/commandsequence.py
- tools/src/test/python/test_command_sequence.py
Even though it seems the following is a valid YAML:
```yaml
commands:
- command:
call:
uri: 'http://localhost:8080/api/v1/messages'
method: POST
data:
messageLevel: warning
duration: PT1H
tags: ['%PROJECT%']
text: reindex in progress
```
is parsed into invalid `opengrok-sync` configuration, with `command` having `None` value. This change catches this.
Inspired by https://github.com/oracle/opengrok/discussions/4449
> check commands structure with None values

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-web/src/main/webapp/enoent.jsp
This change makes the "enoent" history message short. I always found the message too verbose. Also, like it was, it was meant for an administrator (related to #4411); for the end user it was rather useless. Further, it contained hints at deployment/implementation specifics, some of which are no longer existent (database for history cache).
While there, I did some refactoring of related code.
> shorten the lack of history error message

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryCacheResultsTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
This change addresses long standing issue where the 2nd phase of indexing goes through even though history cache creation/update for one of the repositories failed. If projects are enabled and one of the repositories for given project failed history cache creation/update, that project will not be indexed; the projects with all their repositories being fine w.r.t. history cache are allowed to progress to 2nd phase of indexing. If projects are disabled, history cache creation failure of a repository results in the 2nd phase of indexing being skipped altogether.
Obviously, this relies on the individual repository implementations to properly report the history cache operation failure via `HistoryException`.
To suppress the new behavior, one can use the `--ignoreHistoryCacheFailures` indexer …
> Handle history cache failures

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
The changes in PR #4456 rely on error propagation to detect history cache operations failures. This change fixes one of the places where previously the problem was swept under the carpet.
> propagate the error from finishStore() rather than log it

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/History.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/HistoryContext.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/search/context/HistoryContextTest.java
This change fixes diff link generation for histories that contain inactive history entries.
> skip inactive history entries when generating history context

- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/test/java/org/opengrok/web/DiffTest.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
Populated the revision data if there is no error message.
Added additional assertions to confirm revision data is populated while created diff for valid versions
closes #4468
> Fix : NPE when displaying a diff

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialAnnotationParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SCCSRepositoryAnnotationParser.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
This change prevents getting annotations for data/image files or genre-less files.
> avoid annotations for binary files

- tools/src/main/python/opengrok_tools/scm/git.py
- tools/src/main/python/opengrok_tools/utils/command.py
- tools/src/test/python/test_command.py
- tools/src/test/python/test_command_sequence.py
To avoid exhausting memory when commands produce inordinate amounts of output (think reindex from scratch in verbose mode), this change introduces upper limits for the output lines stored by the `Command` class. The default is 10k lines and 250 characters for each line. The truncation is visible in the output for both cases via `...`.
As a side effect, the newline separators are not longer stored in the list of output lines. They are added only when requested using the `getoutputstr()` or `geterroutputstr()`.
> use upper limit for output data in Command

- README.md
Fix Github Build Action Badge as per github [documentation ](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge)
Right now we are using old format(https://github.com/actions/starter-workflows/issues/1525#issuecomment-1763431305)
> Fix Github Build Action Badge

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SCCSHistoryParser.java
This change fixes a small nit I found when traversing the code of `SCCSHistoryParser`.
> do not call getSCCSFile() twice

- dev/main
1. Replace deprecated sonar login parameter in GH Action
2. Pass python version to sonar scanner
> Replace deprecated sonar login parameter in GH Action

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/ConfigMerge.java
- tools/src/main/python/opengrok_tools/config_merge.py
This change introduces output file mandatory parameter to the `ConfigMerge` utility. As a result the tools will no longer consume its output in order to produce new configuration file, avoiding truncation.
> avoid truncation when merging config files

- distribution/pom.xml
When trying to reproduce a Python tools build issue by running the build through `mvnw`, I got this warning when building distribution:
```
[INFO] --- assembly:3.1.0:single (create-archive) @ opengrok-dist ---
[WARNING]  Parameter 'finalName' is read-only, must not be used in configuration
[INFO] Reading assembly descriptor: assembly.xml
[INFO] Building tar: /home/user/opengrok-vladak-scratch/distribution/target/opengrok-1.13.0.tar.gz
[INFO] 
```
Interestingly this warning is not produced when building with system supplied `mvn`.
https://issues.apache.org/jira/browse/MJAR-217 says what needs to be done.
While there, I bumped the version of the Maven plugins used in the distribution module.
> fix finalName warning and update plugins

- Dockerfile
helix-p4d didn't available on ARM64 platform,
there is no obvious impacts after checking docker image on ARM64
After this change, docker image created successfully on ARM64 platform.
> Remove helix-p4d from install list

- docker/start.py
- tools/src/main/python/opengrok_tools/config_merge.py
This change should fix the regression with config file merging in Docker.
Currently I am not able to test locally because of 404 errors on security.ubuntu.com while building the image.
> pass output file path instead of file object

- logging.properties
- tools/logging.properties.template
This change normalizes the log level setting in the example files.
> avoid setting global log level

- tools/src/main/python/opengrok_tools/projadm.py
There should be a way to set indefinite async API timeout for `opengrok-projadm` to have the ability to wait for the API call completion no matter how long it takes. This is currently not possible (`None` value is needed for that and there is positive default) and this change fixes that by making it the default which I think makes sense; one rarely wants to let the API result slip away, esp. when doing reindex from scratch (a case of back-to-back index deletion which is done via async API call and project addition).
> do not set default async API timeout in opengrok-projadm

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/CacheUtil.java
This change encloses paths logged in `CacheUtil` to be in line with rest of the code base.
> quote paths in CacheUtil logging

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/PathAccepter.java
Another case of path logging that needs to be made consistent with the rest of the code base.
> quote logged paths in PathAccepter

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
This change restores the ability to get annotations for xref-able files in the UI. The way it works with this change is that if there is a document for given file, it is used for negative check, i.e. if there is no type in the document or the type is not xref-able, the file is considered not eligible for annotation. If no document can be found for the file, the repository will be checked. This way, with some refactoring, it should work for both the UI and the indexer (when annotation cache is created). Using the "xrefable" property as "annotatable" property (not considering the missing document caveat) is not entirely correct, however it is better to leave this for a subsequent PR; the focus of this PR should be the regression fix.
> fix annotation regression

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerVsDeletedDocumentsTest.java
This change deals with symlinks properly when performing history based reindex. It makes the code robust enough to avoid having directory entries in `IndexDownArgs`.
When I was writing the code for history based reindex, I remember brushing the need to use `accept()` away for some reason. It seems this was not a good idea as it provides a way how to deal with symlinks.
While at it, I changed some of the log statements to be in line with the style of wrapping paths inside single quotes used throughout the code base.
> handle symlinks for history based reindex

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/OpenGrokThreadFactory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryReader.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexCheck.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/OpenGrokThreadFactoryTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryReaderTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexCheckTest.java
While the `@NotNull` decorator informs developers that the correct usage is that the decorated variables should not be `null`, it does not enforce such in any way.
This leads to cases where an incorrectly fed `null` could propagate far away before being detected (such as via `NullPointerException`s).
This commit implements some `null` guards where needed for a fail-fast treatment of `null` inputs.
> Add null guards

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/SuggesterConfig.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/impl/SuggesterServiceImpl.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerProjectsDisabledTest.java
- suggester/src/main/java/org/opengrok/suggest/Suggester.java
- suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
- suggester/src/test/java/org/opengrok/suggest/SuggesterTest.java
This change addresses 2 problems with suggester:
- per class lock held inside the `Suggester` class for init/rebuild/remove operations prevented API calls to proceed for a long time. Together with `SuggesterServiceImpl` and `SuggesterProjectData`, there were 3 layers of locking, making this confusing.
- init/rebuild done as a result of reindexing multiple projects in parallel, resulting in potentially long queue of rebuild operations, executed serially. 
The locking part of the change is done with the assumption that the `lock` object based synchronization in the `Suggester` class was primarily used to protect the insertions/queries to the `projectData` map. I addressed this using `computeIfAbsent` which is atomic for the `ConcurrentHashMap` used.
The rebuild execution part of the change …
> improve suggester throughput

- opengrok-indexer/src/main/java/org/opengrok/indexer/util/ErrorMessageCollector.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/messages/MessagesUtils.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/ErrorMessageCollectorTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/SearchHelperTest.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
1. Created a new Builder for search helper class and used that for created search helper instance( This was done to reduce number of parameters passed to constructor)
2. Reduced complexity of methods in search helper and utl classes
>  Sonar code smell fixes in web package

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDownArgs.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java
This change replaces the `ForkJoinPool` used for distributing `addFile()` tasks in the 2nd phase of indexer processing with fixed thread pool. In my case:
- Oracle OCI VM.Standard.E3.Flex with 16 OCPUs, 128 GB RAM running Solaris 11.4 SRU ~63 and storing OpenGrok data on block volume with 25,000 IOPS / Balanced (VPU/GB:10) / Throughput: 480 MB/s
- indexer running with Java 11 with `-J=-Xmx48g -J=-server` using `--renamedHistory 'on' -r dirbased -G -m '256' --threads 48 --historyThreads 48 --historyFileThreads 32` and annotation cache enabled for all projects
- the input data consists of bigger projects like Linux kernel, FreeBSD, AOSP, Solaris Userland (prepped) - a mix of various repository types (Git, Subversion, Teamware, Mercurial)
it shaves some 8+ hours from the total indexing time: …
> replace ForkJoinPool with fixed thread pool

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/ExecutorTest.java
This change prevents adding `HistoryEntry` objects with null date to the list from the `SubversionHistoryParser`. I had to make changes in the `Executor` to propagate the errors from stream processing for this to work.
It also fixes various style issues and code smells.
> prevent null date in Subversion history entry

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialHistoryParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/SCCSHistoryParser.java
This trivial change fixes file quoting in exceptions thrown from `SCCSHistoryParser`. I noticed these during indexing.
> unify file quoting in SCCS/Mercurial

- suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
This trivial changes unifies logging of paths with the rest of the code base.
This will wrap also cases like this:
```
25-Mar-2024 18:53:31.632 WARNING [Thread-5166] org.opengrok.suggest.SuggesterProjectData.initFields Fields [defs, path, hist, refs, type, full] will be ignored because they were not found in index directory MMapDirectory@/opengrok/data/index/foo lockFactory=org.apache.lucene.store.NativeFSLockFactory@73c140fc
```
however I found no way how to get the file system path out of the `Directory` object.
> quote directort paths in logs in suggester

- distribution/assembly.xml
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/CtagsUtil.java
- tools/pom.xml
This change addresses bunch of nits found in the `CtagsUtil` class.
Also, it seems something has changed in the way `setuptools` name the resulting tarball when building a package. Even though the `[project]` section in `tools/pyproject.toml` has `name = "opengrok-tools"`, the resulting name of the tar ball will now have underscore in it. This should not matter as the `distribution` module will rename it to `opengrok-tools.tar.gz` anyway. The names of the Python packages do not change - they had underscore in them before.
> fix some nits in CtagsUtil + fix build

- dev/before_install
- opengrok-indexer/pom.xml
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileAnnotationCache.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/messages/JSONUtils.java
- pom.xml
- tools/src/main/python/opengrok_tools/utils/java.py
This change updates mainly Jackson but also other outdated dependencies.
> Jackson update

- Dockerfile
> bump Tomcat to 10.1.26

- tools/src/main/python/opengrok_tools/scm/mercurial.py
When indexing a particular repository after a recent change, the incremental indexer run failed with:
```
org.opengrok.indexer.index.IndexDatabase$IndexerFault: attempting to add file '/on11sru-allbranch-clone/usr/man/on/en/xman8/ikeadm.8.xml' with date matching deleted document: 20171211230536714
at org.opengrok.indexer.index.IndexDatabase.processFileHistoryBased(IndexDatabase.java:1779)
at org.opengrok.indexer.index.IndexDatabase.indexDownUsingHistory(IndexDatabase.java:985)
at org.opengrok.indexer.index.IndexDatabase.getIndexDownArgs(IndexDatabase.java:946)
at org.opengrok.indexer.index.IndexDatabase.update(IndexDatabase.java:755)
at org.opengrok.indexer.index.Indexer.lambda$doIndexerExecution$59(Indexer.java:1208)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executo …
```
> always update to the correct head of Mercurial repositories

- tools/src/main/python/opengrok_tools/scm/mercurial.py
Fixes recently introduced problem with revision argument quoting in `opengrok-mirror`.
> remove extra quotes in mercurial.py

- Dockerfile
- docker/README.md
The Docker builds have started failing recently due to the run of pip trying to install packages globally. This change provides remedy by using Python virtual environment.
While there, I made Perforce installation optional because it is failing in my local environment.
> Docker vs pip

- .github/workflows/docker.yml
- .github/workflows/release.yml
- dev/get_upload_url.sh
- dev/ref2tag.sh
- dev/release.sh
The rules that avoid direct pushes to the `master` branch have been put into effect recently. This change modifies the release process not to rely on this anymore. Instead, a PR will be used to bump the versions first, then after it is merged a release will be [created](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) using either Github CLI or the web.
https://github.com/oracle/opengrok/wiki/Release-process will have to be updated
> change release process to avoid pushing to the master branch

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
As mentioned on https://github.com/oracle/opengrok/discussions/4606, empty Git repositories fail history cache creation, making the indexing of related project fail. This change fixes that.
> handle empty Git repositories gracefully

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerVsDeletedDocumentsTest.java
This fixes the failing incremental reindex in the face of sequence of changes to a file that in the end nullify each other by checking the last modified date of the file to the date stored in the corresponding document. The first idea was to simply "`touch`" the files however that would cause unneeded churn.
While there, the changes to the `IndexDatabaseTest` somehow made the Windows builds failing due to pending references to index files (with `AccessDenied` exception thrown from `IOutils.removeRecursive()`), also even in different test classes due to the intertwined nature of indexing and `RuntimeEnvironment`. Hence the index searcher related changes.
> History based reindex vs. git revert

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/MercurialRepositoryTest.java
This change increases coverage of `MercurialRepository`, in particular `MercurialAnnotationParser`. This is a basic test, ideally all the `Annotation` members should be verified in the positive case.
> add tests for MercurialRepository.annotate()

- plugins/src/main/java/opengrok/auth/plugin/ldap/LdapServer.java
When investigating why some of the LDAP servers are down, I noticed the `NamingException` is not logged in `connect()`. This change fixes that.
> log the exception when LDAP connect failed

- .github/workflows/docker.yml
- dev/docker.sh
- dev/dockerhub_readme.py
This change should avoid uploading Docker image/README for all PRs, esp. including those raised by Dependabot.
For the README handling, the alternative would be to equip the corresponding action with `if: ${{ github.event_name != 'pull_request' }}` however the handling is already in the scripts.
> handle PRs gracefully for Docker image build

- Dockerfile
Install `libxml2-dev` to support XML in Universal ctags built for the Docker image.
docker build excerpt:
```
checking for libxml-2.0 >= 2.7.7... yes
checking libxml-2.0 CRLF handling bug... good
```
Previously the answer was `no`.
Checking languages support in the container built with these changes:
```
$ docker exec opengrok-dev /usr/local/bin/ctags --list-languages | grep XML
PlistXML
XML
```
> compile Universal ctags with XML support

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
This change solves a deadlock related to ctags validation which holds the `RuntimeEnvironment#configLock` for writing vs. reading a configuration value by removing the locking and making the `RuntimeEnvironment#validateUniversalCtags()` method synchronized.
The locking in `validateUniversalCtags()` was introduced in 9c92ca95, not sure why it was deemed necessary. The method (potentially) modifies `ctagsFound` and `ctagsLanguages` which are neither part of the `Configuration`. Also, the method is called only from `prepareIndexer` which is run from `main()` at the beginning of the indexing (which means the added `synchronized` is just for a case). The `ctagsLanguages` is needed only by the `Ctags` instances (of which the validate is special case).
> no need to lock configuration for ctags validation

- opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryTest.java
The year was not bumped for `GitRepositoryTest.java` for the last change in 02c841b29b7ee5560ae57844a9e7e7fb5a9606d5, this change fixes that.
> bump year in GitRepositoryTest.java

- opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryTest.java
This  change removes the loops in favor of properly parametrized tests in `GitRepositoryTest`.
> properly parametrize Git repository tests

- opengrok-web/src/main/java/org/opengrok/web/AuthorizationFilter.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/test/java/org/opengrok/web/AuthorizationFilterTest.java
This change adds tests for the `web/AuthorizationFilter` class. I removed the `final` classifier from the `PageConfig` class so that it can be conveniently mocked via Mockito.
> add tests for web/AuthorizationFilter

- docker/start.py
- tools/src/main/python/opengrok_tools/reindex_project.py
add INDEXER_JAVA_OPTS environment varibale
pass java_opts to Indexer to tune jvm options
This feature is useful for docker users
> indexer: add java options to indexer

- docker/README.md
> document INDEXER_JAVA_OPTS

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialTagParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/TagEntry.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/MercurialRepositoryTest.java
This change introduces test coverage for the `MercurialTagParser` class. While there, I fixed issue with parsing tags containing multiple spaces.
> add tests for Mercurial tag parsing

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
While hunting for a bug in the indexer (causing duplicate documents with history based reindex)  I realized that `processFileHistoryBased()` calls `removeFile()` twice unnecessarily in the same block. This was introduced with the changes in 520ce3b908655d5edfc0d1b019dd2a575381a34f.
> avoid calling removeFile() twice in the same block

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
This change quotes the read-only configuration path logged, to align with the rest of code base.
> quote path in log statement

- dev/before_install
- tools/src/main/python/opengrok_tools/groups.py
- tools/src/main/python/opengrok_tools/utils/command.py
- tools/src/main/python/opengrok_tools/utils/java.py
- tools/src/test/python/test_command.py
Fixes a problem with long lines/output generated by the `Groups` command where previously `opengrok-groups` (the wrapper) would truncat it, leading to invalid XML.
While working on this, the Linux build failed on me due to the Python packages (pip) being externally managed, so this change fixes this (for the time being leaving the script behind).
> do not constrain the output of the Groups command in opengrok-groups

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/RuntimeUtil.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
Inspired by https://github.com/oracle/opengrok/discussions/4675, I resurrected an old branch to enforce Java version range for the runtime of the indexer and webapp.
Next to the Oracle Java 11, I also tried with Amazon Corretto 11.0.25.
> enforce Java version

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/CtagsUtil.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/CtagsUtilTest.java
- pom.xml
This change relaxes the ctags check so that it works also for non-writable source root which is legit.
In order to test that, I had to bump Mockito in order to be able to use static method mocking. I contemplated a bit about making `CtagsUtil` non-static however turned the idea down as it would be too big change for such small change and generally it seems that the static methods have their own place for this use case.
> fall back to the default temporary directory for ctags check

- opengrok-indexer/src/main/java/org/opengrok/indexer/Metrics.java
- pom.xml
Updates the Micrometer in order to fix a vulnerability in netty libraries used by the `micrometer-registry-statsd`.
> update Micrometer to 1.14.1

- tools/src/main/python/opengrok_tools/scm/cvs.py
- tools/src/main/python/opengrok_tools/scm/git.py
- tools/src/main/python/opengrok_tools/scm/mercurial.py
- tools/src/main/python/opengrok_tools/scm/repository.py
When mirroring a JDK project with unresponsive Mercurial parent, the `opengrok-mirror` command failed due to timeout which caused `TypeError` exception due to the `status` value being  `None`:
```
processing of project 'jdk8' failed
failed commands:
'sudo -u wsmirror /opengrok/dist/bin/venv/bin/opengrok-mirror --api_timeout 16 --backupcount 120 --workers 3 --strip-outgoing -I -b -c /opengrok/etc/mirror-config.yml jdk8': 1
multiprocessing.pool.RemoteTraceback:      """      Traceback (most recent call last):        
File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker        
result = (True, func(*args, **kwds))        
File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar        
return list(map(*args))        
File …
```
> check command state before accessing return value

- opengrok-indexer/src/main/jflex/analysis/fortran/FortranXref.lex
As of now fortran indexing is broken because of my previous change.
```
Second argument of substring is wrong in my previous commit 
It should be 
cmatch.substring(cmatch.length() - 1, cmatch.length()) instead of  cmatch.substring(cmatch.length() - 1, 1)
```
@vladak  Please review
> Fortran indexing broken 

- plugins/src/main/java/opengrok/auth/plugin/AbstractLdapPlugin.java
When transitioning from the XML based authnz config to YML, I noticed that the exception is missing the configuration path. This change fixes that.
> specify the path in the configuration load exception

- opengrok-indexer/src/main/java/org/opengrok/indexer/Metrics.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerException.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/RuntimeUtil.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerMainTest.java
- opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/DirectoryListingControllerTest.java
- opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/FileControllerTest.java
This change contains couple of notable changes:
- more verbose Java/system/environment information reporting for both indexer and webapp
- the `InterruptedException`/`ExecutionExecption` from `indexParallel()` now bubble up to the indexer, altering the exit value of the indexer process so that automation can e.g. wipe out the index and reindex from scratch.
- removal of the capability to index individual directories (which is probably very rarely used if at all and potential source of index inconsistencies), simplifying `IndexDatabase`. Any extra indexer arguments are now treated as project paths.
In case of OOM error in one of the `indexParallel` tasks, the indexer logs look like this:
```
SEVERE: 6897 successes (100.0%) after aborting parallel-indexing
Jan 07, 2025 11:02:52 AM …
```
> let the indexParallel() exceptions bubble up + removal of per directory reindex

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
Lately I have been debugging a case of failed indexing due to the failed check https://github.com/oracle/opengrok/blob/4ba3aefc4eb07b735a3deeb607bb177f63d19677/opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java#L1734-L1741 and realized the `isStrictlyNewerThanDocument()` should really due better in terms of logging.
For the record, in my case (indexing the linux Git repository) it failed due to `getDocument()` returning null.
> improve logging for isStrictlyNewerThanDocument()

- opengrok-indexer/src/main/jflex/analysis/php/PhpSymbolTokenizer.lex
- opengrok-indexer/src/main/jflex/analysis/php/PhpXref.lex
This change gets rid of the JFlex produced warnings for the PHP lex files.
> use \uFFFF as upper range for PHP identifiers

- opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/LatestRevisionUtil.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileAnnotationCacheTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/MercurialRepositoryTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/AnalyzerGuruDocumentTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerVsDeletedDocumentsTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/search/context/HistoryContextTest.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
- opengrok-web/src/main/webapp/help.jsp
- opengrok-web/src/main/webapp/list.jsp
- opengrok-web/src/main/webapp/menu.jspf
- opengrok-web/src/main/webapp/minisearch.jspf
- opengrok-web/src/test/java/org/opengrok/web/DirectoryListingTest.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
This change allows for real per project history override.
Tested with indexer running with:
```
-P
-S
-R
/var/opengrok/etc/readonly_configuration-per_project_history.xml
-s
/var/opengrok/src.perproj
-d
/var/opengrok/data.perproj
-W
/var/opengrok/etc/configuration.xml
```
where the contents of `/var/opengrok/etc/readonly_configuration-per_project_history.xml` looked like this:
```xml
<java version="11.0.4" class="java.beans.XMLDecoder">
<object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">
<void property="historyEnabled">
<boolean>true</boolean>
</void>
<void property="projectsEnabled">
<boolean>true</boolean>
</void>
<void property="projects">
<void method="put">
<string>foo</string>
<object …
```
> avoid global isHistoryEnabled() checks in favor of per repository check

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruVsRepositoryCacheTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java
This change allows for per project history cache control, fixing hopefully most of the confusion between history/historyCache enabled semantics. Paves the way for #4265.
Will need a change in https://github.com/oracle/opengrok/wiki/Per-project-configuration
> History cache control per project

- README.md
IntelliJ provides professional licenses for their products for those working on OpenGrok. It makes our job easier so adding IDEA logo is fine.
> bump copyright year, add IDEA logo

- docker/start.py
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/ConfigurationTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/UtilTest.java
- opengrok-web/src/main/webapp/WEB-INF/tags/repository.tag
- opengrok-web/src/main/webapp/history.jsp
This change gets rid of the `URL()` constructors deprecated in Java 20 and addresses a case of unescaped patterns.
Background: https://gist.github.com/vladak/beb43b9056b546869196d09a16542466
Approaches #4459 and takes over the `URL()` changes from @tarzanek's PR #4570 
I had to add a flake8 suppression to the Docker entry point to make the build pass.
Tested with this read-only configuration:
```xml
<java version="1.8.0_121" class="java.beans.XMLDecoder">
<object class="org.opengrok.indexer.configuration.Configuration">
<void property="bugPage">
<string>https://github.com/apache/lucene/issues/</string>
</void>
<void property="bugPattern">
<string>LUCENE-(\d+)</string>
</void>
</object>
</java>
```
and The Lucene Git repository.
> replace URL() constructors

- .github/workflows/build.yml
Paves the way for ARM64 Docker images. The Linux ARM64 Github runners are currently in public preview.
> add Linux ARM64 runner

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
This change makes the `possible 'this' escape before subclass is fully initialized` error message produced by newer Java versions (Java 24 in my case) go away by making some of the methods (that could be previously overriden by a sub-class) final.
Approaches #4459.
> avoid this-escape by making some methods final

- opengrok-indexer/src/test/java/org/opengrok/indexer/web/UtilTest.java
- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SuggesterController.java
When compiling with target bytecode set to 21 I discovered there are some remaining `URL(String)` constructors in the code. This change gets rid of them.
Follow-up to #4750.
> replace remaining URL() constructors

- .github/workflows/build.yml
Sometimes having build artifact is handy for testing, verifying. This change uploads build artifact for each OS in the matrix.
> Upload build artifacts

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/OpenGrokThreadFactory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/util/ThreadUtil.java
- suggester/src/main/java/org/opengrok/suggest/Suggester.java
- suggester/src/main/java/org/opengrok/suggest/util/ThreadUtil.java
This change gets rid of the remaining deprecation warnings when building with target version of 21. It's a bit of a hack, however removes potential developer barrier.
> use reflection to get thread ID

- pom.xml
Post Java 21 cleanup the javadoc build job started failing with:
```
[java] Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 65
[java] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
[java] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
[java] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
[java] 	at edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
[java] 	at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:48)
[java] 	at edu.umd.cs.findbugs.classfile.engine.asm.ClassReaderAnalysisEngine.analyze(ClassReaderAnalysisEngine.java:34)
[java] 	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache …
```
> update some of the Maven plugins used for reporting/javadoc

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Annotation.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/AnnotationData.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialAnnotationParser.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/MercurialRepositoryTest.java
This change addresses a problem with imprecise history search from annotate view for projects with multiple Mercurial repositories by storing annotation data for Mercurial repositories with both short/display (`rev`) and longer (`node|short`) version of the revision ID and using the latter to construct the history search links.
Will require reindex from scratch if using annotation cache (for given project).
> use longer revision for Mercurial repository annotation search links

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
This change simplifies the comparison of `Project` instances. Confused Sonar which thinks NPE is possible.
> simplify Project equals()

- opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
When reindexing a project from scratch I noted lack of project name in the `IndexDatabase` logging. This change provides remedy.
> log project in isReadyForHistoryBasedReindex()

- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java
Forgot to bump the year in copyright in the changes for #4748.
> bump copyright in RepositoryInfo

- opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
Another change inspired by log watching.
> quote project name in log entires

- opengrok-indexer/pom.xml
- opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java
> JGit update to 7.2.1

- pom.xml
With the recent JGit update to 7.x, Java 17 or later is required. This change bumps the target version to Java 17.
This will result in major version bump + documentation change.
> set the target Java version to 17

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/BazaarRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/BitKeeperRepository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryFactory.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryWithHistoryTraversal.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/ProjectTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/RepositoryInfoTest.java
This change introduces the `tagsEnabled` per project/repository tunable that allows to control whether tags should be applied to history entries (so that they are visible in history view).
This will require a change to https://github.com/oracle/opengrok/wiki/Per-project-configuration
Tested with the indexer running with:
```
-s
/var/opengrok/src
-d
/var/opengrok/data
-P
-H
-S
-c
/opt/homebrew/bin/ctags
-R
/var/opengrok/etc/ro-config-project.xml
-W
/var/opengrok/etc/configuration.xml
```
and the `/var/opengrok/etc/ro-config-project.xml` overriding the `tagsEnabled`:
```xml
<java version="1.8.0_121" class="java.beans.XMLDecoder">
<object class="org.opengrok.indexer.configuration.Configuration">
<void property="projects">
<void method="put"> …
```
> control history tagging per project

- opengrok-indexer/src/main/java/org/opengrok/indexer/web/Laundromat.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/web/LaundromatTest.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/main/webapp/opensearch.jsp
This change should address SonarQube warning about unsanitized input in the rss and opensearch JSPs. Basic level of sanitization is performed, not enforcing double dots, length restrictions, consecutive dashes in the middle, etc.
> Server name laundering

- opengrok-web/src/main/webapp/history.jsp
This is an attempt to resolve SonarQube warning about lack of sanitization of the `request.getRequestURL()` in `history.jsp`. This should be resolved by constructing the link from scratch. In the page the link will now start with absolute path rather than the scheme+server prefix. This should not matter given that browsers will produce the whole link.
> encode separately to avoid full URL

- opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/LineMatcher.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/PhraseMatcher.java
This change attempts to silence SonarQube warning about confusing method naming.
> rename to avoid confusion with Object.equals()

- opengrok-web/src/main/webapp/list.jsp
- opengrok-web/src/main/webapp/xref.jspf
Silences SonarQube warning w.r.t. accessibility.
> remove redundant image keyword from the img element

- opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/history/MercurialRepositoryTest.java
- opengrok-indexer/src/test/java/org/opengrok/indexer/util/ExecutorTest.java
This fixes the `MercurialRepositoryTest.testBuildTagListOneMore` failure on macOS with Mercurial 7.1.1 by setting the `HGUSER` environment variable which evidently prevents `hg tag` from going into interactive mode.
> fix MercurialRepositoryTest.testBuildTagListOneMore failure with Mercurial 7.1.1 on macOS

- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/main/java/org/opengrok/web/Scripts.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
Continuing the quest to increase coverage of the `PageConfig` class, this change adds tests for the `addScript()` method. Note there is a pre-existing set of tests which exercise the `Scripts` class, this merely adds tests for the missing chain link from the JSPs.
While there, I fixed some pre-existing nits such as the exposed visibility of the `Scripts#Type` enum via the `addScript(String contextPath, String scriptName, Type type)` method (by promoting it to `public`).
> add tests for PageConfig#addScript()

- opengrok-indexer/src/main/java/org/opengrok/indexer/util/IOUtils.java
- opengrok-web/src/main/java/org/opengrok/web/PageConfig.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
Yet another `PageConfig` test coverage change. This time for the `findDataFiles()` method used solely in the JSPs.
> add test for PageConfig#findDataFiles()

- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
- opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
- opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
The coverage of `PageConfig#getEtag()` can be increased further by adding a message to the system.
> increase coverage of PageConfig#getEtag()
