oracle/opengrok

OpenGrok

POSIX sh/test uses a single equals sign for string comparison.

Fix POSIX-compliance issue in OpenGrok

---

OpenGrok
src/org/opensolaris/opengrok/history/SubversionRepository.java

Allow users to specify the svn username and password used when fetching the SVN history via environment variables.

#609: Allow specifying username and password when fetching SVN history

---

src/org/opensolaris/opengrok/search/context/QueryMatchers.java
src/org/opensolaris/opengrok/search/context/RegexpMatcher.java
test/org/opensolaris/opengrok/search/context/ContextTest.java
test/org/opensolaris/opengrok/search/context/RegexpMatcherTest.java

Simple implementation adding context lines with searched words for
Regexp search.
Java Regexp is used to find words on lines, so any differences to Lucene
Regexp are ignored.
This is easy solution, until there is something more robust 100% compatible with Lucene regexps. But for most cases this should work.
TODO: Add some unit tests, as soon as I will find right place for them in existing tests.

Show words in lines context for Regexp search

---

build.xml
src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java
src/org/opensolaris/opengrok/analysis/erlang/Consts.java
src/org/opensolaris/opengrok/analysis/erlang/ErlangAnalyzer.java
src/org/opensolaris/opengrok/analysis/erlang/ErlangAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/erlang/ErlangSymbolTokenizer.lex
src/org/opensolaris/opengrok/analysis/erlang/ErlangXref.lex

This patch is a modification of the patches created by
Haitao Li <lihaitao@gmail.com> back in 2011 and made available
at https://bitbucket.org/liht/opengrok/branch/erlang-analyzer
The OCA is accepted

Add Erlang analyzer

---

src/org/opensolaris/opengrok/configuration/Project.java
web/index.jsp
web/index_body.html
web/repos.jspf

fixes #939
Couple of things to note:
- the table does not contain projects without repo (e.g. directories with just bunch of files)
- I can change that if wanted
- the table spans the whole page (see attached screenshot)
- this is displayed by default if running with projects
- can add config variable if desired

display table with project-repository mappings on front page

---

OpenGrok

String equality should be tested with '=' and not with '=='. The
latter is an extension in bash. I'm seeing the following error on a
system where /bin/sh is dash:
/code/OpenGrok/OpenGrok: 717: [: Linux: unexpected operator

Remove bashism in the OpenGrok script

---

platform/solaris/smf/ogindexd

-R $a was not valid, it should be referring to $READONLY_CFG_FILE

READ_XML_CONF not set properly

---

src/org/opensolaris/opengrok/analysis/c/CXref.lex
src/org/opensolaris/opengrok/analysis/c/CxxXref.lex
test/org/opensolaris/opengrok/analysis/JFlexXrefTest.java

When indexing C++ source code, identifiers that are found within angle brackets are treated as filenames instead of identifiers.  For example, say you have the following source code:
int main() {
Wrapper<MyClass> x;
return 0;
}
When this gets processed, "MyClass" will link to "/source/s?path=MyClass".  Since MyClass is not a filename this search is not likely to return anything useful.  It should be linking to "defs" instead of "path".
The code was intended to handle things like "#include <filename.h>" but it activates in too many places.  The rule should be restricted so that it only applies following "#include".
My new code feels a bit hacky but I'm not familiar with JFlex and this was the best that I could come up with.  Suggestions for a better approach are welcome.

C++ identifiers within angle brackets should be treated as identifiers

---

src/org/opensolaris/opengrok/analysis/csharp/CSharpXref.lex

This issue causes no html anchor generated at the definition position of
the symbol in C# xref source files, so can't navigate to that definition
location(in the same file) by a simple click.

Fix C# yyline mismatch issue.

---

build.xml
src/org/opensolaris/opengrok/analysis/csharp/CSharpAnalyzer.java
src/org/opensolaris/opengrok/analysis/csharp/CSharpScopeParser.lex
test/org/opensolaris/opengrok/analysis/csharp/CSharpAnalyzerFactoryTest.java
testdata/sources/csharp/Sample.cs

I followed Scopes implementation for C/Java and added support for CSharp.
Lex parser without any modification should work in 99% cases.
Known issues:
- generic methods with type constraints are not recognized.
Eg. private T M4<T>(T p) where T : new()
Text 'where T' between ) : confuse the parser
--
We could easily add same support for Javascript, maybe more languages.
Do we want always copy the same .lex file (as it was done for C/Java), or should we share one base for all common languages?
--
I'd like to propose 2 simple patches to Scopes ui, if you and especially author of Scopes agree, I would:
- add at least word 'in ' before scope name in search context - for regular user it may not be clear what the 'name()' really means. 
- blue is nice, but too much visible compared to search …

Add Scopes feature for CSharp

---

src/org/opensolaris/opengrok/analysis/csharp/CSharpXref.lex
test/org/opensolaris/opengrok/analysis/JFlexXrefTest.java

CSharpXref doesn't work correctly for verbatim strings that end with a backslash. This is the fix.

fix syntax highlight for C# verbatim strings

---

OpenGrok

If user does not use default OPENGROK_INSTANCE_BASE or default
WEBAPP_CONFIG_ADDRESS, then attempt to extract WEB-INF/web.xml from
source.war using jar or zip utility, update the hardcoded values and
then update source.war with the new WEB-INF/web.xml

Fix for opengrok issue https://github.com/OpenGrok/OpenGrok/issues/863

---

web/default/style.css
web/history.jsp

Wrapping long strings in commit comments to prevent the history table width from expanding.

Fix for OpenGrok issue https://github.com/OpenGrok/OpenGrok/issues/1031

---

web/menu.jspf

When there are many projects, scrolling through them all becomes difficult with such a small select box.  Dragging the slider by even one pixel can move the list more than 6 elements making it hard to scan for an item of interest and making scrolling very disorienting.
Making it a bit bigger in this case helps greatly.  For installations with a small number of projects the size of the box will not change so there should be no adverse impact on them.

Make the Projects list box larger

---

src/org/opensolaris/opengrok/history/PerforceHistoryParser.java
src/org/opensolaris/opengrok/history/PerforceRepository.java
test/org/opensolaris/opengrok/history/PerforceHistoryParserTest.java

Improve files version in Perforce repository:
Switch from '#file revision' to '@change number' as files version id.
Why?
'@change number' is version counter of whole repository. It's changelist ID, increased with each submit to repository.
'#file revision' - is version counter per file. Increased by 1 with every change on file. And is reset to 1 when file is moved/integrated!
(Description of #@ here http://www.perforce.com/perforce/r12.2/manuals/cmdref/o.fspecs.html)
That means with current #:
- versions of one file are not always distinct
- OG can show file version history like: 1,2,3,4,1,2 - (this completely ruins annotate feature on any moved/integrated file)
- searching by changelist number does not work
- directories use @ as version, so it is not consistent with files
+ the only …

Improve Perforce files history&annotate

---

src/org/opensolaris/opengrok/history/History.java
src/org/opensolaris/opengrok/web/PageConfig.java
web/default/style.css
web/history.jsp
web/offwhite/style.css
web/polished/style.css

fixes #521
It uses some features defined for search pagination - limit, offset and slider composition.
Demo as always available [here](http://virtual99.cz.oracle.com/paginator/).
For example OpenGrok's [readme](http://virtual99.cz.oracle.com/paginator/history/OpenGrok/README.txt)

Paginating history entries

---

web/default/print.css
web/default/style.css
web/offwhite/print.css
web/offwhite/style.css
web/polished/print.css
web/polished/style.css
web/utils.js

fixes #540 
This deals with the problem of copy-paste whitespace between line number and the rest of the code.
It's pure javascript solution therefore it has no data overhead.
On Firefox and Chrome there is a space appended with css :after selector (but it's not copyable) and upon an user's selection this space is extended to ordinary space which is preserved in selected text.
Because of the natural form of files there is couple of limitations
- Line gets selected from the beginning to the end (extending users selection)
- Sometimes it wrongly guesses the first line (or last line) in selection resulting in more lines are selected
But for the usual use case - copying few lines of code to show them somewhere it's sufficient.
Solution is made effective. Lines processing and adding the …

Preserving whitespace on copy-paste

---

src/org/opensolaris/opengrok/analysis/c/CxxAnalyzerFactory.java

`.tcc` is a fairly standard extension for template implementations (e.g. used in libstdc++; see https://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/files.html), so we should analyze `.tcc` files when working with C++ codebases.

Analyze .tcc files as C++ source code

---

web/utils.js

As mentioned in #927, 
commit 22e51bd introduced a bug - not hiding a line number on ```lntoggle()```.
The commit above added a class 'target' to the highlighted links, but in the code there was a strong 
test for ```className === 'someotherclass'``` upon hiding/showing, which should be better replaced by ```$.fn.hasClass()```
Result tested in Mozilla and IE9.

Fixing #927 regression

---

src/org/opensolaris/opengrok/index/Filter.java
src/org/opensolaris/opengrok/index/IgnoredDirs.java
src/org/opensolaris/opengrok/index/IgnoredFiles.java
src/org/opensolaris/opengrok/index/IgnoredNames.java
test/org/opensolaris/opengrok/index/IgnoredNamesTest.java

make the matching in Filter class more predictable

---

src/org/opensolaris/opengrok/web/PageConfig.java
src/org/opensolaris/opengrok/web/Util.java
web/diff.jsp
web/list.jsp
web/mast.jsp
web/raw.jsp
web/utils.js

mast.jsp needs to access some URL parameters in JavaScript code.
Currently, it does this in a Java snippet that escapes the parameter
value and prints it in the HTML. This patch changes it so that the
parameters are fetched by the JavaScript code itself, eliminating the
roundtrip via the Java and HTML domains, which simplifies the quoting.
Also remove Util.escapeXml(). Instead use Util.URIEncode(),
Util.htmlize() and Util.jsStringLiteral() as appropriate.
Util.escapeXml() was a hybrid of the latter two.
Also quote some values that were previously not quoted.

Clean up encoding and decoding of URL parameters.

---

web/utils.js

The code that scrolls to the requested line in an xref page, looks
like this:
$("*").animate(...)
That is, it calls animate() on every element in the page. When viewing
a very big document (say, a source file with 20000 lines), this is
suboptimal. In Chrome, it fails with "RangeError: Maximum call stack
size exceeded". Firefox, IE and Edge don't fail, but the code is very
slow and leaves the page unresponsive for a very long time after it
has loaded.
This patch changes the selector to only select the \<div\> element with
id="content", so that animate() is called on that single element
instead of every element in the document.

Improve scrolling to line number.

---

web/default/print.css
web/default/style.css
web/offwhite/print.css
web/offwhite/style.css
web/polished/print.css
web/polished/style.css
web/utils.js

When line numbers or annotations are toggled, the anchors on every
line of the document are updated with a new class. It is easier to
just change the class of a parent element, such as the "body" element.
The motivation for this change was to speed up toggling of line
numbers in large documents. Unfortunately, it had no measurable
effect on the performance. It seems like most of the time is spent
doing the actual redrawing of the page, and the time spent on
manipulating the DOM is negligible in comparison.
It does however simplify the code that implements the toggling, and
less code is better.

Simplify toggling of line numbers and annotations.

---

src/org/opensolaris/opengrok/configuration/Configuration.java
src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/web/PageConfig.java
web/default/style.css
web/history.jsp
web/utils.js

New feature to allow users to collapse and expand long revision
messages on the history page.

Fix for https://github.com/OpenGrok/OpenGrok/issues/1076

---

web/default/style.css
web/offwhite/style.css
web/polished/style.css
web/utils.js

Moving toggle revision to domReadyHistory.
Copying css rules to offwhite and polised styles.

minor css and js cleanup

---

src/org/opensolaris/opengrok/configuration/Project.java
test/org/opensolaris/opengrok/configuration/ProjectTest.java

This is a follow-up to the fix for #1074.
Project.getProject() currently creates a copy of the project list and
sorts it on every call. This is more work than necessary. A single
pass through the unsorted project list should be enough to find the
longest matching prefix.
The patch also fixes a bug which would cause getProject() to think
that the path /foof/bar would be in the project with path /foo, if
there was no project which had the path /foof.

More project prefix matching improvements

---

build.xml
src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java
src/org/opensolaris/opengrok/analysis/lua/Consts.java
src/org/opensolaris/opengrok/analysis/lua/LuaAnalyzer.java
src/org/opensolaris/opengrok/analysis/lua/LuaAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/lua/LuaSymbolTokenizer.lex
src/org/opensolaris/opengrok/analysis/lua/LuaXref.lex

Based off of the [Lua 5.3 Reference Manual](http://www.lua.org/manual/5.3/manual.html).
I ran it against our (crazy, massively large) codebase and didn't see it trip up on any of our Lua.
I signed the OCA *forever* ago when I used to contribute to the ndbcluster engine on MySQL; not sure if I need to sign anything else for this, but let me know if I do.

add Lua analyzer

---

src/org/opensolaris/opengrok/configuration/Groups.java
test/org/opensolaris/opengrok/configuration/GroupsTest.java
tools/Groups

This should help users to manipulate with group configuration if neccessary.
Script is located in tools/Groups and provides several commands
- ```tools/Groups add``` - adding a group to configuration
- ```tools/Groups delete``` - deleting a group from configuration
- ```tools/Groups list``` - listing all available groups
- ```tools/Groups match``` - match a project name against the groups
General section with usage is available under
```tools/Groups help```
Specific usage with arguments and options is under every command with ```--help``` switch
```tools/Group add --help```
Examples:
1. ```OPENGROK_INSTANCE_BASE=/var/opengrok tools/Groups list``` 
Lists all groups in /var/opengrok/etc/configuration.xml
2.  ```READ_XML_CONFIGURATION=~/myconf.xml tools/Groups add name pattern```
Adds a …

script wrapper for manipulating with groups

---

src/org/opensolaris/opengrok/index/IgnoredDirs.java
src/org/opensolaris/opengrok/web/PageConfig.java
web/default/print.css
web/default/style.css
web/offwhite/print.css
web/offwhite/style.css
web/polished/print.css
web/polished/style.css
web/repos.jspf

In some cases with nested repositories it's not really helpful the information about subrepositories when they don't have their parent url (or branch). I'd suggest to skip those and if the information about parent url is available then provide the xref.
Current (note that the first two subrepositories in "android" are inside the .repo directory):
Proposed:

Don't  display subrepositories without a parent url

---

web/utils.js

I'm disabling the spaces plugin (copy - paste space problem) until the selection is improved. This can't occur in the next rc.
This temporarily solves the stopper #1061

disabling spaces js plugin

---

README.txt
opengrok-indexer/pom.xml
pom.xml
test/org/opensolaris/opengrok/condition/ConditionalRun.java
test/org/opensolaris/opengrok/condition/ConditionalRunRule.java
test/org/opensolaris/opengrok/condition/RepositoryInstalled.java
test/org/opensolaris/opengrok/condition/RunCondition.java
test/org/opensolaris/opengrok/history/BazaarRepositoryTest.java
test/org/opensolaris/opengrok/history/CVSRepositoryTest.java
test/org/opensolaris/opengrok/history/GitRepositoryTest.java
test/org/opensolaris/opengrok/history/MercurialRepositoryTest.java
test/org/opensolaris/opengrok/history/PerforceRepositoryTest.java

In order to remove lots of the warnings that exhibit if a developer attempts to run the tests
without some of the repository tools installed, the addition of JUnit rules are used.
If people aren't opposed to the PR I can add the remaining changes to annotate the remaining tests classes/methods.

Added conditional Junit rule

---

plugins/SampleAuthorizationPlugin.java

The SampleAuthorizationPlugin did not implement the IAuthorizationPlugin interface. This was introduced by #1117 but forgotten by travis.
Also:
Regading the authorization framework we have two new wikis:
- https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-Authorization
- https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-Groupings
Containing fairly similar things like in doc directory but with .md desing.

sample authorization plugin does not implement the interface

---

web/search.jsp
web/utils.js

implements #1136 
Tested in Firefox 39.0 and Explorer 9.0. However this should work everywhere. 
internal demo: http://virtual99.cz.oracle.com/clear/

hiding previous results after search click

---

OpenGrok
README.txt
src/org/opensolaris/opengrok/index/Indexer.java

OpenGrok generates history regardless of what OPENGROK_GENERATE_HISTORY is set
to, for local repositories.  This variable currently only goes into effect for
remote repositories.  Change its semantics such that if -H is not passed, then
history generation and caching is disabled altogether for all repositories.
This is useful when indexing large local repositories such as a local mirror of
the AOSP sources worth 70GB. History generation in this case results in the
indexing never completing.
We also fix the semantics of OPENGROK_GENERATE_HISTORY in the wrapper script,
such that if its set to "off", then we don't pass -H at all to OpenGrok.
Signed-off-by: Joel Fernandes <agnel.joel@gmail.com>

Fix semantics of -H flag and disabling history generation

---

build.xml
src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java
src/org/opensolaris/opengrok/analysis/Ctags.java
src/org/opensolaris/opengrok/analysis/pascal/Consts.java
src/org/opensolaris/opengrok/analysis/pascal/PascalAnalyzer.java
src/org/opensolaris/opengrok/analysis/pascal/PascalAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/pascal/PascalSymbolTokenizer.lex
src/org/opensolaris/opengrok/analysis/pascal/PascalXref.lex

A first go at adding pascal support. ctags has pascal support, but somewhat limited when it comes to object oriented pascal.
It isn't picking up defs as well as I'd like, but it's a start (never used jflex before).
Sort of fixes #929

Add Pascal support

---

src/org/opensolaris/opengrok/analysis/Ctags.java
test/org/opensolaris/opengrok/analysis/pascal/PascalAnalyzerFactoryTest.java
testdata/sources/pascal/Sample.pas

More improvements to pascal support. Follows on from #929 and #1134 
For proper scopes support, I think ctags changes will be required.

Handle pascal properties, and add a JUnit test

---

plugins/src/main/java/HttpBasicAuthorizationPlugin.java

As described on [wiki](https://github.com/OpenGrok/OpenGrok/wiki/OpenGrok-Authorization#http-basic-tutorial) I added a more interesting example of a plugin containing group discovery.
Also mentioned in the tutorial that this plugin **does not cache anything** and traverses through the group structure every time it is asked for a decision - which is not desirable for production mode.
This plugin can be used as an inspiration for other user defined plugins.

adding more complex plugin example 

---

web/js/utils.js
web/menu.jspf
web/search.jsp

The clear button wasn't working at all after moving to jquery 3.1.0. Obviously it couldn't select the [type=text] without having the inputs as text.
Moreover recalling #1136 I forgot to hide the suggestions - fixed now.

fixing clear button

---

src/org/opensolaris/opengrok/web/PageConfig.java
test/org/opensolaris/opengrok/web/PageConfigTest.java

fixes #1173
During this I've discovered [GitRepository.java#L272-L318](https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/history/GitRepository.java#L272-L318), which is the part of the code which inserts different annotations for the specific lines when the revision number is wrong. The git is run with `-C` option searching for lines in the same commit which also got changed. Problem is like in #1173 that it inserts cruelly out of the way results into the file.
**NOTE: the problem happens still when the revision number is wrong (i. e. when user change the parameter `r` in url to whatever)**
It's hard to convert this to unit test - the lines are always eventually found even when they're wrong - so can anyone explain me the intention here?

removing regression of eee3266

---

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java
src/org/opensolaris/opengrok/configuration/Configuration.java

- The authorization framework can properly unload plugins 7fa69f2
- The default value for plugin directory is set in `setDataRoot` ec794d2
- tests don't contain nasty exceptions
- functionality is the same (when the data root is set - the default plugin directory is set as well)

Authorization properly unloads plugins

---

web/js/utils.js

Scopes were failing when the line element (a.l, a.hl) was containing other class than 'l' or 'hl' (like 'selected' when it was selected). This can be easily checked with jquery to avoid direct class match and to keep the expected behaviour.

using jquery in scopes so it does not rely on exact html class match

---

src/org/opensolaris/opengrok/index/IndexDatabase.java

As of #1175 where I discovered some unexpected behaviour around creating the dirty file for a project and at the end of the index also the problem of refreshing the timestamp for the webapp.
I believe that the following condition introduced in [link to the diff](https://github.com/OpenGrok/OpenGrok/commit/61910105#diff-9ee85b0329e20c488bfd4ea96464dae2R342) (cset 61910105) is wrong. 
```java
if (!dirty && !dirtyFile.createNewFile()) {
if (!dirtyFile.exists()) {
log.log(Level.FINE, "Failed to create \"dirty-file\": ", dirtyFile.getAbsolutePath());
}
dirty = true;
}
```
The problem is that it the `createNewFile` returns true if the file was created - so basically if the dirty variable is false and the file **could** be created then the if is skipped => the dirty variable does not set to …

fix updating the timestamp in the webapp

---

web/default/style.css
web/js/utils.js
web/offwhite/style.css
web/polished/style.css

After the update to jquery 3.1.0 there is a visible focus on the content area of the page.
It's the line between the search bar and the content.
For me it's not necessary and it doesn't look nice, so that's why this diff removes it. I hope there is not some special action connected to this.

fixing auto focus on content area

---

src/org/opensolaris/opengrok/history/SubversionHistoryParser.java
src/org/opensolaris/opengrok/history/SubversionRepository.java
test/org/opensolaris/opengrok/history/SubversionHistoryParserTest.java

Like in #1196 for git repositories, this extends the number of valid date formats for svn repositories. Which should prevent unlikely events of slightly different date format in the repository history.

allowing more date formats for svn date parsing

---

src/org/opensolaris/opengrok/history/GitRepository.java
test/org/opensolaris/opengrok/history/GitHistoryParserTest.java

fixes #1193
Using `--date=rfc` option for `git log` command overwrites user configuration and always retrieves the dates in the rfc2822 format.
Covered with a test case.

using --date option when retrieving git history

---

OpenGrok

after #1239 is in upstream this fixes #1223
Introducing new env variable to control if user wants to have projects disabled or enabled. By default it's turned on.

let user to change if the projects are enabled or disabled

---

tools/Groups

The `OPENGROK_DISTRIBUTION_BASE` was set incorrectly to different directory and also it was not possible to overwrite `OPENGROK_JAR`.

fixing autolocation of opengrok.jar

---

web/mast.jsp

Reported in #1223, caused by cset 8389245

Directory listing when projects are disabled no longer displays nullptr exception

---

web/js/tablesorter.parsers.js

making tablesorter size parser more robust

---

web/js/utils.js

If anyone likes the old behaviour then he can disable the new project picker by commenting out its init call in `utils.js`.
Select/DeselectAll and invert should then work like expected. Support for selecting particular groups is not migrated.
```javascript
/**
* Initialize the new project picker
*/
init_searchable_option_list()
```

allowing users to disable the new project picker and use the old one

---

src/org/opensolaris/opengrok/analysis/JFlexXref.java
web/default/style.css
web/offwhite/style.css
web/polished/style.css

This should fix #1232. It works for me on java and C files. Can anyone else please verify it?
The idea is clear - `display: block` automatically does a new line break so `display: inline` leaves the responsibility to the xref text where the newline is already in the source code after each line.

Fixing copy-paste problem when copying scope context

---

web/js/utils.js

fixes #1224
We should anyway consider to replace the `&nbsp;` by something else, like a fix-sized element, since ui positioning is not a job of html anymore.

hiding also the scope space on line toggle

---

web/js/utils.js

Changes the scope view from:
`foo( ..., List&lt;String&gt; subFiles, List&lt;String&gt; repositories, List&lt;String&gt; zapCache, boolean listRepoPaths)`
to:
`foo( ..., List<String> subFiles, List<String> repositories, List<String> zapCache, boolean listRepoPaths)`

render scope signature as html

---

src/org/opensolaris/opengrok/configuration/Configuration.java
src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/history/GitRepository.java
src/org/opensolaris/opengrok/history/Repository.java
src/org/opensolaris/opengrok/history/RepositoryFactory.java
src/org/opensolaris/opengrok/history/RepositoryInfo.java
src/org/opensolaris/opengrok/web/PageConfig.java
web/default/style.css
web/js/repos.js
web/js/utils.js
web/offwhite/style.css
web/polished/style.css
web/repos.jspf

Currently the repos table on home page already shows some details about the available projects. I found it very helpful to also show what is the current **indexed version** for each project. This way you can immediately know how much up to date the project is.
As a start I added the information for git SCM only but I prepared the infrastructure to add for other SCM (much like the “branch” column).

Add current indexed version to repos table.

---

src/org/opensolaris/opengrok/analysis/JFlexXref.java

Mentioned in #1274.
I'm struggling with this for quite long time and I can't find the best solution - currently this is way nicer although not perfect.
Only the next line number jumps to the right and when it folds it becomes aligned with the others.
There is generally a problem with new lines, preformated text `<pre>` and block elements (the `fold` effect needs the element to be at least `inline-block`)

removing the ugly content jump on scope collapse

---

src/org/opensolaris/opengrok/web/Util.java

Observable for example on OpenGrok file `web/default/style.css`. Find revision `1412e1e9` (image attached) and click on it - that takes you into that revision. However the revision number then shows 16/15 which is not correct. I think it's because there are some revisions which don't have information about author (that's different story - they're not available in `git log` in this case):
Before:
After:

fixing revision number in annotation

---

web/default/style.css
web/offwhite/style.css
web/polished/style.css

Removing the text cut in the select box: (before)
(after):

removing select from common input style

---

test/org/opensolaris/opengrok/configuration/messages/NormalMessageTest.java

fixes #1279
The creation of the three messages can't and doesn't happen at the same time.

forcing the same create date for all messages in tests

---

src/org/opensolaris/opengrok/analysis/c/CXref.lex

fixes #1163
I'm not a pro in lex files. However the removed line added a `{EOL}` into the output and after that the `startNewLine();` added a second one. It looks fine to me to trash the trailing whitespace and EOL as it's done also [in general EOL](https://github.com/OpenGrok/OpenGrok/blob/65a0ddded9e4776c836b5c683f3c33f750e0546d/src/org/opensolaris/opengrok/analysis/c/CXref.lex#L128-L132) later and basically it's not valuable for anything.
Requires reindex.

removing extra newline in C/C++ files after one line comment

---

src/org/opensolaris/opengrok/history/GitRepository.java
src/org/opensolaris/opengrok/history/MercurialRepository.java

It's without timeout like it's done in [MercurialRepository#determineParent()](https://github.com/tulinkry/OpenGrok/blob/ad09d029c88af0dcb7492df5e3ed9f66086b417b/src/org/opensolaris/opengrok/history/MercurialRepository.java#L668)

using Executor class for determining the current version

---

index.html

Update required Java version to 1.8 and Tomcat to 8.x, same as given in the requirements file.

bump required Java and Tomcat versions for gh-pages

---

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/configuration/messages/Message.java
src/org/opensolaris/opengrok/configuration/messages/Messages.java
src/org/opensolaris/opengrok/util/XmlEofInputStream.java
src/org/opensolaris/opengrok/util/XmlEofOutputStream.java
test/org/opensolaris/opengrok/configuration/messages/MessagesTest.java

This is one option.
The other option is to use `ObjectInput/OutputStream` which decodes the whole object (and does not need the EOF solution). The problem with this is that the xml decoder does not stop reading after the root element is closed - that's why I introduced this artificial EOF.

adding a possibility to send a response about message acceptance

---

web/default/style.css
web/offwhite/style.css
web/polished/style.css

After UI changes in #1252 the messages box was left intact. I corrected the size to match the project's box.

deleting margin for messages

---

build.xml

check Java version and bail out if unsupported

---

src/org/opensolaris/opengrok/search/Results.java
src/org/opensolaris/opengrok/web/Util.java
web/mast.jsp
web/menu.jspf
web/repos.jspf

fixes #1212
The special group "other" (projects without any group) is not handled. Only on the main page there is the exclamation mark next to the section "Others".
When viewing single project there are all messages which are connected to the project - main messages, project messages and group messages:
On the main page, the exclamation mark is there for every group.

Messages are group aware

---

src/org/opensolaris/opengrok/history/GitRepository.java
src/org/opensolaris/opengrok/util/StringUtils.java
test/org/opensolaris/opengrok/util/StringUtilsTest.java

Apparently our feature from #1262 is only supported in git2.6+ (as discovered [here](https://github.com/OpenGrok/OpenGrok/pull/1262#commitcomment-20273958)).
This patch should support older git versions by converting the date from rfc, without using the `--date=format:` option.
Also this was reported in #1310 which gave me the clue that not everybody uses upgraded git.

Supporting older git < 2.6 which does not have --date:format option

---

src/org/opensolaris/opengrok/history/AccuRevRepository.java
src/org/opensolaris/opengrok/history/BazaarRepository.java
src/org/opensolaris/opengrok/history/CVSRepository.java
src/org/opensolaris/opengrok/history/ClearCaseRepository.java
src/org/opensolaris/opengrok/history/GitRepository.java
src/org/opensolaris/opengrok/history/MercurialRepository.java
src/org/opensolaris/opengrok/history/MonotoneRepository.java
src/org/opensolaris/opengrok/history/RazorRepository.java
src/org/opensolaris/opengrok/history/Repository.java
src/org/opensolaris/opengrok/history/RepositoryInfo.java
src/org/opensolaris/opengrok/history/SCCSRepository.java
src/org/opensolaris/opengrok/history/SSCMRepository.java
src/org/opensolaris/opengrok/history/SubversionRepository.java
test/org/opensolaris/opengrok/history/GitRepositoryTest.java
test/org/opensolaris/opengrok/history/RepositoryTest.java
test/org/opensolaris/opengrok/history/SubversionRepositoryTest.java

fixes #1326
Reindex needed (not full, just some of the properities in configuration.xml have changed).

deduplication of date formats in repositories

---

web/httpheader.jspf
web/js/utils-0.0.3.js

For a large file (.c file 8000 lines) the performance of the scopes window almost disables the user to scroll causing the browser to freeze.
This introduces a timeout so the callback is not triggered after every scroll event.

using a timeout for scopes update

---

web/list.jsp

fixes #1356
This was some kind of race condition (that's what I think). The part under the diff to write the `<style>` into the page config sometimes didn't get executed. It's still in our code that the `cfg` variable is defined as a private property of the compiled JSP which must be a race condition if there is a heavy traffic and threads start to use this variable. **Therefore I suggest the next fix which is to get rid of this private variable.**
This fix makes the `cfg` local variable which shadows the member variable.
I discovered that this behaviour only happens under heavy traffic (or heavy load of the machine + heavy traffic). I tested the localhost with apache benchmark:
```bash
ab -n 1000 -c 10 -H 'X-FROM: 007' http://localhost:8080/source/xref/opengrok-master/src/org/opensolaris/ …
```

defining the type of cfg (PageConfig)

---

tools/Groups

fixes #1321
The only supported env variable for getting input configuration is READ_XML_CONFIGURATION.
The main configuration (and also any other files) can be read with the -i switch.

do not discover the opengrok configuration for reading groups

---

src/org/opensolaris/opengrok/history/GitRepository.java

Same fix for same issue that is avoided by https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/history/GitRepository.java#L165

Remove file/revision ambiguity from git history log command

---

web/repos.jspf

Just to accept this faster to have a non-failing build of webapp:
removing non existent import
```java
-<%@page import="org.jcp.xml.dsig.internal.dom.Utils"%>
```
I have no idea how that came there.

removing unused and non-existent import

---

src/org/opensolaris/opengrok/history/FileHistoryCache.java
test/org/opensolaris/opengrok/history/FileHistoryCacheTest.java

Sometimes in our deployment I saw some files having history entries twice - the history is formed by 2 identical history entry sequences. It's not clear to me how this can happen, it has to be caused by invalid merging of old and new history. It seems this happens for renamed files. This PR makes the area more robust by avoiding the merge for renamed files.

more robust handling of merging history entries for files

---

web/diff.jsp
web/enoent.jsp
web/help.jsp
web/history.jsp
web/index.jsp
web/list.jsp
web/mast.jsp
web/more.jsp
web/opensearch.jsp
web/raw.jsp
web/rss.jsp
web/search.jsp
web/status.jsp

After changes in #1453 not all pages are affected with the source root check.
The error page is not set in every case when the configuration is missing. This PR should set it everywhere.
Actual output when the configuration.xml does not exist (status 200 OK):
Expected output:

checking source root existence in the top level jsps

---

web/foot.jspf
web/js/utils-0.0.8.js

As suggested by @mrate I don't update the scopes window when it's not visible.
The whole change here is about this at the very bottom in `scopes_on_scroll()`:
```javascript
if($.scopesWindow && $.scopesWindow.initialized && !$.scopesWindow.is(':visible')) {
return;
}
```
The rest is just to fully support this behaviour without any visible delay. I tested the results in a big file https://github.com/svn2github/valgrind-vex/blob/master/priv/guest_arm_toIR.c.

speeding up the scopes window

---

README.txt
src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/configuration/messages/ConfigMessage.java
src/org/opensolaris/opengrok/configuration/messages/Messages.java
test/org/opensolaris/opengrok/configuration/messages/ConfigMessageTest.java
tools/Messages

Mentioned in #1479 this implements the possibility to set a webapp option at runtime. It's not really necessary but appears to be quite handy with some options to test them out, like
- `authorizationWatchdogEnabled` (#1465) 
- `hitsPerPage`
- `chattyStatusPage`
- `revisionMessageCollapseThreshold`
- `groupsCollapseThreshold`
- `messageLimit`
and a couple of others. Not every option in `Configuration.java` has a meaning for the webapplication.
**The change is not persistent when server was restarted or webapp was redeployed or when the reindex was run.** For persistent configuration when reindexing use the `OPENGROK_READ_XML_CONFIGURATION` environment variable pointing to a xml file with changed options.

Messages: adding an option 'set' for config message

---

src/org/opensolaris/opengrok/web/Util.java
test/org/opensolaris/opengrok/web/UtilTest.java
web/history.jsp

Reported in internal environment. When there is a bug id (or a review number) which matches the `bugRegex` the commit message is replaced with the link to it. However this happened only for the "long" (original) summary not for the "short" summary. When user clicked "show more" the links disappeared.
Now the code supports both ways.

bugs and reviews are replaced in both short and long summary

---

src/org/opensolaris/opengrok/authorization/AuthorizationCheck.java
src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java
src/org/opensolaris/opengrok/authorization/AuthorizationPluginClassLoader.java
src/org/opensolaris/opengrok/authorization/AuthorizationPluginWrapper.java
src/org/opensolaris/opengrok/configuration/Configuration.java
src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/util/IOUtils.java
test/org/opensolaris/opengrok/authorization/AuthorizationFrameworkTest.java
test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java

Adding a little bit of control to how the authorization is performed in opengrok.
Introducing three new plugin roles:
- required
- requisite
- sufficient
I'll include more detailed description of these in the wiki page once this is merged. These roles should copy the characeristics of the same roles in pam list.
Also the order of plugin execution is determined by their order in the configuration and these three keywords control how to deal with the returned value of the authorization check.
**NOTE: This change is backward compatible with the previous version of auth framework as it adds all discovered plugins as `required`.** The system still remains plug-and-play when using just one plugin as the only action is to put it in the plugin directory.
The configuration entry (in read-only …

Authorization framework enhancements

---

src/org/opensolaris/opengrok/history/GitRepository.java

Fixes #1512, adds `supportsSubRepositories()` to Git.
And I accept the Oracle Contributor Agreement. I haven't signed it and sent it back, but apparently it is enough to specify it in the pull request comment.

Support for nested Git repositories (#1512)

---

src/org/opensolaris/opengrok/index/Filter.java
src/org/opensolaris/opengrok/index/IgnoredNames.java
src/org/opensolaris/opengrok/web/DirectoryListing.java
test/org/opensolaris/opengrok/index/IgnoredNamesTest.java

ignore match should avoid checking absolute paths for filenames

---

plugins/src/main/java/HttpBasicAuthorizationPlugin.java
src/org/opensolaris/opengrok/configuration/Group.java

**This expects the #1525 to be merged as it already implements the new interface.**
This change moves the responsibility of a group discovery
- which repositories are under this group (even indirectly)
- which projects are under this group (even indirectly)
- descendant groups
- parent groups
to the opengrok code and the plugin can just call the new methods if it wants to add all subgroups/repositories/.. to the allowed set.

Easily discover groups in authorization plugins

---

src/org/opensolaris/opengrok/web/ProjectHelper.java

The projects/repositories are filtered always through the getter so this was just needlessly calling the authorization framework for all projects and repositories without any specific gain.

avoid unnecessary calls to authorization framework

---

src/org/opensolaris/opengrok/web/PageConfig.java

Behaviour discovered in #1556 if user visits an URL like http://localhost:8080/source/diff/OpenGrok/random/url then the project can be clearly determined from the URL however the code in the question bubbles down to calling the authorization framework for every project in the cookie (or even after for the default projects). That is not necessary I think.

using the project from URL if possible

---

src/org/opensolaris/opengrok/web/Statistics.java

We may loose some information without the synchronization when there are more parallel requests.

using statistics with synchronized methods

---

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java

The scenario before needlessly slowed the authorization process as it exclusively allowed only one thread processing the stack of plugins.
The problem with the synchronization here is that we don't want to concurrently share the stack when there is a reload of plugins while there is some authorization in progress. ReadWrite lock is more accurate for this situation.

more efficient locking for shared resource with more readers

---

src/org/opensolaris/opengrok/web/ProjectHelper.java

- avoiding concurrent modification exception (when the list is modified later)
This piece of code in repos.jsp produces an CME when modifying the list of repositories (which is taken directly from the RE). Returning a copy solves the problem, the objects in the list are not modified.
```java
List<RepositoryInfo> repos = pHelper.getRepositoryInfo(project);
String projDesc = project.getName();
Integer cnt = 0;
Collections.sort(repos, comparatorRepo); 
%>
<%
for (RepositoryInfo ri : repos) {
if (cnt > 0 && ri.getParent() == null)
// discard repositories without a parent url
continue;
if (cnt != 0) {
projDesc = ri.getDirectoryName()
.replace(cfg.getSourceRootPath() + File.separator, "");
}
%>
```

returning copy of the repository list

---

src/org/opensolaris/opengrok/authorization/AuthorizationEntity.java
src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java
src/org/opensolaris/opengrok/authorization/AuthorizationPlugin.java
src/org/opensolaris/opengrok/authorization/AuthorizationStack.java

Allow user to specify target groups/projects for particular stack (or even a plugin).
When the authorization traverses the stack of plugins/stacks it checks if the plugin/stack is targeted only for some groups/projects and does not execute if it that is not the case.
The syntax is pretty straight-forward (note the section forGroups):
```xml
<void method="add">
<object class="org.opensolaris.opengrok.authorization.AuthorizationPlugin">
<void property="forGroups"> 
<string>Group 1</string>
</void>
<void property="forGroups"> 
<void method="add">
<string>Group 1</string>
</void>
<void method="add">
<string>Group 2</string>
</void>
</void>
<void property="name">
<string>opengrok.auth.plugin.SomePlugin</string>
</void>
<void property="flag">
<string>REQUISITE</string>
</void>
<void …
```

targeting stacks for particular groups or projects

---

src/org/opensolaris/opengrok/history/MercurialRepository.java

seeing that the history log triggers this sort of command (thanks to Solaris `pargs` command):
26891:  /usr/bin/python2.7 /usr/bin/hg log -r reverse(0::'bar') foo
argv[0]: /usr/bin/python2.7
argv[1]: /usr/bin/hg
argv[2]: log
argv[3]: -r
argv[4]: reverse(0::'bar')
argv[5]: foo
argv[6]: --template
argv[7]: changeset: {rev}:{node|short}\\nuser: {author}\\ndate: {date|isodate}\\ndescription: {desc|strip|obfuscate}\\nfiles: {files}\\nfile_copies: {file_copies}\\nmercurial_history_end_of_entry\\n
which works however does not really follow `hg log` usage.

filename should be the last argument of Mercurial history executor

---

src/org/opensolaris/opengrok/analysis/TextAnalyzer.java
src/org/opensolaris/opengrok/search/Results.java
src/org/opensolaris/opengrok/util/IOUtils.java
src/org/opensolaris/opengrok/web/PageConfig.java
web/list.jsp
web/more.jsp

Currently OpenGrok recognizes UTF-8/16 BOM only in `/xref` without parameter such as revision or annotate.
This patch enable to handle it in `/xref` (with any parameter),  `/search` and `/diff` in same way.
I have already signed OCA.

Improve UTF-8/16 BOM handling.

---

src/org/opensolaris/opengrok/configuration/Groups.java
tools/Groups

fixes #1626
The constraint prevents user from creating a parent group without any pattern (a group which won't match anything).

relaxing the constraint of non-empty pattern

---

tools/Groups

The input file does not really make sense for the empty subcommand so I decided to remove it
fixes #1624

removing the input file from empty subcommand 

---

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/web/WebappListener.java

fixes #1609
Be aware that this still issues the first warning that the plugin directory is null (when env is instantiated) and after that it sets the directory and reloads the plugins.

perform any necessary action when the configuration is read from a file

---

src/org/opensolaris/opengrok/web/PageConfig.java
test/org/opensolaris/opengrok/web/PageConfigTest.java

filtering the xref of '/' based on authorization

---

src/org/opensolaris/opengrok/configuration/Groups.java

fixes #1629
```log
skupina 1 ~ 'bigbandbiskupska'
skupina 2 ~ 'test.*'
skupina 3 ~ '.*rok'
skupina 4 ~ '.*te.*'
```

changing quotes to avoid bash interpretation

---

web/index.jsp

fixes #1509 
There was an extra div added in cset dc26274 by an accident making the main page invalid.

removing an extra div - valid main page

---

src/org/opensolaris/opengrok/web/Scripts.java
web/default/style.css
web/help.jsp
web/js/utils-0.0.10.js
web/offwhite/style.css
web/polished/style.css

adding more colors for symbol highlighting

---

src/org/opensolaris/opengrok/web/DirectoryListing.java
test/org/opensolaris/opengrok/web/DirectoryListingTest.java

fixes #1552
Replaced with '-'.
Tablesorters return 0 for all directories (unparseable size):
```
if (parts === null || parts.length < 3) {
return 0;
}
```

removing the size for a directory in directory listing

---

src/org/opensolaris/opengrok/web/Scripts.java
web/default/style.css
web/httpheader.jspf
web/js/diff-0.0.2.js
web/js/utils-0.0.12.js
web/offwhite/style.css
web/polished/style.css

fixes #1488
might fix #1288
I removed the silly content resize javascript and introduced a fixed header for all code related pages. The rest of the changes in the js code are just changes to make it work with the new fixed header.
The result of this change is that viewing a file is still available even if any of our javascript beauty fails when executing.
Anyway I had to introduce a new color for the header because it looks quite ugly when it's white and there is a space between the line number (the header must have a fixed height).

fixed header instead of javascript content height resize action

---

test/org/opensolaris/opengrok/index/IndexerRepoTest.java

When investigating #1666 I found out that ctags binary executed by tests in  IndexerRepoTest.java is not necessarily the one set by `setCtags()` in these tests. This is because the indexer is run via `Indexer.main()` with distinct set of args that are supplied directly so settings in RuntimeEnvironment such as ctags binary do not get into effect unless specified as these args.
Also, given ctags are checked in individual tests, the `@BeforeClass` check is unnecessary.

use ctags binary from RuntimeEnvironment in IndexerRepoTest.java

---

src/org/opensolaris/opengrok/history/FileHistoryCache.java
src/org/opensolaris/opengrok/history/HistoryCache.java
src/org/opensolaris/opengrok/history/HistoryGuru.java
src/org/opensolaris/opengrok/index/IndexDatabase.java
src/org/opensolaris/opengrok/index/Indexer.java
test/org/opensolaris/opengrok/history/FileHistoryCacheTest.java
test/org/opensolaris/opengrok/index/IndexDatabaseTest.java
test/org/opensolaris/opengrok/index/IndexerTest.java
test/org/opensolaris/opengrok/util/TestRepository.java

fixes #767
Also, done some semi-related code cleanup.

remove historycache entries automatically

---

src/org/opensolaris/opengrok/history/GitRepository.java
src/org/opensolaris/opengrok/history/Repository.java
test/org/opensolaris/opengrok/history/GitHistoryParserTest.java
test/org/opensolaris/opengrok/history/GitRepositoryTest.java

- assumes git 2.7.4 that added `iso-strict` date format
- the locale cset will be eventually tested by running extra Jenkins/Travis job in different locale

Git date parsing

---

src/org/opensolaris/opengrok/configuration/Group.java
src/org/opensolaris/opengrok/configuration/Project.java
src/org/opensolaris/opengrok/util/ClassUtil.java
test/org/opensolaris/opengrok/configuration/ConfigurationTest.java

The serialization bug we found is based on unexpected order of the field serialization in xml (and then deserializing them).
This has three possible solutions:
- marking the properties methods with `@Transient` annotation
- removing the setter method for these properties
- marking the properties as transient like in this PR
Note that just using `transient` keyword is not enough because the XML serialization is not a java serialization mechanism and it ignores this modifier. The serialization algorithm is based on presence of "get" and "set" methods to the corresponding fields.

fixing serialization bug with order of class properties

---

.gitignore

Ignore the files that has been generated by IntelliJ IDEA. These files are typically specific to the device where the IDE has been opened on.
I have accepted the OCA agreement and have mailed Oracle the signed copy.

Ignore files generated by IntelliJ IDEA

---

src/org/opensolaris/opengrok/web/JSONSearchServlet.java

Right now, this search servlet doesn't support paginating results. This can be problematic for large code bases that have more then the hard configured limit of MAXRESULTS. Paginating will keep the endpoint performant and allow these larger companies to get at data easily.

Added support for paginating the JSONSearchServlet

---

index.html

I release this trivial patch to the public domain.

Replace long-defunct example of OpenGrok user

---

OpenGrok

@nerakhon complained that stock macOS cannot run the `OpenGrok` script because it is missing `readlink` (which is from GNU utilities). Reverting to the previous version except added the `-P` option to `pwd` which is not POSIX compliant however should be omnipresent in today's Unices.
The difference between the `pwd -P` and `readlink -f` approach is that the latter resolves symlinks in the basename while the former does not, i.e. if both `bar` and `OpenGrok` components are symlinks in `/tmp/bar/OpenGrok`, and the canonical path is `/tmp/foo/blah`, the result from the proposed approach will be `/tmp/foo/OpenGrok` while `readlink -f` will output `/tmp/foo/blah`. That said, for the script itself it should not matter, I am just including it for completeness.

do not rely on readlink

---

src/org/opensolaris/opengrok/configuration/messages/ProjectMessage.java
src/org/opensolaris/opengrok/history/GitRepository.java
src/org/opensolaris/opengrok/history/MercurialRepository.java
src/org/opensolaris/opengrok/history/Repository.java
src/org/opensolaris/opengrok/history/RepositoryFactory.java
test/org/opensolaris/opengrok/configuration/messages/ProjectMessageTest.java

I contemplated a bit whether to add another message to trigger the `RepositoryInfo` refresh however was concerned that there might be too many messages in the system when reindexing many projects in parallel.
Also, there is a problem when webapp is running for a while and configuration is not stored persistently after each reindex cycle that the webapp will have more fresh configuration - with refreshed RepositoryInfo objects. This is left to be solved by whatever wrapper script is used to run the indexing (not the `OpenGrok` shell script but something which is wrapping around it).

refresh current version of project's repositories upon "indexed" message

---

src/org/opensolaris/opengrok/search/context/HistoryContext.java
src/org/opensolaris/opengrok/web/PageConfig.java
test/org/opensolaris/opengrok/search/context/HistoryContextTest.java

This should make sure that all links passed to the `diff` JSP are URIencoded and HTMLized properly (e.g. the `&` character in `href` needs to be `&amp;`).

add HTML encoding of links generated by history search

---

src/org/opensolaris/opengrok/web/PageConfig.java
test/org/opensolaris/opengrok/web/PageConfigTest.java

getLatestRevision() was not careful enough with checking `HistoryEntry` list and its called did not fullfil its promise to return `null` when `getLatestRevision()` fails.

getLatestRevision() fix

---

src/org/opensolaris/opengrok/history/BazaarRepository.java
src/org/opensolaris/opengrok/history/BitKeeperRepository.java
src/org/opensolaris/opengrok/history/CVSRepository.java
src/org/opensolaris/opengrok/history/ClearCaseRepository.java
src/org/opensolaris/opengrok/history/GitRepository.java
src/org/opensolaris/opengrok/history/MercurialRepository.java
src/org/opensolaris/opengrok/history/MonotoneRepository.java
src/org/opensolaris/opengrok/history/Repository.java
src/org/opensolaris/opengrok/history/RepositoryInfo.java
src/org/opensolaris/opengrok/history/SCCSRepository.java
src/org/opensolaris/opengrok/history/SubversionRepository.java
test/org/opensolaris/opengrok/web/ProjectHelperTest.java
test/org/opensolaris/opengrok/web/ProjectHelperTestBase.java

This is a bit of a hack to store only relative paths in `RepositoryInfo` object encoding.

directory name of RepositoryInfo should be stored as relative path

---

src/org/opensolaris/opengrok/history/FileHistoryCache.java
src/org/opensolaris/opengrok/history/HistoryEntry.java

This change caches history of the top-level directory of repository. This is easy to do since the history is available anyway to generate per-file history cache. New history will be incrementally merged with existing cache upon reindex.

cache history for top-level directory in repository

---

OpenGrok

tested with:
```
rm /var/tomcat8/webapps/source.war
OPENGROK_INSTANCE_BASE=/foo ./OpenGrok deploy
cd /tmp
jar xf /var/tomcat8/webapps/source.war
```
and check contents of `/tmp/WEB-INF/web.xml` - should contain this:
```
<context-param>
<description>Full path to the configuration file where OpenGrok can read its configuration</description>
<param-name>CONFIGURATION</param-name>
<param-value>/foo/etc/configuration.xml</param-value>
</context-param>
```

get rid of GNU sed'ism so that file substitution works on all platforms

---

build.xml

Compilation error: "Unsupported Java version: 9. Make sure that the Java version is 1.8 or greater."
This fix adds Java 9 to supported versions.

Java 9 compilation support

---

web/default/style.css
web/menu.jspf

Minor UI fix.
searchable-option-list plugin adds functionality: autocomplete + multi selection handling.
Unfortunately it also causes UI to be jumpy, because it has to be loaded client-side after the initial page load.
Proposed solution is not pretty, but it does the job.
before:
after:
I accept OCA for this patch

searchable-option-list workaround for less jumpy page loading

---

web/list.jsp

refactor annotation code in list.jsp

---

src/org/opensolaris/opengrok/configuration/ConfigMerge.java
src/org/opensolaris/opengrok/configuration/Configuration.java
src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/configuration/messages/ProjectMessage.java
src/org/opensolaris/opengrok/history/HistoryGuru.java
src/org/opensolaris/opengrok/history/RepositoryFactory.java
src/org/opensolaris/opengrok/history/RepositoryInfo.java
src/org/opensolaris/opengrok/index/Indexer.java
test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java
test/org/opensolaris/opengrok/configuration/messages/ProjectMessageTest.java
test/org/opensolaris/opengrok/history/HistoryGuruTest.java
test/org/opensolaris/opengrok/index/IndexerTest.java
test/org/opensolaris/opengrok/search/context/HistoryContextTest.java
test/org/opensolaris/opengrok/web/PageConfigTest.java

In the process of addressing #1809 I tried to fix the HistoryGuru API and its usage, namely:
- addRepositories() not adding repositories to the HistoryGuru map (this gist of the fix for #1809) and needlessly calling invalidateRepositories()
- renamed addRepositories(dir) to setRepositories(dir) to better reflect what it is doing and moved it to RuntimeEnvironment since it also modifies the configuration
- removeCache() using invalidateRepositories() needlessly and actually in a wrong way (invalidateRepositories() needs to be called with full set of repositories since it sets the map from scratch)
- setConfiguration() not setting the repository list in configuration after invalidateRepositories() (the latter can remove some repositories)

populate HistoryGuru repositories list from add project Message

---

src/org/opensolaris/opengrok/analysis/perl/PerlXref.lex
testdata/sources/perl/main.pl

Hello,
Please consider for integration the attached patch to improve the Perl // heuristic to allow arbitrary whitespace between tokens instead of just a single LF.
Also:
- remove no-longer-needed splitEol() and the fields: value1, value2

Improve Perl // heuristic to allow arbitrary whitespace between tokens

---

.gitignore
build.xml
platform/solaris/ips/create.sh
tools/sync/README
tools/sync/command.py
tools/sync/commands.py
tools/sync/filelock.py
tools/sync/reindex-project.ksh
tools/sync/sync.py
tools/sync/test/test_command.py
tools/sync/test/test_commands.py

Here's set of simple scripts we've been using lately internally for setup with projects. They make it possible to handle projects in parallel, speeding the overall indexing. The handling can be a sequence of:
- send a Message that project is synced+indexed
- sync the project (e.g. `git pull`)
- index the project
- remove the previous Message
The `filelock.py` comes from https://github.com/benediktschmitt/py-filelock/

project sync tools

---

OpenGrok

Seems that there were a few more single character options that no longer exist in the Indexer.java inside OpenGrok that I did not see the first time I went through the script.  for Issue #1836

Fixes renamed options that were missing in OpenGrok script 

---

web/menu.jspf

fixes #1362
I wanted to preserve the link (`<a>`) but I was not sure if I styled the link in the same way as `<input>` that it would look the same on different browsers.
Thanks :)

"Help" button should have the same style as "Search" and "Clear"

---

src/org/opensolaris/opengrok/configuration/Configuration.java
src/org/opensolaris/opengrok/configuration/Project.java
src/org/opensolaris/opengrok/index/Indexer.java
test/org/opensolaris/opengrok/configuration/ProjectTest.java

User can specify project customizations in read only configuration by opening the `projects` property and filling the map entry according to the project name and desired customizations.
```xml
<void property="projects">
<void method="put">
<string>OpenGrok</string>
<object class="org.opensolaris.opengrok.configuration.Project">
<void property="navigateWindowEnabled">
<boolean>true</boolean>
</void>
</object>
</void>
</void>
```

project customizations in read-only configuration

---

src/org/opensolaris/opengrok/analysis/perl/PerlLexHelper.java
src/org/opensolaris/opengrok/analysis/perl/PerlProductions.lexh
src/org/opensolaris/opengrok/analysis/perl/PerlSymbolTokenizer.lex
src/org/opensolaris/opengrok/analysis/perl/PerlXref.lex
test/org/opensolaris/opengrok/analysis/perl/sample.pl
test/org/opensolaris/opengrok/analysis/perl/samplesymbols.txt
test/org/opensolaris/opengrok/analysis/perl/samplexrefres.html
testdata/sources/perl/main.pl

Hello,
Please consider for integration this patch with an improvements to parsing of stacked HERE-documents as well as some quote-like operator fixes identified after inspecting the OpenGrok cross-referencing of a few large Perl projects (DBI, JSON, and Text-CSV).
Thank you.

Perl improvements 

---

src/org/opensolaris/opengrok/analysis/JFlexXref.java
src/org/opensolaris/opengrok/analysis/ada/AdaLexHelper.java
src/org/opensolaris/opengrok/analysis/ada/AdaProductions.lexh
src/org/opensolaris/opengrok/analysis/ada/AdaSymbolTokenizer.lex
src/org/opensolaris/opengrok/analysis/ada/AdaXref.lex
src/org/opensolaris/opengrok/analysis/perl/PerlLexHelper.java
src/org/opensolaris/opengrok/analysis/perl/PerlProductions.lexh
src/org/opensolaris/opengrok/analysis/perl/PerlSymbolTokenizer.lex
src/org/opensolaris/opengrok/analysis/perl/PerlXref.lex

Hello,
Please consider for integration this patch with a minor cleanup of some redundancy in shared lex logic between Xrefs and SymbolTokenizers by:
* Adding JFlexXref yypush(string) overload to align with JFlexTokenizer's.
* Publicizing JFlexXref startNewLine() so a separate, public method mediator is not needed.
Also:
* Remove unneeded pushback() and switchState() mediators which I mistakenly thought were needed.
Thank you.

Remove a bit of redundancy

---

src/org/opensolaris/opengrok/analysis/c/CSymbolTokenizer.lex
src/org/opensolaris/opengrok/analysis/c/CXref.lex
src/org/opensolaris/opengrok/analysis/c/CxxSymbolTokenizer.lex
src/org/opensolaris/opengrok/analysis/c/CxxXref.lex
test/org/opensolaris/opengrok/analysis/JFlexXrefTest.java
test/org/opensolaris/opengrok/analysis/c/c_xrefres.html
test/org/opensolaris/opengrok/analysis/c/cc_xrefres.html
test/org/opensolaris/opengrok/analysis/c/sample.c
test/org/opensolaris/opengrok/analysis/c/sample.cc

Hello,
Please consider for integration this patch to fix issue #471, "Generating incorrect links for C/C++ '#include'...."
Also:
- Use Common.lexh in C[xx]SymbolTokenizer.lex.
- Make C[xx]Xref case-sensitive, revising the only affected pattern, {File}.
Thank you.

Accept any path for #include statement for issue #471

---

web/default/mandoc.css

Hello,
Please consider for integration this patch to fix the CSS problem identified in issue #1876. This patch also fixes to use only descendant combinators w.r.t. div#mandoc.
Thank you.

Fix to escape '*' under div#mandoc descendant combinator

---

plugins/LdapPlugin/src/opengrok/auth/plugin/LdapUserPlugin.java
plugins/LdapPlugin/test/opengrok/auth/plugin/LdapUserPluginTest.java
plugins/README.md
plugins/UserPlugin/src/opengrok/auth/plugin/decoders/FakeOSSOHeaderDecoder.java
src/org/opensolaris/opengrok/util/StringUtils.java
test/org/opensolaris/opengrok/util/StringUtilsTest.java

- Looks like the regexp used in `LdapUser` plugin is too strict so I relaxed it a bit.
- the fake OSSO header decoder could be initialized better + make the fake nature more prominent by using `fake-` prefix

Plugin fixes for internal deployment

---

src/org/opensolaris/opengrok/analysis/fortran/FortranAnalyzerFactory.java

Hello,
Please consider for integration this patch to revise the FortranAnalyzerFactory suffixes: remove INC and add free-form suffixes subsequent to F90.
Thank you.

Issue #1896 : remove INC as a default Fortran suffix

---

web/list.jsp

Hello,
Please consider for integration this patch to also recognize a ".markdown" suffix for READMEs.
E.g., https://github.com/jekyll/jekyll
Thank you.

Also recognize .markdown README

---

src/org/opensolaris/opengrok/analysis/csharp/CSharpAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/erlang/ErlangAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/haskell/HaskellAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/javascript/JavaScriptAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/json/JsonAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/perl/PerlAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/php/PhpAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/python/PythonAnalyzerFactory.java
src/org/opensolaris/opengrok/analysis/ruby/RubyAnalyzerFactory.java

Hello,
Please consider for integration this patch to add Ruby magics and path-less magic for Escript, Perl, PHP, and Python, which is seen in some unit test files for those languages. Also the patch removes empty MAGICS for e.g. CSharp, Haskell, etc.
Thank you.

Add Ruby magics and path-less magic for Escript, Perl, PHP, Python

---

build.xml
plugins/LdapPlugin/src/opengrok/auth/plugin/AbstractLdapPlugin.java
plugins/LdapPlugin/src/opengrok/auth/plugin/LdapAttrPlugin.java
plugins/LdapPlugin/test/opengrok/auth/plugin/LdapAttrPluginTest.java
plugins/LdapPlugin/test/opengrok/auth/plugin/LdapFilterPluginTest.java
plugins/LdapPlugin/test/opengrok/auth/plugin/util/DummyHttpServletRequestLdap.java
src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java
src/org/opensolaris/opengrok/authorization/AuthorizationStack.java
src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/util/RandomString.java
src/org/opensolaris/opengrok/web/JSONSearchServlet.java
src/org/opensolaris/opengrok/web/Statistics.java
src/org/opensolaris/opengrok/web/WebappListener.java
test/org/opensolaris/opengrok/authorization/AuthorizationEntityTest.java
test/org/opensolaris/opengrok/authorization/AuthorizationFrameworkReloadTest.java
test/org/opensolaris/opengrok/authorization/AuthorizationFrameworkTest.java
test/org/opensolaris/opengrok/authorization/AuthorizationPluginClassLoaderTest.java
test/org/opensolaris/opengrok/authorization/TestPlugin.java
test/org/opensolaris/opengrok/index/IndexerRepoTest.java
test/org/opensolaris/opengrok/web/DummyHttpServletRequest.java
test/org/opensolaris/opengrok/web/PageConfigTest.java
test/org/opensolaris/opengrok/web/ProjectHelperTest.java
test/org/opensolaris/opengrok/web/ProjectHelperTestBase.java

fixes bunch of problems in `AuthorizationFramework`.
Notable changes:
- HTTP session invalidation now happens in `AuthorizationFramework` as opposed to in the plugins
- random string generation moved from plugin tests to `src/opengrok` so that all tests can use it
- some bad object programming practices softened

Plugins session invalidate

---

src/org/opensolaris/opengrok/history/SubversionRepository.java

I don't have a setup to test this on, however it conforms to the `svn cat` usage.

add auth options and --non-interactive to getHistoryGet()

---

test/org/opensolaris/opengrok/history/CVSRepositoryTest.java

Hello,
Please consider for integration this tiny patch to fix `CVSRepositoryTest` to use `CVSRepository getRepoCommand()`, so that the test uses a developer's environment override of `cvs` command.
Thank you.

Fix to use CVSRepository getRepoCommand() in test

---

OpenGrok
src/org/opensolaris/opengrok/analysis/JFlexSymbolMatcher.java
src/org/opensolaris/opengrok/analysis/JFlexTokenizer.java
src/org/opensolaris/opengrok/analysis/JFlexXref.java
src/org/opensolaris/opengrok/analysis/SymbolMatchedPublisher.java
src/org/opensolaris/opengrok/index/Indexer.java

Hello,
Please consider for integration this patch to optimize for a single `SymbolMatchedPublisher` listener. (If we possibly do need multiple listeners in the future, I think a new fan-out mediator would suffice.)
I also added a `--profiler` switch to `Indexer` and `OPENGROK_PROFILER` env var support to the `OpenGrok` script — which is a convenience to pause the process in order to allow attaching a profiler or debugger. I used this to profile this optimization in NetBeans.
Thank you.

Optimize for a single listener. Support --profiler.

---

src/org/opensolaris/opengrok/analysis/powershell/PowershellSymbolTokenizer.lex
test/org/opensolaris/opengrok/analysis/powershell/sample.psm1
test/org/opensolaris/opengrok/analysis/powershell/sample_xref.html
test/org/opensolaris/opengrok/analysis/powershell/samplesymbols.txt

Hello,
Please consider for integration this fix for PowerShell label handling broken in `feature/symbol_matcher`. I added a `break <label>` statement to sample.psm1.
Thank you.

Fix PowerShell break|continue <label> handling

---

src/org/opensolaris/opengrok/index/PendingFileCompleter.java

Hello,
Please consider integration of this bugfix patch.
Thank you.

Fix to try-with-resources spotted by @tulinkry

---

src/org/opensolaris/opengrok/history/FileHistoryCache.java
src/org/opensolaris/opengrok/history/HistoryGuru.java

Hello,
Please consider for integration this patch to use try-with-resources for a `FileInputStream` in `FileHistoryCache`, to revise so `Buffered...` objects are directly above `File`, and to fix a wrong arg.
For the "wrong arg", the fix has no true effect because the argument is ignored anyway by `FileHistoryCache.getHistory(File, boolean, boolean)`, but it was counterintuitive without the fix.
Thank you.

Close stream. Buffer directly from File. Fix arg.

---

src/org/opensolaris/opengrok/configuration/ConfigurationHelp.java

Hello,
Please consider for integration this fix so that `ConfigurationHelp` also checks for "is" methods.
Thank you.

Fix to also check for boolean-"is" methods for Help

---

src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java
src/org/opensolaris/opengrok/analysis/Ctags.java
src/org/opensolaris/opengrok/analysis/TextAnalyzer.java
src/org/opensolaris/opengrok/analysis/document/MandocRunner.java
src/org/opensolaris/opengrok/analysis/sql/Consts.java
src/org/opensolaris/opengrok/analysis/sql/PLSQLConsts.java
src/org/opensolaris/opengrok/search/Results.java
src/org/opensolaris/opengrok/search/Search.java
src/org/opensolaris/opengrok/search/SearchEngine.java
src/org/opensolaris/opengrok/util/IOUtils.java
src/org/opensolaris/opengrok/web/PageConfig.java
src/org/opensolaris/opengrok/web/Util.java
web/list.jsp
web/more.jsp

Hello,
Please consider for integration this patch to consistently use UTF-8 as a fallback for readers against `SRCROOT`. This is a fix that helps to prepare for later integration of the Lucene `UnifiedHighlighter` (a2a76a2).
I encountered problems with inconsistent charsets when testing OpenGrok on JVMs on macOS and on OmniOS. On macOS, the JDK uses UTF-8 by default as the system charset; while on OmniOS, I determined it was Latin-1.
I think UTF-8 is a more sensible default for OpenGrok because it eliminates some unexpected inconsistency and aligns with the default encoding of Universal ctags. I am using `StandardCharsets.UTF_8` instead of a literal `"UTF-8"` as a way of tagging code that I reviewed. If it was decided later to support specifying an explicit, alternate default charset (for …

Fix to consistently default to UTF-8 for SRCROOT readers

---

src/org/opensolaris/opengrok/analysis/executables/JarAnalyzer.java
src/org/opensolaris/opengrok/analysis/executables/JavaClassAnalyzer.java
src/org/opensolaris/opengrok/index/DefaultIndexChangedListener.java
test/org/opensolaris/opengrok/analysis/executables/JarAnalyzerTest.java
test/org/opensolaris/opengrok/util/TestRepository.java

Hello,
Please consider for integration this patch to fix `JarAnalyzer` and `JavaClassAnalyzer` not to add out-of-order tokens. This is a prerequisite for the upcoming Lucene `UnifiedHighlighter`; and, as Lubos found, for Lucene 7 in PR #1871.
Thank you.

Fix not to add out-of-order tokens for Jar, JavaClass

---

src/org/opensolaris/opengrok/analysis/document/MandocRunner.java

Hello,
Please consider for integration this patch to silence an unhelpful mandoc error regarding its normally-closed error stream.
Thank you.

Fix to ignore IOException from mandoc errstream

---

web/history.jsp

Hello,
Please consider for integration this patch to use in `history.jsp` too the revised version of `createSlider()` which was changed in c29e0463794e (Lucene 7).
I'm not sure if it's a Tomcat weirdness, but after deployment I was seeing `NoSuchMethodError` related to `createSlider()` whose `size` parameter was changed from `int` to `long`.
This now matches the change already made to `search.jsp`.
Thank you.

Fix to call createSlider() with revised signature

---

src/org/opensolaris/opengrok/util/Executor.java

this might fix #2019 and #2013

add buffering to process stream

---

src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java
test/org/opensolaris/opengrok/analysis/AnalyzerGuruTest.java

catch exceptions in static initializer of AnalyzerGuru

---

.travis.yml
opengrok-indexer/pom.xml

On Travis this currently passes because the Ubuntu there has much older pep8 version. On my Ubuntu laptop this fails on `tools/sync/test/test_commands.py`. I will leave it there as a canary.
This also disables the `install` phase that triggered `./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V` in Travis which is most probably not needed as everything is done in the `script:` section (the `mvnw` is good candidate for removal anyway).

add pep8 checks

---

src/org/opensolaris/opengrok/index/IndexDatabase.java

Hello,
Please consider for integration this patch with a minor, FINER logging of some files that aren't `accept()`ed.
Thank you.

Log some additional places where !accept()ed

---

web/enoent.jsp
web/error.jsp
web/help.jsp
web/history.jsp
web/index.jsp
web/mast.jsp
web/search.jsp
web/status.jsp

Hello,
Please consider for integration this patch to use an en-dash in the results item range instead of a hyphen.
With this tiny revision, it became apparent that many jsps did not have their encoding set to UTF-8. It's required or else — in the presence of a non-Latin code point — a conversion of content to ISO-8859-1 is warned and then executed. That happens even if a jsp has an `include` of a file specifying UTF-8 (e.g., `web/httpheader.jspf`).
Thank you.

Use en dash for Results count. Fix to specify UTF-8 for jsps.

---

src/org/opensolaris/opengrok/search/context/PlainLineTokenizer.lex
test/org/opensolaris/opengrok/search/context/ContextTest.java

fixes #2033 
Testing done: manual verification
Other lines were working correctly because they were repaired by this line: `markedLine = yyline+1;`
I hope I did not break anything else.
Thanks for review :)

Fix search matching first line has a line number 0

---

OpenGrok

I'm seeing a warning when using the OpenGrok script to start an index run using opengrok 1.1-rc21:
Loading the default instance configuration ...
Creating default /tmp/opengrok/logging.properties ...
WARNING: Can't find distribution logging configuration (/nail/home/sjaensch/pg/services/opengrok/opengrok-1.1-rc21/bin/../lib/../doc/) to install as default logging configuration (/tmp/opengrok/logging.properties)
LOGGER_CONF_SOURCE is supposed to point to the logging.properties file. This simple PR fixes the issue.
I do accept the terms of the OCA.

Properly set LOGGER_CONF_SOURCE for binary distributions

---

.travis.yml
opengrok-indexer/pom.xml

I think it might be counterintuitive if `mvn clean test` command fails on a completely correct repository just because some SCM tools are not installed. User can skip uninstalled SCM tools by adding `-Djunit-force-all=false` but this option is mentioned at the very bottom of the `README.md` file which makes it very easy to miss. (I for one installed BitKeeper and CVS to make the tests working and did not know about this option until I started to investigate it further...)
Therefore, I think it might be wise to skip some of those tests by default and check them all via Travis.
Thanks for considering this PR :)

Enable conditional test runs by default

---

src/org/opensolaris/opengrok/history/HistoryEntry.java
src/org/opensolaris/opengrok/history/RazorHistoryParser.java
test/org/opensolaris/opengrok/history/HistoryEntryTest.java

Removed `changeRequests` field from `HistoryEntry`. This field was not used at all. Some data were inserted from `Razor` SCM but they were not consumed.
Thanks for considering this PR :)

Remove redundant changeRequests field from HistoryEntry

---

src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java
src/org/opensolaris/opengrok/index/IndexAnalysisSettings.java
src/org/opensolaris/opengrok/index/IndexAnalysisSettingsAccessor.java
src/org/opensolaris/opengrok/index/IndexDatabase.java
src/org/opensolaris/opengrok/search/QueryBuilder.java
src/org/opensolaris/opengrok/search/Results.java
test/org/opensolaris/opengrok/index/IndexAnalysisSettingsTest.java
test/org/opensolaris/opengrok/index/IndexDatabaseTest.java

Hello,
Please consider for integration this patch to store project tabsize (if defined) at the time a document is indexed.
The source text presented to `UnifiedHighlighter` must accord with the text as it was when the indexing occured. A non-zero tab size results in transformed source text via `ExpandTabsReader`, so any change in tab size must be recognized.
In addition to `UnifiedHighlighter` checking tab size, this patch also updates `IndexDatabase` so that it detects a changed tab size in order to reindex files automatically. (This fields-check is augmented in later patches [e16d4b92e351] with additional versioning metadata for analyzers and for `AnalyzerGuru` itself so that re-indexing can occur automatically *as necessary* when OpenGrok is updated.)
Thank you.

Store TABSIZE in a supplementary document for each IndexDatabase

---

src/org/opensolaris/opengrok/analysis/Ctags.java
src/org/opensolaris/opengrok/analysis/CtagsReader.java
src/org/opensolaris/opengrok/analysis/Definitions.java
src/org/opensolaris/opengrok/analysis/ExpandTabsReader.java
src/org/opensolaris/opengrok/analysis/PendingToken.java
src/org/opensolaris/opengrok/analysis/PendingTokenOffsetsComparator.java
src/org/opensolaris/opengrok/analysis/StreamSource.java
src/org/opensolaris/opengrok/analysis/plain/DefinitionsTokenStream.java
src/org/opensolaris/opengrok/analysis/plain/PlainAnalyzer.java
src/org/opensolaris/opengrok/index/IndexDatabase.java
src/org/opensolaris/opengrok/util/IOUtils.java
src/org/opensolaris/opengrok/util/LineBreaker.java
src/org/opensolaris/opengrok/util/ReaderWrapper.java
src/org/opensolaris/opengrok/util/SourceSplitter.java
src/org/opensolaris/opengrok/util/StringUtils.java
test/org/opensolaris/opengrok/analysis/CtagsTest.java
test/org/opensolaris/opengrok/analysis/DefinitionsTest.java
test/org/opensolaris/opengrok/analysis/ExpandTabsReaderTest.java
test/org/opensolaris/opengrok/analysis/JFlexXrefTest.java
test/org/opensolaris/opengrok/analysis/haskell/HaskellXrefTest.java
test/org/opensolaris/opengrok/analysis/plain/DefinitionsTokenStreamTest.java
test/org/opensolaris/opengrok/search/context/ContextTest.java
test/org/opensolaris/opengrok/util/LineBreakerTest.java
test/org/opensolaris/opengrok/util/SourceSplitterTest.java
test/org/opensolaris/opengrok/util/StreamUtils.java

Hello,
Please consider for integration this patch to enhance `CtagsReader` to store true posting for `DEFS` for use by the `UnifiedHighlighter` — i.e. so that a document is not required to be re-analyzed to present `DEFS` search matches.
Because of limitations in ctags results (e.g. partial patterns or truncated patterns) and limitations in the ctags format itself (e.g., having line numbering but no character offsets as required for Lucene postings), `CtagsReader` is enhanced to supplement the tags *when necessary* with additional analysis of the source text.
E.g., in `sample.cc`/`sampletags_cc`, the function definition (excluding body) for `definitionContains()` spans seven lines in source code:
```
int
Ancestor::definitionContains(const fru_regdef_t *def,
const fru_regdef_t *parent_def, …
```

DEFS stores true offsets from enhanced CtagsReader

---

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/history/BazaarHistoryParser.java
src/org/opensolaris/opengrok/history/GitHistoryParser.java
src/org/opensolaris/opengrok/history/MercurialHistoryParser.java
src/org/opensolaris/opengrok/history/MonotoneHistoryParser.java
src/org/opensolaris/opengrok/util/PathUtils.java

With this change it is possible to index internal Solaris source code repository (that contains UTF-8 file names) on a system with `LC_ALL="C"` and `LANG=""`.

document and handle InvalidPathException in history parsers

---

test/org/opensolaris/opengrok/configuration/messages/NormalMessageTest.java

In order to have some room for error, I tried to use the `TestWatcher` to supply a `@Rule` (per http://www.thinkcode.se/blog/2012/07/08/performing-an-action-when-a-test-fails) that would dump all messages in the system to standard output however the `finished()` overloaded method is run only after `tearDown` (@After) which makes this useless.

set expiration date

---

.travis.yml
opengrok-indexer/pom.xml

Enables Travis builds on OS X as well as Linux.
I had to move the javadoc check out of OS X because Maven was failing to find the jrcs dependency for some reason - it was searching for it on Maven central as opposed to locally (most likely because of the way `javadoc` target is invoked - quite possibly this could be done better; I never liked the descending into module directories and invoking the target there).
Also, I got rid of the `junit-force-all` option. There is a bit of risk of losing the coverage however on OS X I don't see how we can make all the tests to be run (especially for those exotic SCMs).

add OS X Travis build

---

OpenGrok

On systems where /bin/sh is dash (like Debian), invoking OpenGrok help
will print the following error message along with its output:
./OpenGrok: 930: [: unexpected operator
Also, the --detailed option won't print all the detailed help.
This patch replaces a bashism (the == operator) with standard shell
syntax (the = operator).

OpenGrok help uses bashism

---

.travis.yml
README.md
doc/release.txt
opengrok-indexer/pom.xml
plugins/pom.xml
pom.xml

Enables Jacoco proper, publishes results to [Coveralls.io](https://coveralls.io/repos) (I enabled the oracle/opengrok repo there).
Used resources:
- https://angus.nyc/2015/continuous-integration-for-java-github
- https://stackoverflow.com/questions/12269558/maven-jacoco-plugin-error
- https://github.com/onelogin/java-saml/issues/74

run Jacoco and publish the results to Coveralls.io

---

src/org/opensolaris/opengrok/history/HistoryGuru.java
src/org/opensolaris/opengrok/history/RepositoryInfo.java

Hello,
Please consider for integration this patch to fix result handling from `getRelativeToCanonical()`. Existing tests cover this change for Linux and Mac. This may or may not be the solution to issue #2069 on Windows, as I could not test on that environment.
Thank you.

Properly handle result of getRelativeToCanonical()

---

.travis.yml
scripts/before
scripts/before_install
scripts/main

Should still work for pull requests.

Do not run Jacoco/Coveralls for forks

---

OpenGrok

passthru for the -p option. I don't like that the shell script is a filter to `Indexer` however until it is rewritten such changes need to happen.

add the OPENGROK_DEFAULT_PROJECTS env var

---

src/org/opensolaris/opengrok/search/Results.java
src/org/opensolaris/opengrok/util/BlockingObjectPool.java
src/org/opensolaris/opengrok/web/DirectoryListing.java
src/org/opensolaris/opengrok/web/Util.java
web/default/style.css
web/status.jsp

`<tt>` tag is not HTML5 compliant (<https://www.w3schools.com/tags/tag_tt.asp>).
Thanks for review :)

Replace deprecated <tt> tag

---

src/org/opensolaris/opengrok/search/Results.java
web/default/style.css

fixes #2082
I was not able to resolve this by css :(
Thanks for review :) 
For comparison: (almost the same part as described in issue)

Search result background color for odd rows fix

---

tools/sync/command.py
tools/sync/cvs.py
tools/sync/git.py
tools/sync/hook.py
tools/sync/mercurial.py
tools/sync/mirror.py
tools/sync/repofactory.py
tools/sync/repository.py
tools/sync/svn.py
tools/sync/teamware.py
tools/sync/test/test_command.py
tools/sync/utils.py

Some of the internal repositories recently started exhibiting strange traffic patterns (either connect was lagging or the data was painfully slow to receive from the other side. For Mercurial for instance this means that commands like `hg incoming` were hanging for hours) which made me realize there is no timeout mechanism in the mirroring scripts.
Also, this fixes bunch of places where logger is not properly passed onto the created objects so some logging was missing.

Mirror timeout

---

src/org/opensolaris/opengrok/index/IndexDatabase.java
src/org/opensolaris/opengrok/index/PendingFileCompleter.java
src/org/opensolaris/opengrok/index/PendingSymlinkage.java

Hello,
Please consider for integration this patch to account for loops in symlinked directories.
I tested with the [openshift-ansible](https://github.com/openshift/openshift-ansible) repository and also with the problematic sample layout provided by @ChristopheBordieu.
Thank you.

Fix #1477, fix #2080 : Handle symlink loop. Xref symlink dir.

---

src/org/opensolaris/opengrok/analysis/CtagsReader.java

Hello,
Please consider for integration this patch to fix issue #2118.
Background: Universal ctags extracts tags from pathologically-long lines but only shows the pattern from the initial part of the line.
OpenGrok will now only try to find heuristically the position of tags beyond the initial pattern
up to a limit of 2,000 characters.
Also, a tiny cache is used to speed sequential tags from the same line.

Fix #2118 : limit CtagsReader lookahead for pathologically-long lines

---

OpenGrok
build.xml
src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java
src/org/opensolaris/opengrok/configuration/Configuration.java
src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/index/Indexer.java
src/org/opensolaris/opengrok/web/Util.java
src/org/opensolaris/opengrok/web/XrefSourceTransformer.lex
test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java
web/enoent.jsp
web/list.jsp
web/mast.jsp
web/projects.jspf
web/rss.jsp

Hello,
Please consider for integration this patch to allow serving OpenGrok content through arbitrary web app deployments and to therefore expunge the `-w` option.
Thank you.

Fix #431 : option -w should die

---

OpenGrok

Partly fixes <https://github.com/oracle/opengrok/issues/2113>
This was needed for demo site. Therefore, I created just a quick fix for Tomcat. I could not find how it should be done for GlassFish or Resin. If you know then please let me know :) 
I tried to conform to this text in Tomcat documentation:
`
If the context path is the empty string then the base name will be ROOT (always in upper case) otherwise the base name will be the context path with the leading '/' removed and any remaining '/' characters replaced with '#'
`
If `OPENGROK_WEBAPP_CONTEXT` variable is not set then `source` is used by default. Otherwise I try to follow the Tomcat instructions specified above.
I program in shell very occasionally so there will be probably some mistakes. So please look at it carefully :)
Also, …

Add support for Tomcat webapp context in deploy command

---

tools/sync/command.py

Lately, the mirroring on our production instance started failing with strange conditions such as `Messages` not being able to retrieve source root or because a branch of a Mercurial repository could not be determined. These commands exited with 0 however the output was empty. It might be because the server is more loaded than usual due to full reindex running in background so thread scheduling is not going in its usual lines.
I think this is caused by an outstanding TODO item (another reason to get rid of these comments and file bugs for each one of them) in `command.py` - if a process exits too quickly, the main thread will not wait for the output thread to read the full output. As a result these single line cases mentioned above will complete with empty output.

wait for output thread to finish reading

---

README.md
opengrok-indexer/pom.xml
plugins/pom.xml
plugins/test/opengrok/auth/plugin/util/DummyHttpServletRequestLdap.java
plugins/test/opengrok/auth/plugin/util/DummyHttpServletRequestUser.java
pom.xml
test/org/opensolaris/opengrok/web/DummyHttpServletRequest.java
web/WEB-INF/web.xml

Basic functionality seems to work on Tomcat 9. I tried search and navigating through project files.
Added methods were generated automatically by Idea. 
I also used fully qualified class name for `javax.servlet.http.HttpSessionContext` so I could remove `import` which caused deprecation warning.
fixes https://github.com/oracle/opengrok/issues/2089
Thanks :)

Update Servlet API to 3.1

---

web/menu.jspf

I noticed that labels have bad `for` attribute with non-existent ids. 
As per W3C:
> The for attribute of the <label> tag should be equal to the id attribute of the related element to bind them together.
Only difference: clicking on label now focuses the related field.
Thanks :)

Fix labels for search inputs

---

OpenGrok
README.md
src/org/opensolaris/opengrok/configuration/Configuration.java
src/org/opensolaris/opengrok/configuration/Project.java
src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/history/FileHistoryCache.java
src/org/opensolaris/opengrok/history/HistoryGuru.java
src/org/opensolaris/opengrok/history/RepositoryFactory.java
src/org/opensolaris/opengrok/history/RepositoryInfo.java
src/org/opensolaris/opengrok/index/IgnoredFiles.java
src/org/opensolaris/opengrok/index/IndexDatabase.java
src/org/opensolaris/opengrok/index/Indexer.java
test/org/opensolaris/opengrok/configuration/messages/ProjectMessageTest.java
test/org/opensolaris/opengrok/index/IndexerRepoTest.java

This basically removes the notion that `Repository` presence constitutes history creation. With these changes it is possible to have history disabled globally and enabled on project level and vice versa.
Also, I believe this is one of the last pieces where configuration is stored outside of `Configuration` object.

allow to enable/disable history per project

---

web/default/style.css

fixes https://github.com/oracle/opengrok/issues/2133
Tested on Safari and Google Chrome. I'm not sure what exactly is broken but this should be equivalent to the desired functionality...
Thanks :)

Cut off diffbar fix

---

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/configuration/messages/ConfigMessage.java

When uploading new configuration via Message this could make the webapp refresh configuration slowly in the presence of stale repositories. This change makes the set configuration process use interactive flag to shorten the timeout with the only exception - reindex.

make the config set/setconf message use the interactive flag

---

src/org/opensolaris/opengrok/configuration/Configuration.java
src/org/opensolaris/opengrok/web/WebappListener.java

2 lines added to log during webapp startup, e.g.:
```
05-Jun-2018 10:19:48.811 INFO [localhost-startStop-1] org.opensolaris.opengrok.web.WebappListener.contextInitialized Starting webapp with version 1.1-rc22 (f8c14b49af83451078552967dac5d22d949f2a09)
05-Jun-2018 10:19:48.811 INFO [localhost-startStop-1] org.opensolaris.opengrok.configuration.Configuration.read Reading configuration from /opengrok/etc/configuration.xml
```

report more information during webapp startup

---

test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java
test/org/opensolaris/opengrok/index/IgnoredNamesTest.java
test/org/opensolaris/opengrok/index/IndexVersionTest.java
test/org/opensolaris/opengrok/index/IndexerRepoTest.java
test/org/opensolaris/opengrok/search/context/SearchAndContextFormatterTest2.java
test/org/opensolaris/opengrok/util/FileUtilities.java
test/org/opensolaris/opengrok/util/PathUtilsTest.java
test/org/opensolaris/opengrok/util/TestRepository.java
test/org/opensolaris/opengrok/web/DirectoryListingTest.java

This method is redundant since Java 7 and it was causing some trouble in determining the line between web and indexer modules.
While I was touching the files I also removed some warnings per IDEA suggestions.
Thanks :)

Remove redundant createTemporaryDirectory method from FileUtilities

---

test/org/opensolaris/opengrok/index/IndexerRepoTest.java

When running per project history tests a directory `dataForPerProjectHistoryTest{number}` is created under `opengrok-indexer`. This can be achieved simply by running `mvn test`.
It can look like this:
However, these directories are not removed when running `mvn clean`.
This PR fixes the problem.
Thanks :)

Per project history test data fix

---

OpenGrok
src/org/opensolaris/opengrok/index/IndexVersion.java
src/org/opensolaris/opengrok/index/Indexer.java
test/org/opensolaris/opengrok/index/IndexVersionTest.java

Today I tried to create some partal indexes (with `indexpart` sub-command of the `OpenGrok` script) by hand and got an error that different project than what was being indexed had old index version. This change should fix that.

Index version check partial

---

src/org/opensolaris/opengrok/configuration/Configuration.java
src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/web/AuthorizationFilter.java
test/org/opensolaris/opengrok/configuration/IncludeFilesTest.java
test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java
web/foot.jspf
web/index.jsp
web/pageheader.jspf

This change makes the location of include files used in web application configurable. By default they are searched for in data root, if include root is specified they are searched for there.
This change also refreshes the contents of these files when new configuration is set in the web application.

configurable directory for web app include files

---

web/list.jsp

This change refactors the annotate JSP code once again, the top-level decision making is now checking only:
- directory
- revision
- otherwise (redirect)

refactor annotate code once again

---

src/org/opensolaris/opengrok/web/api/v1/filter/LocalhostFilter.java

I totally forgot to exclude `search` from `LocalhostFilter`. Therefore, this fix.
Thanks :)

Search endpoint filtered by localhost filter fix

---

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
src/org/opensolaris/opengrok/index/IndexDatabase.java
src/org/opensolaris/opengrok/index/IndexerUtil.java
tools/sync/opengrok.py
tools/sync/reindex-project.ksh

Fixes #2194
There were a few problems:
* if the webapp URI (`-U`) was passed with trailing `/` (e.g. `http://localhost:8080/`) to `Indexer` then it was not able to contact the webapp
* if the webapp URI (`-U`) was passed with trailing `/` to Python scripts then they were not able to contact the webapp
* if the `OPENGROK_WEBAPP_CONTEXT ` env param was empty or contained leading/trailing slashes then `reindex-project.ksh` was not able to download the configuration
The problem was that resulting URIs were containing multiple slashes (e.g. `http://localhost:8080//api/v1/configuration`) which were causing the calls to fail.
This patch should fix the above errors.
Thanks :)

Webapp URI param should be more robust

---

src/org/opensolaris/opengrok/analysis/executables/JFieldBuilder.java
src/org/opensolaris/opengrok/analysis/executables/JarAnalyzer.java
src/org/opensolaris/opengrok/analysis/executables/JavaClassAnalyzer.java

Hello,
Please consider for integration this patch to speed up `JarAnalyzer` by reusing the same string builders for an entire jar.
Thank you.

Issue #2156 : speed up JarAnalyzer

---

opengrok-indexer/pom.xml
src/org/opensolaris/opengrok/history/SCCSRepositoryAuthorParser.java

Jersey does not work with JDK9 right away because of the java modularization. 
As mentioned here: https://www.jeffryhouser.com/index.cfm/2017/12/21/Why-wont-Jersey-work-on-JDK-9
I added these 2 libraries and everything seems to work fine (no exceptions thrown during Tomcat startup).
I also removed one unused import which were preventing compilation with JDK 10.
Thanks :)

Jersey JDK 9 support

---

opengrok-web/pom.xml
src/org/opensolaris/opengrok/search/SearchEngine.java
src/org/opensolaris/opengrok/web/AuthorizationFilter.java
src/org/opensolaris/opengrok/web/api/v1/RestApp.java

This explicitly allows RESTful API calls to go through `AuthorizationFilter`. It seems this is not strictly necessary (as mentioned in #2203 for the `/search` endpoint) however it is better not to rely on the fact that `config.getProject()` returns `null` in `AuthorizationFilter.doFilter()`.

Allow RESTful API in AuthorizationFilter

---

tools/sync/command.py
tools/sync/projadm.py
tools/sync/test/test_command.py

Basically adds a parameter to `Command` constructor to specify whether `stderr` should be redirected to `stdout` as it used to be until now. If not, a new thread consuming `stderr` will be created. New method `geterroutput()` can be used to gather this output.

add parameter to Command constructor to disable stderr redirection

---

src/org/opensolaris/opengrok/web/api/constraints/PositiveDuration.java
src/org/opensolaris/opengrok/web/api/constraints/PositiveDurationValidator.java
src/org/opensolaris/opengrok/web/api/error/ExceptionMapperUtils.java
src/org/opensolaris/opengrok/web/api/error/GenericExceptionMapper.java
src/org/opensolaris/opengrok/web/api/error/ValidationExceptionMapper.java
src/org/opensolaris/opengrok/web/api/error/WebApplicationExceptionMapper.java
src/org/opensolaris/opengrok/web/messages/Message.java
test/org/opensolaris/opengrok/web/api/constraint/PositiveDurationValidatorTest.java

Now when an exception is thrown from REST API endpoint then `error.jsp` page is returned. This change returns only the exception `message` text since it is more readable and better for use with REST API.
Thanks :)

Add generic exception mapper for REST API

---

test/org/opensolaris/opengrok/analysis/TextAnalyzerTest.java

remove tests for default encoding in TextAnalyzer

---

src/org/opensolaris/opengrok/util/ClassUtil.java
test/org/opensolaris/opengrok/util/ClassUtilTest.java

Hello,
this is useful for setting POJO objects in configuration. Also useful for suggester (and its config): https://github.com/oracle/opengrok/pull/2212
Example usage:
```bash
curl -d '{"enabled":"false"}' -X PUT http://localhost:8080/api/v1/configuration/suggesterConfig
```
I wanted to write some tests but I was not able to find any POJO class in configuration (`IgnoredNames` does not work and collections (e.g. `Set<Project>`) cannot be converted from JSON because of the type erasure)
I think it makes sense to extend this in the future to allow nested paths (e.g. `/suggesterConfig/enabled`)
Thanks :)

Allow configuration objects to be set via REST API

---

src/org/opensolaris/opengrok/web/api/v1/suggester/provider/service/impl/SuggesterServiceImpl.java
suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java

Hello,
improves log messages in #2219.
I also added one more check if the project is indexed to `SuggesterServiceImpl`.
Thanks :)

Improve logs when suggester data could not be created

---

test/org/opensolaris/opengrok/history/BazaarHistoryParserTest.java

prevents the test from hitting `null` pointer exception if relative directory name is accessed (needed for #2235)

set directory name before BazaarHistoryParser is created

---

tools/projadm.py

`set_configuration()` should be called with actual data, not file path. Also, due to exceptions are handled in generic way in `put()`, encoding/decoding problem while preparing the data for sending was not apparent until I ran `projadm` in debug mode.

read and send configuration as UTF-8

---

.travis.yml

Originally I wanted to go to Xcode 9.4 (https://blog.travis-ci.com/2018-07-19-xcode9-4-default-announce) however it has too new Java which makes Suggester tests to fail so will do this incremental step first.

bump OS X image to Xcode 8.3

---

opengrok-indexer/build.xml

Fixes regression bug after changing package names.
fixes #2253 
Special thanks to @gtoph
Thanks :)

Fix version reporting

---

tools/src/main/python/readconfig.py

The tools scripts are written so they only work on Python 3. However, in Python 3.4 the `ValueError` is thrown instead of `json.decoder.JSONDecodeError` so this needs special handling.

handle JSON decode error for older json module versions

---

suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java

Hello,
fixes problem of stale directories that were created by a suggester. It seems to work fine -> temporary directories are deleted upon stopping the web application. 
Thanks :)

Fix stale temporary directories created by suggester

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java

There is a duplicate piece of code in `MercurialRepository#findOriginalName()` that breaks the cycle.

remove redundant code

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/SSCMRepository.java

Looks like that the conversion to `Executor` left some `Process` pieces behind.

cleanup unused Process

---

suggester/src/test/java/org/opengrok/suggest/SuggesterTest.java
suggester/src/test/java/org/opengrok/suggest/popular/impl/ChronicleMapAdapterTest.java

Re issue #2302 , here are some fixes for suggester tests that I did while trying to get the tests to run under Windows, caused by Windows being more picky about deleting open files and directories. 
Errors fixed are:
ChronicleMapAdapterTest:
java.nio.file.FileSystemException: C:\Users\me\AppData\Local\Temp\opengrok7369985377004991146test: The process cannot access the file because it is being used by another process.
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
at …

Fix SuggesterTest and ChronicleMapAdapterTest failing under Windows

---

opengrok-indexer/build.xml

When passing `file://` protocol url to svn.exe on Windows, it fails. Let's use `file:///` prefix, with which both Linux and Windows work fine.
Proof: [AppVeyor (Windows)](https://ci.appveyor.com/project/0xfeeddeadbeef/opengrok#L1774) and [Travis CI (Linux)](https://travis-ci.org/0xfeeddeadbeef/opengrok/builds/416571245#L3209) (These builds are for different branch containing [same fix](https://github.com/0xfeeddeadbeef/opengrok/commit/5c5d88bf741614d55238ac477f300268fc1970b8) as this pull request).
Related to #2302.
I agree to OCA terms and conditions: http://www.oracle.com/technetwork/community/oca-486395.html

Allow post-compile-test for SVN to run on Windows

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java

The logic for ctags checking is wrong. It causes tests to fail if there is no valid ctags binary.

fix the logic and report ctags version

---

opengrok-indexer/src/test/java/org/opengrok/indexer/authorization/AuthorizationPluginClassLoaderTest.java

make the AuthorizationPluginClassLoaderTest more robust

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java

Primarily this should fix the recently reported brokeness on Windows where backward slashes ended up in the index.
While at it, I also replaced the leading project path slash with native path separator.

Use more native path separators on Windows

---

opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
tools/src/main/python/projadm.py

Just found out that deletion of a project that does not have xrefs generated and/or is lacking a repository fails. This change remedies that.

Project delete fixes

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SystemController.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SystemControllerTest.java

Tested with:
- create `footer_include` file
- deploy webapp
- check the footer is displayed
- change include file content
- reload:
```shell
curl -v -X PUT http://localhost:8080/source/api/v1/system/includes/reload
```
- check the changed footer is displayed

add API endpoint for include files reload

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/EftarFile.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/EftarFileReader.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/EftarFileTest.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SystemController.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SystemControllerTest.java

Hides path description compilation into binary file behind RESTful API endpoint.
Tested with:
- create `/opengrok/etc/paths.tsv` with some sample path descriptions
- call the API to refresh the descriptions:
```
curl -i -X POST -H "Content-Type: text/plain" \
--data-binary "@/opengrok/etc/paths.tsv" \
http://localhost:8080/source/api/v1/system/pathdesc
```
- view projects with said path descriptions in the UI, make sure they have updated descriptions

add API endpoint to refresh path descriptions

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java

I have accidentally run full indexer with per-project settings in read-only configuration with trailing argument, something like:
```shell
indexer.py ... \
-P -S \
-R /opengrok-upgrade/etc/readonly_configuration.xml \
-s /ws-local-upgrade \
-d /opengrok-upgrade/data \
-W /opengrok-upgrade/etc/configuration.xml \
/opengrok-upgrade/log/reindex.log 2>&1
```
(notice the missing redirect to the ` /opengrok-upgrade/log/reindex.log` log file - it will be treated as `subFile` in `Indexer`, i.e. per-project reindex)
which caused this:
```
java.lang.NullPointerException
at java.lang.String.startsWith(String.java:1405)
at java.lang.String.startsWith(String.java:1434)
at org.opengrok.indexer.configuration.Project.getProject(Project.java:349)
at …
```

make getProject() more robust

---

tools/src/main/python/command.py
tools/src/main/python/indexer.py
tools/src/main/python/java.py
tools/src/main/python/reindex-project.py

Compared to the old `OpenGrok` shell script, the Python scripts do not support passing environment variables to the indexer which hampers things like running the indexer with correct locale. This change should fix that.
Tested with:
```shell
./indexer.py -C -e BAR=YYYYYYYYYYYYYYYYYYYYYYY -e FOO=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \
-D -a ~/opengrok-git-vladak/distribution/target/dist/opengrok-1.1-rc38.jar -- -s
```
and checking the debug output. And also running `indexer.py` with -e and checking its environment variables (with `pargs -e`).

support passing environment variables to indexer

---

opengrok-indexer/build.xml
opengrok-indexer/pom.xml

This gets rid of the `-update-build-info` Ant target by using Git and Properties Maven plugins. I tried to set a system property using the Properties plugin which did not work (it is not clear what properties are written to the file plus the ordering of the plugins can be funny) so in the end I resorted to the replacer plugin that is already used to process Jflex files (having multiple versions of the plugin seems to work fine).
Once piece that is missing compared to previous state is the parsing of the `.git_archival.txt` file. I believe this is no longer needed.

generate info.properties file from Maven

---

tools/src/main/python/config-merge.py
tools/src/main/python/java.py
tools/src/main/python/projadm.py

I forgot to update `projadm.py` to use the `config-merge.py`. Here are the changes that make it possible, e.g.:
```shell
/opengrok/dist/bin/projadm.py -b /opengrok -R /opengrok/etc/readonly_configuration.xml \
-u -r --jar /opengrok/dist/lib/opengrok.jar
```
This will:
- retrieve current config from webapp
- run `config-merge.py` on `/opengrok/etc/readonly_configuration.xml` and the current config and stores the result in `/opengrok/etc/configuration.xml`
- uploads `/opengrok/etc/configuration.xml` to the webapp

Config merge switch over

---

opengrok-indexer/pom.xml

Gets rid of:
```
$ mvn -DskipTests install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.opengrok:opengrok:jar:1.1-rc40
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin com.google.code.maven-replacer-plugin:replacer @ line 318, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

get rid of multiple replacer plugin instances

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
opengrok-web/src/main/webapp/list.jsp

When traversing `PageConfig#getLatestRevision()` I noticed that `getHistory()` is called with UI flag set to false. This is not correct since `PageConfig` is used from UI.

call getHistory() from PageConfig with ui = True

---

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java

There are still some references to Exuberant ctags in `Indexer`. This change takes care of that.

remove references to Exuberant ctags

---

tools/src/main/python/indexer.py

When `indexer.py` is run without -C, it will try to verify there is Universal ctags binary in `PATH` by checking various program names. For those which failed `get_command()` that is called to perform this verification will emit log message with the `ERROR` level which is confusing. This change makes it to use `DEBUG` log level.

prevent get_command() from emitting errors when searching for ctags

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/PageConfigTest.java
opengrok-web/src/main/webapp/list.jsp

This is a bit of a hack to make `list.jsp` jump into the code that generates xrefs on the fly if latest revision cannot be determined and economy mode is on.
Also, an error message was added to avoid empty page appearing on error.

if economy mode is on and history off, generate xref on the fly

---

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java

This change makes it possible to run per-project indexing with just `-H projName` and the Indexer will get the list of repositories from the configuration.
The repository specification was separated into new `--repository` option.

get repositories for a project automatically

---

tools/src/main/python/projadm.py

fixes:
```
$ ./projadm.py -a test --jar ../../../../distribution/target/dist/opengrok-1.1-rc40.jar 
Lock 140106125077248 acquired on /tmp/projadm.py.lock
Adding project test
Starting new HTTP connection (1): localhost
Lock 140106125077248 released on /tmp/projadm.py.lock
File "./projadm.py", line 309, in <module>
configmerge=configmerge,
NameError: name 'configmerge' is not defined
```

fix referencing configmerge if not needed

---

opengrok-indexer/pom.xml
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java

Tested with:
```
Sep 07, 2018 1:13:04 PM org.opengrok.indexer.index.Indexer parseOptions
INFO: Indexer options: [--updateConfig, -U, http://localhost:8080/source]
Sep 07, 2018 1:13:05 PM org.opengrok.indexer.index.Indexer sendToConfigHost
INFO: Sending configuration to: http://localhost:8080/source
Sep 07, 2018 1:13:07 PM org.opengrok.indexer.index.Indexer sendToConfigHost
INFO: Configuration update routine done, check log output for errors.
```
and
```
Sep 07, 2018 1:13:43 PM org.opengrok.indexer.index.Indexer parseOptions
INFO: Indexer options: [--updateConfig, -U, localhost:8080/source]
ERROR: URL 'localhost:8080/source' is not valid.
```

check whether URL is valid

---

appveyor.yml

Appveyor build is still broken but at least it has universal ctags now.

Fix #2318 supply Universal ctags for Appveyor build

---

tools/src/main/python/mirror.py
tools/src/main/python/opengrok.py

The error message looks like this now:
```
ERROR:mirror.py:Cannot get the 'sourceRoot' config value from the web application on http://localhost:8081/source
```

failed requests should include URI

---

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java

The output when using `-S --listRepos` looks like this:
```
INFO: Done scanning for repositories, found 18 repositories (4s)
Repositories in /var/opengrok/src:
/foo (Mercurial)
/foo3 (Mercurial)
/foo-renamed (Mercurial)
/on-test (Mercurial)
/on-test/closed (Mercurial)
/foo(bar) (git)
/my-scripts (Mercurial)
/userland-s11u4 (Mercurial)
/universal-ctags (git)
/symlink (git)
/solaris-userland (git)
/OpenGrok (git)
/OpenGrok/testdata/sources/rfe2575 (SCCS)
/OpenGrok/testdata/repositories/rcs_test (RCS)
/OpenGrok/testdata/repositories/teamware (SCCS)
/tomcat (git)
/bar-renamed (Mercurial)
/symlink2 (git)
```

make the output when scanning/listing repositories a bit more verbose

---

opengrok-web/src/main/java/org/opengrok/web/AuthorizationFilter.java

Under some circumstances the configuration view per each thread
can become desynchronized when using partial index.
The issue itself should be tackled in more robust way.
Described properly in #2382.

Hotfix for non-deterministic results for partial index

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/ProjectTest.java

Tested with this read-only configuration:
```XML
<java version="1.8.0_60" class="java.beans.XMLDecoder">
<object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">
<void property="navigateWindowEnabled">
<boolean>true</boolean>
</void>
<void property="projects">                                                    
<void method="put">                                                          
<string>OpenGrok</string>                                                   
<object class="org.opengrok.indexer.configuration.Project">                 
<void property="navigateWindowEnabled">                                    
<boolean>false</boolean>                                                  
</void> …
```

add global tunable for navigate window

---

opengrok-tools/src/main/python/opengrok_tools/all/utils/command.py
opengrok-tools/src/main/python/opengrok_tools/all/utils/indexer.py
opengrok-tools/src/main/python/opengrok_tools/all/utils/java.py
opengrok-tools/src/main/python/opengrok_tools/indexer.py

This change enables continuous printing of Indexer output to stdout. The output is still stored in pertaining buffers.

continuous output printing in indexer.py

---

distribution/assembly.xml
opengrok-tools/pom.xml

Generating the output under the `target` directory. That also makes it clean when running `mvn clean`.
NOTE: when running `python3 setup.py sdist` the output won't go to `target`. This is just for maven builds.

Opengrok tools mvn

---

opengrok-tools/pom.xml

It didn't work well when splitted.
The package was not ready for testing.

Splitting the install and test phase

---

distribution/assembly.xml
distribution/pom.xml
opengrok-tools/pom.xml
opengrok-tools/setup.py

Use maven native plugins to read and transform
the module version and place it into the setup.py.
fixes #2393
When releasing 1.1 directly, I'd still verify it by hand if everything goes correctly, but there should not be a problem with the transition to the direct release.

Reading the python version from pom.xml

---

opengrok-web/src/main/webapp/WEB-INF/web.xml

The reason for this is that front page and search results can be pretty dynamic today. We have messages, the projects can change over time frequently (partial reindex, continual updates via the rest api).
- This should avoid caching the from page for 30 minutes
- The view can be inconsistent with the system state
- different cookies
- different messages
- different projects
- The same applies for search results
- Other resources are hidden behind the 30 minutes cache interval
touches #2405

Do not cache the front page and search results

---

opengrok-tools/src/main/python/opengrok_tools/utils/commands.py
opengrok-tools/src/test/python/test_command.py
opengrok-tools/src/test/python/test_commands.py

As @gco mentioned, `/bin/false` returns 255 on Solaris (unlike 1 on Linux etc.) which is perfectly fine w.r.t. POSIX which says: "The false utility shall always exit with a value other than zero." So the Python tests that rely on particular return value need to use something else.

use /bin/sh instead of /bin/false to make sure exit value is 1

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
opengrok-web/src/main/webapp/WEB-INF/web.xml
opengrok-web/src/main/webapp/mast.jsp

This enables us to reflect all other factors
which contribute to the resource freshness
- the last file timestamp
- messages on the project
- the timestamp of last index
- the opengrok version
We assemble all these to the weak tag,
and the resource is reloaded only in any of these change
OpenGrok version is added to the weak tag attributes because of utils.js. Until now event when we increase the version of utils.js, the cached xref still pointed to the old version causing some drama with javascript. This way with every new OpenGrok version, each xref will be reloaded (no need for ctrl+shift+R).
fixes #2405

Using weak tag instead of just last modification date

---

opengrok-tools/setup.py

When using local development environment, the install process warns about weird version number like "project.python.package.version". This should detect if maven did the substitution and apply some default version for the local development environment.

detecting local development version

---

distribution/assembly.xml

I noticed that we distribute opengrok.jar without the version, so I think this should be aligned also with the opengrok tools.

removing the version from the distribution of opengrok-tools

---

distribution/assembly.xml
opengrok-tools/pom.xml

adding logging.properties.template to opengrok-tools

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java

The logged exception produces a very long stack trace. I'd just print a warning for non-existent directory as the directory is expected to be deleted.

Muting exception for non-existent directory

---

opengrok-tools/pom.xml

I tested the Maven build with this change on Windows and Ubuntu. This change disables the python-tools tests on Windows as they will never work, but still builds the tools .tar.gz file correctly.

Fix #2462 opengrok-tools module breaks the maven build under Windows

---

opengrok-tools/setup.py

After Travis fails with:
```
[INFO] --- exec-maven-plugin:1.6.0:exec (python-test-install) @ opengrok-tools ---
error in opengrok-tools setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```
this is due to the `~=` specifier in `setup.py`. To make this usable in Travis env we need to stick to the basics.

Tools setup install req

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java

This typo/bug was introduced in https://github.com/oracle/opengrok/commit/2b892162bcf709338fb6776ed184615f9b9890c5.

Actually skip history cache creation when history is disabled for project

---

wercker.yml

Recently our Wercker builds have started failing with:
```
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /pipeline/source/opengrok-indexer && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -javaagent:/pipeline/cache/.m2/org/jacoco/org.jacoco.agent/0.8.1/org.jacoco.agent-0.8.1-runtime.jar=destfile=/pipeline/source/opengrok-indexer/target/jacoco.exec -jar /pipeline/source/opengrok-indexer/target/surefire/surefirebooter8023426895010125981.jar /pipeline/source/opengrok-indexer/target/surefire 2018-10-31T10-37-24_565-jvmRun1 surefire580312577885706607tmp surefire_96852007418474470112tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
```
On internal …

try to change to maven box

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/UtilTest.java
opengrok-web/src/main/webapp/list.jsp
opengrok-web/src/main/webapp/projects.jspf
opengrok-web/src/main/webapp/repos.jspf

This change redacts the user-info part of URL for the project/repository list on the index page.

redact URL in repository listing

---

appveyor.yml
dev/install-python-packages.sh
opengrok-tools/pom.xml
opengrok-tools/src/main/python/opengrok_tools/utils/command.py
opengrok-tools/src/test/python/test_command.py
opengrok-tools/src/test/python/test_commands.py
opengrok-tools/src/test/python/test_indexer.py

Refactor of the property naming, verifying that the build + tests pass correctly on windows build. Ensure python3.4 in appveyor.
When user wants to use his custom version of python, he can use
```bash
mvn -Dpython.system.executable=/opt/python50/bin/python test
```
it will create the virtul env with this base python.

modify the opengrok-tools env paths on windows

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Project.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/OGKUnifiedHighlighter.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/UtilTest.java

this is a good start, next steps are sanitize C:\ or any other letter and strip them
and make sure whole app just uses "/" and on windows all input or output gets properly sanitized and stripped if needed

sanitize more paths on windows, fixes #2335

---

opengrok-indexer/src/main/resources/analysis/c/Cxx.lexh

We noticed that hexadecimal and binary literals in C++ with digit separators are parsed incorrectly in OpenGrok, so this patch fixes them by using the same idiom as decimal and octal integers.
I accept the Oracle Contributor Agreement for this patch.

Fix C++ parsing of hex/binary literals with digit separators

---

pom.xml

When running `mvn versions:display-plugin-updates` to display available plugin updates, Maven was complaining that no minimum Maven version is enforced. This should fix this.

enforce minimum Maven version

---

opengrok-indexer/src/test/java/org/opengrok/indexer/util/FileUtilities.java

While looking at the failing Windows tests @tarzanek found out that these streams are not closed properly.
Note: `assertNotNull(out);` was redundant since constructor will never return `null`
Thanks :)

Close streams while extracting archive

---

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexVersion.java

`testIndexVersionOldIndex` fails on Windows with:
```
[ERROR] testIndexVersionOldIndex(org.opengrok.indexer.index.IndexVersionTest)  Time elapsed: 0.156 s  <<< ERROR!
java.nio.file.FileSystemException: 
C:\Users\appveyor\AppData\Local\Temp\1\data6096978419951074269\index\segments_3: The process cannot access the file because it is being used by another process.
at org.opengrok.indexer.index.IndexVersionTest.tearDown(IndexVersionTest.java:82)
[INFO] Running org.opengrok.indexer.search.context.ContextFormatterTest
```
Line 82 is recursive directory removal. The file/directory needs to be closed in `IndexVersionTest`.

testIndexVersionOldIndex fails on Windows

---

appveyor.yml
opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/util/FileUtilities.java
testdata/repositories/mercurial/hg/hgrc

This was originally root caused by @Orviss. The problem with the failing `FileHistoryCacheTest` tests on Windows were newlines. In particular, the `ZipFile` extraction performed by `FileUtilities` and used by `TestRepository` seems to be extracting the files from `repositories.zip` with CR LF as newlines on Windows even though the files therein were originally created on Unix.
This leads to Mercurial repository to become "dirty" right after extraction. Originally, I wanted to solve this with something like:
```java
package org.opengrok.indexer.history;
import java.io.FilterOutputStream;
import java.io.IOException;
import java.io.OutputStream;
/**
* Convert CR LF bytes in the stream to the LF byte.
*/
public class LFOutputStream extends FilterOutputStream {
public …
```

deal with newlines for tests utilizing Mercurial running on Windows

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/EftarFileReader.java
opengrok-web/pom.xml
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SystemControllerTest.java
suggester/pom.xml

Adding `-Djna=nosys` seems to do the trick.
https://github.com/java-native-access/jna/issues/281#issuecomment-194548638 mentions problems with jna library in the presence of system library.
Also, this property was made default quite recently (https://github.com/java-native-access/jna/issues/384)

suggester + web test fixes for Windows

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java

Hello,
Please consider for integration this patch to eject a problematic ctags instance from the pool and to retry for the affected file.
Log messages are adjusted slightly for clarity.
Thank you.

Retry on ctags tagLine == null. Adjust ctags logging.

---

opengrok-indexer/pom.xml
opengrok-web/pom.xml
opengrok-web/src/main/webapp/opensearch.jsp

Hello,
Please consider for integration this patch to add a jetty-jspc step to affirm that the JSP files compile without error. One JSP, `opensearch.jsp`, had an error and is fixed.
* Set `mergeFragment=false` so pre-compiled JSP classes will not be included in the WAR.
* Also, use `skipTests` not `maven.test.skip` w.r.t. the short-circuiting the setting up of testdata.
Thank you.

Use jetty-jspc. Fix opensearch.jsp exposed error.

---

opengrok-tools/src/main/python/opengrok_tools/mirror.py

fixes #2568
This supports writing wildcards in mirror-config.yml and also uses the relative path to the matched repository:
```yml
#
#
projects:
group-*:
ignored_repos:
- testdata/*
```
=> meaning `group-*/testdata/*` repositories.

allowing wildcards in mirror-config

---

opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerTest.java

The failure in `testGetSuggestionsMultipleProjects()` occurs from time to time, esp. when it is least convenient such as when creating a release. Thus, this change will disable the test until #2030 is solved.

temporarily disable testGetSuggestionsMultipleProjects

---

opengrok-tools/src/main/python/opengrok_tools/sync.py

When adding locking to `sync.py` I was not sure whether the lock needs to be released on `sys.exit()` so a comment was added there. I made a trivial program that mimicks `sync.py` to verify no explicit cleanup is actually needed:
``` python
#!/usr/bin/env python
import os
import sys
import tempfile
from filelock import FileLock, Timeout
import time
tmpfile = os.path.join(tempfile.gettempdir(), "foo.lock")
print(tmpfile)
lock = FileLock(tmpfile)
print(os.getpid())
with lock.acquire(timeout=0):
print("foo!")
try:
time.sleep(30)
except KeyboardInterrupt:
print("Interrupted")
sys.exit(1)
time.sleep(30)
print("done")
```
Running the program:
```
$ ./foo.py 
/var/folders/_d/2m97zqf92nlfyp17tnstfq540000gn/T/foo.lock
39196
foo!
^CInterrupted
```
while observing with dtruss:
```
$ sudo dtruss -p …
```

remove stale comment and cleanup pool of workers on KeyboardInterrupt

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/OptionParser.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/RepositoryTest.java

The serial version UID checks resurfaces in IDEA build so it is necessary to address them.

add serialVersionUID to silence lint

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/FileAnalyzerFactory.java
opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
opengrok-web/src/test/java/org/opengrok/web/WebappListenerTest.java

This change fixes the majority of memory leaks reported by Tomcat when redeploying the webapp.
To trigger the leaks it was sufficient to perform all project search in my staging environment and then restart/redeploy the webapp to see Tomcat report the leaks.
Before:
```
10-Dec-2018 12:57:23.277 SEVERE [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [source] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@4050fe0d]) and a value of type [org.opengrok.indexer.analysis.scala.ScalaAnalyzer] (value [org.opengrok.indexer.analysis.scala.ScalaAnalyzer@7de08937]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid …
```

fix ThreadLocal leaks in webapp

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/archive/GZIPAnalyzer.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java
opengrok-indexer/src/main/java/org/opengrok/indexer/search/SearchEngine.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/TandemFilename.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/TandemPath.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
opengrok-indexer/src/test/java/org/opengrok/indexer/condition/DeliberateRuntimeException.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexDatabaseTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/util/TandemFilenameTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/util/TandemPathTest.java

Hello,
Please consider for integration this patch to ensure that OpenGrok tandem filenames (i.e. filenames that operate in tandem with source files; e.g. `.gz` xref files and `.org_opengrok` interim files) do not exceed 255 byte filenames.
This is backward-compatible with existing 1.1 `DATA_ROOT` outputs* because the new algorithm is only really effective for files that could not be created due to exceeding 255 byte names.
Also:
- Do case-insensitive comparison for `.gz` in `GZIPAnalyzer`.
- Add a `serialVersionUID` to silence lint.
Thank you.
*for filesystems with 255 byte name limits, such as Linux, Windows, and macOS.

Fix #2604, add TandemFilename and TandemPath

---

opengrok-indexer/pom.xml
opengrok-indexer/src/main/java/org/opengrok/indexer/util/StatisticsUtils.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/Statistics.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/RuntimeEnvironmentTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/util/StatisticsUtilsTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/StatisticsTest.java
opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/StatsController.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/StatsControllerTest.java
pom.xml

This change gets rid of the JSON simple library in favor of Jackson.
There were couple of notable decisions I had to do:
- empty/initial Statistics will be encoded into full JSON (avoiding the special case)
- the averages are recomputed with each request so that getters/setters can be clean
- no JSON object passing around anymore - just strings
- StatsController converts the Statistics to JSON implicitly

convert Statistics to use Jackson for JSON processing

---

.travis.yml
pom.xml

The workaround https://bugs.openjdk.java.net/browse/JDK-8212233?focusedCommentId=14225970&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14225970 seems to be working.

workaround for broken javadoc in JDK 11 build

---

suggester/src/test/java/org/opengrok/suggest/SuggesterProjectDataTest.java
suggester/src/test/java/org/opengrok/suggest/SuggesterSearcherTest.java
suggester/src/test/java/org/opengrok/suggest/query/customized/CustomSloppyPhraseScorerTest.java

fixes #2454
From https://lucene.apache.org/core/7_6_0/core/org/apache/lucene/store/ByteBuffersDirectory.html :
> A heap-based directory like this one can have the advantage in case of ephemeral, small, short-lived indexes when disk syncs provide an additional overhead.
which I think is exactly what we need for tests.
Thanks :)

Replace RAMDirectory with ByteBuffersDirectory in tests

---

opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationFramework.java
opengrok-indexer/src/test/java/org/opengrok/indexer/authorization/AuthorizationFrameworkTest.java

This provides basic protection for `null` entities.

deal with null entities in AuthorizationFramework

---

apiary.apib
opengrok-indexer/pom.xml
opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/messages/JSONable.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/messages/Message.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/messages/MessagesContainer.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/messages/MessagesUtils.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/messages/JSONUtils.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/messages/MessageTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/messages/MessagesContainerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/messages/MessagesUtilsTest.java
opengrok-web/src/main/webapp/js/utils-0.0.27.js
opengrok-web/src/main/webapp/mast.jsp
opengrok-web/src/main/webapp/menu.jspf
opengrok-web/src/main/webapp/repos.jspf
opengrok-web/src/main/webapp/search.jsp
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/MessagesControllerTest.java

This change converts Message handling to use Jackson for JSON handling and finally shoves JSON-simple out of the door. The JSON format of the Message changed a bit to accommodate easier serialization.
Tested with:
1. `curl -X POST --data '{ "tags": [ "foo" ], "cssClass": "class", "text": "test message", "duration": "PT10M" }' -H 'Content-Type:application/json' http://localhost:8080/source/api/v1/messages`
1. `curl -X GET http://localhost:8080/source/api/v1/messages`
1. check the UI

use Jackson for JSON serialization of Messages

---

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java

As noticed in the log files supplied in #2647, the exception logging is missing index directory name so it is not clear which project's index was incomplete.

print index directory on exception

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java
opengrok-web/src/main/webapp/js/utils-0.0.28.js

fixes #2640
Hi,
the problem was that `$("#project").searchableOptionList().getSelection()` can return group elements.
Thanks :)

Fix suggestions for groups selections

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/PageConfigTest.java

1. Using assume to skip tests of the platform does not allow read permissions for files.
2. Fix the isUnix() for macosx platform
approaches #2661
fixes #2662

Page config test updates

---

opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationFramework.java
opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginClassLoader.java
opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginFramework.java
opengrok-indexer/src/test/java/org/opengrok/indexer/authorization/PluginClassLoaderTest.java

Separating the idea with plugin framework to a dedicated class and making the authorization framework a subclass of it.
depends on #2658 **(do not review until this one is merged)**
approaches #2588

Separate plugin framework

---

apiary.apib
opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/JFlexXref.java
opengrok-indexer/src/main/java/org/opengrok/indexer/search/QueryBuilder.java
opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/Context.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/JFlexXrefTest.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SuggesterController.java
opengrok-web/src/main/webapp/help.jsp
opengrok-web/src/main/webapp/js/utils-0.0.28.js
opengrok-web/src/main/webapp/menu.jspf
opengrok-web/src/main/webapp/minisearch.jspf
opengrok-web/src/main/webapp/opensearch.jsp
opengrok-web/src/main/webapp/search.jsp
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerTest.java

I've wanted to do this for a very long time :D
Only reason why I think it might be good to keep the name is backwards compatibility. However, it does not correspond to the index name as other fields (`refs,defs,…`) and is just plainly confusing.
Caveats: complete reindex needed (because of the xrefs) and old links will not work.
If you do not like this change then feel free to close this ;)
Thanks :)

Replace "q" query param name with "full"

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java

Hello,
Please consider for integration this fix to bump the `AnalyzerGuru` version, which I forgot to do after having added the `VerilogAnalyzer`.
Thank you.

Bump AnalyzerGuru version after Verilog addition

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java
opengrok-web/src/main/webapp/js/utils-0.0.29.js

escaping extra html in annotate tooltip

---

opengrok-web/src/main/webapp/repos.jspf

indenting only real subrepositories of the project

---

opengrok-tools/setup.py
opengrok-tools/src/main/python/opengrok_tools/sync.py

The minimum version is set according to our internal deployment, i.e. the version it is most tested with.

specify required python version

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java

Hello,
Please consider for integration this patch to support recognizing a `.git` file indicating a Git repository working tree.
Thank you.

Fix #2698 : recognize .git file for a worktree

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java

This change corrects the semantics of the outcome of getIndexSearcher() - it should either raise exception or return null but now both.

avoid returning null objects from getIndexSearcher()

---

opengrok-tools/src/main/python/opengrok_tools/utils/log.py

Running `opengrok-sync` while another was in progress did not result in the `Already running` message. This is due to the filters in `get_console_logger()` missing the `logging.WARNING` range.

logger must cover all levels

---

opengrok-tools/src/main/python/opengrok_tools/mirror.py
opengrok-tools/src/main/python/opengrok_tools/scm/mercurial.py

One of our Mercurial projects failed to sync and this was not noticed in the logs because the `opengrok-mirror` script was run with `-I`. One problem is that incoming check failures are treated as soft, second problem is that Mercurial exit codes are not interpreted correctly - in this case `hg incoming` exits with 255 due to authentication failure.

fail mirroring if incoming check raises exception

---

opengrok-web/pom.xml

While retrying the redeploy using Tomcat plugin as per PR #2711 I noticed the Maven Tomcat plugin hardcodes the properties even though they are present in the POM file. This change remedies that.

actually use the tomcat properties

---

opengrok-tools/src/main/python/opengrok_tools/mirror.py
opengrok-tools/src/main/python/opengrok_tools/scm/__init__.py
opengrok-tools/src/main/python/opengrok_tools/scm/repofactory.py
opengrok-tools/src/main/python/opengrok_tools/utils/__init__.py

depends on #2720
Removing the cross module dependency forcing the particular order of imports.

Moving repofactory to scm module

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/ScriptsTest.java

Using set instead of lists does not add the same record twice.
The records were doubled because (assume we get an exception on index.jsp page):
1. we partially render the index.jsp
2. it includes httpheader.jspf which registers the scripts into PageConfig
3. exception occurs, the error page is being rendered instead
4. error page calls httpheader.jspf again and it adds the script again to the same PageConfig (because the request has not changed)
5. error page renders the scripts twice

Suppressing the double render problem on error

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/document/MandocRunner.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/DefaultIndexChangedListener.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java

Hello,
Please consider for integration this patch to remove the redundant directory traversal while indexing and to adjust logging levels, so that `INFO` is less verbose and `FINEST` fills out.
As an example with the OpenGrok source, previously the indexing would produce logs with the following aggregate number of messages per log level:
```
FINER      3291
INFO       2828
FINEST     1499
FINE       107
WARNING    18
CONFIG     14
```
`FINER` had the most messages, with `INFO` second, and `FINE` with barely any content.
With this patch, a run will produce the aggregate levels below, with `INFO` nicely terse, `FINEST` having the largest number of messages, and `FINE` and `FINER` having about an equal number of messages.
```
FINEST     4668
FINER      1528
FINE       1468
INFO       48 …
```

Vary Level for printProgress(). No redundant getFileCount().

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryTest.java

I noticed that viewing revision of renamed files was broken. The getHistory expects a full path file while the find renamed name returns the name relative to the repository directory. This leads that for renamed files the revision was never found as the filename after renaming was invalid.

Fixing git viewing renamed revision

---

opengrok-web/src/main/webapp/default/style.css
opengrok-web/src/main/webapp/repos.jspf

Main page now lists also projects which are not repositories. The changes are little hard to follow in the diff here because the diff took it a little bit differently. I suggest you open the file and see what is the result. 
Summary:
1. In every group there is an extra table "Project" which lists the group projects as its rows.
2. In other group there is an extra table "Project" which lists the group projects as its rows.
3. In mode without group there is an extra table "Project" which lists the group projects as its rows.
4. In mode without projects nothing has changed.

adding bare project to the main page

---

opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationException.java
plugins/src/opengrok/auth/plugin/LdapUserPlugin.java
plugins/src/opengrok/auth/plugin/decoders/MellonHeaderDecoder.java
plugins/src/opengrok/auth/plugin/decoders/OSSOHeaderDecoder.java
plugins/src/opengrok/auth/plugin/entity/User.java
plugins/test/opengrok/auth/plugin/decoders/MellonDecoderTest.java
plugins/test/opengrok/auth/plugin/util/DummyHttpServletRequestUser.java

This is a simple decoder for the https://github.com/UNINETT/mod_auth_mellon SAML implementation.
Needs `mod_headers` to convert the email Apache environment variable from `mod_auth_mellon` to HTTP header. In Apache config it looks like this:
```
RequestHeader unset MELLON_email
RequestHeader set MELLON_email "%{MELLON_email}e" env=MELLON_email
```
Also, makes some of the error messages more informative.

add Mellon header decoder

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceHistoryParser.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceRepository.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/PerforceRepositoryTest.java

This avoids the errors from perforce when using filenames containing reserved characters, and will fix issue #2746 .
I am not a java developer so much, so I'm happy to adjust the code to match core opinions of how it should be implemented.  Let me know.

Perforce filenames 2746

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java

Basically, the main change is to use `-n 1` instead of revision ranges when getting tag metadata.
Still, the overall approach leaves a lot to be desired as highlighted in the issue. In addition to that, from implementation perspective, running `git` for each tag is sub-optimal.

use more robust approach for obtaining commit ID + date for tags

---

opengrok-indexer/pom.xml

Changes the configuration of `git-commit-id` Maven plugin not to fail if git info cannot be retrieved (using a property as described on https://github.com/git-commit-id/maven-git-commit-id-plugin/blob/master/docs/using-the-plugin.md). This is handy when building from release source archives. Thanks to how `Info.java` works the missing properties will be set to "unknown":
```
$ java -jar ./distribution/target/dist/opengrok-1.2.8.jar -V
Jun 03, 2019 12:15:48 PM org.opengrok.indexer.index.Indexer parseOptions
INFO: Indexer options: [-V]
OpenGrok v1.2.8 rev unknown
```
This will be fixed in source code archives starting from 1.2.9.

do not fail if git info cannot be retrieved

---

opengrok-tools/src/main/python/opengrok_tools/deploy.py

Yesterday I was lazy typing the full path of config file when deploying with the `opengrok-deploy` script and the result was non-functional webapp because it could not find the config file. This change fixes that.

always use absolute path for webapp config file

---

opengrok-tools/src/test/python/test_mirror.py

Recently the Windows tests in AppVeyor started failing with:
```
================================== FAILURES ===================================
__________________ test_invalid_project_config_nonexec_hook ___________________
def test_invalid_project_config_nonexec_hook():
with tempfile.TemporaryDirectory() as tmpdir:
with open(os.path.join(tmpdir, "foo.sh"), 'w+') as tmpfile:
tmpfile.write("foo\n")
config = {"foo": {HOOKS_PROPERTY: {"pre": "foo.sh"}}}
>               assert not check_project_configuration(config, hookdir=tmpdir)
E               AssertionError: assert not True
E                +  where True = check_project_configuration({'foo': {'hooks': {'pre': 'foo.sh'}}}, hookdir='C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpxsvor572')
```
given the …

perform hook executable tests only on Unix systems

---

opengrok-web/pom.xml
opengrok-web/src/main/java/org/opengrok/web/AuthorizationFilter.java
opengrok-web/src/main/java/org/opengrok/web/DirectoryListing.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ConfigurationController.java
pom.xml

Hello,
I noticed that web module does not have checkstyle plugin.
Thanks :)

Enable checkstyle for web module

---

.gitignore
opengrok-indexer/pom.xml
opengrok-web/pom.xml
plugins/pom.xml
pom.xml
suggester/pom.xml

Hi guys,
I was looking on test coverage and I thought that I will improve it little bit, by writing new JUnit tests.
Then I realized that it would be perfect way to learn/use new tricks from JUnit5.
So I thought that it would make sense to first to update OpenGrok to using JUnit 5 and then start changing/adding tests.
What do you think?
Tested by:
```bash
./mvnw test
...
========================== 54 passed in 18.41 seconds ==========================
[INFO] 
[INFO] ---------------------< org.opengrok:opengrok-dist >---------------------
[INFO] Building Distribution 1.2.8                                        [7/7]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven) @ opengrok-dist --- …
```

initialization of Junit 5

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryFactory.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/RepositoryFactoryTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/util/TestRepository.java

The detection of most repository types relies on the existence of special directory/file (e.g. the `.git` directory for Git). Perforce runs external command to detect whether given directory belongs to a repository. When misconfigured this could lead to strange indexing behavior.
This should help to detect+prevent cases as described in #2798.

disallow repository path equal to source root

---

opengrok-web/src/main/webapp/WEB-INF/tags/project.tag

This should fix the missing context path in project links on index page.

add missing brackets for method call

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceRepository.java

Implement determineCurrentVersion() for PerforceRepository
note, I tested this and it works.  However, I've found that after loading the root in the Web U/I, then updating one of the perforce repositories, the web U/I doesn't refresh.  It is still showing the version test of that repository when I first loaded the page.  Shift-refresh doesn't help, and waiting an hour didn't help.
Have I missed something to make this know it needs to recheck via determineCurrentVersion()?

Add support for getting CurrentVersion of PerforceRepository

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java

Addressing https://github.com/oracle/opengrok/issues/2804
Added private as a def declaration option.
Also added protected as a possible option to a definition.
Reference: https://docs.scala-lang.org/style/declarations.html

Update Ctags.java to address Issue 2804: added private and protected to def statement regex

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
opengrok-web/src/main/webapp/WEB-INF/tags/repository.tag

correctly displays subrepository path on the index page

JSTL vs Paths

---

opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java

example of log entry:
```
2019-06-17 15:13:49.834+0200 FINE t1 Executor.exec: Executing command [git, log, --format=commit:%H%nDate:%at, -n, 1, 2.4] in directory /var/opengrok/src/jna with environment: {PATH=/home/vkotal/bin:/home/vkotal/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin, XAUTHORITY=/run/user/1000/gdm/Xauthority, LC_MEASUREMENT=en_US.UTF-8, LC_TELEPHONE=en_US.UTF-8, ...}
```

log environment with Level.FINER

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryFactory.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java

This change restricts the discovery of sub-repositories to the type of repository already found.

add sub-repositories of the same type as parent

---

pom.xml

fixes #2820
```
[INFO] --- maven-help-plugin:3.2.0:active-profiles (default-cli) @ opengrok-top ---
[INFO] 
Active Profiles for Project 'org.opengrok:opengrok-top:pom:1.2.15':
The following profiles are active:
- java9plus-8-release (source: org.opengrok:opengrok-top:1.2.15)
Active Profiles for Project 'org.opengrok:opengrok:jar:1.2.15':
The following profiles are active:
- java9plus (source: org.opengrok:opengrok:1.2.15)
- java9plus-8-release (source: org.opengrok:opengrok-top:1.2.15)
Active Profiles for Project 'org.opengrok:plugins:jar:1.2.15':
The following profiles are active:
- java9plus (source: org.opengrok:plugins:1.2.15)
- java9plus-8-release (source: org.opengrok:opengrok-top:1.2.15)
Active Profiles for Project 'org.opengrok:suggester:jar:1.2.15':
The following profiles are …
```

adding --release 8 argument to JDK9+ builds

---

dev/before_install
dev/docker.sh

The README file on Docker hub is not automatically refreshed. This is because the Docker image builds are performed in Travis and not on Docker hub.
Using https://stackoverflow.com/a/55082686/11582827 and https://success.docker.com/article/how-do-i-authenticate-with-the-v2-api I made this work without enabling automated builds in Docker hub. The API does not seem to be publicly documented but works.

refresh repository README on Docker hub after image push

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java

Removing .gitignore from ignored files

---

plugins/src/opengrok/auth/plugin/UserWhiteListPlugin.java

This change introduces new simple authorization plugin that checks user against a whitelist. It complements/depends on the HTTP Basic Auth decoder (PR #2875).
The idea was spawned by the discussion in #2872. Basically, it allows to shift authorization decision from Tomcat to OpenGrok authorization framework for setup where authentication is done by Tomcat.

introduce UserWhiteListPlugin

---

opengrok-tools/src/main/python/opengrok_tools/utils/commandsequence.py
opengrok-tools/src/test/python/test_command_sequence.py

Allows to have multiple cleanup "commands" in `opengrok-sync` configuration:
Sample config:
```yml
commands:
- command: [cat, '/foo']
cleanup:
- command: [ls, '/etc']
- command: [echo, 'cleanup']
```
Even if any of the cleanup commands fail, the execution continues, unlike what is done for the main sequence of commands.

make cleanup a list in CommandSequence

---

opengrok-tools/src/main/python/opengrok_tools/deploy.py
opengrok-tools/src/main/python/opengrok_tools/utils/xml.py
opengrok-tools/src/test/python/insert.xml
opengrok-tools/src/test/python/invalid.xml
opengrok-tools/src/test/python/new.xml
opengrok-tools/src/test/python/test_xml.py
opengrok-tools/src/test/python/web.xml

This change adds the ability to insert content to the `web.xml` file in the WAR file. This is handy for enabling authentication while deploying.
Will update https://github.com/oracle/opengrok/wiki/Authorization-based-on-HTTP-Basic-Authentication#application-deployment-descriptor once this is merged in.

add option to insert XML snippet into web.xml

---

index.html

Hi,
I've noticed that the web page still contains link to the demo which is no longer working. I've replaced it with the link to Docker image.
Please let me know if you would like to change the wording or replace it with something else.
Thanks :)

Replace demo link with link to docker image

---

.mvn/wrapper/maven-wrapper.properties
.travis.yml
appveyor.yml
dev/javadoc.sh
dev/main
dev/pre-deploy.sh
dev/release.sh
docker/README.md
opengrok-tools/README.md
opengrok-web/pom.xml
pom.xml

Hi,
fixes #2792 
I've noticed that there is a new version of `maven-checkstyle-plugin` so I've tried re-enabling it in web module -> `./mvnw clean compile` works without issues on my Mac and Fedora.
Also, I've updated `mvnw` to newer version and rewritten CI scripts to use it as well. I'm not sure if `appveyor` and `wercker` will work properly since I don't have them enabled in my fork.
Thanks :)

Re-enable checkstyle in web module

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/ScriptsTest.java
opengrok-web/pom.xml
opengrok-web/src/main/webapp/httpheader.jspf
opengrok-web/src/main/webapp/js/utils-0.0.31.js

Hi,
I've added maven plugin which minifies `js` and `css` files. I don't think there will be a noticable improvement since our js and css files are quite small.
`jslint` produces a few warnings so I will create an issue for that as soon as this is merged.
If there is a need to debug the `js` code, then simply `debug=true` query param can be appended to the URL.
Changes in the `util.js` file fixed errors where `class` should be enclosed in `"` -> the same can be seen on jQuery page as well: https://api.jquery.com/jQuery/#creating-new-elements
Thanks :)

Minify js and css files

---

suggester/pom.xml
suggester/src/main/java/org/opengrok/suggest/popular/impl/chronicle/BytesRefDataAccess.java

Hi,
I've copied the usage from https://github.com/OpenHFT/Chronicle-Map/blob/master/src/main/java/net/openhft/chronicle/hash/serialization/impl/ByteArrayDataAccess.java
Thanks :)

Update chronicle-map to 3.17.4

---

suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java

Hi,
I was trying OpenGrok on JDK12 and noticed that suggester was not working. The reason was `ExceptionInInitializerError` thrown when creating chronicle map. Suggester works as expected when the error is caught. Adding `--add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED` params solves the issue and chronicle map works properly.
Thanks :)

Catch ExceptionInInitializerError produced by chronicle-map on JDK12

---

suggester/src/main/java/org/opengrok/suggest/Suggester.java

While reindexing from scratch, I noticed a log message:
```
02-Sep-2019 13:24:44.172 FINE [http-nio-8080-exec-5] org.opengrok.suggest.Suggester.onSearch Could not update search count map
java.lang.NullPointerException
at org.opengrok.suggest.SuggesterProjectData.incrementSearchCount(SuggesterProjectData.java:416)
at org.opengrok.suggest.SuggesterProjectData.incrementSearchCount(SuggesterProjectData.java:397)
at org.opengrok.suggest.Suggester.onSearch(Suggester.java:424)
at org.opengrok.web.api.v1.suggester.provider.service.impl.SuggesterServiceImpl.onSearch(SuggesterServiceImpl.java:244)
at org.apache.jsp.search_jsp._jspService(search_jsp.java:245)
```
It would be useful for which projects the update failed.

report projects in Suggester log message

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/ConfigurationHelp.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java

Tested with hacked Universal ctags:
```diff
diff --git a/main/main.c b/main/main.c
index 2384cea7..f0b608b8 100644
--- a/main/main.c
+++ b/main/main.c
@@ -278,7 +278,11 @@ static bool createTagsFromFileInput (FILE *const fp, const bool filter)
parseCmdlineOptions (args);
while (! cArgOff (args))
{
-                       resize |= createTagsForEntry (cArgItem (args));
+                       const char *carg = cArgItem (args);
+                       if (strstr(carg, "toxic") != NULL)
+                               sleep(3600);
+
+                       resize |= createTagsForEntry (carg);
if (filter)
{
if (Option.filterTerminator != NULL)
```
and a repository that contained `toxic.txt` file. The logs from indexer run then looked like so:
```
WARNING: Terminating ctags process for file …
```

enforce timeout for file processing in ctags

---

opengrok-tools/src/test/python/test_command.py
opengrok-tools/src/test/python/test_command_sequence.py

Lately I found that `opengrok-indexer` hangs the java process underneath because it failed to consume what was written into the pipe. So far this is only happening on one system so the chances are this is isolated failure however to be sure, I added a test to cover the very basic case.

Python test long output

---

opengrok-tools/src/main/python/opengrok_tools/config_merge.py
opengrok-tools/src/main/python/opengrok_tools/groups.py
opengrok-tools/src/main/python/opengrok_tools/indexer.py
opengrok-tools/src/main/python/opengrok_tools/java.py
opengrok-tools/src/main/python/opengrok_tools/reindex_project.py
opengrok-tools/src/main/python/opengrok_tools/utils/parsers.py

Introduce --doprint option to allow better flexibility - possible to run all Java apps with output being continuously written to the console.

allow to set doprint

---

opengrok-tools/src/main/python/opengrok_tools/utils/command.py

Tested with this program running with C locale:
```
#!/usr/bin/env python3.4
from opengrok_tools.utils.command import Command
cmd = Command(["python", "-c", "print(u'\\ua000\\nfoo\\n')"],
env_vars={"LANG": "en_US.UTF-8", "LC_ALL": "en_US.UTF-8"},
doprint=True)
cmd.execute()
print(cmd.getretcode())
print(len(cmd.getoutput()))
```
It reported:
```
'ascii' codec can't encode character '\ua000' in position 0: ordinal not in range(128)
foo
0
3
```
without the fix the program just gets stuck.

handle exceptions when printing in OutputThread

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java

Tested with `RuntimeEnvironment:setConfiguration()` modified to sleep for 5 minutes. First, the method was triggered:
```
curl -X PUT -H 'Content-Type: application/xml' -d @/var/opengrok/etc/configuration.xml 'http://localhost:8080/source/api/v1/configuration?reindex=true'
```
and then I did bunch of requests (`curl  http://localhost:8080/source/`) to make sure they are not blocked anymore.

revise auth framework locking in RuntimeEnvironment

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryFactory.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/CVSRepositoryTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java

@vladak, this PR is a different approach from your #2901 to fixing #2900 where instead of modifying a repository to know of others' type, a property, `isNestable()` (default `false`), indicates if a `Repository` subclass can be contained within other repositories. I think this is simpler to achieve your goal in #2817 of "efficiency (esp. those repository types which do not just look for special files/directories but execute a command to detect a repository)."
Only Git and Mercurial are marked as `isNestable() == true`. (N.b. only Git, Mercurial, and Repo are marked as `supportsSubRepositories() == true`.)

Fixes #2900 : Add Repository isNestable() property

---

opengrok-tools/src/main/python/opengrok_tools/config_merge.py
opengrok-tools/src/main/python/opengrok_tools/deploy.py
opengrok-tools/src/main/python/opengrok_tools/groups.py
opengrok-tools/src/main/python/opengrok_tools/indexer.py
opengrok-tools/src/main/python/opengrok_tools/java.py
opengrok-tools/src/main/python/opengrok_tools/mirror.py
opengrok-tools/src/main/python/opengrok_tools/projadm.py
opengrok-tools/src/main/python/opengrok_tools/reindex_project.py
opengrok-tools/src/main/python/opengrok_tools/sync.py
opengrok-tools/src/main/python/opengrok_tools/utils/command.py
opengrok-tools/src/main/python/opengrok_tools/utils/hook.py
opengrok-tools/src/main/python/opengrok_tools/utils/parsers.py
opengrok-tools/src/test/python/test_parsers.py

This contains bunch of changes:
- chage `--doprint` to be a toggle
- restore logging to the console by default in `opengrok-indexer`
- change the `doprint` logging to use a logger rather than writing to standard output

--doprint fixes

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/AccuRevRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/BazaarRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/BitKeeperRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/CVSRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/ClearCaseRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/MonotoneRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/RCSRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/RazorRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepoRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/SCCSRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/SSCMRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/PerforceRepositoryTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/RepositoryTest.java

remove repository update capability

---

opengrok-indexer/pom.xml
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/Progress.java
opengrok-indexer/src/test/java/org/opengrok/indexer/util/ProgressTest.java
pom.xml
suggester/pom.xml

Lately I found that indexer spends inordinate amount of time in `PendingFileCompleter#complete()` (also there were lots of files under the `xref` directory with the `org_opengrok` suffix) which made me wonder how much time is actually spend there. This change adds simple reporting.

report duration of PendingFileCompleter

---

opengrok-web/src/main/webapp/WEB-INF/tags/repository.tag

Fixes sub-directory links on the index page. Reported in #2925 however I am not going to list that as a fix since that issue tracks multiple problems at once.

fix subdirectory links on the index page

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
opengrok-web/src/main/java/org/opengrok/web/WebappListener.java

This change should speed up diff view for large (in terms of history) repositories.
For renamed files the approach taken (parallelize `getRevision()` in `getDiffData()`) is sub-optimal as the most expensive work (retrieve the history of the file across renames) is done twice (but in parallel as opposed to the previous state). @DaliborSkrobak told me he has maybe an idea how to fix this better.

make getDiffData() parallel

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuruHelp.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/ConfigurationHelp.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/SuggesterConfig.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IgnoredNames.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/StringUtils.java

Hello,
Please consider for integration this patch to improve `--help --detailed` as shown below:
Thank you.
**ignoredNames**
Former:
```
```
New:
```
```
**includedNames**
Former:
```
```
New:
```
```
**pluginStack**
Former:
```
```
New:
```
```
**suggesterConfig**
Former:
```
<java version="1.8.0_222-internal" class="java.beans.XMLDecoder">
<object class="org.opengrok.indexer.configuration.Configuration"/>
</java>
```
New:
```
<void property="suggesterConfig">
<void property="allowComplexQueries">
<boolean>false</boolean>
</void>
<void property="allowMostPopular">
<boolean>false</boolean>
</void>
<void property="allowedFields">
<object class="java.util.HashSet">
<void method="add">
<string>defs</string>
</void>
<void method="add"> …
```

Improve configuration help

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/JFlexSymbolMatcher.java
opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/JFlexXrefUtils.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/UriUtils.java

Hello,
Please consider for integration this patch to remove duplicated code for URI trimming by extracting and sharing `UriUtils.trimUri`.
Thank you.

Share implementation of trimUri()

---

apiary.apib
opengrok-tools/setup.py
opengrok-tools/src/main/python/opengrok_tools/utils/__init__.py
opengrok-tools/src/main/python/opengrok_tools/utils/commandsequence.py
opengrok-tools/src/main/python/opengrok_tools/utils/mirror.py
opengrok-tools/src/main/python/opengrok_tools/utils/patterns.py
opengrok-tools/src/main/python/opengrok_tools/utils/restful.py
opengrok-tools/src/test/python/test_command_sequence.py
opengrok-tools/src/test/python/test_mirror.py
opengrok-tools/src/test/python/test_restful.py

This change adds optional command to be called/executed for disabled projects. Like with sync.py this supports both RESTful API calls as well as command execution. This allows for instance to tag the disabled projects with Messages so they are annotated in the UI.
The disabled command is configured globally and will vary based on project thanks to pattern substitution/append. If this is found not to be flexible enough, it can be modified to allow per-project disabled commands however for the time being I find this good enough.
Examples:
```yml
disabled_command:                                                               
command:                                                                     
- http://localhost:8080/source/api/v1/messages                             
- POST …
```

add disabled project handling to mirror.py

---

opengrok-tools/src/main/python/opengrok_tools/utils/parsers.py

expands on how to use -J with multiple `java` options.

better -J help for python java wrappers

---

apiary.apib
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/messages/Message.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/messages/MessagesContainer.java
opengrok-tools/src/main/python/opengrok_tools/utils/restful.py
opengrok-tools/src/main/python/opengrok_tools/utils/webutil.py
opengrok-tools/src/test/python/test_restful.py
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/MessagesController.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/MessagesControllerTest.java
plugins/src/main/java/opengrok/auth/plugin/util/RestfulClient.java

Trying to use the `opengrok-mirror` handling of disabled projects (#2973) I discovered this gets blocked by cleanup handling in `opengrok-sync` configuration:
```yml
commands:
- command:
- http://localhost:8080/source/api/v1/messages
- POST
- cssClass: info
duration: PT1H
tags: ['%PROJECT%']
text: resync + reindex in progress
... opengrok-mirror with disabled project handling emits the message
cleanup:
- command: ['http://localhost:8080/source/api/v1/messages?tag=%PROJECT%', DELETE, '']
```
To make this possible, I extended the `DELETE` handling in `MessagesController` to accept entity body (this is possible due to HTTP 1.1 spec RFC 7231 as explained on https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request?rq=1) and match also on that.
Tested with …

specify which Messages to delete with text

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/CanonicalRootValidator.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/CanonicalRootValidatorTest.java

Hello,
Please consider for integration this small patch that applies the same `--canonicalRoot` validation upon deserializing `Configuration` as is done for `Indexer`.
Thank you.

Also validate canonicalRoot when deserializing Configuration

---

.travis.yml
Dockerfile

I've seen that it is quite common to build projects directly in `Dockerfile` so I thought I will give it a try. It is then very useful in `docker-compose` since you can build many things by a single command.
If the maven repositories are cached, then it takes about 6 minutes to build the whole docker image. But if travis does not use cache and builds it all from scratch, then it may significantly prolong the travis execution time which might not be that wise.
What do you guys think?
If you do not like it, then feel free to close it :)

Rewrite Dockerfile to build the project

---

opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java

Hello,
Please consider for integration this patch to fix the log message for pending linkages from the recent PR #2947.
Thank you.

Fix log suffix to read "linkages"

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/PlatformUtils.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
opengrok-indexer/src/test/java/org/opengrok/indexer/condition/UnixPresent.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/BazaarHistoryParserTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/util/ExecutorTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/UtilTest.java

Hello,
Please consider for integration this patch to adjust the format of `Executor` logging not to use the default `List` serialization that uses commas but to use a specialized serialization that formats commands as would be required to execute on the platform. I.e. the commands are logged more clearly and also could be copy/pasted to a shell for execution (as when debugging).
E.g. formerly the following would appear in a log:
```
Executing command [git, log, -1, --pretty=%cd#%h %an %s, --date=iso8601-strict]
```
and would now be formatted as:
```
Executing command [git log -1 --pretty=$'%cd#%h %an %s' --date=iso8601-strict]
```
I also included `os.name`-dependent formatting for Windows:
```
Executing command [git log -1 --pretty="%cd#%h %an %s" --date=iso8601-strict]
```
Thank you.

Format argv logging to aid copy/paste execution

---

docker/README.md

While trying the examples in the readme I've noticed the following errors:
```
docker: Error response from daemon: create ~/opengrok-src/: "~/opengrok-src/" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```
and
```
docker: Error response from daemon: invalid volume specification: '/Users/ahornace/opengrok-data/:opengrok/data': invalid mount config for type "bind": invalid mount path: 'opengrok/data' mount path must be absolute.
```
Thanks.

Fix volume paths in docker readme

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryFactory.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/RepositoryFactoryTest.java

Hello,
Please consider for integration this patch to add `--disableRepository <type_name>` handling, which is an easier workaround for #2589 (via `--disableRepository cvs`) versus enhancing ignored-directory handling to support qualifying only a `CVS` directory containing e.g. `cvswrappers`. (A `Configuration` serialization DSL to support this nuanced ignoring did not seem prudent compared to a user-specified disabling of `CVSRepository`.)
Thank you.

Add --disableRepository handling

---

opengrok-tools/src/main/python/opengrok_tools/utils/command.py
opengrok-tools/src/main/python/opengrok_tools/utils/commandsequence.py

This change should deal with most of the log entries for the `Command` class, e.g.:
```
2019-12-06 21:16:20,068    DEBUG opengrok_tools.utils.command | Command '/bin/false 1 opengrok' took 0 seconds
2019-12-06 21:16:20,069    ERROR opengrok_tools.utils.commandsequence | command '/bin/false 1 opengrok' for project opengrok failed with code 1, breaking
```

use __str__ of the Command class for logging consistently

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/sql/PLSQLAnalyzer.java
opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/sql/SQLAnalyzer.java

Hello,
Please consider for integration this patch to bump the versions of `SQLAnalyzer` and `PLSQLAnalyzer` after their recent refactoring.
Thank you.

Bump versions of SQLAnalyzer and PLSQLAnalyzer

---

opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/ada/AdaSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/c/CSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/c/CxxSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/clojure/ClojureSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/csharp/CSharpSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/eiffel/EiffelSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/erlang/ErlangSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/fortran/FortranSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/golang/GolangSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/haskell/HaskellSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/javascript/JavaScriptSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/json/JsonSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/kotlin/KotlinSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/lua/LuaSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/pascal/PascalSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/perl/PerlSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/powershell/PoshSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/python/PythonSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/ruby/RubySymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/rust/RustSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/scala/ScalaSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/sh/ShSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/sql/PLSQLSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/sql/SQLSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/swift/SwiftSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/tcl/TclSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/typescript/TypeScriptSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/vb/VBSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/verilog/VerilogSymbolTokenizerTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/util/StreamUtils.java

Hello,
Please consider for integration this patch to extract a method from code duplicated in symbol tokenizer tests.
Thank you.

Extract symbol-tokenizer test code

---

opengrok-indexer/src/main/resources/analysis/sql/JointSQLProductions.lexh

Hello,
Please consider for integration this tiny patch to remove some duplicate definitions.
Thank you.

Fix accidental duplications left in

---

opengrok-tools/src/main/python/opengrok_tools/utils/command.py
opengrok-tools/src/main/python/opengrok_tools/utils/mirror.py
opengrok-tools/src/test/python/test_mirror.py
opengrok-tools/src/test/python/test_repofactory.py

This change fixes bug in timeout properties not being used in mirror.py at all unless configured on project level.
The added tests merely check parameter passing between functions. More robust test would be e.g. to use GitPython in `git.py` (as suggested in #2852), mock it to timeout the pull operation and verify the timeout in tests.

fix timeout inheritance in mirror.py

---

opengrok-tools/README.md
opengrok-tools/src/main/python/opengrok_tools/scm/repofactory.py
opengrok-tools/src/main/python/opengrok_tools/utils/mirror.py
opengrok-tools/src/main/python/opengrok_tools/utils/opengrok.py
opengrok-tools/src/test/python/test_mirror.py
opengrok-tools/src/test/python/test_repofactory.py

This is a follow-up to #3025, making the changes suggested by @ericsaintetienne and adding better tests.

use kwargs in get_repository(), get_repos_for_project()

---

opengrok-web/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

dev/before_install
dev/install-python-packages.sh

currently all Linux builds fail due to (from `pep8` install):
```
Collecting distlib<1,>=0.3.0
Downloading distlib-0.3.0.zip (571 kB)
|████████████████████████████████| 571 kB 43.4 MB/s 
ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n_2nuwn0/distlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n_2nuwn0/distlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-n_2nuwn0/distlib/pip-egg-info
cwd: /tmp/pip-install-n_2nuwn0/distlib/
Complete output (3 lines):
File "<string>", line 1, in <module> …
```

fix Python install issues

---

pom.xml

Let's see if Jersey 2.30.1 has any affect on the Windows build reliability.

To Jersey 2.30.1 and Jackson 2.10.1

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java

Hello,
Please consider for integration this patch to increase the ctags `--pattern-length-limit` to 180 from the default of 96 to reduce the likelihood of a file re-read by OpenGrok's `Ctags.trySplitSource()`.
180 seems to me large enough for any sensible coding style's maximum line length while still being short enough to avoid pathologically large tags files as used to affect Exuberant Ctags with its unbounded patterns (e.g. as when tagging minified JavaScript).
Thank you.

Use ctags --pattern-length-limit=180 to reduce likelihood of re-read

---

opengrok-indexer/src/main/java/org/opengrok/indexer/search/DirectoryExtraReader.java
opengrok-web/src/main/webapp/list.jsp

Hello,
Please consider for integration this patch to retrieve LOC and #Lines for project-less setups too.
I noticed those values were blank in testing the example for #3058 .
Thank you.

Lookup LOC and #Lines for project-less setup too

---

opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
opengrok-web/src/main/webapp/error.jsp

As mentioned in https://github.com/oracle/opengrok/issues/3054#issuecomment-591386503 the error messaging of the web application in the condition of missing configuration needs to improve.
This is crude but effective way how to stop the deployment. If the `CONFIGURATION` parameter is missing in `web.xml` then it is likely that we cannot trust the contents of the file anyway so tear down of the webapp is in order. I did not find any other way than to throw unchecked exception.

bail deploy if CONFIGURATION is not present

---

apiary.apib
opengrok-indexer/src/main/java/org/opengrok/indexer/history/Annotation.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/HeadHandler.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
opengrok-indexer/src/test/java/org/opengrok/indexer/util/HeadHandlerTest.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/FileNotFoundExceptionMapper.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/NoPathParameterExceptionMapper.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/AnnotationController.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/FileController.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/filter/LocalhostFilter.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/filter/PathAuthorizationFilter.java
opengrok-web/src/main/java/org/opengrok/web/util/FileUtil.java
opengrok-web/src/main/java/org/opengrok/web/util/NoPathParameterException.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/AnnotationControllerTest.java

This change add simple annotation API.
Limitations:
- no support for paging
- description is HTML encoded
While testing I found out that Git annotations are broken so fix for that is included.

Annotation API

---

opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/AnnotationControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ConcurrentConfigurationControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ConfigurationControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/FileControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/HistoryControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/MessagesControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/OGKJerseyTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/RepositoriesControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SearchControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/StatsControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerProjectsDisabledTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SystemControllerTest.java

Let's see if this improves the reliability of tests on Windows.
Inspired by Hadoop's similar problem, "MAPREDUCE-6733, MapReduce JerseyTest tests failing with 'java.net. BindException: Address already in use'", but all new implementation since Hadoop's patch was to customize com.sun.jersey.

Marshal random port through CONTAINER_PORT forced property

---

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java

When discussing slow indexer time in https://github.com/oracle/opengrok/issues/3071#issuecomment-600007923 I found that the traversal time is not reported even though the `Statistics` object is created before hand.

report directory traversal time

---

opengrok-tools/pom.xml

Running ` mvn -Dtest=SuggesterControllerTest -DfailIfNoTests=false clean verify` with the changes in 30788c18ae11181fec0a0e18c8fec2c15be8410e fails with:
```
[INFO] --- exec-maven-plugin:1.6.0:exec (Python lint) @ opengrok-tools ---
************* Module opengrok_tools.mirror
/home/travis/build/vladak/OpenGrok/opengrok-tools/src/main/python/opengrok_tools/mirror.py:40:0: E0401: Unable to import 'filelock' (import-error)
...
```
due to Python test/lint being skipped. This change fixes that.

skip Python lint if tests are skipped

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerMainTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerRepoTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java

Implementing the idea from https://github.com/oracle/opengrok/issues/3071#issuecomment-600886923

allow -S to specify search path

---

suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java

This change sanitizes the values before putting them to `averageLengths` map in suggester project data, thus preventing the `IllegalArgumentException` exception in `initSearchCountMap()`.

check the value before putting to average key lengths map

---

Dockerfile
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java

This change switches the Docker image to JDK 11. It helps with growing RSS of the Tomcat process (presumably by using different GC implementation).

switch Docker image to JDK 11

---

opengrok-indexer/src/test/java/org/opengrok/indexer/util/TestCasePrinterRule.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/SuggesterService.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/impl/SuggesterServiceImpl.java
opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerTest.java
suggester/src/main/java/org/opengrok/suggest/Suggester.java
suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
suggester/src/test/java/org/opengrok/suggest/SuggesterTest.java

This change fixes the popularity data related test failures tracked by #2704. After making `increaseSearchCount()` testable and adding logging it became evident that the failures stem from bailing on waiting on suggester rebuild.

make suggester popularity tests wait on rebuild

---

dev/before_install.windows

Sometimes Windows builds fail because Chocolatey cannot install a package for some reason (e.g. SVN install fails because a request to sourceforge.net timed out). This will manifest later on in the build. The failures in the install phase should short circuit the build immediately.

exit on failure when installing Choco packages on Windows 

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceHistoryParser.java

Adding -s option to limit the history to only include integrations that affect the file as there can be hundreds of branches listed where where it's not touched and shouldn't be included in the history.
Because the current regex can find p4 path information in the comment sections, only search for P4 paths at the start of the line.

P4 filelog parsing update

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java
opengrok-web/src/main/webapp/js/searchable-option-list-2.0.9.js

Hello,
Please consider for integration this patch to fix the bulk operations that are slow when the project count in the thousands (`Select-All`, `Invert-Selection`, `Clear`) by adding a `Map` by `val()` and also avoiding creating HTML elements when exceeding a defined `maxShow`.
When a bulk operation is in-progress, the `X-Items-Selected` update is deferred and only done at the end of the operation.
I encountered one testing problem which I need advice for: I was running with a thousand test projects, but my system could not actually support a query for all 1000 projects, and it showed a page with just `0`. On hitting Back, the page was not in a consistent state, and `Select-All`, `Invert-Selection`, and `Clear` did not work as expected. Any advice?
Thank you.

Fix #1665 : searchable-option-list bulk operations are slow

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/ruby/RubyAnalyzer.java
opengrok-indexer/src/main/resources/analysis/ruby/RubyProductions.lexh
opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/ruby/RubyXrefTest.java
opengrok-indexer/src/test/resources/analysis/ruby/ruby_xrefres.html
opengrok-indexer/src/test/resources/analysis/ruby/sample.rb

Hello,
Please consider for integration this patch with a fix for a rare uncounted Ruby LOC. I spotted it when studying my Ruby HERE-doc support to apply it for HCL and Terraform.
Thank you.

Fix rare uncounted Ruby LOC

---

plugins/src/main/java/opengrok/auth/plugin/ldap/LdapServer.java
plugins/src/test/java/opengrok/auth/plugin/LdapFacadeTest.java

This change adds more info to the `toString()` method of `LdapServer`. This aids debugging when authorization framework is reloaded or when a server is reconnecting.

add username and timeout to toString()

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java
opengrok-web/src/main/webapp/js/searchable-option-list-2.0.11.js

This fixes the bug I accidentally introduced in 5cac8be5c7 when `maxShow` is in effect and a user clicks × to remove an item. Another item should appear but does not do that.
The meat of this fix is in `_removeSelectionDisplayItem`, which Github-diff shows fine below.
Github-diff is showing a much bigger diff than this patch truly is because its diff algorithm is not finding good alignment from my extraction of `_buildSelectionDisplayItem` from `_addSelectionDisplayItem`, and also it shows the whitespace changes.
Following is a picture of a better diff showing just the straight-forward extraction of `_buildSelectionDisplayItem`:
Thank you.

Bugfix/SOL max-show

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java

This is just to silence the following warning:
```
ctags: Warning: "--file-scope" option is obsolete; use "--extras=+F" instead
```
u-ctags has had the `--extras` option since early 2017.

Use `--extras=+F` instead of --file-scope=yes

---

opengrok-web/src/main/webapp/mast.jsp

In the end I chose the simplest solution rather than juggling CSS (https://stackoverflow.com/questions/5135019/css-opacity-only-to-background-color-not-the-text-on-it) and it makes more sense UI wise I think as it is aligned with the rest (project picker, project listing).

do not highlight path in masthead when Message is in effect

---

opengrok-indexer/src/main/java/org/opengrok/indexer/search/SettingsHelper.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java

Hello,
Please consider for integration this patch to extract `SettingsHelper` from `SearchHelper`. This is from open PR #2732 and is a pre-requisite to a number of ready features, including search context and directory \#LinesLOC.
Thank you.

Extract SettingsHelper from SearchHelper

---

opengrok-tools/requirements.txt
opengrok-tools/src/main/python/opengrok_tools/utils/mirror.py
opengrok-tools/src/test/python/test_mirror.py

In order to make operational aspect easier, it would help if the cause of disabled projects could be propagated to the UI when using the `opengrok-mirror` script. The `disabled: true` behavior will be preserved however if the value is a string, it will be appended to the message. I.e. when running the tool with this config:
```yaml
disabled_command:
command:
- http://localhost:8080/source/api/v1/messages
- POST
- messageLevel: info
duration: PT5M
tags: ['%PROJECT%']
text: disabled project
projects:
opengrok:
disabled: true
opengrok-1.0:
disabled: true
disabled-reason: "foo bar"
```
the `opengrok` project's disabled message will be:
```json
{"messageLevel": "info", "duration": "PT5M", "tags": ["opengrok"], "text": "disabled project"}
```
while `opengrok-1.0`'s will be:
```json …
```

append string to Message text for disabled messages

---

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Filter.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IgnoredDirs.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IgnoredFiles.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/IgnoredNames.java

Hello,
Please consider for integration this minor revision to `@Override match()` instead of creating `Ignore()` methods for `Filter` subclasses, which improves clarity.
Thank you.

Filter subclasses override Match() instead of creating Ignore()

---

plugins/src/main/java/opengrok/auth/plugin/ldap/LdapFacade.java

This fixes the ordering in format string.

fix ordering in LDAP error message

---

opengrok-tools/src/main/python/opengrok_tools/projadm.py
opengrok-tools/src/main/python/opengrok_tools/utils/command.py

This change fixes some equivalence checks (as opposed to identity checks) as reported by lgtm.com.

fix equivalence check in Command class

---

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/executables/ELFAnalyzer.java
opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationFramework.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/ClearCaseRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionAnnotationParser.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
opengrok-indexer/src/main/java/org/opengrok/indexer/search/QueryBuilder.java
opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/LineMatcher.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/LaunderUtil.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/Laundromat.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/ConfigurationTest.java
opengrok-indexer/src/test/java/org/opengrok/indexer/web/LaundromatTest.java
opengrok-web/src/main/java/org/opengrok/web/AuthorizationFilter.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SuggesterController.java
plugins/src/main/java/opengrok/auth/plugin/decoders/OSSOHeaderDecoder.java
suggester/src/main/java/org/opengrok/suggest/query/SuggesterPhraseQuery.java
suggester/src/main/java/org/opengrok/suggest/query/customized/CustomPhraseQuery.java
suggester/src/test/java/org/opengrok/suggest/query/SuggesterPhraseQueryTest.java
suggester/src/test/java/org/opengrok/suggest/query/customized/CustomSloppyPhraseScorerTest.java

- Sanitize several user-supplied strings.
- Fix some scope issues.
- Prohibit XML external access.

Fix another batch of Sonar-identified issues

---

dev/checkstyle/suppressions.xml
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/ConfigurationValueConsumer.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/CloseableReentrantReadWriteLock.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/ResourceLock.java
opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/RuntimeEnvironmentTest.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ConfigurationController.java

Hello,
Please consider for integration this patch to minimize reflection into `Configuration` and shift that logic to `ConfigurationController` where it's more difficult to avoid given the REST-exposure of all configuration through a single web method.
`RuntimeEnvironment` can use functional interfaces to achieve the equivalent of the former reflection without having to identify methods by `String`; thereby we get compile-time checks.
I also imported an auto-disposable wrapper around `Lock` so that try-with-resources can be used instead of try-finally.
Thank you.

Minimize reflection into Configuration

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitTagEntry.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitTagParser.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/TagEntry.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitTagParserTest.java

Hello,
Please consider for integration this patch to use @louie0817 bulk Git log-tags command and to fix the issue @louie0817 identified where for multiple tags for the same Git commit, only one was incorporated and the rest silently dropped.
Thank you.

faster Git tags

---

opengrok-indexer/src/main/java/org/opengrok/indexer/search/QueryBuilder.java
opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java

Hello,
Please consider for integration this patch to redirect directly to a file when a search by `PATH` alone produces a single hit.
I noticed this when clicking on OpenGrok's linking of something file-like or path-like (in a comment for example), and I was taken to a search result with one item. This feels weird given the recent #3053.
Thank you.

Redirect when 1 hit for query of just PATH

---

opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/StringUtils.java
opengrok-indexer/src/test/java/org/opengrok/indexer/util/StringUtilsTest.java

Hello,
Please consider for integration this patch so `PendingFileCompleter` uses the regular OpenGrok `getReadableTime()` instead of `DurationFormatUtils` so that sub-second detail is provided.
`StringUtils.getReadableTime()` is updated to use `StringBuilder` and to avoid some pointless high-precision (e.g., "1 day 35 ms") when for other intervals milliseconds are not shown. It is also updated not just to report "0" for near-instant intervals but "0 ms".
Thank you.

Regular readable time

---

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java
opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java

Hello,
Please consider for integration this patch to add a `--nestingMaximum` switch to help user @sirisan who has a `RepoRepository` setup with two levels of nesting.
Default will continue to be just one level.
Thank you.

Resolve #3010 : add --nestingMaximum switch

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java
opengrok-web/src/main/webapp/js/searchable-option-list-2.0.14.js
opengrok-web/src/main/webapp/js/utils-0.0.36.js

Hello,
Please consider for integration this patch to reset the `#type` radio to Any when one clicks to Clear.
Thank you.

Fix #3028 : on Clear, reset the radio to Any

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java

Hello,
This is a fix for redirect-to-match-offset to accommodate projects where tabs are expanded.
Thank you.

Fix to expand tabs as necessary for matchOffset

---

opengrok-tools/src/main/python/opengrok_tools/scm/perforce.py
opengrok-tools/src/main/python/opengrok_tools/scm/repofactory.py

Although opengrok supports Perforce for history, the opengrok-mirror tool does not support syncing the repositories. It has some prerequisites, but only the same as for the history functionality. 
I am signing on behalf of myself as an individual and no other person or entity, including my employer, has or will have rights with respect my contributions.

Add mirroring support for Perforce repositories

---

opengrok-web/src/main/webapp/list.jsp

Hello,
Please consider for integration this patch to create a `BufferedInputStream` for when `AnalyzerGuru` needs to `mark()` and `reset()` in `--economical` mode.
Thank you.

Fix #3145 : buffer for analysis

---

opengrok-tools/src/main/python/opengrok_tools/scm/git.py
opengrok-tools/src/test/python/test_mirror.py

This fixes a build failure which is preventing a release.
The `git config` command works with both old and new version of Git.

fix incoming check and test for newer git verions

---

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
opengrok-indexer/src/main/java/org/opengrok/indexer/util/CtagsUtil.java

This change should get rid of temporary files left around after killed Ctags processes.
I verified that ctags creates the temporary files with names matching given pattern (on Linux):
```
$ strace -e trace=openat ctags -f - opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/LinkageType.java 2>&1 >/dev/null | grep tags\.
...
openat(AT_FDCWD, "/tmp/tags.Z1MYq4", O_RDWR|O_CREAT|O_EXCL, 0600) = 3
```
and made sure the files are properly cleaned up at the end of the indexing.
Also created entries with name matching the pattern and having extra properties such as:
- non-empty directory
- file owned by `root:root` (while the indexer running as non-root user)
to verify the behavior in case of failure.

delete ctags temp files at the end of indexing

---

opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoriesHelp.java
opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryFactory.java
opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java

Hello,
Please consider for integration this patch to fix `--help ctags` and `--help repos`. As `exitWithHelp()` is called before the runtime environment has had its configuration updated with parsed options, `exitWithHelp()` needs to force in some settings for ctags or repos help.
Also this patch shows any user-disabled repositories with `--help repos`.
Thank you.

Fix --help {ctags,repos}

---

plugins/src/main/java/opengrok/auth/plugin/ldap/LdapFacade.java

This log entry should really be logged with at least WARNING level:
```
28-Aug-2020 08:18:10.680 INFO [http-nio-8080-exec-113] opengrok.auth.plugin.ldap.LdapFacade.lookup Communication error received on server ldaps://foo.bar.com timeout: 3000 username: cn=XXX
,ou=XXX,dc=bar,dc=com, reconnecting to next server.
javax.naming.CommunicationException: LDAP server "ldaps://foo.bar.com" is down
at opengrok.auth.plugin.ldap.LdapServer.search(LdapServer.java:212)
at opengrok.auth.plugin.ldap.LdapServer.search(LdapServer.java:193)
at opengrok.auth.plugin.ldap.LdapFacade.lookup(LdapFacade.java:347)
at opengrok.auth.plugin.ldap.LdapFacade.lookup(LdapFacade.java:381)
at opengrok.auth.plugin.ldap.LdapFacade.lookup(LdapFacade.java:295)
...
```

communication error should be logged with WARNING

---

plugins/src/main/java/opengrok/auth/plugin/ldap/LdapFacade.java
plugins/src/main/java/opengrok/auth/plugin/ldap/LdapServer.java
plugins/src/test/java/opengrok/auth/plugin/LdapServerTest.java
plugins/src/test/java/opengrok/auth/plugin/ldap/LdapFacadeTest.java

With this change `LdapFacade` will check the LDAP servers before using them, namely it will check:
- hostname resolves to IP address
- connect succeeds to the TCP port matching the protocol on all the IP addresses for given hostname

LdapFacade to verify LDAP servers

---

opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java

Replaces all (sans `getPath()` itself) references to `this.path` in `PageConfig` with call to `getPath()`.
This should help #3211.

use getPath() for all this.path references

---

opengrok-tools/src/main/python/opengrok_tools/utils/command.py
opengrok-tools/src/test/python/test_command.py

After adding numeric argument to the `sync.py` configuration, I got this exception:
```
File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
result = (True, func(*args, **kwds))
File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
return list(map(*args))
File "/opengrok/dist/bin/venv/lib/python3.7/site-packages/opengrok_tools/sync.py", line 63, in worker
x.run()
File "/opengrok/dist/bin/venv/lib/python3.7/site-packages/opengrok_tools/utils/commandsequence.py", line 121, in run
args_append=[self.name], excl_subst=True)
File "/opengrok/dist/bin/venv/lib/python3.7/site-packages/opengrok_tools/utils/command.py", line 77, in __init__
self.fill_arg(args_append, args_subst)
File …
```

treat all Command arguments as strings when substituting

---

opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationFramework.java
opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationStack.java

follow-up to #2911 - removes metrics that leak project/stack names. This is necessary because:
- the `/metrics/prometheus` endpoint is currently out in the clear
- per project/stack metrics would cause cardinality explosion (negative pattern for monitoring)

remove project/stack specific authorization metrics

---

plugins/src/main/java/opengrok/auth/plugin/LdapAttrPlugin.java
plugins/src/main/java/opengrok/auth/plugin/LdapFilterPlugin.java
plugins/src/main/java/opengrok/auth/plugin/LdapUserPlugin.java
plugins/src/main/java/opengrok/auth/plugin/ldap/LdapFacade.java
plugins/src/test/java/opengrok/auth/plugin/ldap/LdapFacadeTest.java

Yet another change to logging in LDAP authorization plugins. This will facilitate debugging when LDAP searches/servers/... go south. Overwhelming majority of added log messages have the `FINEST` level.
To use this, the Tomcat `logging.properties` can look like this:
```
handlers = 1request-dumper.org.apache.juli.FileHandler, 1catalina.org.apache.juli.AsyncFileHandler, 2localhost.org.apache.juli.AsyncFileHandler, 3manager.org.apache.juli.AsyncFileHandler, 4host-manager.org.apache.juli.AsyncFileHandler, java.util.logging.ConsoleHandler
.handlers = 1catalina.org.apache.juli.AsyncFileHandler, java.util.logging.ConsoleHandler
...
java.util.logging.ConsoleHandler.level = FINEST
java.util.logging.ConsoleHandler.formatter = org.apache.juli.OneLineFormatter
opengrok.auth.level = FINEST
```

add debug logging to LDAP authorization plugins

---

Dockerfile
docker/README.md
docker/index.sh
docker/start.sh

This allows the user to correctly specify the URL subfolder that OpenGrok should run on,
and the container appropriately reacts without having to fully rebuild it.
Fixes: #3153

docker: Fix OPENGROK_WEBAPP_CONTEXT behaviour.

---

opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationFramework.java
opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/WatchDogService.java
opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginClassLoader.java
opengrok-indexer/src/main/java/org/opengrok/indexer/search/SearchEngine.java
opengrok-indexer/src/test/java/org/opengrok/indexer/authorization/AuthorizationFrameworkReloadTest.java
plugins/src/main/java/opengrok/auth/plugin/ldap/LdapFacade.java

This changes metric handling in `AuthorizationFramework` to use tags. Looks like this:
```
$ curl -s -X GET http://localhost:8080/source/metrics/prometheus | grep ^auth
authorization_latency_seconds_max{outcome="negative",} 0.0
authorization_latency_seconds_max{outcome="positive",} 0.0
authorization_latency_seconds_count{outcome="negative",} 0.0
authorization_latency_seconds_sum{outcome="negative",} 0.0
authorization_latency_seconds_count{outcome="positive",} 83.0
authorization_latency_seconds_sum{outcome="positive",} 0.001039
authorization_sessions_invalidated_total 0.0
authorization_stack_reload_total 0.0
authorization_cache_total{what="misses",} 83.0
authorization_cache_total{what="hits",} 58.0
```
which allows for easier creation of all-in-one graphs just like they are available for …

use tags for metrics

---

opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/impl/SuggesterServiceImpl.java
suggester/pom.xml
suggester/src/main/java/org/opengrok/suggest/Suggester.java
suggester/src/test/java/org/opengrok/suggest/SuggesterTest.java

Add basic suggester meters:
```
suggester_init_latency_seconds_count 1.0
suggester_init_latency_seconds_sum 0.035
suggester_init_latency_seconds_max 0.035
suggester_rebuild_latency_seconds_max 0.0
suggester_rebuild_latency_seconds_count 0.0
suggester_rebuild_latency_seconds_sum 0.0
suggester_rebuild_total 0.0
```

add suggester related meters

---

plugins/src/main/java/opengrok/auth/plugin/LdapAttrPlugin.java

Seeing failures of `LdapAttrPlugin` in the log where log entries referenced `User` object instead of `LdapUser` object:
```
21-Aug-2020 16:31:47.512 WARNING [http-nio-8080-exec-92] opengrok.auth.plugin.LdapAttrPlugin.fillSession empty records or attribute values ou for user User{id=foo@bar.com, username=null, cookieTimestamp=null, timeouted=false, attrs={}}
```
made me realize this is the wrong user to log as `LdapAttrPlugin` deals with `LdapUser` when getting the attribute.
While at it, I followed IDEA's advice to refactor this part to avoid the else branch.

changes to LdapAttrPlugin
