src/org/opensolaris/opengrok/web/PageConfig.java, web/httpheader.jspf, web/rss.jsp
=> add RSS feed autodetection

web/default/print.css, web/default/style.css, web/polished/print.css
=> fix placement of the RSS XML logo

src/org/opensolaris/opengrok/history/DirectoryHistoryReader.java, web/rss.jsp
fill revision in DirectoryHistoryReader
fixes #896
fixes #891
=> unify RSS title for directory and file

web/utils.js
Comparing colors is different for each browser.
=> Patch highlight color for IE.

src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java
Fix for #902 
It's my first touch on lucene, so I hope it's arranged correctly.
But sorting by date/path started to work again with this fix.
=> Fix sorting by date/fullpath

src/org/opensolaris/opengrok/analysis/Ctags.java
=> Fix ctags Scala support.

build.xml, src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java, src/org/opensolaris/opengrok/analysis/Ctags.java, src/org/opensolaris/opengrok/analysis/haskell/Consts.java, src/org/opensolaris/opengrok/analysis/haskell/HaskellAnalyzer.java, src/org/opensolaris/opengrok/analysis/haskell/HaskellAnalyzerFactory.java, src/org/opensolaris/opengrok/analysis/haskell/HaskellSymbolTokenizer.lex, src/org/opensolaris/opengrok/analysis/haskell/HaskellXref.lex, src/org/opensolaris/opengrok/analysis/perl/PerlXref.lex, src/org/opensolaris/opengrok/history/HistoryGuru.java, src/org/opensolaris/opengrok/index/IndexDatabase.java, src/org/opensolaris/opengrok/index/Indexer.java, src/org/opensolaris/opengrok/web/DirectoryListing.java, src/org/opensolaris/opengrok/web/SearchHelper.java, web/help.jsp, web/menu.jspf
=> Haskell support

src/org/opensolaris/opengrok/web/PageConfig.java
=> fallback to newer file if genre for older file is null

OpenGrok, src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/history/FileHistoryCache.java, test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java, test/org/opensolaris/opengrok/history/FileHistoryCacheTest.java
and also rename OPENGROK_REMOTE_REPOS variable in OpenGrok shell script.
=> change behavior of tunable

.travis.yml, README.txt, build.xml, nbproject/project.properties, opengrok-web-nbproject/nbproject/project.properties, platform/solaris/ips/create.sh, pom.xml, src/org/opensolaris/opengrok/analysis/Ctags.java
oh yeah ... and emma is dead :(
long live jacoco!
=> jdk8 , fix ctag definitions to work on solaris too

src/org/opensolaris/opengrok/history/HistoryGuru.java, src/org/opensolaris/opengrok/index/CommandLineOptions.java, src/org/opensolaris/opengrok/index/IgnoredDirs.java, src/org/opensolaris/opengrok/index/IgnoredFiles.java, src/org/opensolaris/opengrok/index/IgnoredNames.java, test/org/opensolaris/opengrok/index/IgnoredNamesTest.java
=> split ignoredNames into list for files and directories

OpenGrok
=> escape opengrok jar file

src/org/opensolaris/opengrok/analysis/sh/ShAnalyzerFactory.java
Yes, I accept OCA for this patch
=> Add mk to "Shell script" group

README.txt
=> document partial reindex steps

src/org/opensolaris/opengrok/web/DirectoryListing.java, src/org/opensolaris/opengrok/web/Util.java, test/org/opensolaris/opengrok/web/UtilTest.java, web/default/style.css, web/httpheader.jspf, web/jquery.tablesorter-2.0.5b.js, web/offwhite/style.css, web/polished/style.css
fixes #831
Not sure what to do about licensing. tablesorter is dual licenced - either MIT or GPL.
=> add JQuery tablesorter for sorting directory listing table

build.xml, src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java, src/org/opensolaris/opengrok/analysis/Ctags.java, src/org/opensolaris/opengrok/analysis/golang/Consts.java, src/org/opensolaris/opengrok/analysis/golang/GolangAnalyzer.java, src/org/opensolaris/opengrok/analysis/golang/GolangAnalyzerFactory.java, src/org/opensolaris/opengrok/analysis/golang/GolangSymbolTokenizer.lex, src/org/opensolaris/opengrok/analysis/golang/GolangXref.lex
=> Add Golang support.

web/default/style.css, web/offwhite/style.css, web/polished/style.css
This uses CSS to size and position the elements on the page so you can still scroll when there is no JS enabled
=> Allow scrolling on long source files with no JS enabled

web/default/style.css, web/offwhite/style.css, web/polished/style.css
=> Revert "Allow scrolling on long source files with no JS enabled"

src/org/opensolaris/opengrok/analysis/Ctags.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
=> Don't use user-defined Golang mapping command options with Universal ctags

src/org/opensolaris/opengrok/search/Results.java, src/org/opensolaris/opengrok/web/PageConfig.java, src/org/opensolaris/opengrok/web/SearchHelper.java, web/WEB-INF/web.xml, web/default/print.css, web/default/style.css, web/offwhite/print.css, web/offwhite/style.css, web/polished/print.css, web/polished/style.css, web/search.jsp
fixes #590
previous discussion in #996
=> display last modified date in search results

src/org/opensolaris/opengrok/web/Util.java, web/default/style.css, web/offwhite/style.css, web/polished/style.css, web/utils.js
=> Colorization of changesets by their age

src/org/opensolaris/opengrok/index/IndexDatabase.java
=> Introducing static comparator in IndexDatabase.java

src/org/opensolaris/opengrok/index/IndexDatabase.java
Comparator introduced in #1012
=> Fixing compilation warnings for static comparator

OpenGrok
Minor changes to support tomcat 8 as well. Works with debian/ubuntu tomcat 8 package (currently 8.0.26-1)
=> Tomcat 8 support

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/Group.java, src/org/opensolaris/opengrok/configuration/Project.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/ProjectHelper.java, test/org/opensolaris/opengrok/configuration/GroupTest.java, test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java, web/default/print.css, web/default/style.css, web/menu.jspf, web/offwhite/print.css, web/offwhite/style.css, web/polished/print.css, web/polished/style.css, web/repos.jspf, web/utils.js
I'm getting closer to #480, which I suppose is a prerequisite of the authorization layer.
Groups are taken from configuration file (example below) which is given to the jar run (-W option) and it is therefore propagated to the web application through the socket listener (then it lives in the main configuration file). Project can be in multiple groups.
A new class ProjectHelper is introduced to wrap operations around env.projects so that it can be easily changed later to support authorizator filtering of projects or groups. 
There are couple of screenshots:
1) Groups as a list on the main page. User can click on them and their content gets expanded.
2) UI change of the selectbox to support top level (HTML restriction) groups
3) expanded groups
Working demo available …
=> Implementation of project groupings

README.txt
I added a short note to README about ULIMIT
=> README updates to the tuning section for ULIMIT

web/default/style.css, web/diff.jsp, web/offwhite/style.css, web/polished/style.css, web/utils.js
Fixes #574
A simple navigation box which provides quick jumping through chunks of changed code. One can either click buttons in the box or press 'n' (next) or 'b' (back) keys for jumping.
Demo available:
http://virtual99.cz.oracle.com/diffs/
or
[Direct example](http://virtual99.cz.oracle.com/diffs/diff/sources/OpenGrok/README.txt?r2=%2Fsources%2FOpenGrok%2FREADME.txt%40a58461db&r1=%2Fsources%2FOpenGrok%2FREADME.txt%40d961aa46)
Screenshots:
Tested in IE9, Chrome 46.0 and Firefox 40.0.3.
=> Diff jumper

web/default/style.css, web/offwhite/style.css, web/polished/style.css, web/utils.js
I've implemented just a little feature which is similar to line selection on Github. By clicking on line number while holding shift key one can select range of lines. Those are appended to the url in the hash; so the url can be sent to another person.
Demo is available here:
http://virtual99.cz.oracle.com/lines/
Screenshot:
Tested in IE9, Chrome 46.0 and Firefox 40.0.3.
=> Line highlighter

web/utils.js
Disclosure: I only tested this on Linux/Chrome.
=> Fix #690 Navigate when line numbers are hidden.

web/utils.js
=> Don't add an empty hash into url

src/org/opensolaris/opengrok/index/IndexDatabase.java
=> log files ignored by the indexer

src/org/opensolaris/opengrok/configuration/Project.java, test/org/opensolaris/opengrok/configuration/ProjectTest.java
=> change getProject() to use longest prefix matching

doc/authorization_howto.txt, doc/groups_howto.txt
Documentation for using
1) project groupings #1029 and
2) authorization framework #1083
=> Adding a documentation for groupings and authorization

src/org/opensolaris/opengrok/web/PageConfig.java, web/list.jsp, web/projects.jspf, web/search.jsp
fixes #1064 
and may fix related issues
Solution is compatible with tomcat 9 (tested).
=> fixing inconsistent behaviour of opengrok cookie

src/org/opensolaris/opengrok/index/IndexDatabase.java
=> when logging ignored files, use FINER log level

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/history/BazaarRepository.java, src/org/opensolaris/opengrok/history/GitHistoryParser.java, src/org/opensolaris/opengrok/history/GitRepository.java, src/org/opensolaris/opengrok/history/MercurialRepository.java, src/org/opensolaris/opengrok/history/MonotoneRepository.java, src/org/opensolaris/opengrok/history/SSCMRepository.java, src/org/opensolaris/opengrok/history/SubversionRepository.java, src/org/opensolaris/opengrok/util/Executor.java
=> use infinite timeout for initial history index

src/org/opensolaris/opengrok/history/BazaarRepository.java, src/org/opensolaris/opengrok/history/MercurialRepository.java, src/org/opensolaris/opengrok/history/RepositoryFactory.java
=> make parent/branch logging less aggressive

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java
=> fixing javadoc error

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java, src/org/opensolaris/opengrok/authorization/AuthorizationPluginClassLoader.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
=> Implementing cache and class resolution

web/default/print.css, web/offwhite/print.css, web/polished/print.css
fixes #1108 
print styles were forgotten with the new scopes css styles
=> adding scopes css

build.xml
mentioned in #1131
I'm not sure if this is the correct way but I tested it with netbeans and jenkins builds
=> adding sample plugins to maven build

web/default/style.css, web/offwhite/style.css, web/polished/style.css
implementing #1099 with the orange pallete
internal demo:
http://virtual99.cz.oracle.com/annotations
=> changing the color palette

web/js/repos.js, web/js/utils.js
improves #1140
after discussion with @vladak we decided to hide the footer as well
=> hiding the footer upon search click

web/js/utils.js
I've reworked the spaces plugin so it's more deterministic. Now it's based on visible elements on the screen and it automatically inserts a spaces into those.
**IMPORTANT: This plugin is strictly dependent on ascending order of lines
and on their attribute "name". It performs a binary search which boosts performance
of this plugin for really long files.**
Tested in Firefox 39, IE 9, Chrome 52.
Because of the binary search it also performs quite fine for large files
Example with ~130k lines, start means the starting line, end the ending line in the viewport
```
handleScrollEvent: timer started utils.js:503
Object { start: 133956, end: 133981 } utils.js:540:17
handleScrollEvent: 178.88ms utils.js:541
handleScrollEvent: timer started utils.js:503
Object { start: 133952, end: 133981 } …
```
=> reworking the spaces plugin

src/org/opensolaris/opengrok/web/PageConfig.java
- allow to checkout repositories with paths containing "@" (e.g.  sources/OpenGrok@master, sources/OpenGrok@0.12-stable)
=> Allow "@" in checkout paths

web/default/style.css, web/js/utils.js, web/offwhite/style.css, web/polished/style.css
The plugin didn't process the embedded readme files when you list the directory with the readme file. Now it also takes care about those.
enhances #1150
=> spaces plugin now works on embedded readme

web/js/searchable-option-list-2.0.2.js
I forgot the unused undefined variable in the selection plugin. Sorry.
=> fixing undefined variable

web/mast.jsp
=> fixing annotation link in history view

web/default/print.css, web/default/style.css, web/help.jsp, web/offwhite/print.css, web/offwhite/style.css, web/polished/print.css, web/polished/style.css
=> Reformat CSS.

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/PageConfig.java, src/org/opensolaris/opengrok/web/ProjectHelper.java, test/org/opensolaris/opengrok/web/ProjectHelperTest.java, test/org/opensolaris/opengrok/web/ProjectHelperTestBase.java
fixes #1184 
After #1029 the ui wasn't reflecting the change of configurations because it rather cached the old values. This is now fixed.
=> ui reflects the changes of environment

OpenGrok, web/WEB-INF/web.xml
Adds support for Resin to the OpenGrok script and web.xml as noted in #1178.
=> Support for Resin

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, test/org/opensolaris/opengrok/configuration/ProjectTest.java
=> close only SearcherManagers of projects which are gone upon reindex

web/default/style.css, web/menu.jspf, web/offwhite/style.css, web/polished/style.css
=> forcing the search controls to stay right below the search form

tools/Groups
Now the script correctly uses the `OPENGROK_DISTRIBUTION_BASE` variable to determine where is the `opengrok.jar` file.
The rest of the colours are just format change. I don't know why it was like this before.
=> Groups script fix

src/org/opensolaris/opengrok/history/GitRepository.java
=> fixing javadoc for GitRepository

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java
=> making the message limit a tunnable

web/history.jsp, web/js/utils.js
fixes #1202
On top of it there is some js cleanup and rearrangement and little more verbose comments in the source code.
Also it solves the first point from #1078
=> selecting from history does not reload the page

build.xml
fixes #1225
Also fixes permissions for the OpenGrok script.
=> include Groups and Messages scripts

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/configuration/SuperIndexSearcher.java, src/org/opensolaris/opengrok/search/SearchEngine.java, src/org/opensolaris/opengrok/web/SearchHelper.java, web/search.jsp
fixes #1207
It seems this works. Tested by repeating multiple searches (with positive and none hits), interleaved with reindex.
=> store reference to SearcherManager in IndexSearcher super-class

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/search/Results.java, src/org/opensolaris/opengrok/web/Util.java, tools/Messages, web/default/style.css, web/js/utils.js, web/mast.jsp, web/menu.jspf, web/offwhite/style.css, web/polished/style.css, web/repos.jspf
1. Messages script now has both long and short options
2. Tag "main" is displayed whenever browsing a project (but not on the homepage)
=> Messages options

web/menu.jspf
=> fixing search action to the search servlet

src/org/opensolaris/opengrok/analysis/JFlexXref.java, web/default/style.css, web/js/utils.js, web/mast.jsp, web/offwhite/style.css, web/polished/style.css
Refactoring the window plugin - now it's easy to create a window with less code.
Moving scopes into separated window instead of the grey panel.
Try internal demo [here](http://virtual99.cz.oracle.com/scopes/xref/OpenGrok/src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java) - experiment with navigate also.
=> Scopes window

build.xml, src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java, src/org/opensolaris/opengrok/analysis/Ctags.java, src/org/opensolaris/opengrok/analysis/rust/Consts.java, src/org/opensolaris/opengrok/analysis/rust/RustAnalyzer.java, src/org/opensolaris/opengrok/analysis/rust/RustAnalyzerFactory.java, src/org/opensolaris/opengrok/analysis/rust/RustSymbolTokenizer.lex, src/org/opensolaris/opengrok/analysis/rust/RustXref.lex, test/org/opensolaris/opengrok/search/SearchTest.java, testdata/sources/rust/main.rs
Adding support for the Rust programming language. Mostly based (read copy&paste) on the existing Python and Java implementations.
=> Add support for the Rust programming language

web/default/style.css, web/offwhite/style.css, web/polished/style.css
=> limiting the width of the scopes window

OpenGrok
Definitely was updated this year
=> fixing OpenGrok shell wrapper copyright information

web/repos.jspf
=> merging scm type and parent column into one

src/org/opensolaris/opengrok/history/GitRepository.java
fixed process timeout & exit code
=> adding waitfor for the current branch process

src/org/opensolaris/opengrok/history/MercurialRepository.java
following #1262 for mercurial repos
=> adding current version info into mercurial repository

web/diff.jsp
fixes #549 
Adding a link to downloadable diff file for the given revisions.
Internal demo soon (+30 mins) [here](http://virtual99.cz.oracle.com/diffs)
=> allowing users to download the diff

web/js/diff.js
fixes #1290
Nothing new. Using the window plugin for the diff jumper.
=> converting diff jumper to the new window style

web/js/utils.js, web/mast.jsp
fixes #1289 
Just a new look for the old navigation window. Automatically moves down when scopes are visible (but that isn't new neither).
=> converting navigate window into the new window plugin

web/default/style.css, web/js/utils.js, web/offwhite/style.css, web/polished/style.css
1. detecting if xref has no definitions
fixes #1302
2. auto resizing the window on the first load
=> Display empty navigation window if there are no definitions

web/js/utils.js
On a long page the message window position was wrongly determined, ignoring the actuall scrolled height.
I verified the intelligence window works as well.
=> fixing mouse location for scrolled page

src/org/opensolaris/opengrok/util/XmlEofInputStream.java
The artificial EOF was not designed correctly and it didn't bother to check the real EOF.
=> correct handling of the real EOF

src/org/opensolaris/opengrok/web/DirectoryListing.java, src/org/opensolaris/opengrok/web/PageConfig.java, web/default/style.css, web/history.jsp, web/index.jsp, web/list.jsp, web/mast.jsp, web/minisearch.jspf, web/offwhite/style.css, web/pageheader.jspf, web/polished/style.css, web/search.jsp
makes the UI a bit more tidy and uniform across different view
=> Header cleanup

web/default/style.css, web/offwhite/style.css, web/polished/style.css
=> making the history slider look the same as the search slider

web/default/style.css, web/offwhite/style.css, web/polished/style.css
stabilizing the height if the listing header so it does not get expanded when the tablesorter loads
=> stabilizing the height if the listing header

web/httpheader.jspf, web/js/utils-0.0.2.js, web/minisearch.jspf
=> adding a link to toggle scopes window in xref

test/org/opensolaris/opengrok/web/DirectoryListingTest.java
=> test href attribute of the a element

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/SearchHelper.java, web/error.jsp, web/search.jsp
=> set HTTP error codes for error conditions

test/org/opensolaris/opengrok/history/FileHistoryCacheTest.java
=> enable renamed file handling in proper way

src/org/opensolaris/opengrok/web/PageConfig.java
=> add list of projects to the title of the search page

src/org/opensolaris/opengrok/history/HistoryGuru.java, src/org/opensolaris/opengrok/history/RepositoryFactory.java
=> parallelize invalidateRepositories()

web/httpheader.jspf, web/js/utils-0.0.4.js
=> fixing missing colon for mercurial changesets in annotation

src/org/opensolaris/opengrok/index/IgnoredDirs.java, src/org/opensolaris/opengrok/index/IgnoredFiles.java, src/org/opensolaris/opengrok/index/IgnoredNames.java, src/org/opensolaris/opengrok/index/Indexer.java, test/org/opensolaris/opengrok/index/IgnoredNamesTest.java
=> fix encoding/decoding of IgnoredNames objects

web/httpheader.jspf, web/js/utils-0.0.5.js
Implementing the first part of #1380
=> changing the project picker label

web/default/style.css, web/offwhite/style.css, web/polished/style.css
=> changing the scopes color to darkgray

web/default/style.css, web/menu.jspf, web/offwhite/style.css, web/polished/style.css
=> same font size for the help button

tools/Messages
=> reduce max Java heap size to 32 MB

src/org/opensolaris/opengrok/web/DirectoryListing.java
=> check null pointer returned from dir.list()

src/org/opensolaris/opengrok/util/Executor.java
possibly fixes #1407 
This correctly terminates the timer thread. Hope to see that it will fix #1407
=> always terminate the timer thread

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/configuration/messages/ConfigMessage.java, src/org/opensolaris/opengrok/configuration/messages/Message.java, src/org/opensolaris/opengrok/configuration/messages/Messages.java, src/org/opensolaris/opengrok/index/Indexer.java, test/org/opensolaris/opengrok/configuration/messages/ConfigMessageTest.java, test/org/opensolaris/opengrok/configuration/messages/MessagesTest.java, tools/Messages
=> turn configuration update into Message

src/org/opensolaris/opengrok/configuration/Groups.java, tools/Groups
The empty configuration can be used as a base for creating the read-only
configuration
=> Allowing users to generate empty configuration with Groups command.

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/search/Results.java, src/org/opensolaris/opengrok/web/PageConfig.java, src/org/opensolaris/opengrok/web/SearchHelper.java, test/org/opensolaris/opengrok/web/SearchHelperTest.java, web/WEB-INF/web.xml, web/httpheader.jspf, web/js/utils-0.0.6.js, web/search.jsp
fixes #1363 
- moving last display info into tooltip
- moving the tunable into configuration
- changing the test (a member variable in search helper is missing)
=> moving last display information into tooltip

web/repos.jspf
=> hiding empty groups

src/org/opensolaris/opengrok/web/Util.java, test/org/opensolaris/opengrok/web/UtilTest.java, web/repos.jspf
=> generating a link if parent is a http url

src/org/opensolaris/opengrok/web/Util.java, test/org/opensolaris/opengrok/web/UtilTest.java
It didn't handle the url special chars.
=> escaping uri in linkify()

README.txt, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/configuration/messages/AbortMessage.java, src/org/opensolaris/opengrok/configuration/messages/ConfigMessage.java, src/org/opensolaris/opengrok/configuration/messages/Message.java, src/org/opensolaris/opengrok/configuration/messages/Messages.java, src/org/opensolaris/opengrok/configuration/messages/NormalMessage.java, src/org/opensolaris/opengrok/configuration/messages/StatsMessage.java, test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java, test/org/opensolaris/opengrok/configuration/messages/AbortMessageTest.java, test/org/opensolaris/opengrok/configuration/messages/ConfigMessageTest.java, test/org/opensolaris/opengrok/configuration/messages/ExpirationNormalMessageTest.java, test/org/opensolaris/opengrok/configuration/messages/MessageTest.java, test/org/opensolaris/opengrok/configuration/messages/NormalMessageTest.java, test/org/opensolaris/opengrok/configuration/messages/StatsMessageTest.java, tools/Messages
- oop design for validating custom types
- basic test coverage
- filling the documentation with the new config type
=> validate method for validating the specific message type

README.txt, src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/configuration/messages/RefreshMessage.java, src/org/opensolaris/opengrok/index/Indexer.java, test/org/opensolaris/opengrok/configuration/messages/RefreshMessageTest.java, tools/Messages
=> refresh SearcherManagers after partial reindex

src/org/opensolaris/opengrok/history/AccuRevRepository.java
=> Accurev Repository Update Enhancement

src/org/opensolaris/opengrok/analysis/Ctags.java
=> log exit value from ctags

web/history.jsp
=> adding query string into revision url

src/org/opensolaris/opengrok/web/Util.java, test/org/opensolaris/opengrok/web/UtilTest.java
+ removing non existent import
```java
-<%@page import="org.jcp.xml.dsig.internal.dom.Utils"%>
```
I have no idea how that came there.
=> escaping titles in linkify()

src/org/opensolaris/opengrok/history/RCSRepository.java, test/org/opensolaris/opengrok/condition/RepositoryInstalled.java, test/org/opensolaris/opengrok/history/RCSRepositoryTest.java
=> better RCS repository detection

src/org/opensolaris/opengrok/web/Util.java
=> adding first and last page into slider

src/org/opensolaris/opengrok/configuration/Group.java, test/org/opensolaris/opengrok/configuration/GroupTest.java
=> Invalid pattern in group always throws an exception

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/PageConfig.java, test/org/opensolaris/opengrok/configuration/messages/StatsMessageTest.java, web/foot.jspf, web/index.jsp
Created New PR since I messed up previous one
=> Web app start fix when config file is missing #1413

src/org/opensolaris/opengrok/index/Indexer.java
=> adding port number for outgoing configuration

web/diff.jsp
fixes #1414
The problem was that there was already some output in the response so I moved the output block for downloading before any actual output on the diff page.
=> moving diff download block before any output in request's response

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/index/CommandLineOptions.java, src/org/opensolaris/opengrok/index/Indexer.java, src/org/opensolaris/opengrok/web/PageConfig.java, test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java, test/org/opensolaris/opengrok/index/IndexDatabaseTest.java, test/org/opensolaris/opengrok/index/IndexerTest.java, test/org/opensolaris/opengrok/search/SearchEngineTest.java, test/org/opensolaris/opengrok/search/SearchTest.java, test/org/opensolaris/opengrok/web/SearchHelperTest.java
Implements enhancement proposed in #1357 and also back in old days in #28
=> using multiple default projects

web/default/style.css, web/menu.jspf, web/offwhite/style.css, web/polished/style.css
=> move project picker to the query table

OpenGrok, README.txt, doc/groups_howto.txt, tools/Groups
=> READ_XML_CONFIGURATION -> OPENGROK_READ_XML_CONFIGURATION

web/enoent.jsp, web/error.jsp, web/help.jsp
=> add missing titles

web/diff.jsp, web/foot.jspf, web/history.jsp, web/httpheader.jspf, web/index.jsp, web/js/utils-0.0.7.js, web/mast.jsp, web/menu.jspf, web/minisearch.jspf, web/repos.jspf
fixes #1455
fixes #1490
related to #1488
I double checked all jsps; this configuration appears to work.
Summary:
1. for the `document` variables I used functions so that the inner block does not need to be defined in advance
2. moved the js to footer
3. fixed observed problem described in #1490 
4. merged `$(document).ready()` calls to single call
=> moving javascripts to the page footer

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/WebappListener.java, test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java, test/org/opensolaris/opengrok/web/StatisticsTest.java
=> Eliminating the NPE when using statistics file

src/org/opensolaris/opengrok/web/PageConfig.java, test/org/opensolaris/opengrok/web/PageConfigTest.java, web/enoent.jsp
adding missing bits to the previous pr #1486 based on [the conversation](https://github.com/OpenGrok/OpenGrok/pull/1486#discussion_r108183148)
=> adding checkSourceRootExistence() in enoent.jsp + tests

OpenGrok, src/org/opensolaris/opengrok/index/CommandLineOptions.java, src/org/opensolaris/opengrok/index/Indexer.java
=> add option to disable handling renamed files history

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java, src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/WebappListener.java, web/WEB-INF/web.xml
=> Authorization framework configuration in configuration.xml

src/org/opensolaris/opengrok/search/SearchEngine.java, src/org/opensolaris/opengrok/web/JSONSearchServlet.java
- add ability to restrict searches to specific projects
- use application/json content type
=> Json servlet updates

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/history/BazaarRepository.java, src/org/opensolaris/opengrok/history/BitKeeperRepository.java, src/org/opensolaris/opengrok/history/CVSRepository.java, src/org/opensolaris/opengrok/history/GitRepository.java, src/org/opensolaris/opengrok/history/HistoryGuru.java, src/org/opensolaris/opengrok/history/MercurialRepository.java, src/org/opensolaris/opengrok/history/PerforceRepository.java, src/org/opensolaris/opengrok/history/RCSRepository.java, src/org/opensolaris/opengrok/history/RazorRepository.java, src/org/opensolaris/opengrok/history/RepoRepository.java, src/org/opensolaris/opengrok/history/Repository.java, src/org/opensolaris/opengrok/history/RepositoryFactory.java, src/org/opensolaris/opengrok/history/SCCSRepository.java, src/org/opensolaris/opengrok/history/SubversionRepository.java, src/org/opensolaris/opengrok/index/IgnoredDirs.java, src/org/opensolaris/opengrok/index/IgnoredFiles.java, src/org/opensolaris/opengrok/index/Indexer.java, test/org/opensolaris/opengrok/history/HistoryGuruTest.java, test/org/opensolaris/opengrok/history/PerforceRepositoryTest.java, test/org/opensolaris/opengrok/index/IgnoredNamesTest.java, test/org/opensolaris/opengrok/index/IndexerTest.java, test/org/opensolaris/opengrok/search/SearchEngineTest.java, test/org/opensolaris/opengrok/util/FileUtilities.java, test/org/opensolaris/opengrok/web/DirectoryListingTest.java
first step/groundwork for solving #1458 (once again)
=> spread out configuration of ignored files/dirs to repositories

opengrok-indexer/build.xml
=> fix mvn .bk cleanup

src/org/opensolaris/opengrok/configuration/Configuration.java, web/history.jsp
=> Remove default settings from history.jsp

OpenGrok
=> EXUBERANT_CTAGS -> OPENGROK_CTAGS

web/minisearch.jspf
=> fixing regression of #1493 by removing the extra bracket

web/default/style.css, web/foot.jspf, web/js/utils-0.0.9.js, web/menu.jspf, web/offwhite/style.css, web/polished/style.css
=> adding a select picker to the file type

src/org/opensolaris/opengrok/web/Util.java, test/org/opensolaris/opengrok/web/UtilTest.java, web/history.jsp
fixes #1515
fixes #1517
also together with #1531 (**needs to be merged**) fixes #1508
=> logging exceptions in linkify + support urls without the hostname

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/messages/ConfigMessage.java, test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java, test/org/opensolaris/opengrok/configuration/messages/ConfigMessageTest.java
Approaches #1508 but it's not complete for the urls. However as stated in #1517 it would be nice if the urls did not include the hostname so the checks for it are not possible
For the
- bugPattern it validates the pattern and if it contains at least one capture group
- reviewPattern it validates the pattern and if it contains at least one capture group
=> Configuration checks

web/js/utils-0.0.9.js
=> checking if the line element taken from the hash exists in the page

src/org/opensolaris/opengrok/history/MercurialRepository.java
=> ignore .hgignore

src/org/opensolaris/opengrok/web/DirectoryListing.java, test/org/opensolaris/opengrok/web/DirectoryListingTest.java
=> check ignored entries for simplified directory listing

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java
**This expects the #1525 to be merged as it already implements the new interface.**
I will rebase this when it gets merged.
This change is about:
- support inheritance in plugin classes (currently the super class implementing the interface is not recognized)
- do not necessarily create instances of abstract classes (because it does not work of course)
=> Support inheritance in plugin classes

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java, src/org/opensolaris/opengrok/configuration/Group.java, src/org/opensolaris/opengrok/web/Scripts.java
=> fixing javadoc errors

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java, src/org/opensolaris/opengrok/web/Statistics.java, src/org/opensolaris/opengrok/web/StatisticsFilter.java
this will provide some info measurements for the authorization performance
=> adding basic stats for authorization decisions

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java, src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/Groups.java, src/org/opensolaris/opengrok/configuration/Project.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/index/IndexDatabase.java, src/org/opensolaris/opengrok/index/Indexer.java, src/org/opensolaris/opengrok/search/SearchEngine.java, src/org/opensolaris/opengrok/web/PageConfig.java, src/org/opensolaris/opengrok/web/ProjectHelper.java, src/org/opensolaris/opengrok/web/Statistics.java, src/org/opensolaris/opengrok/web/StatisticsFilter.java, test/org/opensolaris/opengrok/authorization/AuthorizationFrameworkTest.java, test/org/opensolaris/opengrok/authorization/AuthorizationPluginClassLoaderTest.java, test/org/opensolaris/opengrok/configuration/GroupTest.java, test/org/opensolaris/opengrok/configuration/ProjectTest.java, test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java, test/org/opensolaris/opengrok/index/IndexerTest.java, test/org/opensolaris/opengrok/web/ProjectHelperExtendedTest.java, test/org/opensolaris/opengrok/web/ProjectHelperTest.java, test/org/opensolaris/opengrok/web/ProjectHelperTestBase.java
=> check project name exactly in Project.getByName()

src/org/opensolaris/opengrok/history/SubversionRepository.java
=> remove --trust-server-cert option

src/org/opensolaris/opengrok/authorization/AuthorizationEntity.java, src/org/opensolaris/opengrok/authorization/AuthorizationPlugin.java, src/org/opensolaris/opengrok/authorization/AuthorizationStack.java, test/org/opensolaris/opengrok/authorization/AuthorizationStackTest.java
The authorization was not performed for subgroups or subprojects of a configured group for a plugin. The same code as it was in the stack needed to be in the plugin.
=> adding the group discovery for forGroups also into the plugin

README.txt, src/org/opensolaris/opengrok/configuration/Configuration.java, web/WEB-INF/web.xml, web/eforbidden.jsp
=> let the user to customize the 403 error page

web/history.jsp
=> displaying 404 not found for no history

src/org/opensolaris/opengrok/web/PageConfig.java
=> adding a forced redirect for url /xref to /xref/

src/org/opensolaris/opengrok/authorization/AuthorizationEntity.java, src/org/opensolaris/opengrok/authorization/AuthorizationPlugin.java, src/org/opensolaris/opengrok/authorization/AuthorizationStack.java, src/org/opensolaris/opengrok/web/Util.java
May be useful this kind of visualization
=> printing the authorization status on status.jsp

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java
=> clearing the stack in removeAll method

src/org/opensolaris/opengrok/configuration/Group.java, src/org/opensolaris/opengrok/configuration/Groups.java, test/org/opensolaris/opengrok/authorization/AuthorizationFrameworkTest.java, test/org/opensolaris/opengrok/authorization/AuthorizationPluginClassLoaderTest.java, test/org/opensolaris/opengrok/configuration/GroupTest.java, test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java, test/org/opensolaris/opengrok/web/ProjectHelperTest.java, test/org/opensolaris/opengrok/web/ProjectHelperTestBase.java
=> adding a constructor with name and optional pattern for a group

src/org/opensolaris/opengrok/web/ProjectHelper.java
=> refactoring the private variables of project helper to be more readable

README.txt, src/org/opensolaris/opengrok/configuration/messages/ConfigMessage.java
=> adding a tag to the config message to reload all authorization plugins

src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/PageConfig.java, src/org/opensolaris/opengrok/web/Util.java, src/org/opensolaris/opengrok/web/WebappListener.java, test/org/opensolaris/opengrok/authorization/AuthorizationFrameworkTest.java, test/org/opensolaris/opengrok/web/ProjectHelperTest.java, test/org/opensolaris/opengrok/web/ProjectHelperTestBase.java
fixes #1595
the tests should be ok when #1603 is merged.
=> removing singleton pattern from authorization framework

src/org/opensolaris/opengrok/configuration/messages/ConfigMessage.java
=> fix merge of 8ca5403 for e181bd2

src/org/opensolaris/opengrok/web/AuthorizationFilter.java, web/WEB-INF/web.xml, web/eforbidden.jsp
=> display default 403 forbidden page when there is no customization

src/org/opensolaris/opengrok/web/AuthorizationFilter.java
=> improve logging of 403 HTTP errors

src/org/opensolaris/opengrok/analysis/plain/PlainAnalyzer.java, src/org/opensolaris/opengrok/util/NullWriter.java
=> on demand xref generation does not produce Scopes (#1622)

src/org/opensolaris/opengrok/configuration/ConfigMerge.java
=> report exception when file cannot be read in ConfigMerge tool

tools/Groups
=> adding a help message for the -p option

build.xml, src/org/opensolaris/opengrok/history/CVSHistoryParser.java, src/org/opensolaris/opengrok/history/CVSRepository.java, src/org/opensolaris/opengrok/history/RCSRepository.java, test/org/opensolaris/opengrok/history/CVSRepositoryTest.java
These changes fix handling of branches for CVS repository.
=> various CVS fixes

src/org/opensolaris/opengrok/history/CVSHistoryParser.java
=> use lambda function for sorting

platform/solaris/ips/create.sh, platform/solaris/smf/opengrok-migrate-shared.xml, platform/solaris/smf/opengrok-share-files.sh
- added more checks
- cleanup
- fix for #817 to share data across boot environments
=> IPS packaging changes

src/org/opensolaris/opengrok/configuration/Group.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/ProjectHelper.java
=> deduplicating code in RuntimeEnvironment and ProjectHelper

test/org/opensolaris/opengrok/configuration/messages/ExpirationNormalMessageTest.java
fixes #1470
Removing sleeps - the timer thread is now tested just for the concurrent performance.
=> removing sleeps as the tests arbitrarily fail

src/org/opensolaris/opengrok/web/Util.java
=> adding more info about authorization into status.jsp

src/org/opensolaris/opengrok/web/Scripts.java, web/js/utils-0.0.11.js
=> removing tooltip for multiple line selection

src/org/opensolaris/opengrok/configuration/Groups.java, web/repos.jspf
=> displaying the subgroups in ascending order

web/default/print.css, web/default/style.css, web/offwhite/print.css, web/offwhite/style.css, web/polished/print.css, web/polished/style.css
=> cleaning dead styles

src/org/opensolaris/opengrok/web/ProjectHelper.java
=> Filter indexed projects

src/org/opensolaris/opengrok/authorization/AuthorizationEntity.java, src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java, src/org/opensolaris/opengrok/authorization/AuthorizationStack.java, src/org/opensolaris/opengrok/web/AuthorizationFilter.java, src/org/opensolaris/opengrok/web/Statistics.java, src/org/opensolaris/opengrok/web/StatisticsFilter.java, test/org/opensolaris/opengrok/configuration/RuntimeEnvironmentTest.java, test/org/opensolaris/opengrok/configuration/messages/StatsMessageTest.java, test/org/opensolaris/opengrok/web/StatisticsTest.java
=> adding per stack statistics for authorization

src/org/opensolaris/opengrok/web/PageConfig.java, src/org/opensolaris/opengrok/web/SearchHelper.java, test/org/opensolaris/opengrok/web/SearchHelperTest.java
=> Prepare exec projects

src/org/opensolaris/opengrok/configuration/Project.java, src/org/opensolaris/opengrok/web/Scripts.java, web/js/utils-0.0.13.js, web/list.jsp
approaches #1636
Per project tunable to open navigate window by default for source code. This does not create a way how to set this tunable though but just prepares the playground. The way how to set it should be discussed.
=> introducing a project tunable to open navigate window by default

platform/solaris/ips/create.sh, src/org/opensolaris/opengrok/web/SearchHelper.java, test/org/opensolaris/opengrok/web/SearchHelperTest.java
=> More rc6 fixes

src/org/opensolaris/opengrok/history/GitRepository.java, test/org/opensolaris/opengrok/history/GitRepositoryTest.java
I forgot to change `determineCurrentVersion()` to use `iso-strict` format too.
=> determineCurrentVersion() in git repository needs to use iso-strict too

src/org/opensolaris/opengrok/index/IndexChangedListener.java, src/org/opensolaris/opengrok/index/IndexDatabase.java, test/org/opensolaris/opengrok/index/IndexerTest.java
The important piece is this line in `indexDown()`:
```
removeFile(!termPath.equals(path));
```
=> removeFile() needs to be smarter to allow incremental history indexing

src/org/opensolaris/opengrok/history/RepositoryFactory.java, src/org/opensolaris/opengrok/index/Indexer.java, test/org/opensolaris/opengrok/configuration/messages/ProjectMessageTest.java, test/org/opensolaris/opengrok/history/HistoryGuruTest.java, test/org/opensolaris/opengrok/history/PerforceRepositoryTest.java, test/org/opensolaris/opengrok/index/IgnoredNamesTest.java, test/org/opensolaris/opengrok/index/IndexDatabaseTest.java, test/org/opensolaris/opengrok/index/IndexerTest.java, test/org/opensolaris/opengrok/search/SearchEngineTest.java, test/org/opensolaris/opengrok/web/DirectoryListingTest.java
=> setIgnored() -> initializeIgnoredNames in RepositoryFactory

src/org/opensolaris/opengrok/util/ClassUtil.java, test/org/opensolaris/opengrok/configuration/ConfigurationTest.java
serialization/XML encoding strikes back !
=> Class util take2

src/org/opensolaris/opengrok/configuration/Groups.java
=> more single quotes for patterns in Groups output

web/default/style.css
=> wrap all but last td contents in the repository table

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, web/index.jsp
to provide workaround for the problems raised in #1478
=> tunable for displaying listing of repositories on index page

test/org/opensolaris/opengrok/index/IndexerTest.java
=> use try-with-resources in testXref()

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/WebappListener.java
=> get rid of startIndexReopenThread()

src/org/opensolaris/opengrok/configuration/messages/ProjectMessage.java, src/org/opensolaris/opengrok/index/IndexDatabase.java
Forgot to change the most important piece for the fix to actually work.
=> send the "indexed" message even if the project is marked as indexed

OpenGrok, README.txt
=> fix indexpart usage

src/org/opensolaris/opengrok/history/GitRepository.java, src/org/opensolaris/opengrok/history/MercurialRepository.java, src/org/opensolaris/opengrok/history/RepositoryInfo.java, src/org/opensolaris/opengrok/history/SubversionHistoryParser.java, src/org/opensolaris/opengrok/history/SubversionRepository.java
- fills missing features of Subversion repository
- unifies output format for current version
=> Subversion + current version fixes

src/org/opensolaris/opengrok/history/GitRepository.java
=> ignore .gitignore

src/org/opensolaris/opengrok/web/Scripts.java, web/js/utils-0.0.14.js
=> Clicking on line number erases parameters

src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/configuration/messages/ProjectMessage.java, src/org/opensolaris/opengrok/web/ProjectHelper.java, test/org/opensolaris/opengrok/configuration/messages/ProjectMessageTest.java
=> refresh group lists in project message handling

OpenGrok, src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/index/CommandLineOptions.java, src/org/opensolaris/opengrok/index/Indexer.java, test/org/opensolaris/opengrok/history/GitRepositoryTest.java
=> disable generating full history for renamed files by default

src/org/opensolaris/opengrok/web/Scripts.java, test/org/opensolaris/opengrok/web/ScriptsTest.java
Signed-off-by: Daniel Caminada <daniel.caminada@ergon.ch>
=> Return absolute path for scripts if contextPath is empty

src/org/opensolaris/opengrok/history/AccuRevRepository.java, src/org/opensolaris/opengrok/history/HistoryGuru.java, src/org/opensolaris/opengrok/index/Indexer.java
Changed HistoryGuru::addRepository so that it will recognize .opengrok_skip_history files in folders prior to scanning the folder/directory.
=> Have .opengrok_skip_history seen by AccuRev

build.xml
=> ship ctags.config in the dist tarball

OpenGrok
also removes last bits of JavaDB support.
=> Opengrok src root

src/org/opensolaris/opengrok/configuration/Configuration.java, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/PageConfig.java
=> prefer directories in directory listing ordering

README.md, src/org/opensolaris/opengrok/configuration/messages/ProjectMessage.java, test/org/opensolaris/opengrok/configuration/messages/ProjectMessageTest.java, tools/Messages
This will be handy for yet-to-be synchronization library.
=> Message get repos

src/org/opensolaris/opengrok/web/Scripts.java, web/js/utils-0.0.19.js
Resolves #1830.
I accept OCA for this fix.
=> bugfix: #1830 "Type" dropdown field/box missing with non-project mode

src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java, src/org/opensolaris/opengrok/authorization/AuthorizationFramework.java, src/org/opensolaris/opengrok/authorization/AuthorizationPlugin.java, src/org/opensolaris/opengrok/authorization/AuthorizationPluginClassLoader.java, src/org/opensolaris/opengrok/configuration/messages/Message.java, src/org/opensolaris/opengrok/history/HistoryGuru.java, src/org/opensolaris/opengrok/history/RepositoryFactory.java, src/org/opensolaris/opengrok/index/Indexer.java, src/org/opensolaris/opengrok/logger/LoggerUtil.java, src/org/opensolaris/opengrok/web/Statistics.java
When compiling with Java 9 deprecation warnings were shown so I repaired them.
Thanks for review :)
=> Replace Java 9 deprecated calls with appropriate substitutes

OpenGrok
fixes #1823
I didn't see many other env variables in the readme so I decided to put it just in the OpenGrok header.
=> rename IGNORE_PATTERNS to OPENGROK_IGNORE_PATTERNS

test/org/opensolaris/opengrok/condition/ConditionalRun.java, test/org/opensolaris/opengrok/condition/ConditionalRunRepeatable.java, test/org/opensolaris/opengrok/condition/ConditionalRunRule.java, test/org/opensolaris/opengrok/condition/RunningRepeatableConditionTest.java, test/org/opensolaris/opengrok/condition/SkippingRepeatableConditionTest.java
=> making the conditional rules in tests repeatable

LICENSE-adaic.org.txt, build.xml, opengrok-indexer/pom.xml, src/org/opensolaris/opengrok/analysis/AnalyzerGuru.java, src/org/opensolaris/opengrok/analysis/ada/AdaAnalyzer.java, src/org/opensolaris/opengrok/analysis/ada/AdaAnalyzerFactory.java, src/org/opensolaris/opengrok/analysis/ada/AdaLexHelper.java, src/org/opensolaris/opengrok/analysis/ada/AdaProductions.lexh, src/org/opensolaris/opengrok/analysis/ada/AdaSymbolTokenizer.lex, src/org/opensolaris/opengrok/analysis/ada/AdaXref.lex, src/org/opensolaris/opengrok/analysis/ada/Consts.java, src/org/opensolaris/opengrok/web/HtmlConsts.java, src/org/opensolaris/opengrok/web/Util.java, test/org/opensolaris/opengrok/analysis/ada/AdaSymbolTokenizerTest.java, test/org/opensolaris/opengrok/analysis/ada/AdaXrefTest.java, test/org/opensolaris/opengrok/analysis/ada/ada_xrefres.html, test/org/opensolaris/opengrok/analysis/ada/sample.adb, test/org/opensolaris/opengrok/analysis/ada/samplesymbols.txt
Hello,
Please consider for integration this patch to support analysis for the Ada programming language (issue #403).
Thank you.
=> Add classes to support Ada analysis

opengrok-indexer/pom.xml, plugins/LdapPlugin/test/opengrok/auth/plugin/LdapAttrTest.java, plugins/LdapPlugin/test/opengrok/auth/plugin/util/DummyHttpServletRequestLdap.java, plugins/UserPlugin/test/opengrok/auth/plugin/UserPluginTest.java, plugins/UserPlugin/test/opengrok/auth/plugin/decoders/OSSODecoderTest.java, plugins/UserPlugin/test/opengrok/auth/plugin/util/DummyHttpServletRequestUser.java, plugins/pom.xml
- maven only
- still not possible to execute the `test` (or `compile`) goals just for `plugins` project
=> Run plugins test

.gitignore, README.md, build.xml
hamcrest is a dependency for junit, so check that first.
Fix also README.md instructions.
=> Download junit and hamcrest jar files automatically by ant.

src/org/opensolaris/opengrok/analysis/plain/PlainFullTokenizer.lex, src/org/opensolaris/opengrok/search/context/HistoryLineTokenizer.lex, src/org/opensolaris/opengrok/search/context/PlainLineTokenizer.lex
=> Add support for non-english search

src/org/opensolaris/opengrok/web/Scripts.java, web/js/utils-0.0.19.js
Two commits to make clearer what changed:
1. revert of revert of #1830 bugfix
2. rework for #1877
Resolves #1830.
Resolves #1877.
I accept OCA for this fix.
=> Bugfix #1830 #1877

tools/sync/commands.py, tools/sync/hook.py, tools/sync/test/test_commands.py
second round of production inspired fixes to mirroring scripts
=> Mirroring fixups 2

src/org/opensolaris/opengrok/index/IndexDatabase.java
Hello,
Please consider for integration this patch so that `AlreadyClosedException` is detected to terminate a run early. This happens after e.g. `OutOfMemoryException` has occurred and the Lucene `IndexWriter` has aborted. This way, an indexing run will terminate ASAP without doing pointless work that cannot be committed anyway.
Thank you.
=> Fix to handle AlreadyClosedException specially

src/org/opensolaris/opengrok/index/IndexDatabase.java
Hello,
Please consider for integration this patch with a simple comment fix.
Thank you.
=> Fix comment

platform/solaris/ips/create.sh, tools/sync/projadm.py, tools/sync/utils.py
Simple wrapper script of couple of steps used internally for project management.
=> introduce projadm script for automating project data management

src/org/opensolaris/opengrok/web/Scripts.java, web/default/style.css, web/js/diff-0.0.3.js, web/js/utils-0.0.21.js
fixes #1350
Navigate window now has fixed header and scrollable content. Other windows don't need it.
=> fixed header for popup windows with scrollable content inside

pom.xml
JaCoCo updated to the newest version because the previous version had problems with Java 10. I also replaced `\t` chars to ordinary spaces. Thanks :)
=> Update JaCoCo to 0.8.1

tools/sync/hook.py, tools/sync/mirror.py
=> allow hook scipts to benefit from proxy environment

src/org/opensolaris/opengrok/index/Indexer.java
=> print indexer version

test/org/opensolaris/opengrok/configuration/messages/RepositoryMessageTest.java
Repaired one problem from <https://github.com/oracle/opengrok/pull/2100>
Thanks for review :)
=> Remove unnecessary @ConditionalRunRepeatable annotation

tools/sync/projadm.py, tools/sync/utils.py
=> emit errors along with guidance how to fix them

tools/sync/command.py, tools/sync/cvs.py, tools/sync/git.py, tools/sync/mercurial.py, tools/sync/mirror.py, tools/sync/opengrok.py, tools/sync/svn.py, tools/sync/teamware.py, tools/sync/utils.py
this is mainly done to make `--config` optional for `mirror.py`
=> Mirror fixes

src/org/opensolaris/opengrok/configuration/messages/ProjectMessage.java, test/org/opensolaris/opengrok/configuration/messages/ProjectMessageTest.java
fixes an oversight that happened when adding proper per-project configuration functionality.
=> construct Project with Configuration

src/org/opensolaris/opengrok/history/MercurialRepository.java
fixes a problem with lack of renamed file handling for Mercurial repository
=> follow renamed file handling property

plugins/src/opengrok/auth/plugin/AbstractLdapPlugin.java
simple rename for better code readability
=> rename ldap -> ldapProvider

web/eforbidden.jsp
Hello,
Please consider for integration this patch to fix a JSP for a method that changed signature.
Thank you.
=> Fix #2169 for altered sig of getForbiddenIncludeFileContent()

src/org/opensolaris/opengrok/search/Summary.java, web/mast.jsp
=> Main tag fix

opengrok-indexer/pom.xml, src/org/opensolaris/opengrok/configuration/RuntimeEnvironment.java, src/org/opensolaris/opengrok/web/api/v1/controller/MessagesController.java, src/org/opensolaris/opengrok/web/api/v1/controller/RepositoriesController.java, src/org/opensolaris/opengrok/web/api/v1/controller/SearchController.java, src/org/opensolaris/opengrok/web/api/v1/filter/LocalhostFilter.java, src/org/opensolaris/opengrok/web/messages/MessagesContainer.java, test/org/opensolaris/opengrok/web/api/v1/controller/MessagesControllerTest.java, test/org/opensolaris/opengrok/web/api/v1/filter/LocalhostFilterTest.java, test/org/opensolaris/opengrok/web/constraint/PositiveDurationValidatorTest.java
Features:
* added `LocalhostFilterTest`
* added possibility to retrieve all messages in the system
* fixed search endpoint -> it was not working properly because I misinterpreted hits
-> now `maxresults` specifies maximum number of documents that may be retrieved
-> data are grouped by document `path`
* delete messages -> now only one `tag` can be specified (instead of multiple)
* repositories endpoint fix -> repositories type now returns `TEXT/PLAIN` instead of `APPLICATION/JSON`
I wanted to create `SearchControllerTest` as well but there are some problems with `@Context` injection and I was not sure how to add test repository properly and did not want to spend a lot of time with it. So I will look into it later.
Thanks :)
=> Add LocalhostFilter test and other REST API improvements

src/org/opensolaris/opengrok/history/Repository.java, test/org/opensolaris/opengrok/history/RepositoryFactoryTest.java, test/org/opensolaris/opengrok/history/SCCSRepositoryTest.java
This is mainly to reduce intermittent code coverage loss as reported e.g. in https://coveralls.io/builds/17674160/source?filename=src%2Forg%2Fopensolaris%2Fopengrok%2Fhistory%2FRepositoryFactory.java#L116.
=> reduce test coverage gaps

src/org/opensolaris/opengrok/index/Indexer.java
=> fix message for partial index check

src/org/opensolaris/opengrok/index/PendingFileCompleter.java
Hello,
Please consider for integration this patch to `mkdirs()` in `doLink()`. When a leaf directory consists solely of symlinks to other local directories — i.e. with no other content or child content to xref — then the `xref/` directory would not have been created to contain the duplicated symlinks.
Thank you.
=> Fix #2148 : mkdirs() in doLink() in case no other related content

src/org/opensolaris/opengrok/index/IndexDatabase.java
Log warning message rather than print to stderr.
Thanks :)
=> Log warning if webapp could not be notified that project was indexed

checkstyle/style.xml, pom.xml, suggester/pom.xml
Hello,
fixes #2223
I was able to resolve this without additional Maven module. Seems to work properly on my setup. Could you please verify? :) 
Thanks :)
=> Fix checkstyle for suggester module

tools/command.py
When running a test with mirroring a Mercurial repository that relied on SSH pubkey authentication and the keys were misconfigured that made the `hg pull` command to spawn `ssh` in interactive mode. The problem is that the `hg` process happily continued even after `terminate()` (that sends `SIGTERM` signal on Unix). In order to avoid stalling the mirroring, I've added extra methods to terminate the process. 
Creating a process group and killing it as a whole would be better, leaving that for next time.
=> extra effort to terminate the process after timeout

tools/java.py
For refreshing the `dtags.eftar` file it is necessary to run `java` with `-classpath`.
Also fixes MacOS java detection.
=> make it possible to run bare java

.travis.yml, README.md, dev/main, sonar-project.properties
Enables SonarQube checker.
Here are my notes esp. on blockers/constrains:
- the Sonar plugin is invoked directly in Maven using `sonar:sonar` - after jacoco agent is prepared (which it is by default in our Maven plugin configuration). This direct invocation will download the sonar plugin and execute its goal. Personally I'd feel more comfortable if the sonar plugin was listed in the top-level `pom.xml` file.
- in order to submit the results it is necessary to run the analysis on the main branch first (usually the main branch is called `master` otherwise further configuration of Sonar will be required - https://groups.google.com/forum/#!msg/sonarqube/obMtswvz0_U/q_2najAnBAAJ). This is probably done so that it has a baseline. For this reason I had to test my `vladak/OpenGrok:sonarqube` …
=> enable Sonarqube checker

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java
=> Remove deprecated attributes from configuration

plugins/src/opengrok/auth/entity/LdapUser.java, plugins/src/opengrok/auth/plugin/LdapAttrPlugin.java, plugins/src/opengrok/auth/plugin/LdapFilterPlugin.java
bunch of Sonar bug fixes for plugins
=> Sonar plugin fixes

opengrok-indexer/src/main/java/org/opengrok/indexer/web/EftarFileReader.java, opengrok-web/src/main/java/org/opengrok/web/DirectoryListing.java
=> make FNode members private

opengrok-indexer/src/main/java/org/opengrok/indexer/history/SSCMRepository.java
fixes problem (race condition) reported by Sonar
=> properly create temporary directory

opengrok-indexer/src/main/java/org/opengrok/indexer/search/SearchEngine.java
=> fix the operator

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java, opengrok-indexer/src/test/java/org/opengrok/indexer/util/OptionParserTest.java
=> Opt parser private

opengrok-indexer/src/main/java/org/opengrok/indexer/history/AccuRevRepository.java
=> parent member should not shadow parent class field

opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitAnnotationParser.java
=> use try with resources

opengrok-indexer/src/main/java/org/opengrok/indexer/history/SCCSRepository.java
=> Sonar fixes for SCCS

opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java
=> cleanup unused code

suggester/src/main/java/org/opengrok/suggest/popular/impl/chronicle/ChronicleMapAdapter.java
The easier part of #2240 to get rid of stale temporary files.
=> delete temporary file on exception

opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitHistoryParserTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/MercurialRepositoryTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerRepoTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/search/HitTest.java
Fixes some of the Windows test problems.
=> fix some test case failures on Windows

opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitHistoryParserTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryTest.java
=> use more separator chars

opengrok-indexer/src/test/java/org/opengrok/indexer/util/PathUtilsTest.java
=> use URI.create() to construct absolute paths

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
=> fix path construction

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/ClearCaseRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/executables/JarAnalyzerTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/RuntimeEnvironmentTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/HistoryGuruTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexVersionTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/search/SearchEngineTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/search/context/SearchAndContextFormatterTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/search/context/SearchAndContextFormatterTest2.java, opengrok-indexer/src/test/java/org/opengrok/indexer/web/SearchHelperTest.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerProjectsDisabledTest.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerTest.java
The notion of verbosity flag next to logging level is strange. This change removes the flag.
=> get rid of verbosity flag

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java, opengrok-web/src/main/webapp/list.jsp
Replacement for #2180 so that it applies after the recent source code tree restructuring.
=> Re-gen xref if missing. Fix list.jsp w.r.t. isGenerateHtml().

tools/src/main/python/indexer.py, tools/src/test/python/test_indexer.py
Tested with (`hg` is present on the system):
```
/indexer.py -J=-Dorg.opengrok.indexer.history.Mercurial=/foo/bar -D -a /var/tmp/opengrok-1.1-rc41/lib/opengrok.jar -- -h
/indexer.py -D -a /var/tmp/opengrok-1.1-rc41/lib/opengrok.jar -- -h
```
=> merge command options smarter

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
This will also make it more aligned with the -U option of the Python scripts.
=> rename host to uri

opengrok-tools/src/main/python/opengrok_tools/projadm.py
=> Flushing content to the file in projadm

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/ConfigMerge.java, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Groups.java, opengrok-tools/src/main/python/opengrok_tools/config_merge.py, opengrok-tools/src/main/python/opengrok_tools/groups.py
Python scripts can then gather the output according to the exit code.
fixes #2379
=> Print to the stream related to the exit code

opengrok-tools/src/main/python/opengrok_tools/all/scm/git.py, opengrok-tools/src/main/python/opengrok_tools/all/scm/mercurial.py, opengrok-tools/src/main/python/opengrok_tools/all/scm/repository.py, opengrok-tools/src/main/python/opengrok_tools/mirror.py
Tested with a sample Mercurial and Git repo.
=> Mirror incoming check

opengrok-indexer/pom.xml, opengrok-web/pom.xml
Should fix RESTful API problems with Java 9+.
=> add JAX-B dependencies

opengrok-tools/src/main/python/README.md
=> updating the readme with directory specific installation

opengrok-tools/pom.xml
=> Skipping python tests when -DskipTests=true

opengrok-tools/src/main/python/opengrok_tools/deploy.py
Remove dependency on jar/zip/unzip executables and simplify code a bit.
=> deploy.py: repackage WAR files using standard zipfile module

opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
The thread that lost the race needs to move on.
=> swallow FileAlreadyExistsException in doLink()

opengrok-tools/requirements.txt, opengrok-tools/setup.py, opengrok-tools/src/main/python/opengrok_tools/sync.py
looks like this is needed to get the latest secure version.
=> upgrade requests to 2.20.0

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ConfigurationControllerTest.java
fixes #2445
I run the test on the setup as for #2423, for 400 times in a row and didn't encounter any incosistency in terms of repositories on the main page.
=> using the project-repository map while being in write lock

opengrok-tools/src/main/python/opengrok_tools/utils/java.py
=> detect Java binary also via JAVA_HOME env var

opengrok-tools/src/main/python/opengrok_tools/deploy.py, opengrok-tools/src/main/python/opengrok_tools/indexer.py, opengrok-tools/src/main/python/opengrok_tools/java.py, opengrok-tools/src/main/python/opengrok_tools/mirror.py, opengrok-tools/src/main/python/opengrok_tools/projadm.py, opengrok-tools/src/main/python/opengrok_tools/reindex_project.py, opengrok-tools/src/main/python/opengrok_tools/sync.py, opengrok-tools/src/main/python/opengrok_tools/utils/log.py
With the changes:
```
$ opengrok-projadm -a foo
Adding project foo
could not add project foo for web application on http://localhost:8080/source
could not get configuration from web application on http://localhost:8080/source
$ opengrok-projadm -a foo >/dev/null
could not add project foo for web application on http://localhost:8080/source
could not get configuration from web application on http://localhost:8080/source
$ opengrok-projadm -a foo 2>/dev/null
Adding project foo
```
=> add better console logger

distribution/assembly.xml, opengrok-tools/README-dist.txt
most of the README file contents are taken from the original README.md
=> add tools README

opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java
=> Fix inconsistency in handling inclusion of paths.tsv data [issue 2085]

opengrok-tools/pom.xml, opengrok-tools/setup.py, opengrok-tools/src/main/python/opengrok_tools/config_merge.py, opengrok-tools/src/main/python/opengrok_tools/deploy.py, opengrok-tools/src/main/python/opengrok_tools/groups.py, opengrok-tools/src/main/python/opengrok_tools/indexer.py, opengrok-tools/src/main/python/opengrok_tools/java.py, opengrok-tools/src/main/python/opengrok_tools/mirror.py, opengrok-tools/src/main/python/opengrok_tools/projadm.py, opengrok-tools/src/main/python/opengrok_tools/reindex_project.py, opengrok-tools/src/main/python/opengrok_tools/sync.py, opengrok-tools/src/main/python/opengrok_tools/utils/__init__.py, opengrok-tools/src/main/python/opengrok_tools/utils/java.py, opengrok-tools/src/main/python/opengrok_tools/utils/parsers.py, opengrok-tools/src/main/python/opengrok_tools/utils/repofactory.py, opengrok-tools/src/main/python/opengrok_tools/version.py, opengrok-tools/src/test/python/test_versions.py
Moving the version to a different python file so it's available when the commands are invoked with `--version`.
=> Opengrok tools version --version

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
=> printing the indexer exception to stderr

opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java, opengrok-indexer/src/test/java/org/opengrok/indexer/web/PageConfigRequestedProjectsTest.java
=> group parameter for search URL

opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java
=> making protected constant again public

opengrok-tools/MANIFEST.in, opengrok-tools/pom.xml, opengrok-tools/setup.py
distribute the distribution readme not the dev readme
=> distribute the dist readme

opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java, opengrok-indexer/src/test/java/org/opengrok/indexer/web/PageConfigRequestedProjectsTest.java
=> removing non indexed projects from requested projects

.travis.yml, dev/main, pom.xml
=> enable JDK 9

opengrok-tools/src/main/python/opengrok_tools/sync.py, opengrok-tools/src/main/python/opengrok_tools/utils/readconfig.py
will help to diagnose failures as the one seen in #2514
=> print strerror on IOError

.mvn/wrapper/maven-wrapper.properties, appveyor.yml, opengrok-indexer/src/test/java/org/opengrok/indexer/history/BazaarHistoryParserTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/SubversionHistoryParserTest.java
=> fix windows

opengrok-indexer/src/test/java/org/opengrok/indexer/condition/RepositoryInstalled.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/FileHistoryCacheTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/SubversionHistoryParserTest.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
=> FileHistoryCacheTest fix windows

opengrok-indexer/src/test/java/org/opengrok/indexer/util/PathUtilsTest.java
=> PathUtilsTest fix windows

opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
=> IndexerTest

apiary.apib, opengrok-web/pom.xml, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/RepositoriesController.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/RepositoriesControllerTest.java
Remaining Windows/AppVeyor fixes will be accumulated here.
=> remaining Windows/AppVeyor fixes

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java, opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/RuntimeEnvironmentTest.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java
=> clear the groups before populating them

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerUtil.java, opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerUtilTest.java
=> checking if projects are enabled before enabling them

opengrok-indexer/src/main/java/org/opengrok/indexer/history/AccuRevHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/BazaarHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/CVSHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/ClearCaseHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/MonotoneHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/RazorHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SCCSHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SCCSRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SSCMHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/GitRepositoryTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/RepositoryTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/SubversionRepositoryTest.java
=> refactoring date formats to be synchronized per repository

opengrok-indexer/pom.xml
=> fixes OpenGrok-2574 revisit maven patch after jflex update

opengrok-indexer/pom.xml, opengrok-indexer/src/main/java/org/opengrok/indexer/Info.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java, opengrok-web/src/main/webapp/foot.jspf
Show the version when one hovers over the logo at the bottom of the web page.
=> add opengrok version to the main page

opengrok-tools/src/main/python/opengrok_tools/scm/__init__.py, opengrok-tools/src/main/python/opengrok_tools/scm/repo.py, opengrok-tools/src/main/python/opengrok_tools/utils/repofactory.py
This pull request for being able to use sync and mirror with project using Google repo tools.
I do accept the OCA lines
=> Add Google repo tool for syncing

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
This change modifies the behavior of `--noIndex` to encompass also the history cache generation. This way it is possible to change the index page before the initial reindex has complete not to display error about the configuration.
=> --noindex should suppress history cache generation

apiary.apib, dev/checkstyle/suppressions.xml, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/document/MandocException.java, opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationStack.java, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/SuggesterConfig.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/Filter.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/IgnoredDirs.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/IgnoredFiles.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexVersion.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerException.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/ForbiddenSymlinkException.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/messages/Message.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/messages/MessagesContainer.java, opengrok-indexer/src/test/java/org/opengrok/indexer/condition/DeliberateRuntimeException.java, opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/SuggesterConfigTest.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SuggesterController.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SystemController.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/SuggesterService.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/impl/SuggesterServiceImpl.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SuggesterControllerTest.java, suggester/src/main/java/org/opengrok/suggest/Suggester.java, suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java, suggester/src/main/java/org/opengrok/suggest/query/data/BitIntsHolder.java, suggester/src/main/java/org/opengrok/suggest/query/data/HashIntsHolder.java, suggester/src/test/java/org/opengrok/suggest/SuggesterTest.java
This set of changes lowers the impact of suggester rebuild on the webapp/system.
=> Suggester rebuild fixes

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java, opengrok-web/src/main/webapp/js/utils-0.0.26.js
=> making an exception for group Other

pom.xml
=> lucene 7.6

suggester/src/main/java/org/opengrok/suggest/Suggester.java
=> check for null suggester data

sonar-project.properties
Fixes currently failing Travis builds.
=> limit Web suffixes in Sonar

pom.xml
=> lucene 7.7

dev/before, opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/Version.java, opengrok-indexer/src/test/java/org/opengrok/indexer/util/VersionTest.java
=> check git version in GitRepository#isWorking()

opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java, opengrok-web/src/main/webapp/menu.jspf
alleviates the problem of #1576
=> avoid selecting duplicate projects multiple times

pom.xml
=> remove json-simple dependency

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AbstractAnalyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerFactory.java
fixes #2680
@idodeclare can you review?
=> updating copyright to comply with CDDL

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
=> Adding a logger message for waiting

opengrok-web/src/main/webapp/menu.jspf
No exceptions seen any more when performing searches with no match.
=> copy projects before modifying them

opengrok-tools/src/main/python/opengrok_tools/scm/cvs.py, opengrok-tools/src/main/python/opengrok_tools/scm/git.py, opengrok-tools/src/main/python/opengrok_tools/scm/mercurial.py, opengrok-tools/src/main/python/opengrok_tools/scm/repo.py, opengrok-tools/src/main/python/opengrok_tools/scm/svn.py, opengrok-tools/src/main/python/opengrok_tools/scm/teamware.py
This change provides annotation of the commands run by the `mirror.py` script.
=> annotate output from commands

opengrok-tools/src/main/python/opengrok_tools/scm/cvs.py, opengrok-tools/src/main/python/opengrok_tools/scm/git.py, opengrok-tools/src/main/python/opengrok_tools/scm/mercurial.py, opengrok-tools/src/main/python/opengrok_tools/scm/repo.py, opengrok-tools/src/main/python/opengrok_tools/scm/svn.py, opengrok-tools/src/main/python/opengrok_tools/scm/teamware.py
=> fix command printing

opengrok-tools/src/main/python/opengrok_tools/mirror.py, opengrok-tools/src/main/python/opengrok_tools/sync.py, opengrok-tools/src/main/python/opengrok_tools/utils/log.py
will be handy for https://github.com/OpenGrok/docker/pull/32
=> parallelize repository mirroring

opengrok-tools/src/main/python/opengrok_tools/config_merge.py, opengrok-tools/src/main/python/opengrok_tools/deploy.py, opengrok-tools/src/main/python/opengrok_tools/groups.py, opengrok-tools/src/main/python/opengrok_tools/indexer.py, opengrok-tools/src/main/python/opengrok_tools/java.py, opengrok-tools/src/main/python/opengrok_tools/mirror.py, opengrok-tools/src/main/python/opengrok_tools/projadm.py, opengrok-tools/src/main/python/opengrok_tools/reindex_project.py, opengrok-tools/src/main/python/opengrok_tools/sync.py, opengrok-tools/src/main/python/opengrok_tools/utils/log.py, opengrok-tools/src/main/python/opengrok_tools/utils/mirror.py, opengrok-tools/src/main/python/opengrok_tools/utils/utils.py
=> fixups to mirroring functions

opengrok-indexer/src/test/resources/analysis/xml/sample.xml, opengrok-indexer/src/test/resources/analysis/xml/sample_xref.html, pom.xml
Switching Maven repos to HTTPS based on internal report.
=> switch Maven repos to HTTPS

opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceRepository.java
This implements PerforceRepository.getHistory(File,String) to support incremental history.
=> Perforce incremental history

opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceRepository.java
=> recent Perforce changes: compare the value, not object

.gitignore, opengrok-indexer/src/main/java/org/opengrok/indexer/web/ProjectHelper.java, opengrok-web/pom.xml, opengrok-web/src/main/webapp/WEB-INF/tags/project.tag, opengrok-web/src/main/webapp/WEB-INF/tags/projects.tag, opengrok-web/src/main/webapp/WEB-INF/tags/repositories.tag, opengrok-web/src/main/webapp/WEB-INF/tags/repository.tag, opengrok-web/src/main/webapp/repos.jspf
depends on #2718
Using jstl custom tags to implement reusable code.
=> Templating projects and repositories on the main page

opengrok-web/src/main/java/org/opengrok/web/api/v1/filter/CorsEnable.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/filter/CorsFilter.java
PR #2259 was merged without rebase so it caught errors introduced in the meantime. This change fixes that.
=> fix style in web module

opengrok-web/src/main/webapp/WEB-INF/tags/repository.tag
The advice from https://stackoverflow.com/questions/8898815/how-to-use-both-single-and-double-quotes-inside-jstl-el-expression seems to fix the problem of attribute value evaluation.
=> escape string literal using single quotes

opengrok-tools/src/main/python/opengrok_tools/sync.py
=> add YAML to opengrok-sync usage

opengrok-web/src/main/webapp/WEB-INF/tags/project.tag, opengrok-web/src/main/webapp/WEB-INF/tags/repository.tag
Turns out IDEA was right when it complained it cannot access `request`.
=> request needs to be accessed via pageContext in JSTL

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
The original fix is incomplete as noted on https://github.com/oracle/opengrok/issues/2808#issuecomment-504621400
=> propagate the type of repo in non-repo case

opengrok-tools/src/main/python/opengrok_tools/config_merge.py, opengrok-tools/src/main/python/opengrok_tools/groups.py, opengrok-tools/src/main/python/opengrok_tools/indexer.py, opengrok-tools/src/main/python/opengrok_tools/java.py, opengrok-tools/src/main/python/opengrok_tools/mirror.py, opengrok-tools/src/main/python/opengrok_tools/projadm.py, opengrok-tools/src/main/python/opengrok_tools/reindex_project.py, opengrok-tools/src/main/python/opengrok_tools/sync.py, opengrok-tools/src/main/python/opengrok_tools/utils/__init__.py, opengrok-tools/src/main/python/opengrok_tools/utils/commandsequence.py, opengrok-tools/src/main/python/opengrok_tools/utils/exitvals.py, opengrok-tools/src/main/python/opengrok_tools/utils/hook.py, opengrok-tools/src/main/python/opengrok_tools/utils/log.py, opengrok-tools/src/main/python/opengrok_tools/utils/mirror.py, opengrok-tools/src/main/python/opengrok_tools/utils/utils.py
- refactoring the code to use the constants
fixes #2843
=> checking return values for incoming check

opengrok-tools/src/main/python/opengrok_tools/mirror.py, opengrok-tools/src/main/python/opengrok_tools/utils/mirror.py
Improving --incoming check to check also the index presence
for the particular project.
After that, the name "incoming" could be a little misleading
so I refactored the name to "check changes".
fixes #2844
=> Python tools improved incoming check

dev/before_install, opengrok-tools/setup.py, opengrok-tools/src/main/python/opengrok_tools/mirror.py, opengrok-tools/src/main/python/opengrok_tools/utils/log.py, opengrok-tools/src/main/python/opengrok_tools/utils/mirror.py, opengrok-tools/src/test/python/test_mirror.py
To prevent further regressions of #2843, I added a simple unit test. While at it, I refactored the meat of the mirroring - the `mirror_project()` function as suggested in the recent code review.
=> Python mirror tool refactor and test

Dockerfile
=> Removing duplicated CATALINA_HOME in dockerfile

opengrok-tools/src/main/python/opengrok_tools/utils/commandsequence.py
=> match error strings in command output more precisely

.travis.yml, Dockerfile, dev/docker.sh, docker/index.sh
@tulinkry proposed to store the webapp config under `/opengrok` in Docker image which makes sense given that data and source roots are underneath as well.
=> store webapp configuration under /opengrok/etc

opengrok-indexer/src/test/java/org/opengrok/indexer/util/BooleanUtilTest.java
Hi,
I've analysed your code base and noticed that `org.opengrok.indexer.util.BooleanUtil` in the `opengrok` module is not fully tested.
These tests have been created by [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.
=> These tests were written using Diffblue Cover.

opengrok-indexer/src/main/java/org/opengrok/indexer/search/SearchEngine.java
While browsing the code, I noticed that IDEA flagged bulk of the code in `searchSingleDatabase()` and `searchMultiDatabase()` as duplicate. This change refactors the code into new private method.
=> refactor to avoid duplicate code

docker/README.md
Hi,
just a small typo fix.
Thanks :)
=> Fix docker readme typo

docker/README.md, docker/index.sh
=> Add information about mount data folder and configuration folder.

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/executables/ELFAnalyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java, opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/IOUtils.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/OptionParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java, opengrok-tools/src/main/python/opengrok_tools/utils/readconfig.py, opengrok-web/src/main/webapp/js/utils-0.0.31.js, plugins/src/main/java/opengrok/auth/plugin/LdapAttrPlugin.java, suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java, suggester/src/main/java/org/opengrok/suggest/popular/impl/chronicle/ChronicleMapConfiguration.java
Hi,
fixed some simple stuff reported by lgtm: https://lgtm.com/projects/g/oracle/opengrok
Thanks :)
=> Fix some lgtm warnings

opengrok-tools/requirements.txt, opengrok-tools/setup.py, opengrok-tools/src/test/python/test_mirror.py
The reasons are explained in #2852.
=> use GitPython instead of pygit2

docker/index.sh, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java, opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/RuntimeEnvironmentTest.java
=> Enable leading wildcard by default

plugins/src/main/java/opengrok/auth/plugin/LdapFilterPlugin.java, plugins/src/main/java/opengrok/auth/plugin/util/FilterUtil.java, plugins/src/test/java/opengrok/auth/plugin/LdapFilterPluginTest.java, plugins/src/test/java/opengrok/auth/plugin/util/FilterUtilTest.java
Adds basic attribute transforms to `LdapFilterPlugin`.
Sample config:
```xml
<void method="add">                                                         
<object class="org.opengrok.indexer.authorization.AuthorizationPlugin"> 
<void property="name">                                              
<string>opengrok.auth.plugin.LdapFilterPlugin</string>          
</void>                                                             
<void property="flag">                                              
<string>REQUIRED</string>                                       
</void>                                                             
<void property="setup">                                             
<void method="put">                                             
<string>configuration</string> …
```
=> LDAP uid case (in)sensitivity fix for LdapFilter plugin

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java, opengrok-web/src/main/webapp/js/utils-0.0.33.js
=> fix scrolling to symbol in Chrome

pom.xml
=> lucene 8.3

dev/install-universal_ctags.sh
Reset Universal ctags to latest known working version.
=> reset ctags to last known good changeset

opengrok-tools/src/main/python/opengrok_tools/utils/opengrok.py
Forgot to update the scripts after the API endpoint changes in cset e03dc428.
=> fix API call to get repository type

opengrok-web/src/main/webapp/list.jsp
Hello,
Please consider for integration this patch to relocate the conditional calls to `sendRedirect()` to happen before any response is partially constructed.
Thank you.
=> Fix #2997 : redirect (conditionally) before writing partially

pom.xml
=> lucene 8.3.1

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java, pom.xml
=> Lucene 8.4.0

apiary.apib, dev/main, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/HistoryController.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/filter/LocalhostFilter.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/HistoryControllerTest.java
This change adds the API endpoint for history. It supports pagination and history for directories.
=> implement history API endpoint

opengrok-indexer/pom.xml, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/executables/JavaClassAnalyzer.java, pom.xml
=> bcel upgrade to 6.4.1

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/JFlexNonXref.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/JFlexXref.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/JFlexXrefUtils.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/archive/BZip2Analyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/archive/GZIPAnalyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/executables/JavaClassAnalyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/search/QueryBuilder.java, opengrok-indexer/src/main/java/org/opengrok/indexer/search/Results.java, opengrok-indexer/src/main/java/org/opengrok/indexer/search/Summarizer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/HistoryContext.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/DiffData.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/PageConfig.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/QueryParameters.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java, opengrok-indexer/src/main/resources/analysis/document/TroffXref.lex, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/LuceneCompatibilityTest.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SearchController.java, opengrok-web/src/main/webapp/diff.jsp, opengrok-web/src/main/webapp/help.jsp, opengrok-web/src/main/webapp/history.jsp, opengrok-web/src/main/webapp/list.jsp, opengrok-web/src/main/webapp/menu.jspf, opengrok-web/src/main/webapp/minisearch.jspf, opengrok-web/src/main/webapp/more.jsp, opengrok-web/src/main/webapp/opensearch.jsp, opengrok-web/src/main/webapp/search.jsp
@tarzanek ,
This is that commit you wanted as a separate PR.
Regards.
=> Extract to QueryParameters named literals

suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
Even with the changes in 4fcd99b0e06b290c64e81de29c6df89feeaa4733 I got exception:
```
Mar 23, 2020 11:06:14 AM org.opengrok.suggest.SuggesterProjectData initSearchCountMap
SEVERE: Could not create ChronicleMap due to invalid key size: 22.0
java.lang.IllegalArgumentException: Entries should be positive, 0 given
at net.openhft.chronicle.map.ChronicleMapBuilder.entries(ChronicleMapBuilder.java:964)
at org.opengrok.suggest.popular.impl.chronicle.ChronicleMapAdapter.<init>(ChronicleMapAdapter.java:54)
at org.opengrok.suggest.SuggesterProjectData.initSearchCountMap(SuggesterProjectData.java:302)
at org.opengrok.suggest.SuggesterProjectData.init(SuggesterProjectData.java:158)
at org.opengrok.suggest.Suggester.lambda$getInitRunnable$1(Suggester.java:185)
at …
```
=> skip search count map init if number entries is 0

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Scripts.java, opengrok-web/src/main/webapp/js/searchable-option-list-2.0.10.js
@tarzanek , I realized the `boolean` I added was superfluous. Please would you take a look when you get a moment.
Thank you.
=> Remove superfluous boolean

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/CompatibleAnalyser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/FileAnalyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/HistoryAnalyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/document/DocumentMatcher.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/executables/JavaClassAnalyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/executables/JavaClassAnalyzerFactory.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/plain/PlainAnalyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginClassLoader.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/Annotation.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/CVSRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/RCSget.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/package.html, opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/Progress.java, opengrok-web/src/main/java/org/opengrok/web/GetFile.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/FileController.java, plugins/src/main/java/opengrok/auth/plugin/util/RestfulClient.java, suggester/src/main/java/org/opengrok/suggest/SuggesterSearcher.java, suggester/src/main/java/org/opengrok/suggest/query/customized/CustomSloppyPhraseScorer.java
Just went through Sonar and squashed several identified bugs.
=> Squash YYYY and some other Sonar-identified bugs

opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/query/SuggesterQueryParser.java, pom.xml
=> lucene 8.5

opengrok-web/src/main/webapp/diff.jsp
=> fix broken links in diff view

opengrok-web/src/main/webapp/help.jsp, opengrok-web/src/main/webapp/history.jsp, opengrok-web/src/main/webapp/list.jsp, opengrok-web/src/main/webapp/search.jsp
@vladak , this is a PR for a few more fixes of the bugs you identified.
=> Fix more broken links due to indentation

opengrok-indexer/src/main/java/org/opengrok/indexer/web/messages/MessagesContainer.java
When trying to track down a problem with Messages, I realized that when message limit is hit is is not properly messaged (sic!).
=> add log entry and throw exception when message limit is exceeded

plugins/src/main/java/opengrok/auth/plugin/ldap/LdapFacade.java
This change aids debugging of some LDAP failures.
=> log LDAP search parameters for some of the failure cases

opengrok-tools/src/main/python/opengrok_tools/sync.py
This change supports the following workflow:
- a project is added using `projadm.py`
- it is indexed using `sync.py` (so that the same set of per project indexer options is used as is for periodic reindex using the same `sync.py` configuration)
This fixes a problem which happens when the project `sync.py` fails because the periodic `sync.py` is already running. The exclusion using the locking for periodic sync is in order however in this case it causes problems (project is added but not indexed).
=> introduce the --nolock option to sync.py

opengrok-web/src/main/webapp/menu.jspf, opengrok-web/src/main/webapp/search.jsp
Tested also to make sure the `#xrd` functionality still works with this patch.
=> Fix to restore "submit" type

pom.xml
=> Lucene 8.5.2

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java, pom.xml
@vladak @idodeclare are you OK with reflection for picking the latest codec?
fwiw the tools build fails in travis on linux system,
mac and windows are ok
=> lucene 8.6

pom.xml
=> lucene 8.6.1

suggester/pom.xml
Proposed fix for #3206
This change is mechanical and I claim no copyright to it.  I believe I already accepted OCA in the past, but if not, I release this PR under it
Unfortunately, I was not able to build the resulting opengrok -- the build seems to crash for me -- but I did verify the POM is valid.
=> Suggester: upgrade chronicle-core to 2.20.20 for Java 14 support

pom.xml
=> lucene 8.6.2

opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
This will detect the bizarre situation where `add()` is called while `complete()` is running, per my wild theory re #3210.
=> Detect if add() is called while complete() is running

opengrok-tools/src/main/python/opengrok_tools/utils/command.py, opengrok-tools/src/test/python/test_command.py
=> convert the whole command array to string

apiary.apib
The `/stats` endpoint was removed in PR #2911.
=> update Apiary documentation for monitoring

opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
This change adds general request latency monitoring to the web app.
=> monitor request latency

README.md
Fixes a year in copyright as it looks that the project is up-to-date.
=> Fix README copyright

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/document/DocumentMatcher.java, opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationFramework.java, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/ConfigurationHelp.java, opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginClassLoader.java, opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginFramework.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/BazaarHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/CVSHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/ClearCaseHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryCache.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SSCMHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/ClassUtil.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/OptionParser.java, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/AnalyzerGuruTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/LuceneCompatibilityTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/authorization/PluginClassLoaderTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/GroupsTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/search/context/ContextTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/util/OptionParserTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/web/UtilTest.java, opengrok-web/src/main/webapp/diff.jsp, plugins/src/main/java/opengrok/auth/plugin/AbstractLdapPlugin.java, plugins/src/main/java/opengrok/auth/plugin/ldap/LdapFacade.java, plugins/src/test/java/opengrok/auth/plugin/util/FilterUtilTest.java, suggester/src/main/java/org/opengrok/suggest/popular/impl/chronicle/BytesRefSizedReader.java, suggester/src/test/java/org/opengrok/suggest/query/customized/CustomSloppyPhraseScorerTest.java
When reviewing https://github.com/oracle/opengrok/pull/3249 I did not like the `Do` method name (capital letter at the beginning due to `do` being a keyword). So I've changed it to `execute` and I've noticed that there were some `@SupressWarnings` annotations that could be easily fixed so I've tried to fix those plus I did some simple refactoring suggested by IDEA.
=> Fix some warnings

opengrok-web/src/main/java/org/opengrok/web/CookieFilter.java, opengrok-web/src/test/java/org/opengrok/web/CookieFilterTest.java
This change adds simple test for `CookieFilter` and optimizes its implementation a bit.
=> test CookieFilter

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerParallelizer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/LazilyInstantiate.java
=> Add isActive to LazilyInstantiate for simpler IndexerParallelizer

opengrok-tools/src/main/python/opengrok_tools/sync.py, opengrok-tools/src/main/python/opengrok_tools/utils/commandsequence.py, opengrok-tools/src/main/python/opengrok_tools/utils/mirror.py, opengrok-tools/src/main/python/opengrok_tools/utils/opengrok.py, opengrok-tools/src/main/python/opengrok_tools/utils/restful.py, opengrok-tools/src/main/python/opengrok_tools/utils/webutil.py, opengrok-tools/src/test/python/test_command_sequence.py, opengrok-tools/src/test/python/test_mirror.py, opengrok-tools/src/test/python/test_restful.py
This changes the processing of RESTful calls in `CommandSequence`. If the call fails, the "command" is considered as failed.
=> Fail CommandSequence if RESTful call fails

README.md
I added a note about opengrok version meaning when doing an update
=> Mention version scheme in readme

dev/main
This change is needed to fix Windows builds.
=> Chocolatey switched to Python 3.9

opengrok-tools/src/main/python/opengrok_tools/utils/opengrok.py, opengrok-tools/src/main/python/opengrok_tools/utils/restful.py
=> Fixing get_repo_type params

suggester/pom.xml
This seems to fix the failing Docker build.
=> upgrade Chronicle map

plugins/src/main/java/opengrok/auth/entity/LdapUser.java, plugins/src/main/java/opengrok/auth/plugin/LdapFilterPlugin.java
Even better debug messages to aid #3275.
=> better debug messages in LdapFilterPlugin and LdapUser

docker/start.sh
=> expand the URL_ROOT variable correctly

plugins/src/main/java/opengrok/auth/plugin/UserWhiteListPlugin.java, plugins/src/test/java/opengrok/auth/plugin/UserWhiteListPluginTest.java
This change allows to choose the field to check against in the `Userwhitelist` plugin.
=> make Userwhitelist plugin generic

.github/workflows/build.yml
Converts the main build workflow to use matrix for the OS. Keeps status quo otherwise.
=> Matrix os build

opengrok-tools/src/test/python/test_mirror.py
=> using fork as default to create a process

suggester/src/main/java/org/opengrok/suggest/Suggester.java
This change fixes incorrect Timer handling in suggester.
=> record correct timer

suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
I see these messages quite often in the log. This is nothing the admin should be concerned about.
=> log failure to increment unknown term as FINE

opengrok-indexer/pom.xml, opengrok-web/pom.xml, pom.xml
This change disperses some of the clouds over #3384.
=> unify activation versions

distribution/assembly.xml, opengrok-indexer/pom.xml
This change rids of these pesky exceptions during web app deploy.
=> flatten library directory

pom.xml
=> Update ant to 1.10.9

pom.xml
minor update, I don't think reindex is needed
=> lucene 8.8.0

opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java
Should help in cases such as #3418.
=> more verbose error for index problems

tools/src/main/python/opengrok_tools/utils/java.py
=> Command expects cmd to be a list of string

apiary.apib, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SystemController.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/SystemControllerTest.java
Works like this:
```
$ curl -s http://localhost:8080/source/api/v1/system/indextime | jq
"2021-02-15T16:39:16.409+00:00"
```
=> add API to get last index time

opengrok-indexer/src/main/java/org/opengrok/indexer/util/CtagsUtil.java
To get more insight into #3183.
=> log ctags temporary files deletion

opengrok-indexer/src/main/java/org/opengrok/indexer/util/CtagsUtil.java
=> add hard-coded Universal ctags temporary directory

opengrok-indexer/src/main/java/org/opengrok/indexer/util/IOUtils.java, opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/IncludeFilesTest.java
Just a small refactoring.
Thanks! :)
=> Use new Java 11 methods to read/write string from/to files

tools/src/main/python/opengrok_tools/sync.py
Needed for local deployment where one of the projects has extensive pre/post mirror hooks so I'd like to run the sync for it separately, with different schedule. With this change I'd just run the main sync as `opengrok-sync --ignore_project foo --indexed ...`.
=> add option/config for ignoring projects

tools/src/main/python/opengrok_tools/sync.py
Fixes a problem introduced in the last change in changeset 4de89884a4f2694596ac96968cebca24d165e38f where I also forgot to bump the version.
=> fix namespace problem

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
Watching a long `db.optimize()` prompted me to add more metrics to `IndexDatabase`.
=> add IndexDatabase metrics

docker/README.md, docker/start.py, tools/src/main/python/opengrok_tools/reindex_project.py
This change fixes recently introduced problems when running the OpenGrok Docker container.
=> Docker project less

docker/start.py, tools/src/main/python/opengrok_tools/utils/opengrok.py
This brings back repositories in Docker in setup with projects.
=> enable projects separately in Docker

opengrok-web/src/main/java/org/opengrok/web/StatisticsFilter.java
Checked with `/source/metrics/prometheus`.
=> treat annotate as separate metric

docker/start.py
=> add missing split()

docker/start.py
fixes #3498
Big thanks to @xundaoxd
=> Fix docker startup if INDEXER_OPT is not provided

opengrok-indexer/src/main/java/org/opengrok/indexer/history/AccuRevRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/BazaarRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/BitKeeperRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/ClearCaseRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/MonotoneRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/PerforceRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/RCSRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/RazorRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepoRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SCCSRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SSCMRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionRepository.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/RepositoryTest.java
Another step in adapting `GitRepository` to use JGit.
=> change GitRepository#GetHistoryGet() to use JGit

opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java, opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerMainTest.java
No project info to avoid leakage.
=> add FileHistoryCache.get() counters for hits/misses

opengrok-indexer/src/main/java/org/opengrok/indexer/util/FileExtraZipper.java, opengrok-web/src/main/java/org/opengrok/web/PageConfig.java, opengrok-web/src/main/webapp/list.jsp, opengrok-web/src/main/webapp/repos.jspf, opengrok-web/src/main/webapp/xref.jspf
This should help #3523. It hides the original problem with indexing, though.
=> generate xref on the fly if xref is stale or non existent

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryClassLoader.java, plugins/src/main/java/opengrok/auth/plugin/configuration/Configuration.java, plugins/src/main/java/opengrok/auth/plugin/configuration/PluginConfigurationClassLoader.java, plugins/src/test/java/opengrok/auth/plugin/configuration/ConfigurationTest.java, plugins/src/test/resources/opengrok/auth/plugin/configuration/plugin-config.xml
=> restrict XML decoding plugins configuration

opengrok-indexer/src/main/java/org/opengrok/indexer/history/History.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/BitKeeperRepositoryTest.java
=> Use set for renamed files in history

opengrok-indexer/src/main/java/org/opengrok/indexer/web/QueryParameters.java, opengrok-web/src/main/java/org/opengrok/web/PageConfig.java, opengrok-web/src/main/webapp/search.jsp, opengrok-web/src/test/java/org/opengrok/web/PageConfigRequestedProjectsTest.java
=> Respect searchall query param when changing sort option

.mvn/wrapper/maven-wrapper.properties, opengrok-indexer/pom.xml, opengrok-web/pom.xml, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ConfigurationControllerTest.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java, plugins/pom.xml, plugins/src/test/java/opengrok/auth/plugin/FalsePluginTest.java, plugins/src/test/java/opengrok/auth/plugin/LdapFilterPluginTest.java, plugins/src/test/java/opengrok/auth/plugin/configuration/ConfigurationTest.java, plugins/src/test/java/opengrok/auth/plugin/util/WebHookTest.java, pom.xml, suggester/pom.xml
I've done some simple manual tests and everything seemed to work fine.
Thanks.
=> Update Java dependencies

plugins/src/test/java/opengrok/auth/plugin/LdapServerTest.java, plugins/src/test/java/opengrok/auth/plugin/ldap/LdapFacadeTest.java
=> Simplify LdapServerTest

docker/README.md, docker/start.py, tools/src/main/python/opengrok_tools/config_merge.py, tools/src/main/python/opengrok_tools/utils/java.py
This change allow to specify read-only configuration in Docker.
=> allow to use read-only configuration in Docker

docker/start.py
This change is yet another attempt to deal with projects correctly in the Docker image. On startup without configuration, bare configuration is generated. This is done by running the indexer with ` --noIndex`. When `-P` is also used, it will generate configuration with projects however without repositories (when `-S` is not used) it leads to #3465. This was fixed by avoiding `-P` and setting the `projectsEnabled` property via API call once Tomcat is up, however this still leaves a window of incorrectness open when the web application starts because during startup it performs index check and this needs to have accurate `projectsEnabled` value. Until #3469 is fixed, I resorted to repository scan (`-S`) to avoid reintroduction of #3465.
=> take projects into account when generating bare config

opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexerTest.java
Problem:
Conditions within the test method may produce a false test outcome. Once a condition is not met, and the code block inside the condition is not executed, a false 'passed' outcome can be produced without the test ever being executed.
Solution:
Instead of using a conditional to control the test execution, we propose using the Conditional Test Execution Annotation @EnabledIf, which results in a test being aborted before a previous test. Conditional execution is typically used whenever it does not make sense to continue executing a given test method.
=> Refactored IndexerTest to use conditional test execution annotation

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
should fix https://lgtm.com/projects/g/oracle/opengrok/snapshot/36022920d6d1efa52fd40b81a19b27d95c0ea3b3/files/opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java?sort=name&dir=ASC&mode=heatmap#x503edddf86372eff:1
=> use try-with-resources on the Reader

opengrok-web/src/main/java/org/opengrok/web/PageConfig.java, opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
=> deal with symlinks when sorting directory entries

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
=> Fix NPE when source or data root are not provided

Dockerfile, opengrok-web/pom.xml, opengrok-web/src/main/java/org/opengrok/web/Scripts.java, opengrok-web/src/main/webapp/js/diff-0.0.5.js, opengrok-web/src/main/webapp/js/repos-0.0.3.js, opengrok-web/src/main/webapp/js/tablesorter-parsers-0.0.3.js, opengrok-web/src/main/webapp/js/utils-0.0.40.js
fixes #3627
Generated js is in `strict` mode. The only problem was the following code which was missing `p` declaration:
```js
p = inner.getLinesParts(urlPart);
```
So I rewrote `var` usages to newer `let`/`const` which have proper scope.
Thanks! :)
Tested the basic functionality (search, diffs, annotate, nav, scope, suggester) in Chrome and did not see any warnings/errors.
=> Use Google Closure JS compiler

pom.xml
=> lucene 8.9.0

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexCheck.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java, opengrok-indexer/src/test/java/org/opengrok/indexer/index/IndexCheckTest.java
=> Avoid repository invalidation with --checkIndex

opengrok-web/pom.xml
=> Remove unused tomcat.servlet.context.path pom variable

opengrok-indexer/src/main/jflex/analysis/golang/GolangXref.lex, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/golang/GolangXrefTest.java, opengrok-indexer/src/test/resources/analysis/golang/email.go, opengrok-indexer/src/test/resources/analysis/golang/email_xref.html
=> Fix missing email addresses in go xref

Dockerfile, dev/docker.sh
fixes #3683
The list of warnings is on: https://github.com/hadolint/hadolint
I just fixed the ones that made sense to me.
Thanks!
=> Use Dockerfile linter

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/PlainAnalyzerTest.java
This change adds basic functional test for the changes in #3699.
=> add test for xref timeout

dev/release.sh, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/package.html, tools/README-dist.txt, tools/README.md, tools/setup.py
Just a few very minor things I noticed while looking at tools.
Thanks.
=> Fix some links

opengrok-web/src/main/java/org/opengrok/web/Scripts.java, opengrok-web/src/main/webapp/js/searchable-option-list-2.0.15.js
=> Fix project selection by space

Dockerfile, docker/start.py
I thought it would be handy to report the OpenGrok (and thus container version) on Docker container startup.
Uses the advice from https://stackoverflow.com/a/50613762/11582827
=> show version on Docker startup

opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
This change should take care of the spurious failures when indexing data with large set of changed files.
=> replace HashSet with concurrent set in PendingFileCompleter

opengrok-web/src/main/webapp/eforbidden.jsp, opengrok-web/src/main/webapp/enoent.jsp, opengrok-web/src/main/webapp/error.jsp, opengrok-web/src/main/webapp/foot.jspf, opengrok-web/src/main/webapp/help.jsp, opengrok-web/src/main/webapp/history.jsp, opengrok-web/src/main/webapp/index.jsp, opengrok-web/src/main/webapp/mast.jsp, opengrok-web/src/main/webapp/minisearch.jspf, opengrok-web/src/main/webapp/pageheader.jspf, opengrok-web/src/main/webapp/search.jsp, opengrok-web/src/main/webapp/settings.jsp, opengrok-web/src/main/webapp/status.jsp
Just a minor improvement I've noticed. Also, it would probably make sense to use `<code>` instead of `<pre>` for source code display.
Thanks!
=> Use header and footer html5 tags

tools/setup.cfg, tools/src/main/python/opengrok_tools/utils/xml.py, tools/src/test/python/new.xml, tools/src/test/python/test_xml.py, tools/src/test/python/web.xml
=> change Jakarta EE namespace to suit Tomcat 10

pom.xml
=> lucene 8.10.0

opengrok-indexer/src/main/java/org/opengrok/indexer/util/ClassUtil.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
Fixes a problem when setting per project property that is not shadowed by repository property.
=> Projects controller vs repositories

tools/src/main/python/opengrok_tools/projadm.py
This change modifies the default lock file name used by `opengrok-projadm` to be based on the arguments so that multiple copies of the program can be run concurrently as long as they do not perform the action with the same set of projects. Eventually the locking inside the web app should be examined. Perhaps no locking is necessary at all. For now I'd settle with this approach.
=> determine opengrok-projadm lock file name based on program arguments

pom.xml
=> lucene 8.11.0

opengrok-web/src/main/webapp/history.jsp
=> Fix display of author's email address in history

opengrok-indexer/src/main/java/org/opengrok/indexer/Info.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/SSCMRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/LineMatcher.java, plugins/src/main/java/opengrok/auth/plugin/LdapUserPlugin.java
Trying to address more Sonar blockers.
=> another round of fixes for Sonar warnings

opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/FileController.java
Another try-with-resources change to address Sonar warning.
Thanks to @ahornace for the code change suggestion.
=> use try-with-resources

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/CtagsReader.java
=> cleanup some issues reported by Sonar in CtagsReader

plugins/src/main/java/opengrok/auth/plugin/FalsePlugin.java, plugins/src/main/java/opengrok/auth/plugin/LdapFilterPlugin.java, plugins/src/main/java/opengrok/auth/plugin/LdapUserPlugin.java, plugins/src/main/java/opengrok/auth/plugin/TruePlugin.java, plugins/src/main/java/opengrok/auth/plugin/UserPlugin.java, plugins/src/main/java/opengrok/auth/plugin/UserWhiteListPlugin.java, plugins/src/main/java/opengrok/auth/plugin/ldap/FakeLdapFacade.java
More Sonar cleanup, this time in authnz plugin space.
=> cleanup Sonar issues in authnz plugins

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/parser/SuggesterQueryDataParser.java
This change attempts to address data sanitization issue found by CodeQL highlighted in some recent PRs, e.g. https://github.com/oracle/opengrok/pull/3792/checks?check_run_id=4322348553
=> sanitize list of projects in suggester query

dev/checkstyle/style.xml, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Ctags.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/MercurialRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/RCSHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/Repository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/StringUtils.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java, plugins/src/main/java/opengrok/auth/plugin/util/RestfulClient.java, plugins/src/main/java/opengrok/auth/plugin/util/WebHook.java, pom.xml, suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
With recent Sonar cleanups I noticed that we could benefit from this check to avoid such problems in the future. Thanks.
=> Add ParameterName checkstyle check

opengrok-indexer/src/main/java/org/opengrok/indexer/history/BitKeeperHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/BitKeeperTagParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/CVSRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/DirectoryHistoryReader.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/GitRepository.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java
Sonar cleanup in history/repositories.
=> cleanup Sonar issues in repositories

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java, opengrok-web/src/main/java/org/opengrok/web/WebappListener.java
This change makes the `watchDogService` private in `RuntimeEnvironment`.
=> make watchDog private

opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
Another fix for issue found by Sonar.
=> handle delete() better in FileHistoryCache

suggester/src/main/java/org/opengrok/suggest/Suggester.java
This change fixes bunch of minor issues in Suggester.
=> Suggester Sonar fixes

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java
=> Sonar fixes in AnalyzerGuru

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/CtagsReader.java
Fix for another issue identified by Sonar.
=> fix Sonar issues in CtagsReader

plugins/src/main/java/opengrok/auth/plugin/UserWhiteListPlugin.java, plugins/src/test/java/opengrok/auth/plugin/UserWhiteListPluginTest.java
=> handle null parameters in UserWhiteListPlugin more gracefully

opengrok-indexer/src/main/java/org/opengrok/indexer/web/EftarFile.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/EftarFileReader.java
This fixes bunch of issues found by LGTM or IDEA.
=> cleanup Eftar issues found by LGTM

opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/Suggestion.java, opengrok-web/src/main/webapp/search.jsp
Basic treatment for Sonar issues found in `Suggestion`.
=> adress Sonar issues in Suggestion

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/c/CxxConsts.java
I missed this one in PR #3802.
=> make kwd package-private in CxxConsts

opengrok-indexer/src/main/java/org/opengrok/indexer/web/EftarFile.java, opengrok-indexer/src/test/java/org/opengrok/indexer/web/EftarFileTest.java
This change fixes remaining Sonar issue in `EftarFile`.
=> fix more Sonar issues in Eftar

plugins/src/main/java/opengrok/auth/plugin/AbstractLdapPlugin.java
This change fixes the issues found by Sonar.
=> reduce visibility of some methods/fields in AbstractLdapPlugin

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/Definitions.java, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/pascal/PascalXrefTest.java
This change addresses bunch of issues in `Definitions` found by Sonar and IDEA.
=> Sonar fixes in Definitions

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/PendingToken.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/plain/DefinitionsTokenStream.java, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/PendingTokenTest.java
This change makes the `nonpos` field package-private.
=> reduce field visibility in PendingToken

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/XrefStyle.java
This change fixes another issue reported by Sonar.
=> lower the visibility of the DEFINITION_STYLES array in XrefStyle

opengrok-web/src/main/java/org/opengrok/web/WebappListener.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/suggester/provider/service/impl/SuggesterServiceImpl.java, suggester/src/main/java/org/opengrok/suggest/Suggester.java
This change fixes suggester rebuild termination when web app undeploy is in progress.
=> Suggester rebuild vs undeploy

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuruHelp.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/FileAnalyzerFactory.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/archive/ZipMatcherBase.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/document/DocumentMatcher.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/executables/JavaClassAnalyzerFactory.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/plain/PlainAnalyzerFactory.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/IOUtils.java, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/JFlexXrefTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/plain/PlainAnalyzerFactoryTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/analysis/plain/PlainAnalyzerTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/util/StreamUtils.java
=> Plain-text matcher should try UTF-8 decoding

opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
While primarily intended to fix (im)possible `cfg` null pointer dereference in Indexer (reported via LGTM), I took the chance to fix bunch of nits reported by SonarLint/IDEA.
=> fix Indexer nits

opengrok-web/src/main/java/org/opengrok/web/Scripts.java, opengrok-web/src/main/webapp/default/print-1.0.2.css, opengrok-web/src/main/webapp/default/style-1.0.4.css, opengrok-web/src/main/webapp/diff.jsp, opengrok-web/src/main/webapp/help.jsp, opengrok-web/src/main/webapp/httpheader.jspf
This change replaces the `b` and `i` elements in the diff page with `strong` and `em` elements, respectively.
=> Diff page html cleanup

opengrok-indexer/src/main/java/org/opengrok/indexer/authorization/AuthorizationFramework.java, opengrok-indexer/src/main/java/org/opengrok/indexer/framework/PluginFramework.java, opengrok-indexer/src/test/java/org/opengrok/indexer/authorization/AuthorizationFrameworkTest.java
This change fixes 2 issues in `PluginFramework` found by Sonar.
=> fix Sonar issues in PluginFramework

opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java, tools/src/main/python/opengrok_tools/projadm.py, tools/src/main/python/opengrok_tools/utils/opengrok.py
This change converts the project add API endpoint to asynchronous.
=> convert project add API to asynchronous

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexCheck.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
This change makes the indexer a bit more resilient w.r.t. the arguments used.
=> keep the subFiles in a Set

opengrok-web/src/main/webapp/help.jsp
=> Update help wrt new symbol highlighting

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/RepositoryInfo.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java
=> add more info to repository scan log messages

opengrok-indexer/pom.xml, opengrok-indexer/src/main/java/org/opengrok/indexer/history/CVSHistoryParser.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryEntry.java, opengrok-indexer/src/test/java/org/opengrok/indexer/history/CVSRepositoryTest.java
This change should fix sorting of CVS revision numbers.
=> sort revisions for CVS repository semantically

apiary.apib, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Group.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/GroupsController.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/GroupsControllerTest.java
Another batch of retrieval specific APIs for project groups:
- get group pattern
- match name against pattern
=> more API endpoints for project groups

suggester/src/main/java/org/opengrok/suggest/SuggesterProjectData.java
This change makes the lookup operation for a term more resilient.
=> fix NPE in SuggesterProjectData

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AbstractAnalyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/TextAnalyzer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java, opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/OGKUnifiedHighlighter.java, opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java
Spawned by https://github.com/oracle/opengrok/pull/3912#issuecomment-1250358374
=> fix some Javadoc warnings

.github/workflows/docker.yml, dev/dockerhub_readme.py
Fixes docker hub README check for pull requests.
=> check env more thoroughly when uploading Docker hub README

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
This change adjusts some nits found in AnalyzerGuru, esp. the lack of quoting of file names in the logs.
=> Analyzer guru nits

Dockerfile
This change fixes some recently introduced warnings for the Dockerfile.
=> address some hadolint warnings

apiary.apib
=> document annotationCacheEnable repository property

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/LatestRevisionUtil.java
Discovered when observing webapp logs.
=> fix quotes for logging

opengrok-indexer/src/main/java/org/opengrok/indexer/web/Util.java, opengrok-web/src/main/java/org/opengrok/web/PageConfig.java, opengrok-web/src/main/webapp/history.jsp
When reading the `history.jsp` code, I noticed bunch of issues worth fixing.
=> fix some history.jsp nits

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
Make sure that `Statistics` is always reported in `HistoryGuru#getLastHistoryEntry()`.
=> make sure the Statistics is always reported

docker/start.py
Should fix the project bootstrap issue in Docker.
=> list_projects() returns None on failure

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexerUtil.java, plugins/src/main/java/opengrok/auth/plugin/util/RestfulClient.java
This change fixes bunch of Sonar warnings.
=> Sonar fixes for 2023/02

opengrok-indexer/src/main/java/org/opengrok/indexer/analysis/AnalyzerGuru.java, opengrok-web/src/main/webapp/xref.jspf
This change should provide more robustness for the plain text handling in the webapp.
=> check argument of doCtags()

opengrok-indexer/src/main/java/org/opengrok/indexer/history/SubversionHistoryParser.java
This change makes couple of minor logging improvements in `SubversionHistoryParser`.
=> logging improvements for Subversion

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/Indexer.java, opengrok-indexer/src/main/java/org/opengrok/indexer/index/PendingFileCompleter.java
This change adds more path quoting for log entries.
=> add quotes for path logging

opengrok-indexer/src/main/java/org/opengrok/indexer/index/IndexDatabase.java
Another instance of progress reporting that deserves some improvement.
=> improve progress logging

docker/start.py
This change completes the API timeout propagation in Docker image.
=> propagate the API timeout to all indexers

tools/src/main/python/opengrok_tools/utils/commandsequence.py
This change adds checking of the command structure in the `opengrok-sync` configuration.
=> check command structure more thoroughly

opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileHistoryCache.java
This change removes the write locking in `FileHistoryCache`. There is a slight improvement in indexing time.
=> remove locking when writing cache files

opengrok-indexer/src/main/java/org/opengrok/indexer/util/Executor.java
Another change that unifies the logging of paths.
=> enclose directory in single quotes in Executor

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Configuration.java, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/ConfigurationHelp.java, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Group.java, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/Groups.java, opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/RuntimeEnvironment.java, opengrok-indexer/src/test/java/org/opengrok/indexer/authorization/AuthorizationEntityTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/GroupsTest.java, opengrok-indexer/src/test/java/org/opengrok/indexer/configuration/RuntimeEnvironmentTest.java, opengrok-web/src/main/java/org/opengrok/web/ProjectHelper.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/GroupsController.java, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/ProjectsController.java, opengrok-web/src/test/java/org/opengrok/web/PageConfigRequestedProjectsTest.java, opengrok-web/src/test/java/org/opengrok/web/ProjectHelperExtendedTest.java, opengrok-web/src/test/java/org/opengrok/web/ProjectHelperTest.java, opengrok-web/src/test/java/org/opengrok/web/ProjectHelperTestBase.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/GroupsControllerTest.java, opengrok-web/src/test/java/org/opengrok/web/api/v1/controller/ProjectsControllerTest.java
fixing #1587, I accept the terms of me contributing to this project
These changes include changing Group from set to Map and changing its corresponding client and unit tests.
=> Changing Groups to Map, fixing #1587 ,I accept the terms of me contributing to this project

pom.xml
=> lucene 9.6

tools/src/main/python/opengrok_tools/sync.py
This change allow to match ignored project names, using [fnmatch](https://docs.python.org/3/library/fnmatch.html#fnmatch.fnmatchcase), e.g.:
```
opengrok-sync --ignore_project 'foo*' \
-l debug -c sync-debug.yml -U http://localhost:8080/opengrok_web_war/
```
=> support pattern matching ignored project names

opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java, pom.xml, suggester/src/main/java/org/opengrok/suggest/SuggesterSearcher.java, suggester/src/main/java/org/opengrok/suggest/query/SuggesterPhraseQuery.java, suggester/src/main/java/org/opengrok/suggest/query/customized/CustomPhraseQuery.java
=> lucene 9.7.0

apiary.apib, opengrok-web/src/main/java/org/opengrok/web/api/v1/controller/SearchController.java
This change provides tag in the search results returned by the search API; was inspired by https://github.com/oracle/opengrok/discussions/4379#discussioncomment-6481001.
=> provide tag in search results

docker/start.py
Make it clear what kind of index check is done in Docker.
=> add explicit index check type

pom.xml
no format change
no reindex needed
=> lucene 9.8.0

opengrok-indexer/src/main/java/org/opengrok/indexer/search/context/StrictLineBreakIterator.java
Hi
I have removed an unused assignment
ciao
matteo
=> Removed unused assignment

opengrok-web/pom.xml, pom.xml, suggester/pom.xml, suggester/src/main/java/org/opengrok/suggest/popular/impl/chronicle/BytesRefDataAccess.java
Upgrade jstl and chronicle-map
Added new jstl-api dependency which is needed from version 3
Tested by running the web app in tomcat 10 and indexing a repo using the same configuration
=> upgrade jstl and chronicle-map

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
Inspired by https://github.com/oracle/opengrok/discussions/4438
=> return right away from getHistory() if repository cannot be found

opengrok-indexer/pom.xml
=> Change commons-io scope from compile to test.

Dockerfile
Simple Tomcat update in the Docker image to provide fixes for the latest CVEs.
=> update Tomcat to 10.1.16

opengrok-indexer/src/main/java/org/opengrok/indexer/logger/LoggerUtil.java
Remove un-used code from logger util
=>  Remove unused code from logger util

dev/docker.sh
Simple change for Docker build to use buildx.
=> switch to docker build to buildx

tools/src/main/python/opengrok_tools/projadm.py
Another thing I forgot to change after adding mandatory argument to the `ConfigMerge` program.
=> adapt projadm to the current ConfigMerge usage

pom.xml, suggester/src/main/java/org/opengrok/suggest/query/customized/CustomPhraseQuery.java
=> lucene 9.9.0

pom.xml
=> lucene 9.9.1

CONTRIBUTING.md
Fix typos in CONTRIBUTING.md file.
Issue: #4529
=> Fix typos in CONTRIBUTING.md file

pom.xml
just bug fix, no reindex needed
=> Lucene 9.9.2

opengrok-indexer/src/main/java/org/opengrok/indexer/configuration/PathAccepter.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/FileAnnotationCache.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/LatestRevisionUtil.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/Statistics.java
This changes logging of file paths to avoid Sonar reported log injection attacks.
=> launder logged file paths

opengrok-indexer/src/main/java/org/opengrok/indexer/history/AbstractCache.java, opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java, opengrok-indexer/src/main/java/org/opengrok/indexer/util/PathUtils.java
=> launder and quote yet more paths

opengrok-indexer/src/main/java/org/opengrok/indexer/history/HistoryGuru.java
This change improves logging and checking for various history cache related events.
=> improve logging for various history cache events

.github/dependabot.yml, Dockerfile
=> add org.opencontainers labels and add Dependabot configuration

.github/dependabot.yml
Fix the value so that it passes verification.
=> Docker should in low caps

opengrok-web/src/main/java/org/opengrok/web/GetFile.java, opengrok-web/src/main/java/org/opengrok/web/PageConfig.java, opengrok-web/src/test/java/org/opengrok/web/GetFileTest.java
This change adds basic test coverage for the `GetFile` class used in the webapp. I fixed some related nits along the way.
=> add test coverage for GetFile

opengrok-indexer/src/main/jflex/analysis/php/PhpSymbolTokenizer.lex, opengrok-indexer/src/main/jflex/analysis/php/PhpXref.lex
=> bump year in copyright

opengrok-web/src/main/java/org/opengrok/web/PageConfig.java, opengrok-web/src/main/webapp/diff.jsp
This change attempts to fix an issue reported by SonarQube w.r.t. sanitization of input data. Also fixes bunch of nits.
=> diff.jsp link encoding

opengrok-web/src/main/webapp/diff.jsp, opengrok-web/src/test/java/org/opengrok/web/PageConfigTest.java
Fix couple of code smells reported by SonarQube.
=> Fix some code smells
